### ISSUE TITLE
Provide dialect-independent translations

### ISSUE THREAD

**Issue by pferreir** [indico/indico#1007]
``` yaml
# Ticket imported from Trac
```

We should focus on languages regardless of dialects (we are not going to produce two separate english versions of Indico anyway) and use 'dialects' only for things such as date standards. I think this is technically possible and will make things easier in the long run.

The simple solution is to change `setLocale` so that it loads 'en' instead of 'en_GB', 'fr' instead of 'fr_FR'... and rename the dictionaries accordingly.

**Comment by ThiefMaster** [comment]
> we are not going to produce two separate english versions of Indico anyway

this did not age well :D (we have en_GB and en_US now)

and some time ago we actually ensured to include territory info for all locales, because it *is* important for some languages
