### ISSUE TITLE
Upload file from Cloud Storage

### ISSUE THREAD

**Issue by jbenito3** [indico/indico#1042]
``` yaml
# Ticket imported from Trac
```

Submitted by: Andreas.Pfeiffer___at___cern.ch

```

in addition to the existing uploading a local file and
adding an external link to contributions and events, I
propose to add a possibility to upload a (remote) file
specified by a URL. 

The concrete use-case behind this is that I was at a 
conference and the latest version of my presentation 
was in my public Dropbox folder (for which I can get
a URL). As I only had my iPad/iPhone with me, I needed
to find a nice colleague whose laptop I could borrow to
simply download the talk from the Dropbox URL, then
upload the local file to the (indico) agenda. This would
have been much easier if there would be a way to upload
a file specified by URL. 

Please note that this should really be an down/up-load of 
the file, not just keeping the URL, as the URL may go away 
later, so the idea is to copy the file specified by the URL 
and add it to the indico agenda.

```

**Comment by ThiefMaster** [comment]
This is kind of dangerous, as it may allow someone to access files available in the internal network where an Indico instance is running even though the files are not available from the public internet.

With internet connections being faster and faster nowadays I don't think this makes much sense anymore.

However, being able to import a file straight from e.g. Dropbox, CERNBox, etc (using their APIs) could be nice - but I'm not sure how many people would actually use such a feature. Probably not too many...

**Comment by felicepantaleo** [comment]
Browsing CERNbox from indico to select the file to upload to indico would be a very appreciated feature indeed.
