### ISSUE TITLE
indico URLs - keep confId in front, keep parameter order

### ISSUE THREAD

**Issue by arescope** [indico/indico#1047]
```yaml
# Ticket imported from Trac
```

currently INDICO URLs seem to put the most discriminative element first in the parameter list of the URL, i.e
https://indico.cern.ch/conferenceDisplay.py?confId=152323 = event URL
https://indico.cern.ch/materialDisplay.py?materialId=minutes&confId=152323 = URL for minutes, confId gets pushed to back
similar
http://indico.cern.ch/conferenceTimeTable.py?confId=149557#20120521 == CHEP2012
https://indico.cern.ch/abstractDisplay.py?abstractId=489&confId=149557 == one abstract in CHEP2012, again confId at end

It looks like browsers such as chrome will use longest-match on the URL in order to group related pages and keep track of "most often accessed". The current INDICO URL style does not work well in this case. Could I suggest to reorder the parameters so that the most significatn (i.e confId) is kept at front? Similarly, if there is some other "hierarchy" (conf->talk->material->file1,file2,.. ?), suggest to keep the parameters ordered by most-significant first.

**Comment by ThiefMaster** [comment]
obsolete since flaskification
