### ISSUE TITLE
Room Booking: Allow to filter week days on Room Booking calendar

### ISSUE THREAD

**Issue by jbenito3** [indico/indico#1088]
``` yaml
# Ticket imported from Trac
```

From: karsten koeneke

Dear Indico team,

I would like to request a feature.
In the "Room booking" categorie, one can display "My bookings" or "My
PRE-bookings" and adjust the date range to show via "change period", which
is very nice.

However, it would be great if one could also specify which days of the week
to show. For example, normally, I am responsible for one or two regular
meetings, let's say I am responsible for meetings every Tuesday and
Thursday as an example. It would be good to be able to select and de-select
the days of the week when I change the period to display, e.g. with 7
(de-)selectable buttons, one for each day of the week in the popup box
"Choose Period" that appears when I click on "change period". By default,
all seven should be selected to reflect the current behaviour.
This way, I could choose to only display Tuesdays and Thursdays and thus
have a much simpler overview of my (pre-)booked meeting rooms.

Thanks a lot already for taking this into consideration.

Karsten

**Comment by pferreir** [comment]
The new interface should remove the need for this option.
