### ISSUE TITLE
Add dictionary editor for plugin options

### ISSUE THREAD

**Issue by pferreir** [indico/indico#1105]
``` yaml
# Ticket imported from Trac
```

I noticed that we are spending too much energy developing dedicated dictionary editors for plugin options, i.e. list of currencies.
A possibly good idea would be to develop a general dictionary editor that would allow easy management of said fields with no need to develop a dedicated interface. Basically, a very simple JSON editor.

**Comment by ThiefMaster** [comment]
we have wtforms widgets, including generic ones like MultipleItemsField for this kind of stuff nowadays
