### ISSUE TITLE
Room configuration - Several dates and unavailability reason

### ISSUE THREAD

**Issue by pferreir** [indico/indico#1115]
``` yaml
# Ticket imported from Trac
```

Currently, one can only select a single "unavailability period" for each room, using the web interface. The backend, however, is already made in such a way that a list of periods can be stored.
It would as well be nice to add a small description for each period, such as "maintenance works" or "closed during christmas holidays".

**Comment by ThiefMaster** [comment]
Multiple periods are supported since 1.9; if there's need for a detailed reason blockings can be used
