### ISSUE TITLE
Contribution display: make it better

### ISSUE THREAD

**Issue by jbenito3** [indico/indico#1127]
```yaml
# Ticket imported from Trac
```

When the contribution has a lot of data, it looks beautiful. On the other hand, it is not the case when there is no much data.
We should find a nice solution for it: responsive layout? 2 layouts using Template inheritance?

Example of ugly contribution: http://indico.cern.ch/contributionDisplay.py?contribId=0&confId=215945

**Comment by OmeGak** [comment]
Not relevant anymore, since there has been plenty of style improvements in the meantime in contribution display pages.
