### ISSUE TITLE
Material name ellipsis hides extension

### ISSUE THREAD

**Issue by pferreir** [indico/indico#1141]
``` yaml
# Ticket imported from Trac
```

In the conference timetable, two files with the same (long) name and different extensions will both show up as 'file_name_xxxx...', thus keeping the extension hidden from the user. We should either show the extension and only abbreviate the rest of the name, or add an icon or another graphic element.

**Comment by ThiefMaster** [comment]
We now have icons and tooltips with the full name everywhere; and in the conference timetable (where we have no icon) we don't truncate long names.
