### ISSUE TITLE
Option flag for adding the .ics (ical) file to an event reminder

### ISSUE THREAD

**Issue by arescope** [indico/indico#1158]
``` yaml
# Ticket imported from Trac
```

Dear Indico Support Team,
I would like to know if it is possible to attach the .ics file in an alarm email corresponding to an event (?).
For the moment, one can include a text version but not the .ics file (via Tools -> Alarms -> Create a new alarm email).
Potentially, two files could be chosen (same as the ones available on the event page):
- the "Event calendar file";
- the "Detailed timetable calendar file".
  Thanks for letting me know.
  Best regards,

**Comment by pferreir** [comment]
We can mostly reproduce the [implementation from newdle](https://github.com/indico/newdle/pull/231/files).

**Comment by pferreir** [comment]
Since we're at it, what about adding also a "send ICS file along with registration acceptance e-mail" option in a registration form's settings?
