### ISSUE TITLE
Remind password when there are secondary email addresses

### ISSUE THREAD

**Issue by jbenito3** [indico/indico#1160]
``` yaml
# Ticket imported from Trac
```

When a user has primary email address and secondary email addresses, there is a weird situation when he asks to be sent his password (because we forgot it).
Indico will send the password to his primary email address, no matter what. Imaging that he writes a secondary mail address, he will still receive it in the primary one. This is confusing and needs to be fixed.

**Comment by ThiefMaster** [comment]
Since 1.9.x we use the entered email address
