### ISSUE TITLE
Management area UX

### ISSUE THREAD

**Issue by jbenito3** [indico/indico#1181]
``` yaml
# Ticket imported from Trac
```

There are many users that are still confused between the management and display areas.
In the management area we see the same header as for Category Display (with the blue bar). That's taking a lot of space and it is useless while being in the management area. 
We should take advantage of that space for management tools.

**Comment by ThiefMaster** [comment]
people have large screens nowadays ;)

**Comment by jbenito3** [comment]
> people have large screens nowadays ;)

2012 ;)

**Comment by ThiefMaster** [comment]
i know :D
