### ISSUE TITLE
Room Booking: Redesign room booking pages for Rooms

### ISSUE THREAD

**Issue by jbenito3** [indico/indico#1193]
``` yaml
# Ticket imported from Trac
```

Both pages, modify and display, are using many tables and the display is not user-friendly:

Modify: https://indico/roomBooking.py/roomForm?roomLocation=CERN&roomID=1
Display: https://indico/roomBooking.py/roomDetails?roomLocation=CERN&roomID=1

**Comment by pferreir** [comment]
Doesn't apply anymore.
