### ISSUE TITLE
Session close func: used?

### ISSUE THREAD

**Issue by jbenito3** [indico/indico#1196]
``` yaml
# Ticket imported from Trac
```

Under session modif tools we can find the option to close or lock the session. This blocks the access to the session properties, even though one can still modify the session from the Timetable (at least date-time, place and color).

Shall we keep it?

If yes: we must block the modif options from the timetable.
If
If no: well, delete the code...

**Comment by ThiefMaster** [comment]
Session locking has been removed, and event locking just switches to read-only instead of blocking access.
