### ISSUE TITLE
Old email not removed from ACL when editing speaker email

### ISSUE THREAD

**Issue by jbenito3** [indico/indico#1215]
``` yaml
# Ticket imported from Trac
```

While editing contribs from the TT popup (Basic edition):
- If there is a speaker/author/coauthor with submission rights and we do modify the email address: the new 'email address' will be granted with submission rights but the previous one is not revoked.
- ~~We can add the same user to the author list and the co-author list.~~

**Comment by ThiefMaster** [comment]
the first behavior still happens

**Comment by ThiefMaster** [comment]
semi-related: #2559

**Comment by plourenco** [comment]
Not applicable anymore with the refactoring of the person link field in #5129.
