### ISSUE TITLE
Dashboard: timezone support

### ISSUE THREAD

**Issue by OmeGak** [indico/indico#1244]
``` yaml
# Ticket imported from Trac
```

User dashboard uses Moment.js for human-like date formatting, but the library does not support timezones for the time being. As for now, all dates in the Dashboard are displayed in local time regardless of the user's timezone.

Suggested solution is updating Moment.js when the timezone support is in available. There is no ETA, but regarding the author, it shouldn't take long. Discussion can be checked here: https://github.com/timrwood/moment/issues/482

**Comment by ThiefMaster** [comment]
The dashboard is not using momentjs anymore since everything is rendered on the server side.
