### ISSUE TITLE
Modification key allow access to conf edition but not to display view

### ISSUE THREAD

**Issue by OmeGak** [indico/indico#1258]
```yaml
# Ticket imported from Trac
```

Events protected by modification key cannot be accessed to its event page view but only the modification one. The expected behavior is that if a user can modify the event he can also access its event page.

Steps to reproduce the error:
* Create any event.
* Go to Management > Protection.
* Set the event as restricted.
* Set a modification key.
* Log in with a non privileged user.
* Access corresponding conferenceModification.py.
* Modification key is requested.
* Change to event page.
* Error message.

**Comment by ThiefMaster** [comment]
Obsolete since modification keys are gone
