### ISSUE TITLE
Chatroom: Refresh button doesn't fetch changes on serverside

### ISSUE THREAD

**Issue by OmeGak** [indico/indico#1260]
``` yaml
# Ticket imported from Trac
```

Chatrooms created in Indico and modified on serverside later need to be refreshed manually pressing the corresponding button. This refresh process is not fetching changes from the server. The opposite process is working fine: changes made in Indico are reflected in the server.

**Comment by ThiefMaster** [comment]
name/description/password are updated during a manual refresh
