### ISSUE TITLE
Participants: Excuse absence behavior is a bit confusing

### ISSUE THREAD

**Issue by OmeGak** [indico/indico#1267]
``` yaml
# Ticket imported from Trac
```

In managing the attendance of participants, when trying to _Excuse absence_ one would expect to change between the three possible states of attendance directly from one to another, however, in order to excuse the absence of a participant, this needs to be set as ''Didn't attend'' before, showing a warning dialog otherwise.

The problem is that, by default, all participants' status is "Attended" and it requires two actions. One solution is allowing to change the state of attendance freely, or giving the option to excuse the participant from the warning dialog.

**Comment by ThiefMaster** [comment]
"Excuse absence" does not exist anymore since 1.9.x.
