### ISSUE TITLE
Dashboard: Speakers in lectures are listed as managers

### ISSUE THREAD

**Issue by OmeGak** [indico/indico#1275]
``` yaml
# Ticket imported from Trac
```

In the Dashboard we partition the rights a user has in an event in _manager_, _reviewer_ and _attendee_ flags. 

One of the rights in **linkedTo** we are using to set the _manager_ flag is "chair".  This works fine for meetings and conferences, but not for lectures. This is because "chair" is the right granted to speakers in lectures, causing the _manager_ flag to be shown when it should be the _attendee_ one.

**Comment by ThiefMaster** [comment]
This is still the case and probably *very* easy to fix: Check the event type in `get_events_with_linked_event_persons` (and possible rename it to make it clear that this is about chairpersons)
