### ISSUE TITLE
Room Booking: bookings should be assignable to session slots, not sessions

### ISSUE THREAD

**Issue by jbenito3** [indico/indico#1314]
``` yaml
# Ticket imported from Trac
```

Two problems:
1. ~~~After rejecting/cancelling, it redirects out of the event~~~
2. Book and assign to session: nowadays it makes no sense, it should be book and assign to session slot. It is not only a matter of changing the label but the functionality should actually assign the room to the session slot.

**Comment by pferreir** [comment]
Already targeted by #3707
