### ISSUE TITLE
Group by years

### ISSUE THREAD

**Issue by DirkHoffmann** [indico/indico#1330]
```yaml
# Ticket imported from Trac
```

It would be nice, if one could have a "grouped" view, for example by years of the contents of one category.
This option should always be available, but the default display (grouped by year / ungrouped) should be configurable by the category manager(s).

**Comment by DirkHoffmann** [comment]
I saw that there is a progressive unfold for very long histories in a category, a bit like what fb is doing.
So I am not convinced that my request is still valid. I am ready to close it for the benefit of other more important features.

**Comment by pferreir** [comment]
I think that in 1 year or so we will have a software stack that will allow us to do much better than we do now. But I think that the way we show information is good enough for the moment, and I wouldn't change it much.
So, I agree with closing this ticket, unless you have some revolutionary idea that you believe that should be discussed.
