### ISSUE TITLE
No notify speakers and submiters if they do not have an account and event is private

### ISSUE THREAD

**Issue by arescope** [indico/indico#1344]
``` yaml
# Ticket imported from Trac
```

Good morning,

I have come across a rather annoying problem in Indico. I have created a new conference and put the viewing access on restricted with (in principle!) only Dr. Roger Bailey being able to modify the conference. However, in entering the speakers and already giving them submission rights, it appears that they already received the email that they have been given submission rights and to create an indico account (see below)

You have been added as author/speaker of the following contributions:
- "Event" "Power Converters 2014":
- "Contribution" "EMC" (Speaker)
- Access: https://indico.cern.ch/contributionDisplay.py?contribId=20&confId=263328

and material submission rights have been granted to you.
Please create an account in Indico in order to use these rights. You can create your account at the following URL:

https://www.cern.ch/externals/registeraccount.aspx?cpEmail=a.charoy%40aemc.fr

_Note that you must use this email address a.charoy@a... when creating the account_

As the speakers have not yet been invited it is now embarrassing that they have been informed! If the event is meant to be private, does this not mean the whole thing is private, so why have they been contacted?

With kind regards,

Barbara

**Comment by ThiefMaster** [comment]
We don't send emails to people when being added to ACLs or as speakers anymore
