### ISSUE TITLE
Dashboard cache refreshing

### ISSUE THREAD

**Issue by OmeGak** [indico/indico#1375]
``` yaml
# Ticket imported from Trac
```

Currently, the only way to refresh the dashboard linked_events cache is to wait until the cache TTL expires. By default, this is set to 10 minutes in Server Administration.

The refresh button that appears for admins in the dashboard **does not** refresh the cache, but instead it only forces the regeneration of Redis linked_events object.

It would be desirable to mark the linked_events cache as dirty whenever any of its values is changed, ensuring instant update of the Dashboard.

**Comment by ThiefMaster** [comment]
This is obsolete since it doesn't use the API anymore
