### ISSUE TITLE
Dashboard linkedTo inconsistency

### ISSUE THREAD

**Issue by OmeGak** [indico/indico#1378]
```yaml
# Ticket imported from Trac
```

The dashboard fails to represent some links of users to events due to some actions of Indico not triggering update of Redis linked_events object or design flaw.

This is a list of cases where the links are found not to be updated as expected.

Abstracts:
* Abstract submitter is listed as attendee. Being submitter doesn't mean one is attending. Maybe a new icon representing this kind of relation with an event is needed.
* The presenter of an approved abstract becomes the presenter of a contribution. This link is not created in the process. 

Contributions:
* Removing speaker/author/coauthor from 'Contribution full edition menu' in a Conference doesn't remove link to event. 

Others:
* Adding user as chairman doesn't add link to event. He should be listed as with management rights.

**Comment by ThiefMaster** [comment]
Obsolete since we are getting rid of linkedTo

**Comment by OmeGak** [comment]
:hankey:
