### ISSUE TITLE
Calendar link for Favorites

### ISSUE THREAD

**Issue by indico-bot** [indico/indico#1384]
``` yaml
# Ticket imported from Trac
# Reported by: aem
```

According to my knowledge it is currently not possible to use one calendar link for all favorite categories. Currently i subscribed to many categories in google calendar and it would be much smoother to have one unique calendar link for all favorite categories.

**Comment by OmeGak** [comment]
Related SNOW ticket: `CHG34188`

**Comment by jgronefe** [comment]
Dear all, 

I too would love to use such a feature. I recently noticed that Indico added a couple of events to my CERN Outlook calendar. Something like a "I will attend this meeting" button that would add an event to my calendar automatically would be nice. 

Best Julius

**Comment by ThiefMaster** [comment]
this is available in the dashboard since some time
