### ISSUE TITLE
Indico is escaping HTML contained in  titles and content also in the PDF export

### ISSUE THREAD

**Issue by indico-bot** [indico/indico#1393]
``` yaml
# Ticket imported from Trac
# Reported by: soleantelada
```

For example in titles like R&D Energy Recovery.... it is not showing the ampersand plus the

letter after it when exporting to PDF. It is necessary now to separate the letters like 

this 'R & D' so they appear in the PDF document

**Comment by ThiefMaster** [comment]
We don't allow HTML in titles etc anymore and thus proper escaping is applied
