### ISSUE TITLE
Turn "EventsAtHand" into a full-pledged jQuery widget

### ISSUE THREAD

**Issue by OmeGak** [indico/indico#1397]
``` yaml
# Ticket imported from Trac
```

Extract EventsAtHand functionality from UserDashboard.tpl into a proper jQuery widget that can be called anywhere. Allowing also configuration to improve the versatility of the widget.

This goes along with the idea of having a more personalized Indico Homepage.

**Comment by ThiefMaster** [comment]
We no longer write jQuery widgets ;)
