### ISSUE TITLE
Favourite talks

### ISSUE THREAD

**Issue by jbenito3** [indico/indico#1409]
``` yaml
# Ticket imported from Trac
```

From the timetable, a user would be able to choose the talks he wants to attend and then, he/she could have a view of his/her own timetable. This is useful for large conferences (1 week or more, and many talks)

**Comment by kewisch** [comment]
Looks like we have a new ticket for this at #5337

**Comment by pferreir** [comment]
Closing in favor of https://github.com/indico/indico/issues/5337
