### ISSUE TITLE
Meeting sessions and contributions location does not appear

### ISSUE THREAD

**Issue by arescope** [indico/indico#1410]
``` yaml
# Ticket imported from Trac
```

To be discussed

When we set up the location of a session or contribution to inherit from parent and we customize some of them with another location it does not appear and can be confused for users.

**Comment by nop33** [comment]
To be a bit more descriptive on how to reproduce:
* Create a new Session in the timetable management area, setting the location to be inherited.
![](http://i.imgur.com/GucD5Bz.png)
* The location correctly inherited in:
  * `event/<event-id>/manage/timetable/` :heavy_check_mark: 
  * `event/<event-id>/timetable/` :heavy_check_mark: 
  * `event/<event-id>/session/<session-id>` :heavy_check_mark: 
* Change the location by doing a "Basic edit" on the session slot in `event/<event-id>/manage/timetable/`.
* Result:
  * `event/<event-id>/manage/timetable/` :heavy_check_mark: 
  * `event/<event-id>/timetable/` :heavy_check_mark: 
  * `event/<event-id>/session/<session-id>` :boom: 

What is remarkable is that it doesn't always happen..!

**Comment by ThiefMaster** [comment]
fixed in 1.9.x
