### ISSUE TITLE
Room Booking: Extend room booking date range flexibility

### ISSUE THREAD

**Issue by jbenito3** [indico/indico#1422]
``` yaml
# Ticket imported from Trac
```

Right now one can do:
- single day booking
- once a week
- once every 2 weeks
- once every 3 weeks
- once a month

It is not possible to do it once every 4 weeks (different to 1 month).

A possible solution would be to do something like:
- once every [text field] weeks 

Where the user could type the number of weeks.

**Comment by OmeGak** [comment]
Related SNOW ticket `CHG32392`.

**Comment by pferreir** [comment]
Already implemented in 2.2.
