### ISSUE TITLE
Room Booking: Room booking confirmation system

### ISSUE THREAD

**Issue by jbenito3** [indico/indico#1426]
``` yaml
# Ticket imported from Trac
```

Discuss a possible solution to this request (RQF0275369):

Our observation in ATLAS is that a lot of people book rooms for weekly or so meetings and do not release them when they skip meetings or don't need a room. As a net effect this results in a no free rooms to book and rooms not used.

We were wondering if we could change INDICO to allow reservations for weekly meetings, but have INDICO sending a mail e.g. a week before asking for re-confirmation by clicking a link. That way the room would be freed if people do not re-confirm. Could such a feature be implemented ?

**Comment by pferreir** [comment]
This is more of a CERN-internal policy issue which has already been addressed through the room usage policy.
