### ISSUE TITLE
Room Booking: Visual feedback for moderated rooms on list of rooms

### ISSUE THREAD

**Issue by OmeGak** [indico/indico#1433]
``` yaml
# Ticket imported from Trac
```

In previous versions of room listings we had three different kinds of rooms:
- Basic room: everybody can book
- Private room: restricted group can book
- Moderated room: booking requires confirmation from a room manager

In the current version there is no way to tell if the room is moderated (PRE-bookable only).

It should be rather easy to add an icon with a qtip indicating this fact. Even a more polished solution is adding this information as an attribute like ''"Video conference available"\* or *"private"'', so moderated rooms can also be filtered.

**Comment by pferreir** [comment]
Already solved in 2.2.
