### ISSUE TITLE
Room Booking: Create jquery widgets for RoomBooking components

### ISSUE THREAD

**Issue by OmeGak** [indico/indico#1435]
``` yaml
# Ticket imported from Trac
```

The room booking interface makes use of some components in different pages. At the moment, there is code redundancy as both initialization and logic are defined for each .tpl file or in global scope, making them hard to maintain and causing interface inconsistency.

We should wrap them into proper jQuery widgets and integrate methods defined in tools-like files.

These components are:
- Date Range
- Time Range

**Comment by pferreir** [comment]
"Time range" is probably going away, and in any case we're moving to a reactive framework.
