### ISSUE TITLE
Allow participants to decide on a date for a meeting ("Doodle style")

### ISSUE THREAD

**Issue by pferreir** [indico/indico#1459]
``` yaml
# Ticket imported from Trac
```

This could be a nice feature and it has been requested more than once.
I am not sure on how the workflow would go,  but a simple list of choices and a voting mechanism could do it.

**Comment by OmeGak** [comment]
As proposed recently on an email sent to us. Having this doodle take into account available rooms as well would be a plus.

**Comment by ThiefMaster** [comment]
Not sure what's the point of including rooms there. It's not like you need to collaborate with others on choosing the room...

**Comment by OmeGak** [comment]
No, but you want to propose a few rooms and then based on people's and room availability a final date is chosen.

**Comment by ThiefMaster** [comment]
Ah, so it'd be a convenience feature for the user creating the Doodle. That sounds more useful for sure (even though you can't know if the room will still be available when all people have chosen their preferred dates).

**Comment by OmeGak** [comment]
Pre-book maybe until a final date is agreed on?

**Comment by ThiefMaster** [comment]
Not a good idea. Some of those bookings could end up accepted just be be cancelled again...

**Comment by pferreir** [comment]
Preemptive pre-bookings are a risky thing, especially at CERN - imagine the amount of people that have dibs on the rooms in 600-R-*. I think we should start small with this and then add complexity bit by bit. A simple doodle-like thingy would already be pretty nice.

**Comment by pferreir** [comment]
https://github.com/indico/newdle 🍜
