### ISSUE TITLE
Registration Stats

### ISSUE THREAD

**Issue by jbenito3** [indico/indico#1464]
```yaml
# Ticket imported from Trac
```

The current page for stats (registrants) is really old, ugly and useless:

https://indico.cern.ch/ihelp/html/_images/confreg16.png

We should redesign it and we could do something like this:

http://www.napac13.lbl.gov/jacow-spms-cws/html/Participants.html#countries

* Total attendees/day
* Attendees per country
* etc

**Comment by pferreir** [comment]
Fixed in #1456
