### ISSUE TITLE
Registration form: workflow to receive supervisor letter

### ISSUE THREAD

**Issue by jbenito3** [indico/indico#1469]
``` yaml
# Ticket imported from Trac
```

The use case is:
- A user (student) registers in Indico. 
- The registration form has a field in which the student will enter the email address of his supervisor.
- Indico sends an email to the supervisor asking for 'a letter' (any kind, e.g. agreement, consent, feedback, etc)
- Supervisor uploads the letter through Indico
- 'Registrars' are notified.

**Comment by pferreir** [comment]
This seems to be outside Indico's scope. We already have a file upload function too.
