### ISSUE TITLE
Room Booking: Book a Room filtering for custom attributes

### ISSUE THREAD

**Issue by OmeGak** [indico/indico#1475]
``` yaml
# Ticket imported from Trac
```

Generalize the _Require_ buttons to filter by any of the custom attributes. 

We have to come up with a nice and easy way to represent an arbitrary amount of custom attributes both in the filtering buttons and in the list of rooms.

**Comment by pferreir** [comment]
This has already been implemented through "features" which can be assigned to an icon by the admin.
