### ISSUE TITLE
Dashboard: Refactor EventsAtHand into a JS plugin

### ISSUE THREAD

**Issue by OmeGak** [indico/indico#1479]
``` yaml
# Ticket imported from Trac
```

Converting EventsAtHAnd into a full-pledged plugin would allow us to embed it easily anywhere with little effort. This will be handy for the social homepage upgrade and other personal improvements.

**Comment by ThiefMaster** [comment]
The dashboard isn't using JS anymore but renders everything from a Jinja template.
