### ISSUE TITLE
Multi-part lecture links and materials

### ISSUE THREAD

**Issue by indico-bot** [indico/indico#148]
``` yaml
# Ticket imported from Trac
# Reported by: dmartinc
```

When a multi-part lecture is created, little numbered links appear on the display page of each of the event. For example, in the display page of the first lecture there will be a little '2' and '3' that when clicked will lead to the other parts.

Internally, Indico stores this as materials, called "part2", "part3", etc. Each material has a link resource inside, whose name _and_ value are the URL.

So far so good (maybe), but:

-These materials appear in the "Materials" section of the event in the management interface;
-It is possible for the user to accidentally delete the material and thus the link;
-It is possible for an imaginative user to manually create a "part9" material with a link inside, and this will make a little '9' appear in the display page with the link.

On the other hand this system allows Indico admins and support to add new parts to a multi-part lecture, to remove this links, etc.

In any case, it seems that this system is not ideal. Some possible improvements:
-Hide the materials whose name start by "part" and then have a number (the same way they are now recognized in order to display links).
-Add something to the description of these materials (so that an inexpert user knows what's going on).
-Group all the links under 1 material, called "Lecture links", or something. Then each resource has a name "part1", "part2" and a link as value, instead of having the link as name as it is now.
-Ditch the whole system and store these links internally, as linked conference ids or objects. If possible, put an interface somewhere (General-Settings? a new section?) to allow the Event Manager to un-link multi-part lectures or to create a new part.

If we hide the materials or ditch the system, and we don't have some interface somewhere for Event Managers to manage this, we might receive support requests like "I created a 3-part lecture but I would like it to be 4-part", that only indico admins with access to the DB console will be able to perform.

Example:
http://indicobeta.cern.ch/conferenceDisplay.py?confId=71089
http://indicobeta.cern.ch/conferenceModification.py/materialsShow?confId=71089

**Comment by pferreir** [comment]
See #1512 too

**Comment by OmeGak** [comment]
The idea of a **course** that spans over several weeks kind of event also fits here. The actual occurrences of the course would not happen everyday, so they don't fit as a continuous event and should be made as linked events. However, they all would share a big amount of information that should probably stay synchronized.

The way I see it, the **course** would take a step a bit further than the simple idea of series of events, since they all would conceptually form a more compact kind of event rather than separated ones, but the implementation could probably benefit from it.

**Comment by pferreir** [comment]
Already implemented.
