### ISSUE TITLE
Feedback for automatically deleted alarms

### ISSUE THREAD

**Issue by OmeGak** [indico/indico#1504]
``` yaml
# Ticket imported from Trac
```

Alarms scheduled for already finished events are deleted automatically from the scheduler. Whereas this behavior is expected, the list of alarms displayed to the manager doesn't reflect this fact.

We should:
1) Warn the manager when creating a scheduled alarm
2) Display deleted alarms in the alarm log

**Comment by ThiefMaster** [comment]
obsolete since 1.9.x
