### ISSUE TITLE
Electronic Agreement for Subcontributions

### ISSUE THREAD

**Issue by arescope** [indico/indico#1509]
```yaml
# Ticket imported from Trac
```

https://indico.cern.ch/event/273747/manage/collaboration/elecAgree/?sortBy=speaker

**Comment by pferreir** [comment]
This would require changes on the Micala side. We could leave the code already done and just disable the selection in the UI (comment out?).

**Comment by ThiefMaster** [comment]
This is already implemented as a plugin setting.
