### ISSUE TITLE
Registration Summary: show if paid

### ISSUE THREAD

**Issue by jbenito3** [indico/indico#1513]
```yaml
# Ticket imported from Trac
```

The registration summary can be accessed from a unique link like this:

https://indico.cern.ch/event/XXXXX/registration/register/success?authkey=ABCDEFG&registrantId=999

That link is included in the after-registration email to the user. 

Some organisers have reported that users do not remember if they have paid or not, so it would be very useful to display some feedback in that page.

**Comment by nop33** [comment]
This is already implemented right? We have this "[checkbox] Paid" in the invoice box in the registration page.

**Comment by ThiefMaster** [comment]
yes, it's the pretty thing we added that shows unpaid/pending/paid

**Comment by nop33** [comment]
So why not closing the ticket? :)

**Comment by pferreir** [comment]
Done.
