### ISSUE TITLE
File stats are (most likely) not working

### ISSUE THREAD

**Issue by pferreir** [indico/indico#1524]
``` yaml
# Ticket imported from Trac
```

The stats for file downloads don't seem to be working (at least at CERN).
This should be investigated and fixed.

**Comment by pferreir** [comment]
OK, it seems like Piwik cannot do this properly (they won't provide an accurate count). So, we will need to store this ourselves in some way.

**Comment by ThiefMaster** [comment]
feature removed in 3.0
