### ISSUE TITLE
Upcoming events only show public events

### ISSUE THREAD

**Issue by DirkHoffmann** [indico/indico#1526]
``` yaml
# Ticket imported from Trac
```

We are on 1.1.2 now, but apparently no reindexing or cleanup action has corrected the error.

The "Upcoming Events" list on the home page is incomplete.

We have setup two categories to be observed objects in InDiCo. One is the base/root category (0), the other one (6) is a category that does not exist any more. It cannot be deleted though. 

'''This problem with deleting an non-existing category may or may not be related to the main problem described below.'''

Usually none of the upcoming events is displayed in the list at the right border of on the homepage. Sometimes one or two show up, without any obvious systematic reason. Today (April 23rd), I see an upcoming event starting on June 4th. There should be dozens (well, limited to 20 or so) according to the calendar, "today's events" or "this week's events".

**Comment by ThiefMaster** [comment]
This is fixed in 1.9.x/2.0: https://github.com/indico/indico/blob/master/indico/modules/categories/util.py#L140
