### ISSUE TITLE
Category and event organisation

### ISSUE THREAD

**Issue by DirkHoffmann** [indico/indico#1531]
``` yaml
# Ticket imported from Trac
```

The present schema allows
- only categories in a category
- only events in a category.

It would be helpful (cf. discussions in 1st Indico workshop and on project-indico-administrators@c..., Dec 3rd, 2013) to have a more flexible schema:
- mixing: categories + events in a category
- linking: pointer to another category or another event, but displayed exactly like a category or event.
  Linking should be possible cross-Indico-wise (from one server instance to another).

**Comment by DirkHoffmann** [comment]
For reference: The edit "indico-bot commented on May 12, 2014" had been submitted by Albert Shih from OPM (no account on github).

**Comment by pferreir** [comment]
Yes, I recognised his username :smiley:

**Comment by pferreir** [comment]
Sub-categories and events can currently co-exist in Indico 2.0's DB. We still have to work a bit on the UI, though.

**Comment by mvidalgarcia** [comment]
Related SNOW ticket `RQF0918880`

**Comment by DirkHoffmann** [comment]
What is a SNOW ticket? 👿

**Comment by ThiefMaster** [comment]
CERN's internal support ticket tracker (service-now)

**Comment by Eothred** [comment]
We started out with a brief set of categories, then ended up with a ton of events in certain categories which I think would make sense to split out further. Being allowed to mix sub-categories and events in a given category would be a great help in this situation.

**Comment by ThiefMaster** [comment]
mixed content is possible as of v3; and I think we have another issue suggesting linked events
