### ISSUE TITLE
Ellipsis dots show outside box (IE)

### ISSUE THREAD

**Issue by pferreir** [indico/indico#1536]
``` yaml
# Ticket imported from Trac
```

The ellipsis dots sometimes show up outside the boundaries of a block in a timetable that is particularly packed.

![dotoutsideblock](https://cloud.githubusercontent.com/assets/2699/6017147/40dface8-ab8b-11e4-8d27-5587ccf5de23.GIF)

**Comment by jacquesd** [comment]
The fix in #1762 is not optimal as hiding the overflowing text using CSS hides too much of the content. There is unfortunately no simple way to fix this.

**Comment by ThiefMaster** [comment]
IE is no longer relevant
