### ISSUE TITLE
Removal of LocalIds not possible after switch to LdapAuthenticator

### ISSUE THREAD

**Issue by DirkHoffmann** [indico/indico#1539]
```yaml
# Ticket imported from Trac
```

There is a bug, or at least an inconsistency between 
https://github.com/indico/indico/blob/master/indico/MaKaC/authentication/AuthenticationMgr.py#L125
and 
https://github.com/indico/indico/blob/master/bin/utils/removePasswords.py#L45

The call to `AuthenticationMgr.removeIdentity()` should remove an instance of `LocalIdentity()`. Let's call it `id`.
However, in the `remove()` method as well as in the `add()` method of `class AuthenticationMgr` there is a call to `self.getById( id.getAuthenticatorTag()`. The `id.getAuthenticatorTag()` must be `'Local'` in this case.
However, if the `LocalAuthenticator` is switched off in the configuration, the call to `AuthenticationMgr.getById()` returns a `None` object. Thus removal of "old" LocalIds from the Avatars will not work with the given code.

Proposed solution(s): 
1. (workaround) Hardcode call to `LocalAuthenticator.remove(id)` instead of `AuthenticationMgr().removeIdentity(id)`.
2. (better) Add method `AuthenticationMgr.getByIdWhateverAuthenticatorIsActiveOrNot()` which gets the right authenticator in any case. Use that in `add()` and `remove()`.

**Comment by DirkHoffmann** [comment]
All right, if you want this to be in for v1.2.1 next month, you can assign it to me, and I will give it a try within the limited time.
I updated the description, referencing github and according to the new function name.
The change in the MaKaC code is trivial enough, but I guess you want to test it nevertheless in a web framework. I don't know how to do that (and will have no time to setup an environment). Can anybody else do it in case?
I have enough test cases for the interactive (cmdline) part though.
I will also need instructions as what to clone exactly (branch v1.2 I guess) and where to start. Assuming that the pull request will be made correctly over github, once I committed the patches back in my repository there.

**Comment by pferreir** [comment]
Given that this is not a serious bug, the time constraints and that we are going to rewrite this part very soon, I'd say let's schedule it for 1.9.2.
Let's just make sure that removal of accounts whose authenticators (or whatever we call then from now on) are disabled should work.

**Comment by DirkHoffmann** [comment]
Sure, if it is going to be rewritten, there is no point in patching the code.
However, I am not sure to understand "let's just make sure that removal [...] should work". AFAIR, that was exactly the whole point. Removal does not work.
So what is the proposal exactly?

**Comment by pferreir** [comment]
What I mean is that, once we rewrite the code, we should do it in a way that fixes the issue (removal should work) :wink:

**Comment by pferreir** [comment]
Removal should now work (1.9.2).

**Comment by DirkHoffmann** [comment]
What exactly is the rule now? Are "Avatars without Id" allowed (again, as before 1.0 or so)? Removal of Ids is certainly useful for some cases (like admin paranoia) and less critical than removal of Avatars. Come-back users would be mergeable (or auto-merged) when they have a new Id (after internal or external registration).
It would be worth mentioning the exact rule in the documentation (wiki?) somewhere, in the part that also the "advanced users" (like Indico instance admin without computing knowledge) read.

**Comment by ThiefMaster** [comment]
The whole AuthenticationMgr is gone. If you want to remove local accounts in 1.9.2, you'd simply use SQL for it, e.g. this:

    Identity.find(provider='indico').delete()

**Comment by DirkHoffmann** [comment]
Okay, no need (and no time from my side) to go into details right now. But I hope there is still the possibility to remove `Id`s from `Avatar`s by HTTP(S) for the admins. When users leave an organisation, some admins don't like to "see" the logins still attached to a deactivated `Avatar`. And in some cases it may be wanted to reuse an old UID for a new, totally disconnected user, if it happens to be like `einstein` or another VIP.

**Comment by ThiefMaster** [comment]
Ah yes, that's easily possible:

![accounts](https://cloud.githubusercontent.com/assets/179599/7495037/a5ad1bc4-f40b-11e4-91c7-36ea331538b8.png)

**Comment by ThiefMaster** [comment]
One could even have a periodic task that checks e.g. all accounts currently used in Indico against the LDAP server and remove them if they don't exist there anymore.

**Comment by DirkHoffmann** [comment]
Today (7:19am) Adrian wrote:

> 
> Ah yes, that's easily possible:

Nice mouth-watering answer :-)
