### ISSUE TITLE
Easy way to search "bookings for me"

### ISSUE THREAD

**Issue by OmeGak** [indico/indico#1548]
``` yaml
# Ticket imported from Trac
```

"Search bookings" allows specifying the criteria for searching bookings for any user. However, it's not clear how to quickly make a search of bookings made for the current user, and on top of it, some get confused as the distinction between bookings made by the user and for the user is not clear. A good example of this issue is ticket INC0585508 in Service Now.

Some ideas to address the issue:
1. Add a link in the side-menu with "Bookings for me"
2. Extend the meaning of "My bookings" by showing also bookings the current user with the possibility of hiding those not made by him/her.
3. Add a button in the "Search bookings" form to fill the field with the current user.

**Comment by pferreir** [comment]
In version 2.2, we display under "my bookings" both reservations made by the user and for the user. Having a way to discriminate between the two doesn't seem to add much value. So, I believe the solution we have now come to should be enough to address the original question.
