### ISSUE TITLE
Avoid Whoosh LockErrors

### ISSUE THREAD

**Issue by ThiefMaster** [indico/indico#1581]
``` yaml
# Ticket imported from Trac
```

Whoosh only allows one writer at a time so opening another one fails with a !LockError. This is bad UX since users might get an error when trying to create an event if the index is locked.

Using Whoosh's !AsyncWriter would most likely solve this.

**Comment by surajbeston** [comment]
This worked quite good for me
```
from whoosh.index import LockError    
while True:
        try:
            writer = ix.writer()
            break
        except LockError:
            time.sleep(0.2)
```

**Comment by ThiefMaster** [comment]
@surajbeston umm why are you commenting on a 6-year-old issue? The project isn't even using whoosh anymore.
