### ISSUE TITLE
Unexpected behavior when editing session slot start time

### ISSUE THREAD

**Issue by OmeGak** [indico/indico#1583]
```yaml
# Ticket imported from Trac
```

The validation of start time modification of a session slot in the timetable view is not working as expected when there are contributions living inside. 

To reproduce the issue, first assume the following session:

```
14:00 --- Session start ---
    14:10 ~ 15:00 Contribution
15:00 --- Session end ---
```

Trying to modify the start time of the session from 14:00 to 14:10 triggers an error dialog with the following message:

  The session slot cannot end at (2014-10-12 14:50) because there is a contribution (2014-10-12 15:00) ending after that time.

So it seems that instead of pushing back by 10 minutes the end time, we are doing the opposite and thus triggering the error message.

This problem is reproducible both from the session details qtip and basic edition dialog.

**Comment by pferreir** [comment]
Fixed in 7105cf960bd2256872864720c6df8cb51bd1e254.
