### ISSUE TITLE
Validate "from" field before sending

### ISSUE THREAD

**Issue by pferreir** [indico/indico#1584]
``` yaml
# Ticket imported from Trac
```

When mass mailing conference registrants, people can basically write whatever they want as "From" address. An invalid address will result in the SMTP server refusing the e-mail (which the user never gets to know about, BTW).
## Part II

The whole e-mail sending form is old and awful-looking. It might be worth re-doing it from scratch.

**Comment by ThiefMaster** [comment]
We already restrict it to addresses used somewhere else in the event.
