### ISSUE TITLE
Create a timetable layout with weekdays as columns

### ISSUE THREAD

**Issue by pferreir** [indico/indico#16]
``` yaml
# Ticket imported from Trac
```

```
I would like to have a layout for the timetable with the weekdays as columns

Cheers

Ola
```

This has been discussed previously. Will require changes in the TT architecture, though, since the timetable is organized it a "tab-per-day" logic.
The other issue is that of how parallel events in the same day will be handled.

**Comment by 2xB** [comment]
This sounds like today, **Indico Weeks View** and **Compact Style** fulfill this?
