### ISSUE TITLE
Filtering a timetable by sessions fails after resetting the filter on IE9

### ISSUE THREAD

**Issue by OmeGak** [indico/indico#1600]
The dropdown menu doesn't show up. Steps to reproduce the bug on this [event](https://indico.cern.ch/event/342240/timetable/#20141007.detailed):
- Filter (about on top right)
- Sessions (at bottom of page) -> Deselect all, but not Introduction. (this works OK)
- Click outside to get rid of the little window.
- Reset Filter (works OK)
- Click again on Sessions button. It does not show up the window to select sessions anymore!
- Only a reload of the page makes it work again.

**Comment by ThiefMaster** [comment]
IE is no longer relevant
