### ISSUE TITLE
Room Booking: Store date/time from Room Search and use it in Booking Form

### ISSUE THREAD

**Issue by pferreir** [indico/indico#1618]
Scenario:
1. Select "Search Rooms"
2. Select "Available" and a random date
3. Click "Search"
4. Click "book" on one of the rooms that are listed
5. The date will be that of today, not the one that was selected in the search

While this is not a bug, it would simplify the workflow for room booking users that use this functionality.

**Comment by nop33** [comment]
This was mentioned again in a SNow ticket. Created Change Request: `CHG34123`

**Comment by pferreir** [comment]
This interface will be rewritten and merged with the booking process. This ticket can go away.
