### ISSUE TITLE
Non-existing users remain in ACL

### ISSUE THREAD

**Issue by OmeGak** [indico/indico#1619]
We've been receiving a few tickets and error reports caused by this bug lately.

The issue is that Avatars that don't exist anymore in the database remain in the ACL or Modification Lists. Not only that, it's impossible to remove from those lists, so they keep showing in the interface and event managers keep asking us to remove them manually.

We should at least check if the user don't exist anymore when trying to revoke access/modification from the interface, and then delete it from the list anyway.

**Comment by pferreir** [comment]
This should be something to check in 1.9.2.

**Comment by pferreir** [comment]
Actually, 1.9.7 makes more sense.

**Comment by ThiefMaster** [comment]
We already remove broken entries from AccessController modifier/access lists when retrieveing them

**Comment by pferreir** [comment]
Ah, true. Then, let's just close this issue.
