### ISSUE TITLE
LDAP plugin crashes for more then one email address in the mail field

### ISSUE THREAD

**Issue by dietrichliko** [indico/indico#1638]
Hi!

In my LDAP there some entries with multiple email addresses. There are several places
in LDAPAuthentication.py that assume that the mail returned from LDAP is a string and
not - as in my case - a list of strings. 

The most easy solution is to simply use the first email. As indico
supports additional emails in a seperate attribute, one could implement a more fancy solution ...

Cheers, Dietrich

I had to patch at three places to get it working for me.

In the method createUser of class LDAPAuthenticator I added:

mail = udata['email']
if isinstance(mail,list):
   mail = mail[0]
av.setEmail(mail)
(for example)

In authenticate of LDAPIdentity

strip does not work on list, so same logic

in findUser of LDAPConnector

Here the variable is ret['mail'], which is not hashable, when its a list.

**Comment by pferreir** [comment]
Fix for 1.2 merged in 724c0ab2e307311748b4dd6005ca9e862c6f8a81.
