### ISSUE TITLE
Migrate the E-payment modules

### ISSUE THREAD

**Issue by pferreir** [indico/indico#1646]
- [x] Core E-payment processing
    - [x] Create unit tests
    - [x] Create migration for transactions table
    - [x] Show some transaction data on the edit registrant page (add new method to payment plugins for it)
 - [x] CERN E-Payment (check convergence with YellowPay?)
    - [x] Create form to submit the POST request
    - [x] Test with the developer account
    - [x] Authenticate received response
    - [x] Store transactions
 - [x] Paypal
    - [x] Verify paid amount, inform organizer in case of inconsistency
    - [x] Test amount verification by altering the amount before paying
    - [x] Use requests instead of urllib? (test at Adrian's)
    - [x] Better UX when Pending transaction status
 - [ ] ~~Skipjack (does anyone use it?)~~
 - [ ] ~~Worldpay (same?)~~
 - [x] "YellowPay" (called PostFinance nowadays) (completely unused!)
 - [x] Test everything with a registrant w/o an indico account

**Comment by ThiefMaster** [comment]
Current payment module usage (number of events, only those that have at least one transaction for that module):
```python
[('TransactionPayLaterMod', 69),
 ('FIASpayTransaction', 2),
 ('TransactionPayPal', 13),
 ('TransactionWorldPay', 1),
 ('TransactionCERNYellowPay', 71)]
```

**Comment by pferreir** [comment]
Yeah, it's clear that worldPay, skipjack and FIAS won't be ported. And YellowPay will be left for a second phase.

**Comment by pferreir** [comment]
Implementation done.
