### ISSUE TITLE
Webcast/recording request - highlight that people have to sign the agreement 

### ISSUE THREAD

**Issue by pferreir** [indico/indico#1647]
Right now, the warning is pretty discrete:

![e-agreement warning](https://cloud.githubusercontent.com/assets/2699/4919202/331bcdf0-64f8-11e4-9c87-7a1527b7fd5b.png)

We should make it more visible.

However, there are other (nice) things we could do:
 * Show the warning only after the request has been approved (or at least make it more discrete otherwise?)
 * Mention the fact that the signatures are needed on the notification e-mail (add link)

**Comment by ThiefMaster** [comment]
In v1.9.1 the warning is only shown (in a less discrete way) if the request is accepted and there are unsigned agreements.
