### ISSUE TITLE
Groups in the OpenDirectory LDAP

### ISSUE THREAD

**Issue by dietrichliko** [indico/indico#1654]
Hello!

Sorry, I have another issue with my LDAP, which is OpenDirectory from MacOSX.

Groups are implemented in a way similar to SLAPD, but are not compatible. The groups 
do not contain the "dn" of the members, but the "uid" in an attribute "memberUid".

For my use case I could fix it in a straight forward way by adding a further LDAP 
style "OpenDirectory". I found two relevant places in LDAPAuthentication.py

I do not know, if other LDAP implementations use other variations ...

Cheers, Dietrich

class LDAPConnector 

method userInGroup
```
        elif self.groupStyle == 'OpenDirectory':
            query = 'memberUid={0}'.format(login)
            res = self.l.search_s(groupDN, ldap.SCOPE_BASE, query)
            return res != []
```
method findGroupMemberUids
```
        elif self.groupStyle == 'OpenDirectory':
            #read member attibute values from the group object
            memberUids = None
            res = self.l.search_s(groupDN, ldap.SCOPE_BASE)
            for dn, data in res:
                if dn:
                    memberUids = data['memberUid']
            Logger.get('auth.ldap').debug('findGroupMemberUids(%s) returns %s' % (group, memberUids))
            return memberUids
```

**Comment by pferreir** [comment]
OK, I'm afraid we don't have the time to produce a proper workaround for 1.2 (and this is kind of a niche product, so maybe you can just use a patched version for now), but I will make sure we offer better customisation options in 1.9.2 (2.0). I'm leaving this open as a reminder.

**Comment by pferreir** [comment]
Maybe you can try out our new authentication library?

https://gist.github.com/jacquesd/836e566c3b272fc55ac3

It is pretty versatile and we'd be very glad to have feedback on it!
