### ISSUE TITLE
Allow events to be favorited (added to dashboard)

### ISSUE THREAD

**Issue by pferreir** [indico/indico#1662]
Right now, only categories can be added. Adding events can be pretty useful e.g. for conferences or lectures.

---

Main tasks to do here:

- Add UI for users to toggle favorite event state (ideally a small react component)
- Create backend to store the user's favorite events (similar to category favorites)
- Take favorite events into account when determining category suggestions
- Show favorite events on dashboard in "Your events at hand" with a new role icon ("Favorite" ⭐)

**Comment by ThiefMaster** [comment]
When we add this, we should also take into account that the CERN calendaring plugin should add such events to the user's calendar.
