### ISSUE TITLE
Trying to migrate from 0.98-rc1 to Indico 1.2

### ISSUE THREAD

**Issue by satoledano** [indico/indico#1667]
Got this error while executing `migrate.py`:

```
# Indexing Conference Title (1.1)

Migration failed! DB may be in  an inconsistent state:
Traceback (most recent call last):
  File "/opt/indico/bin/migration/migrate.py", line 1096, in main
    dry_run=args.dry_run)
  File "/opt/indico/bin/migration/migrate.py", line 1042, in runMigration
    task(dbi, withRBDB, prevVersion)
  File "/opt/indico/bin/migration/migrate.py", line 771, in indexConferenceTitle
    nameIdx.index(conf.getId(), conf.getTitle().decode('utf-8'))
  File "/usr/lib/python2.6/site-packages/indico-1.2-py2.6.egg/MaKaC/common/indexes.py", line 1254, in index
    intId = self.addString(entryId)
  File "/usr/lib/python2.6/site-packages/indico-1.2-py2.6.egg/MaKaC/common/indexes.py", line 1193, in addString
    raise KeyError("Key '%s' already exists in index!" % stringId)
KeyError: "Key '10' already exists in index!"
```

**Comment by pferreir** [comment]
Hi. Any news on this?

**Comment by clerian** [comment]
Hello,

I've got the same problem when migration from indico 1.0. The only difference is that it is Key '2' in my case. 

I tried to resolve it by running the various reindex scripts under bin/maintanance but this didn't help. I've also tried to run the migration script several times on a new database copy and on a reindexed version.

thanks!

**Comment by satoledano** [comment]
I solved this, now I need to remember how...

On Wed, Apr 1, 2015 at 4:04 AM, clerian <notifications@github.com> wrote:

> Hello,
>
> I've got the same problem when migration from indico 1.0. The only
> difference is that it is Key '2' in my case.
>
> I tried to resolve it by running the various reindex scripts under
> bin/maintanance but this didn't help. I've also tried to run the migration
> script several times on a new database copy and on a reindexed version.
>
> thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/indico/indico/issues/1667#issuecomment-88441114>.
>



-- 
Soledad Antelada Toledano
IT Division
Lawrence Berkeley National Laboratory
1 Cyclotron Road, Mail Stop 50B2215
Berkeley, CA  94720-8226

Office: (510) 486-6861

SAToledano@lbl.gov

**Comment by satoledano** [comment]
I think this is one of the things that worked for me

https://github.com/pferreir/indico/commit/074728b268e93fce2a209e1d57d715aabcba8e1d.diff


On Wed, Apr 1, 2015 at 3:07 PM, Soledad Antelada Toledano <
satoledano@lbl.gov> wrote:

> I solved this, now I need to remember how...
>
> On Wed, Apr 1, 2015 at 4:04 AM, clerian <notifications@github.com> wrote:
>
>> Hello,
>>
>> I've got the same problem when migration from indico 1.0. The only
>> difference is that it is Key '2' in my case.
>>
>> I tried to resolve it by running the various reindex scripts under
>> bin/maintanance but this didn't help. I've also tried to run the migration
>> script several times on a new database copy and on a reindexed version.
>>
>> thanks!
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/indico/indico/issues/1667#issuecomment-88441114>.
>>
>
>
>
> --
> Soledad Antelada Toledano
> IT Division
> Lawrence Berkeley National Laboratory
> 1 Cyclotron Road, Mail Stop 50B2215
> Berkeley, CA  94720-8226
>
> Office: (510) 486-6861
>
> SAToledano@lbl.gov
>
>
>


-- 
Soledad Antelada Toledano
IT Division
Lawrence Berkeley National Laboratory
1 Cyclotron Road, Mail Stop 50B2215
Berkeley, CA  94720-8226

Office: (510) 486-6861

SAToledano@lbl.gov

**Comment by clerian** [comment]
Thanks, your comment pointed me in a good direction. It didn't work for me, but what I did is:

changing line 773 in migrate.py ( nameIdx.index(conf.getId(), conf.getTitle().decode('utf-8')) )

to be:
try:
            nameIdx.index(conf.getId(), conf.getTitle().decode('utf-8'))
        except KeyError:
            print console.colored('conference ID: {0} has a problem, skipping'.format(conf.getId()), 'red')


I had 3 or 4 broken entries, but the everything else just worked and the indico installation is now working.

**Comment by pferreir** [comment]
The changes mentioned by @satoledano are already in the latest 1.2 branch. I'll close the ticket.
