### ISSUE TITLE
Update/cleanup dependencies

### ISSUE THREAD

**Issue by ThiefMaster** [indico/indico#1673]
- [ ] Remove indirect dependencies from our requirements.txt (we should only reference packages we directly depend on, not dependencies of our dependencies) unless we need a newer version than required (e.g. jinja should remain in requirements.txt even though flask already requires it)
- [ ] Check if we have dev-only dependencies in requirements.txt and move them to requirements-dev.txt
- [ ] Check/update the remaining dependencies

**Comment by smartass101** [comment]
I would also like to add that having hardcoded versions (`package==version`) in dependencies is not a good idea (at least in the long term) for several reasons:
- some packages like `pytz` become obsolote quite quickly
- maintainers of packages on pypi might remove older versions from pypi
- prevents usage of packages in newer distributions and thus requires needless compilation, as is the case with e.g. lxml

I think you could specify only the minimum version in most cases (`package>=version`).

**Comment by ThiefMaster** [comment]
I think there are three cases:

- Core dependencies such as Flask or SQLAlchemy. Those should always have a specific version required. Otherwise a minor upgrade might break things  due to a regression. This happened in SQLAlchemy before but was quickly spotted when updating locally. So those dependencies should never switch to another version but the one a developer has already tested locally
- Simple libraries, like pytz, lxml, certifi, translitcodec or Python 3 stdlib backports (enum34). Those should not require a specific version (or only a minimum version). We already do this for some newly added entries in requirements.txt, but the whole idea of this issue is to clean it up more and use more sane values.
- Dependencies of libraries we use. Those do not belong into our requirements.txt at all unless we require a newer version than the minimum version required by the library. Jinja is a good example. Flask only requires Jinja 2.4, but we want 2.8 because of features not present in older versions. So it's something where we want to require that version.

**Comment by smartass101** [comment]
I agree with the app-critical dependencies. Other libraries like libxml (most importantly those that are more complicated to build) that have a reasonably stable API should really only specify the minimum version required. I also agree with the exceptions to lower-level dependencies. I'm looking forward to a simpler installation :smile:

**Comment by pferreir** [comment]
I think even "simple libraries" can be pretty dangerous. It happened in the past that libraries of that nature substantially changed their API in between versions. It would be nice to be able to lock ourselves to a major version while allowing minor versions upgrades to be performed. That will only be dangerous if the library maintainer ignores semantic versioning, which still happens sometimes but is rare.

**Comment by pferreir** [comment]
[Apparently](http://stackoverflow.com/questions/8795617/how-to-pip-install-a-package-with-min-and-max-version-range), `pip` supports version ranges. That could be a solution.

**Comment by smartass101** [comment]
AFAIK `easy_install` also uses setuptools, so it [should support it too](https://pythonhosted.org/setuptools/pkg_resources.html#requirements-parsing). However, I fully support a migration to `pip`.
