### ISSUE TITLE
Federated login with multiple mails

### ISSUE THREAD

**Issue by fmarco76** [indico/indico#1691]
The field mail returned by an IdP can contain multiple values and in this case the match does not work properly because it try to compare the full list with the single mail in the Avatar. Actually, it seems the system is designed to manage only a single mail coming from the IdP.

Using shibboleth the multiple mails are returned as semi-colon separated list of mails.

At the end a new account is created with the mail field contains the list of mails returned by the IdP instead of a single mail and the others as secondary emails.

**Comment by ThiefMaster** [comment]
Obsolete since the rewrite of the user/authentication system.
