### ISSUE TITLE
CSS Customisation problem

### ISSUE THREAD

**Issue by fmarco76** [indico/indico#1695]
The css theme load as first file among the css files so many element cannot be easily customised because they are defined in following css. Would be nice to have the css theme files loaded at the end in order to allow easier customisation

**Comment by pferreir** [comment]
Thanks. We'll soon rewrite the theme engine. I'm keeping this open as a reminder.

**Comment by ThiefMaster** [comment]
Conference CSS is included after everything else (except global customization css) now.
