### ISSUE TITLE
customUserFilter not working like expected

### ISSUE THREAD

**Issue by hger** [indico/indico#1707]
When setting the customUserFilter in /opt/indico/etc/indico.conf on indico 1.2 to objectCategory=user I expect the search result to only return objects of type user. This is not the case. It will also return object of type: Contact

If I search using a simple python script like so:
```python
#!/usr/bin/python
try:
    import os, sys, ldap
except Exception, error:
    print "Error, missing required modules: " + str(error)
    sys.exit()
domainID = 'esss.lu.se'
whoisthis = 'someone@some.where.se'
def ldapSRV():
    ldapSRVS = os.popen('/usr/bin/host -t SRV _ldap._tcp.dc._msdcs.' + domainID).readlines()
    ldapSRV = ldapSRVS.pop().strip().split().pop()
    return ldapSRV
who = 'readonly@' + domainID
cred = "Password"
base = 'DC=esss,DC=lu,DC=se'
scope = ldap.SCOPE_SUBTREE
query = '(&(objectclass=*)(mail=' + whoisthis + '))'
res_attrs = ['*']
try:
    srv = ldapSRV()
    l = ldap.open(srv)
    l.simple_bind_s(who, cred)
    print "Successfully bound to server " + srv
    l.set_option(ldap.OPT_REFERRALS, 0)
    res = l.search_ext_s(base, scope, query, ['Name'])
    l.unbind_s()
except ldap.LDAPError, error_message:
    print('Could not Connect: %s ' % error_message)
print(res)
```
I get this information:
`[('CN=one some,OU=acclists,OU=Mail Contacts,OU=Exchange,DC=esss,DC=lu,DC=se', {'name': ['one some']})]`

If i change this line:
`query = '(&(objectclass=*)(mail=' + whoisthis + '))'` to
`query = '(&(objectclass=user)(mail=' + whoisthis + '))'`
i get an empty result as the object is not a user object.
This is how indico should behave when configured like below?

Please advice

Below is the relevant code from the indico.conf file.

`AuthenticatorList    = [('Local', {}), ('LDAP', {'uri': 'ldap://esss.lu.se:389', 'useTLS': True, 'peopleDNQuery': ('sAMAccountName={0}', 'DC=esss,DC=lu,DC=se'), 'groupDNQuery': ('sAMAccountName={0}', 'DC=esss,DC=lu,DC=se'), 'groupStyle': 'ActiveDirectory', 'accessCredentials': ('CN=readonly,CN=Users,DC=esss,DC=lu,DC=se','Password'), 'customUserFilter': "(objectCategory=user)"})]`

**Comment by pferreir** [comment]
I guess it all depends on what is being used in your own LDAP server? Here at CERN `objectCategory=user` seems to work. But it depends on your directory, really.

**Comment by hger** [comment]
ok
