### ISSUE TITLE
Search box: "only this category" button broken on ipad

### ISSUE THREAD

**Issue by ThiefMaster** [indico/indico#1713]
Reported in INC0707585. Apparently pressing it immediately switches back to "search everywhere" in v1.9. Needs to be tested both in 1.9 and 1.9.1, but chances are good that it's broken in both versions since we didn't change that much in the JS code of the search plugin.

**Comment by pferreir** [comment]
This button looks great on a desktop but it's true that is not very usable on touch screens. This should be addressed.

**Comment by ThiefMaster** [comment]
Legacy search. no longer relevant.
