### ISSUE TITLE
easy_install failed

### ISSUE THREAD

**Issue by egamby** [indico/indico#1718]
Hi,

I tried to install indico 1.2 using easy_install but it failed:

Searching for indico
Reading http://pypi.python.org/simple/indico/
Reading http://indico-software.org
Reading http://indico-software.org/wiki/Releases/Indico0.98-rc1
Reading http://indico-software.org/wiki/Releases/Indico0.98.0
Reading http://indico-software.org/wiki/Releases/Indico0.98.1
Reading http://indico-software.org/wiki/Releases/Indico0.98.2
Reading http://indico-software.org/wiki/Releases/Indico0.99
Reading http://indico-software.org/wiki/Releases/Indico1.0
Reading http://indico-software.org/wiki/Releases/Indico1.1
Reading http://indico-software.org/wiki/Releases/Indico1.2
No local packages or download links found for indico
error: Could not find suitable distribution for Requirement.parse('indico')

I think this is because http://indico-software.org now redirects to https://indico.github.io.

I downloaded to egg instead.

Best Regards,
Emmanuel

**Comment by ThiefMaster** [comment]
Hi, I've just disabled the redirect for the wiki/Releases pages. They don't look pretty when opened in a browser but easy_install should be able to get the download links from there. Could you try again and see if it works?

**Comment by egamby** [comment]
Hi, It works now. Thanks!
