### ISSUE TITLE
Non bookable periods are not displayed nor checked on the view

### ISSUE THREAD

**Issue by OmeGak** [indico/indico#1722]
Non bookable periods are similar to blockings as they prevent reservations to be created. However, we don't display them in any calendar view nor do any check for them during the reservation workflow. This leads to people trying to book rooms that are not bookable and then getting an error in the last step because no occurrences could be created for that day without giving any particular reason as to why.

We should:
- [x] Add visual feedback in the calendar view (similar to blockings maybe?)
- [x] Prevent people to go past the second step of the reservation workflow
## Screenshots

The room is unavailable for that day but it show up normally. The green bar can be clicked and brings you to the next page. 

![screenshot from 2015-01-13 10 44 15](https://cloud.githubusercontent.com/assets/716307/5718797/da52b4a4-9b11-11e4-8b82-e8f0e8de1988.png)

On the next page, one can try to pre/book and the error dialog pops up when the server creates no occurrences for the reservation.

![unnamed](https://cloud.githubusercontent.com/assets/716307/5718807/fc11abcc-9b11-11e4-85a1-5469314f35c2.png)

**Comment by ThiefMaster** [comment]
Could possibly be combined with #1609 / #1586 which adds a new bar for nonbookable dates due to advance days.

**Comment by pferreir** [comment]
Maybe @jacquesd can have a look at it once we're done with the e-payment stuff :wink:
