### ISSUE TITLE
Upgrade to WTForms 2.0

### ISSUE THREAD

**Issue by ThiefMaster** [indico/indico#1730]
This would allow stripping whitespace from all fields by default without specifying a filter for it on every single field: https://github.com/wtforms/wtforms/issues/148#issuecomment-70427395
Doing so is quite useful to avoid "dirty" data with leading/trailing whitespace in the DB (usually a whitespace-only string shouldn't be allowed in required fields)

Chances are good that no changes in the code are required, but of course we'll have to check whether we do any magic mostly in IndicoForm that might have to be changed.

**Comment by crast** [comment]
Upgrade guide: http://wtforms.readthedocs.org/en/2.0.2/whats_new.html
