### ISSUE TITLE
Reservations in the future can't be modified to an earlier date

### ISSUE THREAD

**Issue by OmeGak** [indico/indico#1731]
When trying to modify a reservation, users can't select a day prior to the day the reservation was initially created for because the days in the calendar appear grayed out.

This is what happens:

    Today |----------- invalid dates -----------| Reservation |------------ valid dates
    19 Jan                                          12 Feb

This is what should happen:

    Today |------------ valid dates ------------| Reservation |------------ valid dates
    19 Jan                                          12 Feb

**Comment by OmeGak** [comment]
Nothing important, but looking at your patch I see the following issue. As @ThiefMaster pointed out today, we allow the original start date in order to apply modifications that don't change the date. However, with the current logic we allowing to change the start date to a later one that it still is in the past, while I think we shouldn't.

This is the situation right now:

    Start |----- valid dates -----| Today |----- valid dates -----| End
    5 Jan                           21 Jan                          12 Feb

I think it should be like this:

    Start |---- invalid dates ----| Today |----- valid dates -----| End
    5 Jan                           21 Jan                          12 Feb

**Comment by ThiefMaster** [comment]
I don't think that's really necessary. We do record all kind of changes, so someone changing old bookings on purpose to shorten them (for whatever reason) would leave traces.

**Comment by OmeGak** [comment]
But do we want to allow it?

**Comment by ThiefMaster** [comment]
If we change the logic I think we should disallow *any* modification of booking dates that are in the past. So if the start date is in the past, don't let the user modify that date at all.

**Comment by OmeGak** [comment]
Why not? :+1:
Opinions @pferreir?

**Comment by pferreir** [comment]
I think it makes perfect sense. We should let the user change dates that are in the future. That can be the end date or both, depending on whether the booking has already had its first occurrence.
I cannot see any problem with that, why would anyone want to move a booking that is already happening anyway?
If this is easy to implement, I'd fix it now. Otherwise, we can open a ticket for this.

**Comment by jacquesd** [comment]
Re-closing this issue as the fix for it has been committed and the following issue now has its own ticket (#1753) and a PR with the fix (#1756).
