### ISSUE TITLE
Provide proper install docs using virtualenv

### ISSUE THREAD

**Issue by pferreir** [indico/indico#1737]
This would allow people to use the same strategy that we are already using in production, of properly isolating the Indico environment.

**Comment by ThiefMaster** [comment]
I think it would make perfect sense to only officially support a virtualenv-based setup as of 2.0...

**Comment by pferreir** [comment]
Yes, that would be the idea. Sorry if I wasn't clear, but the idea is basically to only provide support for that kind of setup.

**Comment by ThiefMaster** [comment]
https://docs.getindico.io/en/latest/installation/
