### ISSUE TITLE
Wiki pull request

### ISSUE THREAD

**Issue by DirkHoffmann** [indico/indico#1739]
Please pull latest changes from 
 `git@github.com:DirkHoffmann/indico.wiki.git`
or 
 `https://github.com/DirkHoffmann/indico.wiki.git`.

**Comment by pferreir** [comment]
Thanks a lot! I have merged them, and added some small changes (mainly using the same syntax for links everywhere: `[...](...)`.

**Comment by DirkHoffmann** [comment]
I am amazed it works :-)

**Comment by pferreir** [comment]
:astonished:

**Comment by DirkHoffmann** [comment]
The hard part will be for me now to sync my repos back with your changes. (I skip my public mourning about SVN :wink: 
After 40, one should learn 10 new things per year to keep the brain in shape. Someone told me that learning chinese counts for two things. Then git counts for three! :grinning: 
Just discovered :smiley_cat: and his family :smile_cat: :smiling_imp: :baby_chick: …. Now playing :+1: (Counts for another one to learn them all by heart.)
