### ISSUE TITLE
Register for conference error

### ISSUE THREAD

**Issue by hger** [indico/indico#1742]
We have many people that are trying to register for conferences that fail. The error message seems to indicate some problems talking with our LDAP server. We also had problems logging in to indico using our LDAP accounts using TLS so I rewrote the routine that starts the session with TLS, see below. (in file: LDAPAuthentication.py)
```python
    def open(self):
        """
        Opens an anonymous LDAP connection
        """
        self.l = ldap.initialize(self.ldapUri)
        self.l.set_option(ldap.OPT_REFERRALS, 0)
        self.l.set_option(ldap.OPT_X_TLS_CACERTFILE, '/etc/ssl/certs/gd_bundle.crt')
        self.l.set_option(ldap.OPT_X_TLS_NEWCTX, 0)

        self.l.protocol_version = ldap.VERSION3

        if self.ldapUseTLS:
            self.l.set_option(ldap.OPT_X_TLS, ldap.OPT_X_TLS_ALLOW)
        else:
            self.l.set_option(ldap.OPT_X_TLS, ldap.OPT_X_TLS_NEVER)

        if urlparse(self.ldapUri)[0] != "ldaps" and self.ldapUseTLS:
            self.l.start_tls_s()

        return self.l
```
Now the errors seem to indicate tls errors again but in a different python script:
```
Error details

exception message => {'desc': 'Connect error'}
exception type => <class 'ldap.CONNECT_ERROR'>
traceback => 
  File "/usr/lib/python2.7/site-packages/indico-1.2-py2.7.egg/MaKaC/webinterface/rh/base.py", line 522, in process
    res = self._process()

  File "/usr/lib/python2.7/site-packages/indico-1.2-py2.7.egg/MaKaC/webinterface/rh/registrationFormDisplay.py", line 147, in _process
    matchedUsers = AvatarHolder().match({"email": email}, exact=1)

  File "/usr/lib/python2.7/site-packages/indico-1.2-py2.7.egg/MaKaC/user.py", line 1248, in match
    matches = authenticator.matchUser(criteria, exact=exact)

  File "/usr/lib/python2.7/site-packages/indico-1.2-py2.7.egg/MaKaC/authentication/LDAPAuthentication.py", line 181, in matchUser
    ldapc = LDAPConnector.getInstance()

  File "/usr/lib/python2.7/site-packages/indico-1.2-py2.7.egg/MaKaC/authentication/LDAPAuthentication.py", line 349, in getInstance
    connector.open()

  File "/usr/lib/python2.7/site-packages/indico-1.2-py2.7.egg/MaKaC/authentication/LDAPAuthentication.py", line 402, in open
    self.l.start_tls_s()

  File "/usr/lib/python2.7/site-packages/python_ldap-2.4.18-py2.7-linux-x86_64.egg/ldap/ldapobject.py", line 571, in start_tls_s
    return self._ldap_call(self._l.start_tls_s)

  File "/usr/lib/python2.7/site-packages/python_ldap-2.4.18-py2.7-linux-x86_64.egg/ldap/ldapobject.py", line 106, in _ldap_call
    result = func(*args,**kwargs)

request handler => MaKaC.webinterface.rh.registrationFormDisplay.RHRegistrationFormCreation
url => https://indico03.esss.lu.se/indico/event/277/registration/register
```
So do I need to change also this file to use same setup as above?
Or could this error signify something else?
Please advice. 

I have roughly 100 of these errors meaning 100 people that cannot register for conferences here in Lund. This is a big issue for us.
/Håkan

**Comment by pferreir** [comment]
Which file do you mean? `LDAPAuthentication.py` should be the only place to change (only `start_tls_s()` call).
And do you mean that it works for some users and fails for others?

**Comment by hger** [comment]
Yes I mean that some users have no issue with registering and some have issues. But it is alot of issues and a big problem for us. And I realized that the other file is part of the python-ldap package and not included with indico. My bad. But the problem remains.

**Comment by pferreir** [comment]
The fact that some users work OK and others don't makes me believe that it may be a problem with the LDAP server, or some failure of Indico to handle some corner case.
It would be good to know:
 * What LDAP server you are running (Active Directory, OpenLDAP, ...?)
 * What was the previous error that you had before you patched `LDAPAuthentication.py`
 * If there is any error output in `indico.log` (there should be some) and what
 * Whether you have tried to run the whole thing without TLS (supposing both machines are on a safe network)

That would help us know a little bit more.

**Comment by hger** [comment]
Yes, answers:
Active Directory 2008r2 on 2008 level
The previous error before the patch of the LDAPAuthentication.py file was that users could not login using their LDAP accounts. May have been other issues that I solved by another patch off the same file, see below
```python
RETRIEVED_FIELDS = ['sAMAccountName', 'cn', 'mail', 'o', 'ou', 'company', 'givenName',
                    'sn', 'postalAddress', 'userPrincipalName', "telephoneNumber", "facsimileTelephoneNumber"]
UID_FIELD = "sAMAccountName"  # or uid
MEMBER_ATTR = "member"
MEMBER_PAGE_SIZE = 1500
```
Notice that it says sAMAccountName in the above code
In the log file (indico.log) there are entries like the one above, CONNECT_ERROR

I did just set the server back to not use TLS:
```
[('Local', {}), ('LDAP', {'uri': 'ldap://dc01.esss.lu.se:389', 'useTLS': False, 'peopleDNQuery': ('sAMAccountName={0}', 'OU=ImportedUsers,DC=esss,DC=lu,DC=se'), 'groupDNQuery': ('sAMAccountName={0}', 'DC=esss,DC=lu,DC=se'), 'groupStyle': 'ActiveDirectory', 'accessCredentials': ('CN=readonly,CN=Users,DC=esss,DC=lu,DC=se','Password'), 'customUserFilter': "(objectCategory=user)"})]
```
But this is not a good solution as you are aware.

**Comment by ThiefMaster** [comment]
Sounds very much like a problem with your LDAP server. Connecting errors shouldn't be related to the data you send.

**Comment by hger** [comment]
OK thank you
