### ISSUE TITLE
CKeditor: Add Ctrl+K as a shortcut for hyperlink creation

### ISSUE THREAD

**Issue by pferreir** [indico/indico#1743]
As per user request and according to "common practice":

http://meta.stackexchange.com/questions/49948/use-ctrlk-to-insert-modify-a-hyperlink-instead-of-code

**Comment by ThiefMaster** [comment]
Ugh, what's wrong with CTRL+L for "Link"? Who had the great idea to use K for links? Shame on you, Microsoft!

**Comment by pferreir** [comment]
Well, apparently Google docs uses it too. Ctrl+L will normally take you to the URL bar.
