### ISSUE TITLE
Buttons for material download broken (sessions)

### ISSUE THREAD

**Issue by pferreir** [indico/indico#1744]
When we have a session split across two different days (2 slots) and 2 more resources of the same material type, the "dropdown list" will only work for the first one. This happens because the IDs of the dom elements collide:

https://github.com/indico/indico/blob/master/indico/MaKaC/webinterface/tpls/events/include/Material.tpl#L19

**Comment by ThiefMaster** [comment]
Obsolete?

**Comment by pferreir** [comment]
Yeah, obsolete.
