### ISSUE TITLE
Lower default for number of worker processes?

### ISSUE THREAD

**Issue by DirkHoffmann** [indico/indico#1752]
It seems that the default number of worker processes
```WSGIDaemonProcess WSGIDAEMON processes=<num_processes>```
is very high (32) by default in the config of InDiCo distributions. 

Maybe it should be set lower for all the sites with smaller infrastructure than that of CERN :wink:

**Comment by pferreir** [comment]
We should definitely make it clear in the documentation that 32 processes is a bit too much for smaller setups.

**Comment by pferreir** [comment]
Solved by f67f233995d296add836e3091dc251da260bb2fa.
