### ISSUE TITLE
Prevent the modification of a booking's start and end dates if it is in the past

### ISSUE THREAD

**Issue by jacquesd** [indico/indico#1753]
If a booking has either its start date, end date or both in the past; it should not be allowed to modify them as discussed in the issue #1731.
  - [x] prevent the modification of past start dates on the server side
  - [x] prevent the modification of past start dates on the client side
  - [x] prevent the modification of past end dates on the server side
  - [x] prevent the modification of past end dates on the client side

**Comment by pferreir** [comment]
Datepicker still usable if I click on "Today". Also, would it be possible to remove `cursor: pointer` when the picker is disabled?

**Comment by jacquesd** [comment]
fixed: e01132d3276bf0a7a1b43fb623df81bed5b17e58

**Comment by pferreir** [comment]
What about the cursor?
