### ISSUE TITLE
Registration Form - Impossible to select preferred choice for session

### ISSUE THREAD

**Issue by pferreir** [indico/indico#1754]
Easy to reproduce:
 1. Registration form in its default configuration
 2. Add at least a session to the event
 3. Try to register, won't be able to select preferred choice

**Comment by ThiefMaster** [comment]
Fixed in ffa6f3fba2c1e3d0840f07eb736773e05c51962f (v1.2) and ec087944f2f4ad62bd22b7b5a07d13b461e63f5d (v1.9)
