### ISSUE TITLE
Use jQuery dropdown for the manage contribution menu

### ISSUE THREAD

**Issue by nop33** [indico/indico#1760]
Currently we are using a PopupMenu to create the dropdown menu when clicking on a "manage contribution" button (meeting page):
![](http://i.imgur.com/u5TZQbs.png)

It would be nicer to use a more modern dropdown like the jQuery one:
![](http://i.imgur.com/edgCXIv.png)

The definition of the "manage contribution" button is in the file `/MaKaC/webinterface/tpls/events/include/ManageButton.tpl`

The way to implement the jQuery dropdown is:
- render an `<ul class="dropdown">` (which will include all the menu items) right after the `<a>` button
- activate the dropdown using the jQuery widget `dropdown()` on a parent or on the manage button itself.

**Comment by ThiefMaster** [comment]
done a long time ago
