### ISSUE TITLE
Footer overlaps functional elements

### ISSUE THREAD

**Issue by OmeGak** [indico/indico#1763]
The footer is currently overlapping functional elements in some pages as a consequence of adding `margin-top: -100px;` to `.footer.footerCERN`. This rule was added by 5eae9d59e3a5e438624afc673c7d415199eabcd2 in order to prevent the scrollbar appearing when not necessary.

### Footer overlapping
![screenshot from 2015-02-04 16 49 03](https://cloud.githubusercontent.com/assets/716307/6043700/6975d3cc-ac8e-11e4-89da-2386b955d76d.png)

### Page with scrollbar
![screenshot from 2015-02-04 16 49 21](https://cloud.githubusercontent.com/assets/716307/6043764/dddd060e-ac8e-11e4-863a-7e22e9d62a0f.png)

**Comment by nop33** [comment]
I noticed the overlapping footer today while working on the Vidyo plugin. The buttons become unclickable.
![](http://i.imgur.com/zdieslq.png)

**Comment by OmeGak** [comment]
Temporary fix on my wip branch: c83f861ddfe8ecd19a67a357a14bd54874906994

**Comment by nop33** [comment]
Fixed by c83a05bfa3421a986abade744eecd6a48932ee0e
