### ISSUE TITLE
Unify plugin/non-plugin core functions

### ISSUE THREAD

**Issue by OmeGak** [indico/indico#1765]
To follow up discussion started with: https://gist.github.com/OmeGak/e816b2faccc80cc12d9b

**Comment by ThiefMaster** [comment]
My suggestion is to use a single `render_template` function (probably inside flask-pluginengine) which supports `':foo'` as a template name. Using such a name would cause an exception when outside a plugin context and otherwise use the current plugin as the plugin prefix.

**Comment by ThiefMaster** [comment]
Postpone to the end of 1.9.2 in case there's time? We are unlikely to add that many plugin templates during v1.9.2 so the workload would be pretty much the same.

**Comment by pferreir** [comment]
Agreed :+1:

**Comment by ThiefMaster** [comment]
IIRC this was originally my idea, but in the end what we have right now works pretty fine.
