### ISSUE TITLE
Default session lifetime doesn't work well with memcached

### ISSUE THREAD

**Issue by ThiefMaster** [indico/indico#1766]
> Expiration times can be set from 0, meaning "never expire", to 30 days. Any time higher than 30 days is interpreted as a unix timestamp date. If you want to expire an object on january 1st of next year, this is how you do that. 

So with the default of 31 days sessions expire immediately, making it impossible for anyone to login. The solution is to always use a timestamp when saving something to memcached (requires a `MemcachedCacheStorage` wrapper): https://github.com/indico/indico/blob/master/indico/MaKaC/common/cache.py#L495

Or maybe it's better to simply drop memcached support or reduce the default session TTL to 30 days?

**Comment by pferreir** [comment]
Why not reducing the TTL? Anything wrong with that?
I am no fan of just dropping memcached, especially at a moment when we're going relational and the added value of redis is going to decrease.

**Comment by ThiefMaster** [comment]
Reducing the default TTL would work, but then the bug in our cache implementation remains...

Why I'm for dropping memcached:

- It limits keys to 250 chars and even disallows spaces. That's why we ended up using a sha256 hash instead of the plain key which makes looking at the cache contents pretty much impossible.
- Nowadays memcached has pretty much no performance benefits over redis
- Memcached is the only cache backend that has guaranteed non-persistence. Both Redis and files don't lose everything e.g. when you restart it. While cache data is volatile, losing all active sessions in a reboot is not very nice.

**Comment by pferreir** [comment]
I understand your point, but the question is: is it really worth restricting people to a single alternative, when you can have two with just a little added cost (which has been already mostly paid for anyway).
I sincerely thing redis is much superior to memcached for all purposes, but memcached is still pretty ubiquitous and supporting it is a plus.

**Comment by ThiefMaster** [comment]
"but memcached is still pretty ubiquitous" - is it? haven't heard much about it lately.

Anyway, then I'd at least go for the clean solution (using a wrapper like we have for the other backends) and "officially" recommend redis as the cache backend.

**Comment by pferreir** [comment]
Can't find any numbers, but it comes in almost all Linux distros. Redis is also now kind of common, but not sure about the proportions.
I agree with your opinion: clean solution and redis as recommended :+1:

**Comment by ThiefMaster** [comment]
dc7844593aba7f18074e0297bafb45fcde80ce7d
