### ISSUE TITLE
Possibly faulty encoding of subject in e-mails

### ISSUE THREAD

**Issue by pferreir** [indico/indico#1770]
If a mail is sent out with accents in the subject, they seem to be rendered wrong at least in some mail clients.

```
Fwd: [600-R-001] Booking confirmed on 13 f??vr. 2015 15:30:00
```

**Comment by ThiefMaster** [comment]
Would be interesting to see the raw email. If the subject is correctly utf8-encoded I guess it's the client's fault.

**Comment by pferreir** [comment]
Sent you by private mail, @ThiefMaster

**Comment by ThiefMaster** [comment]
ok, the subject isn't base64-encoded...
