### ISSUE TITLE
Broken Avatar object stored in Registrant objects

### ISSUE THREAD

**Issue by OmeGak** [indico/indico#1771]
`Registrant` objects return `Avatar` object with wrong `id` if linked to an external account. The DB is plagued with this and it seems that nobody noticed for long time. 

To give an example:

```python
>>> AvatarHolder().getById('LDAP:1234567890abcdefghij:john.doe@cern.ch').id
'70600'

>>> ConferenceHolder().getById(302395).getRegistrantById('26').getAvatar().id
'LDAP:1234567890abcdefghij:john.doe@cern.ch'
```

This little script prints all the events with broken avatars in the registrant objects:
```python
from indico.util.console import conferenceHolderIterator

for _, event in conferenceHolderIterator(ConferenceHolder(), deepness='event'):
    broken = [r.getAvatar() for r in event.getRegistrants().values() if r.getAvatar() and not r.getAvatar().id.isdigit()]
    if broken:
        print event, broken
```

**Comment by pferreir** [comment]
I have the feeling this is not the only place where it happens.

**Comment by pferreir** [comment]
This is there at least since the first LDAP patch:

https://github.com/indico/indico/blob/master/indico/MaKaC/authentication/LDAPAuthentication.py#L692

**Comment by pferreir** [comment]
And there are also some `Nice:xxxx` identities, which proves that this didn't affect only LDAP identities. I think this have been around basically forever.

**Comment by pferreir** [comment]
The latest changes should have fixed this behaviour.
