### ISSUE TITLE
New session block automatically gets session title also as sub-title

### ISSUE THREAD

**Issue by shesselbach** [indico/indico#1779]
If one uses "Add new session" -> "Add another block to" an existing session in timetable management this new block automatically gets the session title also as sub-title:
![timetable1](https://cloud.githubusercontent.com/assets/7440294/6289748/a11f8a66-b922-11e4-89e0-968e34fb793d.png)

This is despite the fact that the initial edit window shows no sub-title:
![addblock](https://cloud.githubusercontent.com/assets/7440294/6289810/112ce2b8-b923-11e4-9b87-233adf0699e4.png)

This can be solved only afterwards by going back and edit this block after creation and deleting the unwanted (double) sub-title.

This has been reported by a user of our site and I reproduced it on 
https://indico-sandbox.cern.ch/event/18/timetable/#20150220

**Comment by mic4ael** [comment]
Issue has been fixed in the latest release of Indico.
