### ISSUE TITLE
htdocs/ihelp empty

### ISSUE THREAD

**Issue by chrisbgp** [indico/indico#1783]
installed with easy_install (version 1.2)
- .../indico/htdocs/ihelp/html is empty
- .../indico/htdocs/ihelp/pdf is empty

no links on the indico help page are working. is this problem known?

**Comment by pferreir** [comment]
Hi. Do you mean that you ran `easy_install` after having checked out the repo, or that you just ran `easy_install indico`?

**Comment by chrisbgp** [comment]
Hello, I didn't install from git. I got the stable release via easy_install. I hope using issues from github is ok for that too?

**Comment by pferreir** [comment]
No, that's OK. I was just wondering if that might be caused by an accidental install from a repo.

**Comment by chrisbgp** [comment]
Also if I do a system wide search for "IndicoUserGuide.pdf", there are no results. Maybe I should try to reinstall?

**Comment by uhuaha** [comment]
I installed version 1.9.6 but I am having the same problem. Did you find a solution? If yes, could you please post it here? Thanks in advance!

**Comment by ThiefMaster** [comment]
These docs are not part of the indico package anymore.
