### ISSUE TITLE
Poster layout list broken in some browsers

### ISSUE THREAD

**Issue by pferreir** [indico/indico#1786]
This is only admin-visible: `/admin/layout/posters/`
In some browsers, the display is completely broken. @OmeGak, can you add a screenshot (it's fine in mine)?

**Comment by OmeGak** [comment]
![screenshot from 2015-03-03 15 18 42](https://cloud.githubusercontent.com/assets/716307/6464209/02435a22-c1b9-11e4-87ed-1725f030f3da.png)

**Comment by ThiefMaster** [comment]
Floats striking once again?

**Comment by pferreir** [comment]
probably some `clear: ...` missing. Or just a line height issue...
