### ISSUE TITLE
Deleting used custom room attributes raises exception

### ISSUE THREAD

**Issue by OmeGak** [indico/indico#1787]
Removing a `RoomAttribute` should also remove all associated `RoomAttributeAssociation`. We get an `IntegrityError` instead. It seems that we are dealing with this properly for the deletion of `EquipmentType` at the DB level.

The issue can be reproduced from:
> Server Administration > Rooms > Room Booking > Management > Location

**Comment by ThiefMaster** [comment]
This happened because we were using `.delete()` instead of `db.session.delete(...)`

http://docs.sqlalchemy.org/en/rel_0_9/orm/query.html#sqlalchemy.orm.query.Query.delete
