### ISSUE TITLE
Move daily digest reminder for room startup support to core repo

### ISSUE THREAD

**Issue by OmeGak** [indico/indico#1794]
This is implemented as a CERN-specific script and it lives within our puppet hostgroup in `CERN_scripts/sendEmailNeedAssistanceStartup.py`.

What it does is sending a daily digest to the support team using the http api informing about the rooms that need assistance with startup. I don't see any reason why not to have this built-in in indico alongside with the other reminders.

**Comment by pferreir** [comment]
This is very CERN-specific. I'd say at most in some CERN-specific plugin.
