### ISSUE TITLE
Unexpected behavior when editing session in event page

### ISSUE THREAD

**Issue by nop33** [indico/indico#1795]
Using the edit (pencil) button next to a session in the timetable area of an event page, does not prompt to edit the correct session.
Example:
Trying to edit the basic info of "Talk from organizers" will end up editing the session right bellow (meeting new members)
![](http://i.imgur.com/7GWPPrM.png)

Another example:
Editing the 1st session, will give an error, whereas editing the 3rd session will prompt to edit the 1st one:
![](http://i.imgur.com/wPCifVE.png)

**Comment by nop33** [comment]
I have the impression that the source of the problem is the ordering of the session titles and not the ordering of the management buttons.
When 2 sessions overlap, the pattern that I found is that the longer session will show up **after** the shorter one, whereas the management button of the longer one will show up **before** the shorter one.

**Comment by nop33** [comment]
The process to reproduce the problem is the following:
* Add a new session (*Fresh Session 1*) in the timetable with start time X (*10:00*)
* Add a block inside *Fresh Session 1* (*Session Block 1*),  with the same start time X (*10:00*)

The timetable will look like this:
![](http://i.imgur.com/eBsz0Yd.png)

And the agenda will look like this:
![](http://i.imgur.com/ijNgn77.png)

**The management buttons and the section titles are inverted.**

By changing the start time of the *Session Block 1*  to 11:00, the agenda will look now like this, and the management buttons correspond now to the **correct** sessions:
![](http://i.imgur.com/3xy3ymB.png)

So: When a session block that belongs in a session has a start time which is equal or earlier than the parent session, the problem appears.

Proposed solution:
* I believe we shouldn't allow session blocks to have a start time earlier than the parent session. This doesn't solve the problem completely since it also occurs when the start time between child and parent session are equal.
* In this case, the session titles in the agenda should be inverted.

Any thoughts on this? @pferreir , @ThiefMaster , @OmeGak , @jacquesd ?

**Comment by pferreir** [comment]
This is clearly a bug, independently of session blocks having a starting time that is earlier of equal to the session or any other block. Session blocks have their own ID, so, this shouldn't happen. There's clearly a problem and that's what we should target.
