### ISSUE TITLE
Direct access link for epayment is wrong

### ISSUE THREAD

**Issue by nop33** [indico/indico#1805]
In the management area ()/event/XXXXXX/manage/registration/users/X/, the link to epayment of the registrant is incorrect:
![](http://i.imgur.com/Mf246H3.png)

It should be replaced by the link to the registration page.

**Comment by ThiefMaster** [comment]
I think we should only show this link if the user has no indico account. Otherwise it's kind of pointless, and if we included the authkey in that case we'd point to a page that, if logged in to a different account, would be a bit  broken since any links on that page would not include id and key

**Comment by nop33** [comment]
So how should I proceed with this?
* if the registrant has an Indico account, then the link would be /event/X/registration/, which is pointless as @ThiefMaster said.
* if the registrant has no acc, then the link would contain the authkey and registrant_id parameters, but still, if the manager clicks on that link, the page would be a bit broken, as mentioned above.

Should I only add the link in case of a registrant without an acc?

**Comment by ThiefMaster** [comment]
One option would be to show it only if the guy doesn't have an account and add a message indicating that it should not be used while logged in to an indico account.

**Comment by nop33** [comment]
OK, I added the correct link only when the guy has no account:
![](http://i.imgur.com/PAbAOKD.png)

**Comment by pferreir** [comment]
"While logged in **with** an Indico account"
