### ISSUE TITLE
Polish service request view for service managers

### ISSUE THREAD

**Issue by OmeGak** [indico/indico#1812]
Two main issues with what the service managers see on a service request page:

* Managers get the *"Your request is currently pending approval"* info box.
* Managers can currently *withdraw* a request as if they were an issuer. This leaves the door open for "rejecting" a request without leaving trace, sending notification or giving feedback.

**Comment by ThiefMaster** [comment]
We do send a notification about withdrawn requests

**Comment by pferreir** [comment]
Still, I agree that "withdraw" should be reserved to the user (and admins, of course).

**Comment by OmeGak** [comment]
How come this was not assigned to @mic4ael?

**Comment by ThiefMaster** [comment]
:laughing:

**Comment by mic4ael** [comment]
I think I am not enough polish
