### ISSUE TITLE
Registration form fields are not sorted properly in the email

### ISSUE THREAD

**Issue by ThiefMaster** [indico/indico#1817]

**Comment by nop33** [comment]
It's quite strange, in my locahost the order is correct, whereas on production it's not.

**Comment by ThiefMaster** [comment]
Fixed in v1.9.1 1e178328278112d725244f93a6896b4c2cec049b

**Comment by ThiefMaster** [comment]
This fix introduces a new problem. Now all custom fields are missing in the email...
