### ISSUE TITLE
Nodeenv  is needed during install

### ISSUE THREAD

**Issue by cabernet138** [indico/indico#1823]
Hello,

I'm trying to install indico on ubuntu. During the process of installation (following the docs)  based on the git cloning

fab  setup_deps :
...
[localhost] local: git submodule update --init --recursive
[localhost] local: which curl > /dev/null && echo $?
[localhost] local: nodeenv -c -n 0.10.24 /var/www/indico/ext_modules/node_env
/bin/sh: 1: nodeenv: not found

have to easy_install nodeenv to continue the process. (this is not documented if I'm not wrong)
Cheers.

seems to be ok : 
Done, without errors.
[localhost] local: mkdir -p /var/www/indico/indico/htdocs/js/lib
[localhost] local: cp build/angular.js /var/www/indico/indico/htdocs/js/lib/
[localhost] local: cp build/angular-resource.js /var/www/indico/indico/htdocs/js/lib/
[localhost] local: cp build/angular-sanitize.js /var/www/indico/indico/htdocs/js/lib/
[localhost] local: cp css/angular.css /var/www/indico/indico/htdocs/css/lib
Installing PageDown
[localhost] local: mkdir -p /var/www/indico/indico/htdocs/js/lib/pagedown/
[localhost] local: cp *.js /var/www/indico/indico/htdocs/js/lib/pagedown/

Done.

:-)

**Comment by ThiefMaster** [comment]
When installing from a git clone you have to run `pip install -r requirements.dev.txt` to install all the development dependencies.

**Comment by cabernet138** [comment]
Ok.
Skiped this line because it is stated before the cloning in the doc (so was not clear for me, I'm not a "pythonist", sorry ;-)
May be it would be more clear if the two lines pip ... / git clone were switched.
Thanks

**Comment by ThiefMaster** [comment]
That file doesn't exist until you cloned the repo...

**Comment by cabernet138** [comment]
Yep. Thus the cloning shoud be stated before...

**Comment by pferreir** [comment]
OK, fixed in 61fdec3bb5b733d64381eef3f3ceb431aab0d3dd.
Thanks!
