### ISSUE TITLE
http://indico-software.org/wiki/Admin/Installation#a3.ConfiguringApache

### ISSUE THREAD

**Issue by cabernet138** [indico/indico#1824]
Following the online installation doc, I reached : 

Congratulations!
Indico has been installed correctly.
...
For information on how to configure Apache HTTPD, take a look at:
http://indico-software.org/wiki/Admin/Installation#a3.ConfiguringApache

But this link is not valid anymore.
Should be : http://indico.readthedocs.org/en/latest/installation/#configuring-apache-recommended ?

**Comment by pferreir** [comment]
Merged in 8eba9c5a8f19ad59a4c430e569f73b02f881c7c0.
