### ISSUE TITLE
Remove warnings in CI about indico-software.org host

### ISSUE THREAD

**Issue by DirkHoffmann** [indico/indico#1826]
You are likely to know this. Automatic build in CI Travis yields many warnings 
`This repository located at indico-software.org is not a trusted host, if this repository is available via HTTPS it is recommend to use HTTPS instead, otherwise you may silence this warning with '--trusted-host indico-software.org'.`
So if it is simple (and possible at all) to do that, it would remove 90% of noise warnings from the build log.

**Comment by ThiefMaster** [comment]
Fixed in 6ffc8bf
