### ISSUE TITLE
Set sane defaults in `logging.conf`

### ISSUE THREAD

**Issue by pferreir** [indico/indico#1829]
Right now, for instance, we have `NOTSET` for the global Indico logger. Using `INFO` for everything (except e-mail) could actually be a good idea.

**Comment by pferreir** [comment]
And please backport to 1.2.

**Comment by ThiefMaster** [comment]
Using logging.yml instead of logging.conf would also be a nice thing for a future version. The ini format for logging is kind of terrible.

**Comment by pferreir** [comment]
Indeed, but let's open a separate ticket for that, for a future release.

**Comment by DirkHoffmann** [comment]
Also keep in mind that there seem to be two different logging systems available. One is configured in `indico.conf`, the python logging is then configured in `logging.conf`. Would be better to have everything concerning logging (choice of system + logging levels) in the same place.
Regarding e-mail, I think they are going out for errors only anyway. I did not find a configuration for that. May be hardcoded :scream:
