### ISSUE TITLE
Session coordinators index is not updated properly

### ISSUE THREAD

**Issue by nop33** [indico/indico#1834]
When adding a coordinator in an event's session, the `_sessionCoordinators` attribute (`SCIndex`) of the class `Conference` gets updated correctly. Adding the same person as a coordinator to another session, will not update the index though. The `addSessionCoordinator` method gets executed, but the `_sessionCoordinators` index does not get updated.

**Comment by nop33** [comment]
After some debugging, I noticed that the index get's updated correctly during the request, but by the end of the request, when I check in `indico shell`, the index returns only one result.
I checked if there is a call to `unindex` for any reason, but didn't find anything.
Something else that I noticed is that during the request after some debugging steps and before the request finishes, I was getting an error that `NoneType` has no attribute `root` which probably refers to this `DBMgr.getInstance().getDBConnection().root()`, when trying to import the `ConferenceHolder` in the debugging console.

**Comment by ThiefMaster** [comment]
was that error in the werkzeug debugger? if yes: the zodb connection is already closed in there, so you cannot access zodb in there anymore

**Comment by nop33** [comment]
No, I used wdb to set some brakepoints and see what's happening. So until the ZODB connection was closed, the index had all the sessions correctly. When checking the `event._sessionCoordinators.getSessions(avatar)` from the `indico shell` afterwards, it gives only one result, hence the problem with the "My Sessions" page.

**Comment by pferreir** [comment]
Debuggers are always a little bit quirky. It's better to print the repr in that situation.

**Comment by nop33** [comment]
Beside some crazy stuff that I found, I arrived to a point that I don't understand. When this line of code is executed `ls = set(self._conf.getCoordinatedSessions(self._aw.getUser()))` (https://github.com/indico/indico/blob/master/indico/MaKaC/webinterface/rh/conferenceDisplay.py#L838) and I try to step inside with the debugger, instead of going to the `getCoordinatedSessions` method of the `Conference` class, it goes to the `setstate` function of the `Connection` ZODB class (https://github.com/zopefoundation/ZODB/blob/55ffc29ce9420dcffab022791ddc40008387bd82/src/ZODB/Connection.py#L855). Why is this happening? Executing the similar method `self._conf.getManagedSession(self._aw.getUser())` and stepping in with the debugger, get's me to the definition of the method.

**Comment by ThiefMaster** [comment]
That's ZODB trying to access some object it hadn't loaded so far.

**Comment by nop33** [comment]
Just an update.
I have no problems with adding/removing coordinators in a test conference I created. All works fine.
Now, the problems I have are related to an existing conference (341292) and specifically with the sessions 15 and 17.
Removing a session coordinator works fine (I have print statements and I see that the `self._sessionCoordinators.getSessions(avatar)` index has the correct contents. For example, I remove myself from the session 15 coordinators. All good.
Even after refreshing the "My Sessions" page, the removed sessions does not appear, which is fine.
The moment I add myself as a coordinator of another random session, for a magical reason, the session 15 and 17 appear again in the index (although I specifically removed them some seconds ago).
