### ISSUE TITLE
The order of the sessions vary from view to view

### ISSUE THREAD

**Issue by nop33** [indico/indico#1835]
In a conference page, depending on the type of view (Parallel, Indico style, etc.), the timetable displays the order of the sessions differently. For example in the Parallel view, the order is based on start time and code, whereas in Indico style it's based on start time and end time.

**Comment by pferreir** [comment]
Is that really an issue? They are different views - in the Indico view, we are actually "serializing" contributions (as they cannot be displayed in parallel), so, I would think it's normal that it behaves differently.

**Comment by nop33** [comment]
But the guy has a point regarding sessions that have the exact same start time and end time. I would expect that the second order should be an alphabetical order of the code or title. What do you think?

**Comment by pferreir** [comment]
Ah yes. Last resort, then we can order by code. That seems fair enough to me.
