### ISSUE TITLE
Improve login message

### ISSUE THREAD

**Issue by DirkHoffmann** [indico/indico#1836]
I am ready to contribute this trivial element, but I must be sure that it is not lost. Maybe it can also serve as a reminder that coding of Indico should always happen in a way that it can be use outside CERN without to many source code changes ;-)

This regards 1.2.1.rc1 installed last week for CTA.The login page https://ctax.lsw.uni-heidelberg.de/indico/user/login contains a message "Please note you can use your external (LDAP) account" which is totally misleading in the case of CTA (and likely many other), as LDAP is **the one and only** account used by the majority (non-expert) users.

I will have a look at the logic (probably depending on the activation of various Authenticators) and try to make a more constructive proposal for improvement.

**Comment by pferreir** [comment]
We are rewriting this at the moment, but if there is a simple solution for the 1.2.x branch, I don't see any problem in changing that.

**Comment by DirkHoffmann** [comment]
Thanks for taking this into account.
After some thinking, I believe that the aim of that message is certainly to indicate activation (or not) of various login-mechanisms ("Authenticator"s). Maybe a concise line like 

* Enabled authentication(s): genuine (Indico local), central LDAP directory, central SSO, ...

would be sufficient. Ideally it would specify "CTA LDAP", "CERN SSO" etc., but that implies additional configuration. Probably it is not a good idea to change 
`    AuthenticatorList = ['Local', 'LDAP', 'MyAuthSystem']`
in `indico.conf` too much. I see two possibilities:
* an additional, optional ` AuthenticatorNames = ['Indico local' , 'CTA directory', 'Best UID/pwd']`, which would need to be always in parallel with `AuthenticatorList`, or bug otherwise.
* a list of list option for adding names alike
`    AuthenticatorList = ['Local', ('LDAP', "CTA standard directory"), 'MyAuthSystem']`
where the second element would be used for "human readable display" where applicable. It would need a lot of refactoring where `AuthenticatorList` is used (hopefully only in one place - the getter routine :wink:).

BTW: Shouldn't the config items be tuples (`AuthenticatorList = ('Local', 'SSO')`) rather than mutable lists (`AuthenticatorList = ['Local', 'SSO']`)?

**Comment by pferreir** [comment]
This is solved by 2.0. You can now specify a "title" for each authentication method.
