### ISSUE TITLE
reindex-groups script? 

### ISSUE THREAD

**Issue by DirkHoffmann** [indico/indico#1839]
According to [this thread](https://groups.cern.ch/group/project-indico-administrators/Lists/Archive/Feed Back about 1.2.1 RC1 and groups ERROR) there may be cases where `LDAPGroup` instances in the database(?) become weird like `persistent broken MaKaC.user.LDAPGroup instance '\x00\x00\x00\x00\x00\x9e\xccw'` for example.

The recipe given there (and improved here)

``` python
from MaKaC.authentication.LDAPAuthentication import LDAPAuthenticator
for j in [LDAPAuthenticator().matchGroupFirstLetter(i) for i in GroupHolder().getBrowseIndex()]:
     if len(j) > 0:
         for k in j:
             print k.getName()
             gt.pop(k.getName())
             gt.insert(k.getName(), k)
```

helped me to get rid of these broken instances. However, I had to remove some of these (which were no longer in LDAP, but existing as broken instances in the DB still) manually by checking the instance types in 

``` python
[i for i in GroupHolder()._getTree('groups').values()]
```

Maybe such a sanity check should be added as script in the [maintenance](../tree/master/bin/maintenance) directory or/and systematically run from the migration script?

**Comment by ThiefMaster** [comment]
ZODB-related -> obsolete since a long time ;)
