### ISSUE TITLE
ImportError: No module named web.flask.app

### ISSUE THREAD

**Issue by liuqing820105** [indico/indico#1841]
when i access http://10.10.8.89/indico
the web indicates an "500 internal server error"
and here is the information shows in the apache error_log
##############################################################################
[Thu Apr 16 01:45:15.811422 2015] [:error] [pid 6212] [remote 10.10.8.9:208] mod_wsgi (pid=6212): Target WSGI script '/opt/indico/htdocs/indico.wsgi' cannot be loaded as Python module.
[Thu Apr 16 01:45:15.811572 2015] [:error] [pid 6212] [remote 10.10.8.9:208] mod_wsgi (pid=6212): Exception occurred processing WSGI script '/opt/indico/htdocs/indico.wsgi'.
[Thu Apr 16 01:45:15.811730 2015] [:error] [pid 6212] [remote 10.10.8.9:208] Traceback (most recent call last):
[Thu Apr 16 01:45:15.811808 2015] [:error] [pid 6212] [remote 10.10.8.9:208]   File "/opt/indico/htdocs/indico.wsgi", line 17, in <module>
[Thu Apr 16 01:45:15.812114 2015] [:error] [pid 6212] [remote 10.10.8.9:208]     from indico.web.flask.app import make_app
[Thu Apr 16 01:45:15.812191 2015] [:error] [pid 6212] [remote 10.10.8.9:208] ImportError: No module named web.flask.app

**Comment by pferreir** [comment]
Are you sure your apache config is fine? Did you install Indico in a virtualenv?
That looks like a `PYTHONPATH` issue.

**Comment by dfgordon** [comment]
We have the same problem.
Some interesting notes:

From the python command line interface (CLI), "import indico" works.
However "from indico.web.flask.app import make_app" produces the error (also from CLI).
Moreover, help(indico) lists nothing in the package!
Seems to me the egg itself has a problem?

This happens either using easy_install to install v1.2 or checking out v1.2.x and using pip for requirements[-dev].txt and setup.py to install the indico egg.
Putting "python-path=[...]/site-packages" on the WSGIDaemon line does not eliminate the error.
Directly downloading the zip file, unpacking, and copying into site-packages (perhaps a naive procedure) gives the correct CLI behavior (but leads to a new apache error).

Most of this was done using Scientific Linux 6.6 with software collections python27 and httpd24, which evidently works for Brookhaven's indico servers.  We played with Ubuntu also and got somewhat farther (the home page displays), but never had a functional server.

**Comment by pferreir** [comment]
I repeat the question I made to @liuqing820105: are you using a virtualenv?
It looks like a path issue.

**Comment by dfgordon** [comment]
Thanks, in no case was a virtualenv used (should we?).  Maybe software collections would cause similar issues?  We are trying to use /opt/rh/python27/root/usr/lib/python2.7 instead of /usr/lib/python2.6.  As far as I can see that is working; after all apache seems to find the indico base package.

**Comment by pferreir** [comment]
Is your `mod_wsgi` package picking up the correct python interpreter? It is normally tied to the original system interpreter.

Anyway, there is a possibility, which is caused by some issue with setuptools. You should have a `cds-indico-extras.pth` file (or similar) somewhere in your `site-packages` dir. Try removing it.

**Comment by dfgordon** [comment]
Sorry, did a clean re-install of SL6.6 and then ran into some other issue with not finding pytz (which is there and imports OK from CLI), then decided to try SL7.1 since python2.7 is the default and maybe all this is avoided.
So I guess I can’t try your idea now.  Thanks for the suggestion though, maybe we will come back to it.

**Comment by dfgordon** [comment]
Udpate:
Putting indico 1.9.4 in a virtualenv on Ubuntu produced the issue again.
However, removing "cds-indico-extras[...].pth" as suggested solved the problem.

**Comment by ThiefMaster** [comment]
We should really get rid of those namespace packages once and for all... and either use e.g. `indico-extras` as a name or find a better way where we don't abuse python packaging for non-python data...

**Comment by ThiefMaster** [comment]
Obsolete, indico-extras is gone.
