### ISSUE TITLE
Submitter right for subcontribution presenter

### ISSUE THREAD

**Issue by jouvin** [indico/indico#1843]
In the subcontribution dialog, it is possible to add a `presenter` (why it is not called a `speaker` as for contribution?) but there is no way to grant him the submission rights in the same dialog, as it is the case for contribution presenters. Giving him these rights require to go to contribution protection tab, which is misleading...

**Comment by pferreir** [comment]
CERN: See related `CHG33935` in SNow.

**Comment by ThiefMaster** [comment]
same as #2363
