### ISSUE TITLE
Attach comments to registrant entries

### ISSUE THREAD

**Issue by OmeGak** [indico/indico#1847]
Suggested during the meeting with University of Heidelberg. Add some free-form text field in the management area of a registrant entry for event managers to add remarks.

**Comment by OmeGak** [comment]
As discussed in the ticket attached to `SNOW CHG33712`, this could be a improved beyond into a full-fledged new feature within the registration module. Bottom line remains the same: having manager-editable-only fields, but there are two different needs to be addressed:

* Having rich fields for internal notes as initially proposed.
* Displaying extra information to users post-registration i.e. such as room allocated.

Both really belong outside of the registration form page and in any case and we should study how to integrate them in the UI. It will probably involve a revamp of the registrant details page (management area) and restructuring of the registration summary page (user view). As for how to describe new fields, a new tab similar to the registration form would probably do.

**Comment by ThiefMaster** [comment]
A simple "comment" field for managers would be a good start and easy to do while migrating the registration form

**Comment by pferreir** [comment]
I believe most of the points here are covered by the last update (except for the part where we publicly expose those fields, if necessary). Not sure how to do that, but I guess we can follow that up in a different ticket?
