### ISSUE TITLE
Use of `JinjaWidget` for general code snippets

### ISSUE THREAD

**Issue by OmeGak** [indico/indico#1873]
The idea behind this is to encourage using widgets but for snippets of html + javascript that we want to use consistently across the system in the same fashion as we are currently doing with the forms. 

- [ ] Make some Python function available in the template to render the snippet.
- [ ] Agree on how to look up snippet templates from said function. Maybe templates under a `snippets` folder?
- [ ] `JinjaWidget` is already generic enough so it should be moved out of `forms` module.

**Comment by ThiefMaster** [comment]
Probably only worth spending time on when we really end up with a situation where such a widget system would help.

**Comment by OmeGak** [comment]
`error-message-box` for flashed messages is already a good candidate for such a widget system.

**Comment by OmeGak** [comment]
Some datepickers plus filters in room booking as well.

**Comment by ThiefMaster** [comment]
But that doesn't need any special JS so simply importing the jinja macro and calling it does the job (without adding a layer of custom stuff)

**Comment by ThiefMaster** [comment]
Datepickers are usually pretty form related

**Comment by pferreir** [comment]
As discussed, the benefits of this approach are not clear right now. It may be something to explore in the future, but for now it doesn't make our life much easier.
