### ISSUE TITLE
Author, Speaker and Contribution Lists are displayed even if they are disabled in the menu

### ISSUE THREAD

**Issue by shesselbach** [indico/indico#1874]
If in a conference the Author, Speaker or Contribution Lists are disabled in the menu these lists are displayed anyway if the URLs are guessed which is fairly easy. 

E.g. for https://indico-sandbox.cern.ch/event/18/ these lists are disabled but the URLs
 * https://indico-sandbox.cern.ch/event/18/authors
 * https://indico-sandbox.cern.ch/event/18/speakers
 * https://indico-sandbox.cern.ch/event/18/contributions

show the lists. This might not be what the organizers of a conference expect when they disable these lists in the menu. There might be reasons to hide them from the public. It would be better not show the lists in this case like for the Registrants List which gives an error if disabled:
https://indico-sandbox.cern.ch/event/18/registration/registrants

For the same reasons the Author Details page
 * https://indico-sandbox.cern.ch/event/18/contribution/0/author/0

should be hidden if the other lists are disabled. Or this should be made otherwise configurable.

**Comment by mic4ael** [comment]
The issue has been fixed in the latest release
