### ISSUE TITLE
The contents of the Author Details page should be configurable

### ISSUE THREAD

**Issue by shesselbach** [indico/indico#1875]
The contents of the Author Details page, e.g.
- https://indico-sandbox.cern.ch/event/18/contribution/0/author/0

should be configurable because there might be legal problems with showing some details (especially telephone/fax numbers), particularly because just now these details are always accessible, #1874. But even if #1874 is resolved, conference organizers might want to be able not to show some details (e.g. telephone/fax numbers) on the Author Details page.

**Comment by ThiefMaster** [comment]
We only show title, affiliation and name.
