### ISSUE TITLE
Ignore accents in user search

### ISSUE THREAD

**Issue by pferreir** [indico/indico#1888]
Last name, first name and organization should be accent-insensitive.
Postgres provides the [`unaccent(...)` function](http://www.postgresql.org/docs/9.1/static/unaccent.html), which can be useful. It requires the corresponding extension to be activated by the superuser, however.

**Comment by mic4ael** [comment]
Steps required to install required packages (Fedora):
sudo dnf install postgresql-contrib.x86_64;
sudo su postgres;
psql indico;

# create unaccent extension
create extensions unaccent;

**Comment by pferreir** [comment]
That needs superuser access. We don't have that in prod, we have first to see how feasible it would be to have that.

**Comment by ThiefMaster** [comment]
They won't give us superuser since you can use it to run shell commands (I had asked when there was no way to reload the configs), but I'd assume they wouldn't have problems enabling the extension...
