### ISSUE TITLE
Let users choose between "firstname lastname" and "lastname, firstname" notation

### ISSUE THREAD

**Issue by ThiefMaster** [indico/indico#1892]
While "firstname lastname" feels nicer, some people prefer the other way round, A user setting would be the best solution for this.

We'd probably need a separate property for it (`full_name_disp` or something like that) which would honor the setting of the currently logged in user (so `full_name` stays consistent in places where we don't have a single user who'll see the name).

**Comment by pferreir** [comment]
I guess that for the moment we could just go back to "last_name first_name".
I am kind of hesitant on whether to make this a setting. There are so many places where names show up...

**Comment by ThiefMaster** [comment]
everywhere? would be a bit ugly imo... or just in favorites?

Anyway, with a custom property this would be quite easy (simply changing `.full_name` to `.full_name_disp` or whatever in places where it makes sense)

**Comment by pferreir** [comment]
Sorry, see my updated comment above :arrow_up:

**Comment by pferreir** [comment]
Superseded by #2455
