### ISSUE TITLE
Merging an admin into a non-admin user will cause loss of admin rights

### ISSUE THREAD

**Issue by nop33** [indico/indico#1894]

**Comment by ThiefMaster** [comment]
Should we even allow that? If any but not both users are an admin we should 
at least show a warning.

**Comment by nop33** [comment]
I just screwed up my local admin account :P So yes, I agree with the warning.

**Comment by ThiefMaster** [comment]
Unless the *target* account is an admin, we could probably even disallow the merge. I don't see why someone would want to merge an admin account into a non-admin account.

**Comment by nop33** [comment]
It's true, I don't see any point in that either. Is there any use-case for keeping this "feature"?

**Comment by pferreir** [comment]
I agree with disallowing the merge of an admin into a non-admin account. Make sense.
