### ISSUE TITLE
Email pending users when added to database

### ISSUE THREAD

**Issue by OmeGak** [indico/indico#1900]
Although the interface suggests this is happening, it was actually never implemented.

![screenshot from 2015-05-28 13 34 17](https://cloud.githubusercontent.com/assets/716307/7859124/52bfe2f4-053e-11e5-9d46-3597502cd898.png)

> Note: If this person does not already have an Indico account, 
he or she will be sent an email asking to register as a user.
After the registration the user will automatically be given
submission rights.

This should probably be triggered in `indico.modules.users.util.get_user_by_email`.

**Comment by ThiefMaster** [comment]
Not completely if the pending user creation in `get_user_by_email` is the proper place for that. The pending users on those pages are created in `principal_from_fossil`

**Comment by OmeGak** [comment]
We should probably have just a standalone util function to create them and then let it be called from wherever it is needed.

**Comment by ThiefMaster** [comment]
https://github.com/indico/indico/pull/1959#issuecomment-234558648
