### ISSUE TITLE
Most recent code in remotes/origin/v1.2 gives 'invalid XXX date' when creating event

### ISSUE THREAD

**Issue by lickdragon** [indico/indico#1903]
Hi,
   In the 1.2 branch, as of commit 3095b0cb882cf5c221d1ee3a02fc96511599c199,  when I try to create any event I get an error 'invalid XXXX date when trying to create any type of event.

E.g. for event type lecture, when I choose any date (including in the future!) 
the following popup error is displayed:
Invalid lecture date: Sun May 31 2015 08:00:00 GMT-0500 (CDT)

I am importing a 0.97.1 database first, and have not tested with an empy database.

Thanks!
C.

**Comment by pferreir** [comment]
Is there an error in `indico.log`? Any traceback/error message you can show us?

**Comment by ThiefMaster** [comment]
I remember fixing something that was broken in @jacquesd's check (for dates outside ZODB's valid date range).. missing T between date and time iirc. which made the `new Date(...)` call return nonsense in Firefox but worked in Chrome.

**Comment by pferreir** [comment]
Yeah, but that means that the user would try to use a really silly year, such as `25000`. Not sure that's the case.

**Comment by ThiefMaster** [comment]
No, the broken date objects actually failed the check for perfectly valid dates

**Comment by lickdragon** [comment]
FWIW I was testing with Firefox when I received the error.  I will need to create a new Indico VM to test again - the original is now in production with 1.2 (stable).

**Comment by ThiefMaster** [comment]
6555a6f

**Comment by ThiefMaster** [comment]
Cherry-picked e67c8c961c0ef707df99aa675a8f3593a6848e5c
