### ISSUE TITLE
Creating a Session will always inherit location of parent, with no way to modify it afterwards

### ISSUE THREAD

**Issue by nop33** [indico/indico#1909]
Assuming that the location of an event is the following:

![](http://i.imgur.com/XqKJ3ir.png)

Add a new Session in the `/event/<event-id>/manage/timetable/` page using a different location than the one of the parent (event).
In page `event/<event-id>/session/<session-id>/` we see that on the top, the *Session Zero* `Session` inherited the location from the parent, but the *Session Zero* `SessionSlot`  has the correct location:

![](http://i.imgur.com/jsmTKpc.png)

**Comment by nop33** [comment]
After discussing with @pferreir, we decided to drop the support for location in the `Session` class, since it's useless, we only care for the location of the `SessionSlot`s.

**Comment by pferreir** [comment]
We had already dropped support for that, but apparently we forgot to delete it from that page.

**Comment by nop33** [comment]
To completely drop the support of location in the Session class, it should stop inheriting from Locatable. It doesn't harm keeping it for now and wait until we tackle that part of code.

**Comment by pferreir** [comment]
Agreed.

**Comment by ThiefMaster** [comment]
Obsolete since the removal of ZODB-based sessions
