### ISSUE TITLE
Bypass webcast/recording request automatic rejection for admins

### ISSUE THREAD

**Issue by nop33** [indico/indico#1912]
The webcast/recording requests get automatically rejected when there's no contribution in the rooms capable of webcasting/recording.

**Comment by ThiefMaster** [comment]
Ugh.. that's a bit tricky. We'll have to add a `created_by_av_manager` flag to the request (luckily we have `data` where we can easily store it). Then you can simply not auto-reject it whenever that flag is set.

**Comment by ThiefMaster** [comment]
Fixed in a7855e35 on gitlab
