### ISSUE TITLE
Registrants export API does not contain custom statuses

### ISSUE THREAD

**Issue by ThiefMaster** [indico/indico#1942]
> I tried to access registrants data for an upcoming conference we are
> organizing 
> I was able to extract all registration data as described on http://indico.readthedocs.org/en/latest/http_api/exporters/registration/#full
> But I could not get access to the custom statuses which can be defined
> i.e. at the registration setup in the managament interface

Probably makes sense to include this information...

**Comment by pferreir** [comment]
:+1:

**Comment by mic4ael** [comment]
- [ ] Additionally, prevent from adding a status with already defined caption

**Comment by ThiefMaster** [comment]
Since we can have multiple administrative sections now and don't necessarily have unique titles, I'd go for a structure like this:

    administrative_data: [{'section': 'foo', 'field': 'bar', field_id: 123, data: '...'}, ...]

That way we are flexible and don't have to worry about duplicate titles.

**Comment by pferreir** [comment]
PR made obsolete after reg. form migration.
