### ISSUE TITLE
Indico problems with 389 DS LDAP

### ISSUE THREAD

**Issue by albertocrj** [indico/indico#1945]
Hi Folks,

Indico version: 1.2.1rc1

I'm try to integrate with my 389DS but I'm getting the following error:

```
Exception type:     <class 'ldap.SERVER_DOWN'>
Exception message:  {'info': '(unknown error code)', 'desc': "Can't contact LDAP server"}
Traceback:  

  File "/usr/local/lib/python2.7/dist-packages/indico-1.2.1rc1-py2.7.egg/MaKaC/webinterface/rh/base.py", line 523, in process
    res = self._process()

  File "/usr/local/lib/python2.7/dist-packages/indico-1.2.1rc1-py2.7.egg/MaKaC/webinterface/rh/login.py", line 110, in _process
    return self._makeLoginProcess()

  File "/usr/local/lib/python2.7/dist-packages/indico-1.2.1rc1-py2.7.egg/MaKaC/webinterface/rh/login.py", line 74, in _makeLoginProcess
    av = authManager.getAvatar(li)

  File "/usr/local/lib/python2.7/dist-packages/indico-1.2.1rc1-py2.7.egg/MaKaC/authentication/AuthenticationMgr.py", line 58, in getAvatar
    user = auth.createUser(li)

  File "/usr/local/lib/python2.7/dist-packages/indico-1.2.1rc1-py2.7.egg/MaKaC/authentication/LDAPAuthentication.py", line 133, in createUser
    data = self.checkLoginPassword(li.getLogin(), li.getPassword())

  File "/usr/local/lib/python2.7/dist-packages/indico-1.2.1rc1-py2.7.egg/MaKaC/authentication/LDAPAuthentication.py", line 210, in checkLoginPassword
    if not ldapc.openAsUser(userName, password):

  File "/usr/local/lib/python2.7/dist-packages/indico-1.2.1rc1-py2.7.egg/MaKaC/authentication/LDAPAuthentication.py", line 404, in openAsUser
    self.login()

  File "/usr/local/lib/python2.7/dist-packages/indico-1.2.1rc1-py2.7.egg/MaKaC/authentication/LDAPAuthentication.py", line 357, in login
    self.l.bind_s(*self.ldapAccessCredentials)

  File "/usr/lib/python2.7/dist-packages/ldap/ldapobject.py", line 222, in bind_s
    msgid = self.bind(who,cred,method)

  File "/usr/lib/python2.7/dist-packages/ldap/ldapobject.py", line 216, in bind
    return self.simple_bind(who,cred)

  File "/usr/lib/python2.7/dist-packages/ldap/ldapobject.py", line 201, in simple_bind
    return self._ldap_call(self._l.simple_bind,who,cred,RequestControlTuples(serverctrls),RequestControlTuples(clientctrls))

  File "/usr/lib/python2.7/dist-packages/ldap/ldapobject.py", line 99, in _ldap_call
    result = func(*args,**kwargs)

Request handler:    RHSignIn
URL:    https://homolog2-indico.local/user/login
Params:     login = alberto.viana
returnURL = http://homolog2-indico.local/

Here's my indico.conf:
AuthenticatorList = [('Local', {}), ('LDAP', {'uri':'ldap://ldap.homlog.rnp',
                                                'useTLS':       False,
                                               'peopleDNQuery': ('uid={0}', 'ou=people,dc=homolog,dc=rnp'),
                                               'accessCredentials': ('uid=app.indico.r,ou=homolog,ou=rnp','my_user_password'),
                                               'groupStyle': 'SLAPD',
                                               })
                                               ]
```

If I try to connect manually, seems to work fine:

```
Python 2.7.6 (default, Mar 22 2014, 22:59:56) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import ldap
>>> con = ldap.initialize('ldap://ldap.homolog.rnp')
>>> dn = "uid=app.indico.r,ou=homolog,ou=rnp"
>>>  pw = "my_user_password"
>>> con.simple_bind_s( dn, pw )
(97, [], 1, [])
```

Any clue?

Thanks Alberto Viana

**Comment by pferreir** [comment]
It's weird. Seems like the server's unaccessible from the Indico machine? Are those logs obtained on the same machine? I believe `SERVER_DOWN` doesn't necessarily  mean the server is down, IIRC.

/cc @jacquesd 

--

BTW, if you would like to make sure that there is support for 389 in future versions of Indico, it would be great if you could test it against our new authentication lib:

https://gist.github.com/jacquesd/836e566c3b272fc55ac3

**Comment by albertocrj** [comment]
Pedro,

Yes, the logs were obtained in the same machine. Yeah, I think that too, but how can I debug it on indico?

I also made a script in python to test the connection and everything works fine.

All my tests are running from my indico's machine.

I will test this new lib against my 389 and let you know.

Thanks

**Comment by jacquesd** [comment]
Indeed, when implementing the new authentication lib, we had issues with ldap throwing `SERVER_DOWN` errors when it faild to do a SSL handshake.
But this should not be the case here as you don't use SSL (I recommend you do ).

The code you use to connect manually seems slightly different. Could you try and run this adapted version and let us know if it works?
```python
import ldap
conn = ldap.initialize('ldap://ldap.homolog.rnp')
conn.set_option(ldap.OPT_REFERRALS, 0)
conn.protocol_version = ldap.VERSION3
conn.set_option(ldap.OPT_X_TLS, ldap.OPT_X_TLS_NEVER)
dn = 'uid=app.indico.r,ou=homolog,ou=rnp'
pw = 'my_user_password'
conn.bind_s(dn, pw)
```

**Comment by albertocrj** [comment]
Hi,
Just to confirm to you that right now I'm not using the new lib. I tried this code and everything works fine too:
```
>>> import ldap
>>> conn = ldap.initialize('ldap://ldap.homolog.rnp')
>>> conn.set_option(ldap.OPT_REFERRALS, 0)
>>> conn.protocol_version = ldap.VERSION3
>>> conn.set_option(ldap.OPT_X_TLS, ldap.OPT_X_TLS_NEVER)
>>> dn = 'uid=app.indico.r,ou=homolog,ou=rnp'
>>> pw = 'my_user_password'
>>> conn.bind_s(dn, pw)
(97, [])
```

I'm not sure why, but everything is working now. I didn't change anything (neither in indico or in my 389). After test your code, I tried to auth and it's working....

I think that you can go ahead and close this ticket.

Some day in the next week I will test the new lib. I think that everything is going to work, because 389 is really similar to openldap, but I let you know.

**Comment by albertocrj** [comment]
Pedro,

One last doubt, I intend to use LDAPS ou TLS (as you recommended), where can I put my certs variable? In indico.conf? I could not found any related doc.

Thanks.

**Comment by pferreir** [comment]
You cannot specify certificates using 1.2.x. In version 2.x you'll be able to do that. Actually, I believe you can use the test app to check that? /cc @jacquesd

**Comment by jacquesd** [comment]
The test app handle LDAPS and TLS, but we had a few issue with verifying the connection using a certificate. Under heavy load, the `python-ldap` library sometimes  fails to verify the certificate and throws a `SERVER_DOWN` error. We are still investigating ,but for testing purposes it should work fine.

**Comment by pferreir** [comment]
I guess that's an implementation-specific problem, maybe @albertocrj can try on his side.

**Comment by ThiefMaster** [comment]
Likely fixed with recent python-ldap versions
