### ISSUE TITLE
Not Found 404 on start first time

### ISSUE THREAD

**Issue by epaolillo** [indico/indico#1947]
Dears, i  installed Indico in Ubuntu Server 14.10, after the process, i get an 404 error when access to the site.

Not Found

The requested URL /indico was not found on this server.
Apache/2.4.7 (Ubuntu) Server at 10.65.3.116 Port 80

Any suggestions. thanks in advance.
Ezequiel Paolillo.

**Comment by pferreir** [comment]
I guess your apache config is not properly working? It's hard to know without any logs or the relevant parts of the Apache config file.

**Comment by epaolillo** [comment]
error.log from apache2 logs

[Thu Jun 25 14:44:32.602397 2015] [:error] [pid 21540:tid 140703665420032] [client 192.168.237.56:34661]   [Errno 13] Permission denied: '/var/www/.python-eggs'
[Thu Jun 25 14:44:32.602421 2015] [:error] [pid 21540:tid 140703665420032] [client 192.168.237.56:34661] 
[Thu Jun 25 14:44:32.602430 2015] [:error] [pid 21540:tid 140703665420032] [client 192.168.237.56:34661] The Python egg cache directory is currently set to:
[Thu Jun 25 14:44:32.602438 2015] [:error] [pid 21540:tid 140703665420032] [client 192.168.237.56:34661] 
[Thu Jun 25 14:44:32.602446 2015] [:error] [pid 21540:tid 140703665420032] [client 192.168.237.56:34661]   /var/www/.python-eggs
[Thu Jun 25 14:44:32.602454 2015] [:error] [pid 21540:tid 140703665420032] [client 192.168.237.56:34661] 
[Thu Jun 25 14:44:32.602462 2015] [:error] [pid 21540:tid 140703665420032] [client 192.168.237.56:34661] Perhaps your account does not have write access to this directory?  You can
[Thu Jun 25 14:44:32.602470 2015] [:error] [pid 21540:tid 140703665420032] [client 192.168.237.56:34661] change the cache directory by setting the PYTHON_EGG_CACHE environment
[Thu Jun 25 14:44:32.602478 2015] [:error] [pid 21540:tid 140703665420032] [client 192.168.237.56:34661] variable to point to an accessible directory.
[Thu Jun 25 14:44:32.602486 2015] [:error] [pid 21540:tid 140703665420032] [client 192.168.237.56:34661]

**Comment by epaolillo** [comment]
Dear, I was can continue and a new error is visible in log, after click in any link inside Indico:

[Thu Jun 25 15:00:06.514531 2015] [:error] [pid 22476:tid 139744226809600]   File "/usr/lib/python2.7/smtplib.py", line 251, in __init__
[Thu Jun 25 15:00:06.514565 2015] [:error] [pid 22476:tid 139744226809600]     (code, msg) = self.connect(host, port)
[Thu Jun 25 15:00:06.514586 2015] [:error] [pid 22476:tid 139744226809600]   File "/usr/lib/python2.7/smtplib.py", line 311, in connect
[Thu Jun 25 15:00:06.514619 2015] [:error] [pid 22476:tid 139744226809600]     self.sock = self._get_socket(host, port, self.timeout)
[Thu Jun 25 15:00:06.514640 2015] [:error] [pid 22476:tid 139744226809600]   File "/usr/lib/python2.7/smtplib.py", line 286, in _get_socket
[Thu Jun 25 15:00:06.514671 2015] [:error] [pid 22476:tid 139744226809600]     return socket.create_connection((host, port), timeout)
[Thu Jun 25 15:00:06.514693 2015] [:error] [pid 22476:tid 139744226809600]   File "/usr/lib/python2.7/socket.py", line 571, in create_connection
[Thu Jun 25 15:00:06.514724 2015] [:error] [pid 22476:tid 139744226809600]     raise err
[Thu Jun 25 15:00:06.514773 2015] [:error] [pid 22476:tid 139744226809600] error: [Errno 111] Connection refused
[Thu Jun 25 15:00:06.514795 2015] [:error] [pid 22476:tid 139744226809600] Logged from file app.py, line 164

**Comment by ThiefMaster** [comment]
Your SMTP settings in indico.conf are not correct so sending an error email failed.

**Comment by epaolillo** [comment]
So... if i dont have well configurated SMTP then anything works???
Attach image

![selection_229](https://cloud.githubusercontent.com/assets/2317905/8361888/19b120bc-1b4c-11e5-825c-8703b4927f9a.jpg)

**Comment by pferreir** [comment]
No, the SMTP problem is just a side-effect. Can we get the traceback corresponding to the error in that screenshot? It should be in `indico.conf`.

**Comment by ThiefMaster** [comment]
Most likely importing `bcrypt` failed. Usually you can solve it by running `python -c 'import bcrypt'` as root.

**Comment by pferreir** [comment]
That thing again... I hope 2.0 is immune to that.

**Comment by ThiefMaster** [comment]
Yes, we'll simply fail with an ImportError at import time if bcrypt is not importable instead of silently ignoring it until it's actually accessed.
