### ISSUE TITLE
Room Booking: Hidden rooms

### ISSUE THREAD

**Issue by OmeGak** [indico/indico#1949]
Ticket in SNOW `INC0808339` involved a lot of people trying to figure out why one of the rooms didn't show the correct information from GESLOC on Indico. 

The situation finally was simply that the room had been used at some point for meetings and therefore it's listed in Indico as disabled. However, since `foundationsync` plugin only fetches meeting rooms (which I think it's as it should), the information eventually gets outdated in our system.

The problem is that maybe the rooms should be hidden altogether, and not only disabled, in order to avoid confusion. And this brings me to the suggestion of having a new `hidden` state for rooms, so that they disappear completely from the interface.

**Comment by pferreir** [comment]
See #3065

**Comment by pferreir** [comment]
No longer applies in 2.2.
