### ISSUE TITLE
Slides files hidden behind the down arrow :-(

### ISSUE THREAD

**Issue by SebastianLopienski** [indico/indico#1966]
I just noticed that in the new interface at indico.cern.ch, when slides attached to a contribution have both PDF and PPT version, I have to click on the down arrow and then select the format I want. Previously I could see both PDF and PPT icons right away - so one click less! Is this a permanent change? Any chance of reverting back to this previous interface?

**Comment by pferreir** [comment]
OK, now folders with up to 2 files should be displayed inline. In any case, folders are not needed anymore.

**Comment by SebastianLopienski** [comment]
Cool, thanks!
