### ISSUE TITLE
Previewer for attachments

### ISSUE THREAD

**Issue by pferreir** [indico/indico#1973]
It should be some kind of overlay with at least a "close" and a "download" button. By default, when the user clicks on a file that a 'previewer' exists for, it should open a new overlay with a preview (for images and PDFs that could be an `iframe`).

Other things to take into account:
 * [x] Extensibility - plugins should be able to add their own previewers
 * [x] Some file types should (probably) be downloaded immediately, as it's not always easy to preview them (e.g. PPT, DOC) (TBD).

**Comment by nop33** [comment]
I think this can be closed.

**Comment by pferreir** [comment]
Let's wait until #1984 gets merged.
