### ISSUE TITLE
"Add myself" option in addition to add new/indico user

### ISSUE THREAD

**Issue by ThiefMaster** [indico/indico#1977]
> again making a conference, I always have the same awkwardness: adding myself.
> Would it be possible to have an "Add me" button next to "Add Indico User" and "Add New" wherever one can add someone?

CHG33901

**Comment by pferreir** [comment]
Isn't it enough to have yourself in your favorites? Sure, this is a common UX pattern, but I'm wondering whether we will have space for yet another option (since we always have to have "Add Indico User" and "Add new").

**Comment by ThiefMaster** [comment]
added in #4411
