### ISSUE TITLE
Add auto-complete to "create" folder dialog

### ISSUE THREAD

**Issue by pferreir** [indico/indico#1978]
Users are still used to the old "materials-based" logic. While I'm convinced 95% of people just don't need folder, we should provide a kind of bridge to that old behaviour.
The idea would be to turn the "folder name" field into an auto-complete box, based on a set of hardcoded names. The legacy ones are defined [here](https://github.com/indico/indico/blob/v1.2/indico/MaKaC/webinterface/materialFactories.py#L400).
But the list should be configurable (DB setting?).

**Comment by pferreir** [comment]
I'd suggest:
* Paper
* Slides
* Poster
* Minutes
* Agenda
* Pictures
* Document
* Drawings
* Proceedings
* Webcast
* Video
* Recording
* Notes
* Summary
* Text
* List of Actions

**Comment by ThiefMaster** [comment]
> * Text

Shouldn't people usually use notes for that?

**Comment by pferreir** [comment]
Well, there's also "Notes". This is targeted at people who want to upload e.g. PDF files.
