### ISSUE TITLE
Sensible default for "cloning date"

### ISSUE THREAD

**Issue by pferreir** [indico/indico#1990]
We're setting today by default, which is really not a good idea.

**Comment by DirkHoffmann** [comment]
:+1: 
It is more likely that I want to clone a meeting on the next same weekday. (So if the meeting was on a Monday a long time ago, it would be cloned not today, not last Monday, but the Monday next week.)
If the to-be-cloned meeting was already cloned and there is a link to the first original, it would be easier to predict what the next likely occurrence is.
Or do you have something else in mind?

**Comment by pferreir** [comment]
@DirkHoffmann, no, that's exactly it. Thanks!

**Comment by DirkHoffmann** [comment]
Maybe it would be useful (and quick) to propose three or four dates for the clone:
* Today
* Same week day next week
* Same week day in 2 weeks
* Same week day in 3 weeks
* ..

**Comment by ThiefMaster** [comment]
Sounds like a bit of overkill. It's not that hard to select the day in the calendar widget... I think having a sane default should be enough.

**Comment by DirkHoffmann** [comment]
Considering that clone-once is likely to be D+7 and D+14 in the majority of cases, the calendar is rather exceptionally more helpful than that.

**Comment by ThiefMaster** [comment]
The related PR was merged.
