### ISSUE TITLE
PDF files uploaded with wrong content type

### ISSUE THREAD

**Issue by OmeGak** [indico/indico#1994]
It seems some PDF files are uploaded with `application/x-download` as content type. It seems caused by some weird configuration in [pretty old](https://bugzilla.mozilla.org/show_bug.cgi?id=373621) versions of Firefox. There are currently over 200 instances of this issue in the production DB. Trying to preview the file causes an error since the content type is not supported.

I see two possible lines of action:
* Support `application/x-download` in the PDF previewer.
* Translate `application/x-download` to `application/pdf` on upload.

**Comment by ThiefMaster** [comment]
We don't even use  the mime type sent by the browser anymore (but we did for a week or so after the migration): https://github.com/indico/indico/blob/master/indico/modules/attachments/controllers/management/base.py#L94

So no recent file with a `.pdf` extension should have that content type.

**Comment by OmeGak** [comment]
I'll clean the db and close the issue then.
