### ISSUE TITLE
Download button in file previewer doesn't download file in Firefox

### ISSUE THREAD

**Issue by OmeGak** [indico/indico#1995]
The download button in the file previewer just opens the file in the full screen embedded browser previewer instead of actually downloading it.

**Comment by jacquesd** [comment]
I had a look and we are sending files with the `Content-Disposition` header set to `inline`. Accroding to MDN:
> If this attribute is present and `Content-Disposition:` is set to `inline`, Firefox gives priority to `Content-Disposition`, like for the filename case, while Chrome gives priority to the `download` attribute.

There are two simple solutions.
1. We leave it as it is. When the user click on *Download*, the file will be displayed inline (the user then has to right click *Save as* to save the file).
2. We send the file with the `Content-Disposition` set to `attachment` which will force the browser to download the file.

Note that in the latter case, we need to differentiate (for example with a query string parameter) the link in the download button from the one opening the previewer. (As a middle click on the latter would not open the file in a new tab but download it.) Internally, this would also require to expose the `inline` argument from the `send_file` function in `web/flask/util.py` all the way to the `send` function of `AttachmentFile`.

I personally suggest we go for the second solution.
