### ISSUE TITLE
Contributions on wrong session column in timetable view

### ISSUE THREAD

**Issue by OmeGak** [indico/indico#1997]
Related SNOW ticket `CHG33932`.

Contributions appear sometimes on a wrong session column in timetable view. I wasn't able to reproduce it, but it can be seen on [this timetable](https://indico.cern.ch/event/356420/timetable/#20150723.detailed).

![screenshot from 2015-08-03 15 16 46](https://cloud.githubusercontent.com/assets/716307/9038334/cbc59556-39f3-11e5-9301-daabede28302.png)

**Comment by ThiefMaster** [comment]
Same as #2999
