### ISSUE TITLE
Evaluation: Allow users to select horizontal vs. vertical radio fields

### ISSUE THREAD

**Issue by pferreir** [indico/indico#1999]
Stuff like `(x) Good  ( ) OK  ( ) Bad` or `( ) 1  ( ) 2  ( ) 3` doesn't need line breaks.

**Comment by ThiefMaster** [comment]
AFAIK radio boxes should never be aligned horizontally from an UI/UX point of view - unless there's a clear separator you don't immediately know if the label of the box is on the left or on the right.

**Comment by pferreir** [comment]
Maybe we can use the same kind of widget we use for e.g. room booking? This is really useful for evaluations.

**Comment by mic4ael** [comment]
This issue can be closed I think.
