### ISSUE TITLE
Dependencies errors on installation

### ISSUE THREAD

**Issue by epaolillo** [indico/indico#2003]
Dears, i need to know which Linux distribution are used for install Indico.
Im used Ubuntu, but many dependencies are missed or not founded.

Is possible what are use Scientific Linux distribute?
Please, tell me which is you recommended Distribution.

Thanks you very much!

**Comment by pferreir** [comment]
Hi,

There is no "recommended distribution" as such. Any linux distro with Python 2.7 will work.
As for the dependency errors, if you paste some info on the errors you're getting, then we'll be able to help.

**Comment by epaolillo** [comment]
Ok, if i follow the "step by step" installation at manual, doesnt work.
I paste the logs errors, to find a solution.

Thank you very much!!


[Mon Jun 29 06:54:33.859963 2015] [mpm_event:notice] [pid 22721:tid 140091192878976] AH00489: Apache/2.4.7 (Ubuntu) OpenSSL/1.0.1f mod_wsgi/3.4 Python/2.7.6 configured -- resuming normal operations
[Mon Jun 29 06:54:33.860016 2015] [core:notice] [pid 22721:tid 140091192878976] AH00094: Command line: '/usr/sbin/apache2'

access.log

192.168.1.15 - - [29/Jun/2015:11:48:34 -0300] "OPTIONS / HTTP/1.1" 200 195 "-" "Mozilla/5.0 (compatible; Nmap Scripting Engine; http://nmap.org/book/nse.html)"
192.168.1.15 - - [29/Jun/2015:11:48:34 -0300] "OPTIONS / HTTP/1.1" 200 195 "-" "Mozilla/5.0 (compatible; Nmap Scripting Engine; http://nmap.org/book/nse.html)"
192.168.1.15 - - [29/Jun/2015:11:48:34 -0300] "OPTIONS / HTTP/1.1" 200 195 "-" "Mozilla/5.0 (compatible; Nmap Scripting Engine; http://nmap.org/book/nse.html)"
192.168.1.15 - - [29/Jun/2015:11:48:34 -0300] "OPTIONS / HTTP/1.1" 200 195 "-" "Mozilla/5.0 (compatible; Nmap Scripting Engine; http://nmap.org/book/nse.html)"
192.168.1.15 - - [29/Jun/2015:11:48:35 -0300] "OPTIONS / HTTP/1.1" 200 195 "-" "Mozilla/5.0 (compatible; Nmap Scripting Engine; http://nmap.org/book/nse.html)"
192.168.1.15 - - [29/Jun/2015:11:48:35 -0300] "OPTIONS / HTTP/1.1" 200 195 "-" "Mozilla/5.0 (compatible; Nmap Scripting Engine; http://nmap.org/book/nse.html)"
192.168.1.15 - - [29/Jun/2015:11:48:35 -0300] "OPTIONS / HTTP/1.1" 200 195 "-" "Mozilla/5.0 (compatible; Nmap Scripting Engine; http://nmap.org/book/nse.html)"
192.168.1.15 - - [29/Jun/2015:11:48:37 -0300] "OPTIONS / HTTP/1.1" 200 195 "-" "Mozilla/5.0 (compatible; Nmap Scripting Engine; http://nmap.org/book/nse.html)"
192.168.1.15 - - [29/Jun/2015:11:48:40 -0300] "GET /robots.txt HTTP/1.1" 404 463 "-" "Mozilla/5.0 (compatible; Nmap Scripting Engine; http://nmap.org/book/nse.html)"
192.168.1.15 - - [29/Jun/2015:11:48:48 -0300] "GET /favicon.ico HTTP/1.1" 404 464 "-" "

**Comment by pferreir** [comment]
Those logs are not very helpful, considering that you are having (apparently) dependency issues. That would be the important thing to know: which dependencies are missing and error messages you are getting.

**Comment by epaolillo** [comment]
i was looking for the indico logs, but i dont know where find.
What is the ordinary path where are that logs?

**Comment by pferreir** [comment]
Sorry, maybe I misunderstood, but you told me that "many dependencies are missed or not found." Which dependencies are those?
