### ISSUE TITLE
Remove legacy principal list selector

### ISSUE THREAD

**Issue by OmeGak** [indico/indico#2006]
We still have the legacy principal list selector hanging around. Nothing urgent, but we got complaints that it doesn't show the email and that is a problem when there are duplicated users listed. Rather than fixing it we should replace all occurrences of the old widget with the new one.

Here there is an example of both widgets in the same page and the problem with duplicated users:

![screenshot from 2015-08-18 10 42 09](https://cloud.githubusercontent.com/assets/716307/9326292/ff39dae0-4598-11e5-8bc6-199f1800b1c2.png)

**Comment by ThiefMaster** [comment]
Obsolete since we've rewritten the protection page
