### ISSUE TITLE
Resend survey notification on reopening/rescheduling

### ISSUE THREAD

**Issue by OmeGak** [indico/indico#2007]
Currently we only send a single notification when the survey starts. In cases where the survey is reopen or reschedule to start later after having been opened already no notification is sent. We should either send the notification anew or go for a more manual approach by adding a button to resend it on demand.

**Comment by ThiefMaster** [comment]
I think this should be a checkbox in the "schedule" dialog (which would be hidden if no notification has been sent before).

Also, should we add a confirm prompt when opening a survey manually in case notifications are going to be sent? I can already imagine people opening it just to test it and then getting complaints from people who were notified about it being opened even though it wasn't.
