### ISSUE TITLE
Cannot limit iCal export with API key

### ISSUE THREAD

**Issue by DirkHoffmann** [indico/indico#2009]
When I download `https://my.indico/export/categ/123.ics`,
then I may specify  `https://my.indico/export/categ/123.ics`**`&from=-7d`**.
But for `https://my.indico/export/categ/123.ics&apikey=aabbcc&signature=ddeeff&from=-7d` 
I get a **403 - Forbidden** response.
(On https://indico.cern.ch, https://indico.cern.ch/category/186/ for example.)

**Comment by pferreir** [comment]
First of all, the URL should be:
`https://my.indico/export/categ/123.ics`**?**`apikey=aabbcc&signature=ddeeff&from=-7d`

Any chance the signature is actually wrong? Are you disabling timestamps?

**Comment by DirkHoffmann** [comment]
Yes, the working example was a copy-paste failure indeed. :scream: 
And I don't know where the second one came from, because right now the link given by Indico on the category page contains **`from=-7`**. :confused: 
And for the signature, I must admit I had completely forgotten how they are made. Actually I do not really see, why non-persistent signatures would be useful. In order to import categories into calendars, a constant URL will be used by the majority of users. (I doubt that there are many who would make the technical effort to re-direct from a key-generation URL on a secure host to Indico via volatile signature URLs.)
Well, sorry for the noise. I I was successful importing my calendar now. I will try the signature generation "later". ;-)
Maybe the default could be -40d or -90d rather than -7d. (Sometimes I like to look after old meetings.) But I understand you do not want to overload the servers. Probably I should copy interesting meetings into my own calendar as soon as they show up.

**Comment by ThiefMaster** [comment]
non-persistent signatures were what we initially had to prevent reusing "stolen" urls. nowadays with everything being on SSL (hopefully) it's indeed not extremely useful. the only usecase i could imagine is a website that wants to use the api client-side without giving the user access to anything else (i.e. it'd create the signed url on the server side and then only provide the clientside code with that url) or permanent access to the data from the generated url. Anyway, when it comes to how to access the API I posted some ideas in #1934
