### ISSUE TITLE
ubuntu install guide available

### ISSUE THREAD

**Issue by dfgordon** [indico/indico#2017]
I wrote a detailed installation guide for indico 1.2 on Ubuntu, documenting every step starting with a raw server installation, along with a bit of background (which I hope I got right).  If there is any interest in this let me know.

Apologies that this is not exactly an "issue" but I didn't know where else to go with it.

**Comment by ThiefMaster** [comment]
Can you attach it somewhere so we can have a look at it?

**Comment by dfgordon** [comment]
I found only image formats can be attached from GitHub, but will try to attach a pdf via e-mail response.
It could be put as text with some loss of clarity, or as latex with a bit of effort (current source is MS Word).

**Comment by ThiefMaster** [comment]
Documentation should be written in reStructured text to be included in Indico. Anyway, for a first look any format is fine. If attaching it here doesn't work you could simply upload them on your webspace if you have some or use a Git repo for it.

**Comment by pferreir** [comment]
I don't know whether it would be wise to include an install guide for a specific OS in the repo. Maybe we should have in the wiki instead?

**Comment by ThiefMaster** [comment]
Yeah, I hoped it'd be generic enough to avoid having references to ubuntu in there at all

**Comment by dfgordon** [comment]
I’m pleased to follow any guidance regarding where to post, except that I am at an institution where posting anything on an internal outward facing server takes high level authorization, so that option is probably out.

As a generalization strategy, it might be possible to re-cast things in two tracks, one for Debian and one for RPM.  That would cover most of linux without favoring anybody’s distribution.  I would have to go test a procedure on RPM, but am willing to do so as a service.

By way of background, we are linux users and scientific programmers, not system administrators, which perhaps affects some of the emphasis.  I dug deep into google search results trying to find this sort of guide with no luck, leading me to suppose there may be some demand for it.

**Comment by pferreir** [comment]
Maybe we could add this to our already existing [installation guide](http://indico.readthedocs.org/en/latest/installation/)?

I think it would be great to have more detailed installation instructions, also in what concerns editing `indico.conf` (especially important for version 2.0).

Having some OS-specific (but still general) instructions would of course help, but I am not sure how far we should go. It's something else that we have to keep updating. And other projects prefer to leave things in general terms:
  * https://docs.getsentry.com/on-premise/server/installation/
  * https://github.com/discourse/discourse/blob/master/docs/INSTALL.md (only docker install)
  * http://docs.celeryproject.org/en/latest/getting-started/introduction.html

**Comment by yuhow** [comment]
I am currently trying to install Indico on Ubuntu. But I encounter lots of problem... Could you please provide me your guideline? So many thanks for your help!

**Comment by dfgordon** [comment]
Yes, there are lots of pitfalls.  I am on vacation and don’t have it here, but will try to remember to forward it when I return.

**Comment by dfgordon** [comment]
Hello, I attached the guide.  I hope it helps.
-Dan Gordon

**Comment by yuhow** [comment]
Dear Dan,

Umm... Could you remind me where I could find that guide?


Thanks a lot

**Comment by dfgordon** [comment]
Did you find the attachment yesterday?

**Comment by ThiefMaster** [comment]
Did you attach it to the email? Here on GitHub no attachment shows up...

**Comment by dfgordon** [comment]
OK, I posted the file here:

https://indico.syntek.org/category/1/# <https://indico.syntek.org/category/1/#>

Look under Files/document.
It is not really an appropriate place to post this, but perhaps it will do for now.

-Dan

**Comment by ThiefMaster** [comment]
Copied it to github (in a browser attaching files works fine): [Indico12-Setup-Ubuntu.pdf](https://github.com/indico/indico/files/57064/Indico12-Setup-Ubuntu.pdf)

**Comment by ThiefMaster** [comment]
legacy, and we have a proper official install guide now
