### ISSUE TITLE
Include Presenters in the Author list

### ISSUE THREAD

**Issue by nop33** [indico/indico#2029]
Currently the Author list (`event/<event_id>/manage/call-for-abstracts/abstracts/perform-action`) displays the following participants lists:
![](http://i.imgur.com/DSW6Mhw.png)
omitting the Presenters.

Another idea is that we could add the Presenters and the Submitters in the list of abstracts (`event/<event_id>/manage/call-for-abstracts/abstracts/`), but since the table is going to be quite huge, maybe we should consider to have configurable columns so people can see/export only what the need.

**Comment by OmeGak** [comment]
We will be using the new author list widget in `v1.9.9`, so this won't be a problem anymore.
