### ISSUE TITLE
Clone surveys while cloning an event

### ISSUE THREAD

**Issue by ThiefMaster** [indico/indico#2045]
We used to have this with the old evaluation system. Probably only few people ever used it but it would be nice to add it back at some point.

**Comment by pferreir** [comment]
Let me add that I got feedback from a user who actually used the Import/Export XML feature. I'm not sure whether bringing both back is the way to go, but at least one should be available.

**Comment by ThiefMaster** [comment]
If we want to bring import/export back I think it should be JSON instead of XML for sure... but it seems cloning makes more sense since we have cloning for everything else while we had import/export only for evaluations

**Comment by OmeGak** [comment]
The CERN Summer Student Programme plan to start using surveys next year. 

While question export/import will save them time, survey configurations still require manual configuration. Having 3 lectures per day during roughly two months adds up to manually configuring several dozens surveys. Cloning surveys on event clone would avoid that.
