### ISSUE TITLE
There is no indico-checkin consumer key for OAuth

### ISSUE THREAD

**Issue by mvala** [indico/indico#2047]
I would like to see QR code of the event and i am getting:

```
There is no indico-checkin consumer key for OAuth
```

What do i need to do to configure it? I have installed indico check-in app.

**Comment by risturiz** [comment]
I have this problem too.

**Comment by ThiefMaster** [comment]
In 1.2 you need to create an oauth app in the admin settings with the exact name `indico-checkin`

**Comment by risturiz** [comment]
Thats right... @ThiefMaster help me on irc... Login with admin user then "Server Admin" -> "Services" and click tab "OAuth"... You have to add consumer with name "indico-checkin" and you will hace the qr code (i have another problem with android app, that redirect to localhost when i want to create the event with qr code)

**Comment by ThiefMaster** [comment]
obsolete; 2.x creates those oauth consumers automatically
