### ISSUE TITLE
Moderated event creation

### ISSUE THREAD

**Issue by ThiefMaster** [indico/indico#2057]
In some categories it would be useful if users could create events that need to be approved by a category manager before they are actually created.
- Test category (non-CERN users in our case) - letting everyone create events there invites spam and trolling, but there are some valid use cases, e.g. people who have a conference that's organized via our Indico system and need a test event to test certain features.
- High-profile categories (e.g. "conferences") - people end up creating test events in such categories even though they don't belong in there. Since such categories are likely to be displayed in a prominent way (upcoming events, external sites, etc) only "proper" events should show up there.

**Comment by pferreir** [comment]
:+1:

**Comment by pferreir** [comment]
@tgbaron just had the same idea. This would indeed really help.

**Comment by jouvin** [comment]
+1.

We have a use case at LAL a little bit different from those mentioned in the description. This is about the organization of the internal seminars at the lab. To streamline the process that currently involves an offline interaction with the seminar coordinator, we’d like to allow anybody in the lab to be able to create a “tentative seminar” based on the Indico calendar availability and have the coordinator validating the “tentative entry” before its appears in the calendar of events. Something somewhat similar to the “pre-reservation” workflow for room booking but applied to events. This sounds as something we could do with the proposed feature.
