### ISSUE TITLE
Locked events: keep data in management area readable (e.g. registrant database)

### ISSUE THREAD

**Issue by shesselbach** [indico/indico#2058]
This _feature request_ was suggested by one of our users:

Usually Indico events are locked to make them _read-only_, so they
can't be changed anymore. A very unfortunate side effect is that
the whole management interface is disabled. That makes it impossible
to inspect such an event and determine information which is only
visible via the management interface, like the registrant data base.
It be very helpful to have the management interface available for
locked events, but of course with all options which can change data
disabled.

I'm aware that one can _un-lock_ an event, but making something
writable just to read and inspect it seems to me the wrong way
to handle this use case.

**Comment by ThiefMaster** [comment]
I agree, the current behavior of locked events is pretty broken/useless.

We are actually considering to completely remove this feature. It is not widely used (at least in our case) anyway. But if we end up keeping it for some reason, we'd certainly change it in the way you suggested: Make everything read-only but keep it accessible.

**Comment by shesselbach** [comment]
The answer of our user:
"Yes, protecting against *accidental modifications* is the main reason to lock an event."

**Comment by ThiefMaster** [comment]
We improved this in 2.0 to make things read-only without removing any read access in locked events.
