### ISSUE TITLE
Remove deletion code in create_xyz fixtures

### ISSUE THREAD

**Issue by ThiefMaster** [indico/indico#2059]
Not sure why I added them initially... but after somebody asked me yesterday why we need to explicitly delete the objects when exiting the fixture I just gave it a quick try and it doesn't seem to be necessary at all..

Probably I had added those deletes in one place (maybe when migrating `create_user` to the new user system since it had deletion code before) and then had to add them everywhere else to avoid deleting things that were still referenced elsewhere.

Not sending explicit deletes (we rollback when leaving the `db` fixture anyway) also results in a massive speed-up (from 344s to 72s).

**Comment by jbenito3** [comment]
somebody... :smile_cat:

**Comment by pferreir** [comment]
:dancer:
