### ISSUE TITLE
Secure login URL appears not to respect BaseURL/BaseSecureURL

### ISSUE THREAD

**Issue by bjornwiberguadmuuse** [indico/indico#2061]
Indico v1.2.1rc1 on Red Hat Enterprise Linux 7:

Visiting Indico via HTTP and clicking on Login yields a series of redirects, where the last one appears not to respect the BaseURL/BaseSecureURL setting.

Instead of ending up at:
https://uuc-web003-t.its.uu.se/indico/user/login?returnURL=http%3A%2F%2Fuuc-web003-t.its.uu.se%2Findico%2F
...one instead ends up at:
https://uuc-web003-t.its.uu.se/user/login?returnURL=http%3A%2F%2Fuuc-web003-t.its.uu.se%2Findico%2F
...which of course does not exist.

[excerpt from /opt/indico/etc/indico.conf]
```
BaseURL              = "http://uuc-web003-t.its.uu.se/indico"
BaseSecureURL        = "https://uuc-web003-t.its.uu.se/indico"
AuthenticatedEnforceSecure = "yes"
```

[excerpt from /opt/indico/tmp/vars.js.tpl.tmp]
```
       Login: {"rules": [{"args": [], "trace": [{"is_dynamic": false, "data": "|"}, {"is_dynamic": false, "data": "\/user\/login"}], "defaults": null, "converters": {}}], "endpoint": "user.signIn", "type": "flask_rules"},
```
Example which shows the 303 redirect from Indico:
```
bwiberg@UADM-LL044739:~$ wget -S 'http://uuc-web003-t.its.uu.se/indico/user/login?returnURL=http%3A%2F%2Fuuc-web003-t.its.uu.se%2Findico%2F'
--2015-09-15 14:12:38--  http://uuc-web003-t.its.uu.se/indico/user/login?returnURL=http%3A%2F%2Fuuc-web003-t.its.uu.se%2Findico%2F
Slår upp uuc-web003-t.its.uu.se (uuc-web003-t.its.uu.se)... 130.238.7.185, 2001:6b0:b:242:130:238:7:185
Ansluter till uuc-web003-t.its.uu.se (uuc-web003-t.its.uu.se)|130.238.7.185|:80... ansluten.
HTTP-begäran skickad, väntar på svar...
  HTTP/1.1 303 SEE OTHER
  Date: Tue, 15 Sep 2015 12:12:38 GMT
  Server: Apache
  Content-Length: 405
  Location: https://uuc-web003-t.its.uu.se/user/login?returnURL=http%3A%2F%2Fuuc-web003-t.its.uu.se%2Findico%2F
  Keep-Alive: timeout=5, max=100
  Connection: Keep-Alive
  Content-Type: text/html; charset=utf-8
Adress: https://uuc-web003-t.its.uu.se/user/login?returnURL=http%3A%2F%2Fuuc-web003-t.its.uu.se%2Findico%2F [följer]
--2015-09-15 14:12:38--  https://uuc-web003-t.its.uu.se/user/login?returnURL=http%3A%2F%2Fuuc-web003-t.its.uu.se%2Findico%2F
Ansluter till uuc-web003-t.its.uu.se (uuc-web003-t.its.uu.se)|130.238.7.185|:443... ansluten.
HTTP-begäran skickad, väntar på svar...
  HTTP/1.1 404 Not Found
  Date: Tue, 15 Sep 2015 12:12:38 GMT
  Server: Apache
  Content-Length: 330
  Keep-Alive: timeout=5, max=100
  Connection: Keep-Alive
  Content-Type: text/html; charset=iso-8859-1
2015-09-15 14:12:38 FEL 404: Not Found.
```
I have tried stopping Apache, removing the vars.js.tpl.tmp and starting Apache again, but the same thing happens again.

How is the secure login redirection URL constructed? It appears not to care for our /indico/ location...

**Comment by ThiefMaster** [comment]
It's recommended to use / instead of /indico. In newer versions that's actually the default and I think 1.2 has issues in some cases when it comes to ssl redirects and /indico (I thought we fixed them in 1.2.1 though...)

Anyway, it's a good idea to use full-ssl nowadays, i.e. use a https url in BaseURL, too, and redirect all http requests to https immediately.

**Comment by bjornwiberguadmuuse** [comment]
Thanks, I'll switch to HTTPS entirely then!

But it may be worth taking a closer look at how the login URL is constructed.

Also, the indico.conf.sample with v1.2.1rc1 specifies:

BaseURL              = "http://localhost:8000/indico"
BaseSecureURL        = "https://localhost:8443/indico"
AuthenticatedEnforceSecure = "yes"

...so I guess it needs to be adjusted as well for future releases.

**Comment by ThiefMaster** [comment]
In the branches leading towards 2.0 it's already changed ;)

**Comment by bjornwiberguadmuuse** [comment]
Thanks!

**Comment by bjornwiberguadmuuse** [comment]
It appears there are other references to /indico -- namely /indico/static -- in the CSS files, even after adjusting the base URLs not to end with /indico.

Could you please comment on whether this is also something that will go away in upcoming releases?

130.238.131.157 - - [15/Sep/2015:15:23:07 +0200] "GET /indico/static/fonts/icomoon/icomoon.woff?_=NA HTTP/1.1" 404 3272 "https://uuc-web003-t.its.uu.se/static/assets/sass/screen_sass_e889727a.css" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:40.0) Gecko/20100101 Firefox/40.0" "uuc-web003-t.its.uu.se"
130.238.131.157 - - [15/Sep/2015:15:23:07 +0200] "GET /indico/static/fonts/roboto/Roboto-Regular-webfont.woff?_=NA HTTP/1.1" 404 3272 "https://uuc-web003-t.its.uu.se/static/assets/sass/screen_sass_e889727a.css" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:40.0) Gecko/20100101 Firefox/40.0" "uuc-web003-t.its.uu.se"
130.238.131.157 - - [15/Sep/2015:15:23:07 +0200] "GET /indico/static/fonts/icomoon/icomoon.ttf?_=NA HTTP/1.1" 404 3272 "https://uuc-web003-t.its.uu.se/static/assets/sass/screen_sass_e889727a.css" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:40.0) Gecko/20100101 Firefox/40.0" "uuc-web003-t.its.uu.se"
130.238.131.157 - - [15/Sep/2015:15:23:07 +0200] "GET /indico/static/fonts/roboto/Roboto-Regular-webfont.ttf?_=NA HTTP/1.1" 404 3272 "https://uuc-web003-t.its.uu.se/static/assets/sass/screen_sass_e889727a.css" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:40.0) Gecko/20100101 Firefox/40.0" "uuc-web003-t.its.uu.se"
2001:6b0:b:285:adca:b630:ea06:7363 - - [15/Sep/2015:15:24:58 +0200] "GET / HTTP/1.1" 200 4370 "https://uuc-web003-t.its.uu.se/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:40.0) Gecko/20100101 Firefox/40.0" "uuc-web003-t.its.uu.se"
2001:6b0:b:285:adca:b630:ea06:7363 - - [15/Sep/2015:15:25:05 +0200] "GET /indico/static/fonts/roboto/Roboto-Regular-webfont.woff?_=NA HTTP/1.1" 404 3272 "https://uuc-web003-t.its.uu.se/static/assets/sass/screen_sass_e889727a.css" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:40.0) Gecko/20100101 Firefox/40.0" "uuc-web003-t.its.uu.se"
2001:6b0:b:285:adca:b630:ea06:7363 - - [15/Sep/2015:15:25:05 +0200] "GET /indico/static/fonts/icomoon/icomoon.woff?_=NA HTTP/1.1" 404 3272 "https://uuc-web003-t.its.uu.se/static/assets/sass/screen_sass_e889727a.css" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:40.0) Gecko/20100101 Firefox/40.0" "uuc-web003-t.its.uu.se"
2001:6b0:b:285:adca:b630:ea06:7363 - - [15/Sep/2015:15:25:11 +0200] "GET /indico/static/fonts/icomoon/icomoon.ttf?_=NA HTTP/1.1" 404 3272 "https://uuc-web003-t.its.uu.se/static/assets/sass/screen_sass_e889727a.css" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:40.0) Gecko/20100101 Firefox/40.0" "uuc-web003-t.its.uu.se"
2001:6b0:b:285:adca:b630:ea06:7363 - - [15/Sep/2015:15:25:11 +0200] "GET /indico/static/fonts/roboto/Roboto-Regular-webfont.ttf?_=NA HTTP/1.1" 404 3272 "https://uuc-web003-t.its.uu.se/static/assets/sass/screen_sass_e889727a.css" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:40.0) Gecko/20100101 Firefox/40.0" "uuc-web003-t.its.uu.se"

Many thanks in advance!

**Comment by ThiefMaster** [comment]
Did you restart the webserver? You might also have to delete any `.webassets-cache` folders and the cached js vars (simply deleting everything in the tmp and cache folders is probably best) that are around.

**Comment by bjornwiberguadmuuse** [comment]
Thanks, that seems to do the trick! I now perform the following on indico.conf configuration changes:

/bin/rm -rf /opt/indico/cache/generic_cache /opt/indico/htdocs/static/assets/.webassets-cache /opt/indico/tmp/egg-cache /opt/indico/tmp/mako_modules
/bin/rm -f /opt/indico/tmp/vars.js.tpl.tmp

Does this sound sensible, or should I purge anything more?

Many thanks in advance!

**Comment by bjornwiberguadmuuse** [comment]
Related to this: Shouldn't /static be mapped to /opt/indico/htdocs/static? Or does it need to go through the application in order for files to be generated?

For instance:

https://uuc-web003-t.its.uu.se/static/assets/js/indico_common_c3e326ec.min.js

The documentation at:

http://indico.readthedocs.org/en/latest/installation/#configuring-the-web-server

...only states:

Alias /indico/images "/opt/indico/htdocs/images"
Alias /indico/css "/opt/indico/htdocs/css"
Alias /indico/js "/opt/indico/htdocs/js"
Alias /indico/ihelp "/opt/indico/htdocs/ihelp"

...but not /static?

**Comment by ThiefMaster** [comment]
`/static/plugins/...` is dynamically mapped to static folders of indico plugins (iirc. not in 1.2.x, but in newer versions). Anything else could indeed be mapped to the htdocs/static folder though.

**Comment by bjornwiberguadmuuse** [comment]
OK, many thanks, I'll let Apache serve /static/assets (/opt/indico/htdocs/static/assets) and /static/fonts (/opt/indico/htdocs/static/fonts) -- the only two folders present from what I can see -- from disk, then.
