### ISSUE TITLE
Search view: improve readability of dates; add link+title of meeting

### ISSUE THREAD

**Issue by marcovanleeuwen** [indico/indico#2066]
Hi,

I would suggest to display two thing more prominently when displaying search results on Indico: the date of the meeting (there is a date; not sure whether it is the event date, or the file date, but it does not stand out) and the name of the meeting in which slides etc were presented (maybe instead of the  button 'meeting details').

Currently, the size and file type are prominently displayed, but those are not so interesting (in particular the file type in text, since the icon also indicates it).

Best regards,

Marco.

**Comment by ThiefMaster** [comment]
Is this a suggestion for search results on indico.cern.ch? In that case the GitHub issue tracker is the wrong place for it - the CERN indico instance uses "cernsearch" which is a proprietary search engine used by various services at CERN and not part of indico (we only embed it using an iframe). You might want to email indico-support@cern.ch instead.

**Comment by marcovanleeuwen** [comment]
Thanks for the tip; this was indeed for the CERN indico; I will take it up with them.
