### ISSUE TITLE
Comply with PEP470 (external repos)

### ISSUE THREAD

**Issue by pferreir** [indico/indico#2073]
[PEP470](http://legacy.python.org/dev/peps/pep-0470/) aims at "fixing" packages that are hosted in PyPI but have their binary files elsewhere.

IIRC the only reason for hosting Indico outside PyPI is the total size of the package, which surpasses the 50MB (?) maximum (maybe that has changed too?). We should analyze whether that is still an issue (I'd say so, since we still bundle a few 3rd party libs and a lot of images). OTOH there are possible solutions such as:
- Moving forward with the removal of certain 3rd party JS libs that still remain in the code base;
- Splitting the main package in smaller chunks;
- Hosting binaries such as fonts using some other mechanism;

Otherwise, someone has made available [guidelines for a self-hosted repo](https://packaging.python.org/en/latest/self_hosted_repository/). That's maybe an easier solution, but one that is less user-friendly.

This is pretty urgent since there is a 3 month deadline that has to be respected. **After that, they'll pull the plug.**

**Comment by ThiefMaster** [comment]
Can't people just `pip install http://.....`? Then we could simply use GitHub releases.

**Comment by pferreir** [comment]
> Can't people just pip install http://.....? Then we could simply use GitHub releases.

Having an `indico` package in PyPI also ensures no-one else takes the name.
Moreover, `pip install indico` is much more convenient. Except for Go's, I don't know of any package manager where people have to explicitly use URLs. That's what package managers exist for: so that you have a central index of packages and don't need to look up the URL and check out the repo for yourself.

> There are those extremely outdated "video services guides" in ihelp... I guess they could go away? That would remove ~10MB.

Yes. If [this](https://github.com/indico/indico/tree/master/indico/htdocs/ihelp/VideoServices) is what you're talking about, then, it really seems ancient.

> We could default to MathJax's CDN

Not that enthusiastic about it. It's an additional point of failure :unamused:

**Comment by ThiefMaster** [comment]
3b36483

**Comment by ThiefMaster** [comment]
```
-rw-r--r--  1 root root  66M Sep 25 10:44 indico-1.9.6-py2.7.egg
-rw-r--r--  1 root root  64M Sep 25 10:45 indico-1.9.6-py2-none-any.whl
-rw-r--r--  1 root root  45M Sep 25 10:44 indico-1.9.6.tar.gz
```

Current build without the obsolete docs. pyc files are ~11M. Could we just use a sdist that still includes all the prebuilt stuff? That way we'd already be below the 50MB limit. Shipping pyc files seems a bit pointless anyway.

**Comment by jbenito3** [comment]
guys, what about using bower or so? so we can also get rid of the js libs...

**Comment by ThiefMaster** [comment]
Don't we want to have everything needed to run indico in the pip-installable package? I think without JS libs and documentation PDFs we'd be way below the limit anyway.

**Comment by jbenito3** [comment]
WRT the JS libs: ah, ok I misunderstood. My mind was on `pip install` and maybe using something like: http://setuptools-bower.readthedocs.org/en/latest/

**Comment by pferreir** [comment]
Yeah, bower is run packaging-time, it's not gonna save us from shipping JS packages.

**Comment by ThiefMaster** [comment]
We aren't relying on anything outside PyPI anymore
