### ISSUE TITLE
Indico evaluation problem

### ISSUE THREAD

**Issue by yakyNIIF** [indico/indico#2077]
We have installed indico 1.2 on debian jessie and we found a problem related to evaluation.
When we have created an evaluation form and if we tried to open it then we got these message instead of form:

```
----------------------------------------------
No period for evaluation:

     Start date: Thursday 17 September 2015
     End date: Wednesday 09 December 2015
----------------------------------------------
```

We tried to open on 17 of September. If we changed the start date to 16 of September, then the evaluation form became active. 
Sometime this solution is not enough so we have to change the start date to earlier.

Please help solve this issue for us.

Thanks and regards,
Janos BODOR

**Comment by pferreir** [comment]
We've fully rewritten the Evaluation form for 1.9.5, so that should work OK now (if I understood it correctly). I'd advise you to try 2.0 when it comes out in early 2016.

**Comment by yakyNIIF** [comment]
Thank you for your information and advice.
