### ISSUE TITLE
Incorrect functioning of Registration email notifications

### ISSUE THREAD

**Issue by yakyNIIF** [indico/indico#2078]
We have created an event include a registration form and we noticed a strange thing.
The registration setup of indico web page has an option: Email registrant (on new registrations)
If this box is not ticked then email does not go to registrant and organiser(s), so we get no notification of registrations.
If this box is ticked than the registrant gets the email, confirming they are registered at the same time the organizers also gets it. 

This means we can no longer run any kind of waiting list by allowing more registrations than places, as they get automatically told their registration was successful.

Please help solve this issue for us.

Best Regards,
Janos BODOR

**Comment by pferreir** [comment]
OK, we'll take that into account for the next version. Thanks for the report.

**Comment by yakyNIIF** [comment]
OK, thank you very much.

**Comment by zoleeca** [comment]
As my collegue mentioned, there are two ways to enhance this:
* enable organizers-only notifications (or at least document behavior correctly)
* if done, enable online editing of mail templates sent after registration, if possible

**Comment by pferreir** [comment]
We're probably going to introduce a "moderation" workflow anyway, so, that should be already provided.

**Comment by zoleeca** [comment]
Great news!

**Comment by pferreir** [comment]
Moderation workflow already included in 1.9.6 and will be released in 2.0. I guess we can close this!
