### ISSUE TITLE
Bug in cloned registration form

### ISSUE THREAD

**Issue by yakyNIIF** [indico/indico#2084]
I would like to report a strange error. We have upgraded indico 1.1.2 to 1.2 and we noticed an error related to copying event.
So, if we have copied an event under the new indico - which event has created for indico 1.1.2 - then the registration form of new event is incorrect.
For example:
- In a dropdown list, either the order of answers are missing, or the first option has disappeared.
- It is particularly strange in questions also such as Gender whether the only answer is "Male".

Please help solve this issue for us.

Thanks and regards,
Janos BODOR

**Comment by zoleeca** [comment]
I'd like to raise this as it is a serious issue that it is also not easy to realize. When a system is typically used for creating similar reoccuring events it is very hard to explain this bug to event admins.
This really makes admins think this software is unreliable in a hideous way.

**Comment by ThiefMaster** [comment]
This is fixed in 1.9.x/2.0
