### ISSUE TITLE
Fix (don't use) monospace font for contribution descriptions on event pages

### ISSUE THREAD

**Issue by ThiefMaster** [indico/indico#2087]
Reverting 8908413 might be enough unless that results in some other place losing monospace formatting where we do want it (ping @pferreir)

**Comment by pferreir** [comment]
I wouldn't do this. `<pre>` is supposed to be monospace anyway, otherwise it doesn't make sense. And yeah, this will break some stuff.
I would instead fix those fields so that we don't use `<pre>`.
