### ISSUE TITLE
Add redirect for materialDisplay.py? links

### ISSUE THREAD

**Issue by nop33** [indico/indico#2107]
Example: 
> http://indico.cern.ch/materialDisplay.py?contribId=201&sessionId=23&materialId=slides&confId=55893

> That URL worked in 2009, whereas today it fails.
> Instead, the correct version today is as follows:

> https://indico.cern.ch/event/55893/session/23/contribution/201/attachments/982972/1397532/DataAccessTechForum.pdf

**Comment by nop33** [comment]
Related change request: CHG34032

**Comment by ThiefMaster** [comment]
Actually it should point to the folder, not the file. We used to redirect straight to the file when there was just one file in a folder though. But I don't think we need that - going to the folder should be enough.
