### ISSUE TITLE
Add "Propose as duplicate"

### ISSUE THREAD

**Issue by pferreir** [indico/indico#2139]
There doesn't seem any reason why a track reviewer cannot propose an abstract as duplicate. After all, the last word should be given to the convener.

**Comment by tgbaron** [comment]
the original feedback from the user (TWEPP'16 manager)

> A track reviewer can mark an abstract as being a duplicate (which is useful).
> The problem is that if just one reviewer (out of several) has marked an abstract as being duplicate it gets “blocked” and one cannot make it merged or accepted.
> Each reviewer must be capable of marking an abstract as being a possible duplicate, but only the track convener (or conference manager) must be capable of making the final classification of the abstract as being a duplicate (once again caused by the confusion between track reviewers and track convener/manager)
