### ISSUE TITLE
Include registration ID in the registration list column selector and exports

### ISSUE THREAD

**Issue by nop33** [indico/indico#2158]
After a request from a user in #INC0894301 (Change request: #CHG34059)

**Comment by ThiefMaster** [comment]
Why in the column selector? We always display it and I think it makes perfect sense to also always include it in the CSV export (I think we also always include it in the PDF).

**Comment by nop33** [comment]
We include it in the book version of the PDF. I would say it should go inside the column selector (active as a default), so that people can exclude it from exports if they want.

**Comment by nop33** [comment]
What is a better solution?
* Add the "Registration ID" in the column selector so that people can decide whether they want it in the exports or not
* Not add it in the column selector and always include it in the exports

**Comment by ThiefMaster** [comment]
I'd always include it

**Comment by pferreir** [comment]
:+1: for always including it.

**Comment by nop33** [comment]
OK, working on it. Thx.
