### ISSUE TITLE
Cannot start

### ISSUE THREAD

**Issue by cmorgia** [indico/indico#2180]
Dear all,
I tried to refresh the code to commit 8ffef31 but no matter what I do (even with fresh new PostgresQL and ZODB databases), I get the following error:

sqlalchemy.exc.InvalidRequestError
InvalidRequestError: Table 'events.payment_transactions' is already defined for this MetaData instance.  Specify 'extend_existing=True' to redefine options and columns on an existing Table object.

Does it make any sense?

Thanks!
Claudio

**Comment by ThiefMaster** [comment]
Try deleting all *.pyc files

**Comment by cmorgia** [comment]
It works! Thanks much!

**Comment by ThiefMaster** [comment]
It's a good idea to always delete those when changing branches (you can actually create post-checkout hook for it)

This is what I have in my local development environment for example:

```sh
> cat .git/hooks/post-checkout
#!/bin/bash

prev_head=$1
new_head=$2
checkout_type=$3

[[ $checkout_type == '1' ]] || exit 0
[[ $prev_head == $new_head ]] && exit 0

cd "./$(git rev-parse --show-cdup)"
find . \( -name '*.pyc' -or -name '*.pyo' -or -name '__pycache__' \) -exec rm -rf {} +
rm -r .coverage htmlcov 2> /dev/null
rm -r ~/dev/indico/data/tmp/mako_modules/ 2> /dev/null
echo Cleaned up python cache files
exit 0
```
