### ISSUE TITLE
Display checked-in users in a different style/color

### ISSUE THREAD

**Issue by pferreir** [indico/indico#2202]
Example:

![screen shot 2016-01-12 at 16 36 30](https://cloud.githubusercontent.com/assets/2699/12267902/a3e4e8bc-b94a-11e5-9c4c-c67389a0c973.png)

People that have been checked in (attended the event) could be shown in a different color (or others could be shown as translucent, for instance).
It's important to keep in mind that, in most events, check-in is not even used.

**Comment by ThiefMaster** [comment]
I guess this would also need an option to enable/disable it. I don't think everyone would appreciate the checkin status to be public.

**Comment by pferreir** [comment]
Totally agreed. Even though in meetings that's not a big deal.

**Comment by florv** [comment]
Provided an option is enabled, I think we could group the list by checked-in status (i.e. show two lists). This would be easier see at a glance who checked-in or not.

Also I think the settings to show checked-in status publicly should be per-event.
