### ISSUE TITLE
Registration form "add section" constructs incorrect URL

### ISSUE THREAD

**Issue by catselbow** [indico/indico#2209]
I'm running indico 1.9.6, and I'm trying to add a new section to a registration form for a conference.  While editing the registration form, I can click on Add New --> Section, and I'm prompted for the title of the new section and I can click "Add", but the new section never appears.

A similar thing happens when I try to use the "+" to add a new field.  The operation doesn't appear to fail, but the new field doesn't appear.

 My site has a name like "http://example.com/indico".  Looking at the httpd access logs, I see that most requests ask for "/indico/...", but the POST that attempts to add a new section asks for "/event/...", leaving off the "/indico", and getting a 404 error.  Looking through the code, I don't see where this request is constructed.

For now, I've worked around the bug by using an Apache mod_rewrite rule to rewrite the bad URL.  With that change, sections can be added with no problem.

**Comment by ThiefMaster** [comment]
Hi, I've pushed a fix for this a few minutes ago: a163f7a
