### ISSUE TITLE
Add gravatar function to user name

### ISSUE THREAD

**Issue by DirkHoffmann** [indico/indico#2229]
Github is only one example that uses gravatar, as it allows to retrieve a selected for any user who has ever registered with gravatar by an equivalent call like
`wget http://www.gravatar.com/avatar/$(echo -n hoffmann@cppm.in2p3.fr | md5sum)`
[Python instructions here](http://de.gravatar.com/site/implement/images/python/).

Following [this discussion on project-indico-administrators](https://groups.cern.ch/group/project-indico-administrators/Lists/Archive/uploading attendee's photos), I make this concrete proposal.
It would be nice in a first step to have the (independent) possibility to optionally 
- add gravatars to registrants lists
- add gravatars to agendas
- add them to other places I forgot.

**Comment by ThiefMaster** [comment]
I don't think gravatar makes sense for that specific use case - few people I know have their photo as their gravatar. It'd be more applicable as an option for a *user* avatar (we do intend to have some way of letting users use avatars from various sources) than as a source for a photo (in case of registration I could imagine it being used for an ID badge)

**Comment by DirkHoffmann** [comment]
You are right. Gravatar may be a bit too much abused by people, who do not put their real life photo there. It may look like a gadget, but it still helps to find or recognise people faster in long lists (after you have seen their gravatar once).

**Comment by chrisrouch** [comment]
I don't think it matters to us if indico uses gravatar or some other mechanism. But it would be useful to have the option to see the users photos.

**Comment by pferreir** [comment]
:+1: for photos. We need to make it in such a way that we can get photos from different sources, though:
 * LDAP
 * Gravatar
 * Direct upload
 * Photos from OAuth-connected providers (?)

**Comment by ThiefMaster** [comment]
same as #4453

**Comment by DirkHoffmann** [comment]
> same as #4453

Yes, but much older. ;-)
Close this (or the other one) as duplicate?
