### ISSUE TITLE
Registrant export

### ISSUE THREAD

**Issue by DirkHoffmann** [indico/indico#2230]
The Indico data export API is quite complete for events already. But it would be nice, if we could export also the registrant/participant list of an event via that API. Same holds true for more specialised lists like "all speakers" or "all contributors". 
Any chance to get this soon? Probably the code is exisiting already (via dropdown menues, for CSV and PDF) and just needs refactoring.

**Comment by ThiefMaster** [comment]
We already have an API to export registrations - but unlike the "classic" API it's OAuth based since it's used by the checkin app:

https://github.com/indico/indico/blob/master/indico/modules/events/registration/api.py
https://github.com/indico/indico/blob/master/indico/modules/events/registration/blueprint.py#L205-L209

**Comment by DirkHoffmann** [comment]
Today (10:26am) Adrian wrote:

> We already have an API to export registrations - but unlike the "classic"
> API it's OAuth based since it's used by the checkin app:
> 
> https://github.com/indico/indico/blob/master/indico/modules/events/registra
> tion/api.py
> https://github.com/indico/indico/blob/master/indico/modules/events/registra
> tion/blueprint.py#L205-L209

I would probably need instructions how to use it.

If it is available towards this summer on indico.in2p3.fr (meaning that the 
corresponding release is out soon enough to have it installed there), then it 
might turn out very useful for me!

**Comment by pferreir** [comment]
> If it is available towards this summer on indico.in2p3.fr (meaning that the
corresponding release is out soon enough to have it installed there), then it
might turn out very useful for me!

There's an older implementation in 1.2. Maybe it's enough:

https://github.com/indico/indico/blob/v1.2/indico/web/http_api/hooks/registration.py

@ThiefMaster, does it really need OAuth? I was under the impression it works with any API auth method.

**Comment by ThiefMaster** [comment]
it does (legacy api hooks don't let you require a certain oauth scope so it's actually a normal RH). But I guess it wouldn't be too hard to adapt it so it can also work with api keys (custom decorator instead of just `@oauth.require_oauth('registrants')`)

**Comment by pferreir** [comment]
I guess it depends on what @DirkHoffmann wants to do with this...

**Comment by pferreir** [comment]
But I don't see any mention of OAuth in the [1.2 code](https://github.com/indico/indico/blob/v1.2/indico/web/http_api/hooks/registration.py).

**Comment by ThiefMaster** [comment]
we weren't using oauth scopes in 1.2 yet so in 1.2 it should indeed work fine with any kind of api authentication

**Comment by pferreir** [comment]
Great! Closing ticket. @DirkHoffmann, let us know how it goes!

**Comment by DirkHoffmann** [comment]
Today (4:31am) Pedro Ferreira wrote:

> I guess it depends on what @DirkHoffmann wants to do with this...

Remember two years ago, "Journée Informatique RI3" ? I think you watched a 
video ;-)

It is the same event, but I am in the organising team this time. Already last 
time @ChristianHelft wanted to to generate a gallery of participants. And we 
have the photos (or want to reuse those on informatique.in2p3.fr from users).

So I could match the users by comparing e-mails, ideally in an automatic way, 
with a PHP hack.

However, if we have to install code on indico.in2p3.fr, which is not 
official, it will be a problem. The colleagues in charge are very reluctant 
to change anything on the system after the recent failure to upgrade.

**Comment by DirkHoffmann** [comment]
Today (4:34am) Pedro Ferreira wrote:

> Great! Closing ticket. @DirkHoffmann, let us know how it goes!

OK. We have 1.2 on indico.in2p3.fr. And if I understand you correctly, the 
hook should be distributed with it. But I am afraid I will still need 
instructions how to use it.

https://indico.in2p3.fr/export/event/9954.json yields correctly something 
about the event, and event the level of details that I want. But 
https://indico.in2p3.fr/export/registration/9954.json is a 404. (Well, kind 
of: Page not found, but no HTTP error code.)

I tried some combinations I could figure out /export/event/registration/, 
/export/registrants/, /export/event/9954/registrants.json, ... None of them 
makes do!?

**Comment by DirkHoffmann** [comment]
Strange btw: Why the OP cannot reopen the ticket? :wink:

**Comment by ThiefMaster** [comment]
https://indico.in2p3.fr/export/event/9954/registrants.json

**Comment by DirkHoffmann** [comment]
OK, thanks @ThiefMaster. It says "Access to this resource is restricted." now. 
Still, I am wondering, if I would prefer a plain 403 in that case.
But I should get it to work now.

**Comment by ThiefMaster** [comment]
You need to pass an API key. Also, it is a 403 - just with a friendly message included.

**Comment by DirkHoffmann** [comment]
Today (5:44am) Adrian wrote:

> You need to pass an API key. Also, it is a 403 - just with a friendly
> message included.

You are absolutely right! I was looking where Firefox is telling me that. But 
it is not, or apparently not without the right plugin.

Back to curl.

And also the 404 I mentioned before is set correctly.

**Comment by ThiefMaster** [comment]
it's shown in the developer tools (ctrl+shft+k)

since you mentioned curl, we can recommend [httpie](https://github.com/jkbrzt/httpie). it's a more human-friendly http client for the shell and can be simply installed via `pip install httpie`

**Comment by DirkHoffmann** [comment]
Today (5:52am) Adrian wrote:

> it's shown in the developer tools (ctrl+shft+k)

Yes, good hint. I only used Firebug up to now.

> since you mentioned curl, we can recommend httpie. it's a more
> human-friendly http client for the shell and can be simply installed via pip
> install httpie

Not bad, indeed. I am just afraid it screwed up my argparse version with an 
upgrade.

**Comment by DirkHoffmann** [comment]
BTW: Works like a charm. Thanks!
