### ISSUE TITLE
Wrong users added instead of contributors.

### ISSUE THREAD

**Issue by martin-kuba** [indico/indico#2231]
This is a bug that is present for a long time, at least from version 0.98.1, and it is still present in Indico 1.2.1rc2.

The bug shows itself when you try to add a manager that is not a real user, only a contributor.
The contributor id, which is a small number like 0, 1, 2 and so on, is used as a user id.
So usually you end up adding the main administrators or one of the first created users with id 1,2,3
instead of the contributor.

I think the bug is that the search dialog for users offers contributors. Contributors who do not have accounts cannot log into Indico and cannot manage anything, so there si no point in adding them as managers.

The attached screen shots show I  tried to add a contributor named Carretero as a manager, but Martin Kuba (me, the user with id 0) was added instead.

![adding_manager_indico121rc2](https://cloud.githubusercontent.com/assets/10230702/12743106/ba26e070-c98b-11e5-82d1-c514bb685a0c.png)
![added_manager_indico121rc2](https://cloud.githubusercontent.com/assets/10230702/12743108/bf998ec2-c98b-11e5-8e37-a444ce55cb20.png)

**Comment by chrisrouch** [comment]
We noticed that if the user selected has a star then they are added as expected. Without a star we see the behaviour described here.

**Comment by martin-kuba** [comment]
Only real users can be starred, so a user with a star cannot be a contributor without a user id.

**Comment by pferreir** [comment]
Weird that we've never noticed that. This will for sure be fixed in 2.0 (it's been rewritten), but we'll have to check if there's an easy fix in 1.2.x.

**Comment by ThiefMaster** [comment]
fixed in 1.9.x/2.0
