### ISSUE TITLE
Wrong french translation...

### ISSUE THREAD

**Issue by C138** [indico/indico#2234]
I successfully installed Indico 
"The version of this Indico installation is: 1.2.1rc5"

However, I noted few annoying (french) translation errors

Déssiner == Dessiner !!
Vérouill\* == Verrouill*

These are big mistakes.
Try to use transiflex but the french score is 100%...

**Comment by pferreir** [comment]
Thanks for the heads-up. I guess that kind of thing happens when you have to translate so much stuff. Pinging @tgbaron and @DirkHoffmann.

**Comment by DirkHoffmann** [comment]
Thanks for notifying. However it is now difficult to make a quick search in transifex, as there are two dozen different files to check. (Why, by the way? That was much more convenient before.) Any hint where this is used???

**Comment by DirkHoffmann** [comment]
Also I am wondering where "dessiner" (paint!?) would be used at all in Indico.

**Comment by pferreir** [comment]
> However it is now difficult to make a quick search in transifex, as there
> are two dozen different files to check. (Why, by the way? That was much
> more convenient before.)
>
Plugins. We were including translations within the core before. We can
always grep the files in the actual repo, but it used to be easier indeed...

>

**Comment by pferreir** [comment]
* https://github.com/indico/indico/blob/master/indico/translations/fr_FR/LC_MESSAGES/messages.po#L9651
 * https://github.com/indico/indico/blob/master/indico/translations/fr_FR/LC_MESSAGES/messages.po#L15591

**Comment by DirkHoffmann** [comment]
Strange enough, my checkout only contains one *.po file, well two (in master):
`./indico/translations/fr_FR/LC_MESSAGES/messages-js.po`
`./indico/translations/fr_FR/LC_MESSAGES/messages.po`
`messages.po` is the guilty one.
But how does this match with the 24 files in Transifex??? There is no file ("resource") with such a name:  chat.js chat.py core.js core.py importer.js importer.py importer_invenio.js importer_invenio.py livesync.js livesync.py livesync_invenio.js livesync_invenio.py payment_manual.js payment_manual.py payment_paypal.js payment_paypal.py piwik.js piwik.py search.js search.py search_invenio.js search_invenio.py vc_vidyo.js vc_vidyo.py. Obviously, that won't be corrected whatever we do in Transifex.
There are other incongruities (sûr, auorisé). I don't know how to improve these. Likely they only concern pre-1.9 versions. Edit messages.po and pull request?

**Comment by DirkHoffmann** [comment]
OK, got it. It's in `core.py`. I know who made the wrong translation now. :wink: Will translate them in Transifex.

**Comment by DirkHoffmann** [comment]
Oh: "Erreur : Vous n'êtes pas autorisé à modifier une chaîne révisée."
Waiting for some with higher privileges to verify my proposals …
I think that is all I can do for today.

**Comment by DirkHoffmann** [comment]
I tried to upload a complete file with more corrections (using copy-paste to go much faster). But when re-uploading, Transifex complainsThere is a syntax error in your file.
Line 15122: 'msgstr' is not a valid Python format string, unlike 'msgid'. Reason: In the directive number 1, the character ' ' is not a valid conversion specifier.
Line 15129: 'msgstr' is not a valid Python format string, unlike 'msgid'. Reason: In the directive number 1, the character ',' is not a valid conversion specifier.
msgfmt: found 2 fatal errors:

**Comment by C138** [comment]
Sorry, was thinking that it would be easier to find the wrong sentences in Transifex (this I would have added the Indico "context")

By the way, Equipe == Équipe ;-)

**Comment by DirkHoffmann** [comment]
Today (2:02pm) C138 wrote:

> Sorry, was thinking that it would be easier to find the wrong sentences in
> Transifex (this I would have added the Indico "context")
> 
> By the way, Equipe == Équipe ;-)

It is discussable, because Indico is produced in Switzerland. But Académie 
Française recommends to write capitals with accents indeed.

Would you mind to get an account on Transifex and enter your remarks directly 
there? (You can search for the faulty translations, by looking into 
"Trans. text"; the standard search function looks *only* into the original 
[english] text!)

**Comment by pferreir** [comment]
Well, I would keep our french as neutral as possible. We're not going to write "septante" either :wink:
If the Académie Française really suggests to keep the accent, I would keep it.

**Comment by C138** [comment]
Hi
https://fr.wikipedia.org/wiki/Fran%C3%A7ais_de_Suisse#Usage_typographique
Seems that there is not so much differences regarding french and swiss typography ;-)
Thanks

**Comment by C138** [comment]
Hello,
I think that I already have a transifex account ;-)
But, I'm browsing  the (very long) file fr_FR/LC_MESSAGES/messages.po and seems that I can't find any "obvious" wrong french translation ;-)
Best.

**Comment by C138** [comment]
Yop
Logout item, "déconnexion" should be capitalized "Déconnexion" 
(like others items in this menu Mon profil / Mes préférences / Identification comme)

Have my transifex account activated, request to join Indico is sent... but not sure about de best way to find and report such "details"... 

Best regards.

**Comment by DirkHoffmann** [comment]
> 
> Have my transifex account activated, request to join Indico is sent... but
> not sure about de best way to find and report such "details"...

Just ask me in private (or Thomas). The idea is that you "propose" a change 
or "report" a problem, as all translation strings have been "verified" by 
Thomas and are therefore locked for normal contributors.
 									Dirk

**Comment by DirkHoffmann** [comment]
@C138, typography is not orthography. Indico uses indeed swiss typography (no spaces), as opposed to what @pferreir states about septante.
But Orthography concerns accents on capital letters for example.

**Comment by pferreir** [comment]
The french translation has been rewritten, so I'm closing this.

**Comment by DirkHoffmann** [comment]
As a followup for @C138, please note that we decided in the [last Indico Workshop](https://indico.cern.ch/event/614422) to favour discussions about translations on https://talk.getindico.io/.
You will find there a reference to the (rather) new [Wiki page on Indico i18n](https://github.com/indico/indico/wiki/Internationalisation) with a lot of practical hints and tricks to find and test PO files.
And probably you can see on [Transifex](https://www.transifex.com/indico/indico/translate/#fr_FR) that there are 281 new chains to be translated for french. Feel free to contribute.
