### ISSUE TITLE
Registration list customization: Add button to enable all columns at once

### ISSUE THREAD

**Issue by nop33** [indico/indico#2243]
Currently if someone wants to enable all columns in a registration list (either to view the report on the browser, or export it to Excel), they have to manually click on every column toggler:
![image](https://cloud.githubusercontent.com/assets/1579899/12882101/a11c1438-ce4f-11e5-9858-cc299e653e96.png)
This can be frustrating when the registration form consists of a large amount of fields.
A button in the customization page of the registration list to "Enable all columns" would solve such a problem.

**Comment by nop33** [comment]
Related SNow ticket: #INC0958116

**Comment by pferreir** [comment]
It would be nice to improve a little bit the display style. I got complains from people saying that the fact that the "eye thingy" is only visible when you hover your mouse is pretty confusing.
