### ISSUE TITLE
404 not found on http://localhost/indico/

### ISSUE THREAD

**Issue by knbs** [indico/indico#2251]
Hello I'm following this guide http://indico.readthedocs.org/en/latest/installation/ to install indico on ubuntu 14.04

I have create the indico.conf  file on `/etc/apache2/sites-available` folder like the guide says, and enabled it with `a2ensite indico.conf` and restarted apache with `service apache2 restart`.

After this when I try to access to http://localhost/indico/ it returns 404 Not Found page:

Not Found
The requested URL /indico/ was not found on this server.
Apache/2.4.12 (Ubuntu) Server at localhost Port 80

**Comment by liviuirimia** [comment]
This is the indico.conf that works for me
`AddDefaultCharset UTF-8

<VirtualHost *:80>
        # mod_wsgi indico

    ErrorLog /var/log/httpd/error.log
        LogLevel warn

    Alias /indico/images "/opt/indico/htdocs/images"
    Alias /indico/css "/opt/indico/htdocs/css"
    Alias /indico/js "/opt/indico/htdocs/js"
    Alias /indico/ihelp "/opt/indico/htdocs/ihelp"

    WSGIDaemonProcess WSGIDAEMON processes=32 threads=1 inactivity-timeout=3600 maximum-request = 500 python-eggs=/opt/indico/tmp/egg-cache

    WSGIScriptAlias /indico "/opt/indico/htdocs/indico.wsgi"

    <Directory "/opt/indico">
        WSGIProcessGroup WSGIDAEMON
        WSGIApplicationGroup %{GLOBAL}
        Options FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>
</VirtualHost>

<VirtualHost *:443>

    ErrorLog /var/log/httpd/error.log
            LogLevel warn

    Alias /indico/images "/opt/indico/htdocs/images"
    Alias /indico/css "/opt/indico/htdocs/css"
    Alias /indico/js "/opt/indico/htdocs/js"
    Alias /indico/ihelp "/opt/indico/htdocs/ihelp"

    WSGIScriptAlias /indico "/opt/indico/htdocs/indico.wsgi"

    SSLEngine on
    SSLCertificateFile    /etc/pki/tls/certs/indico.crt
    SSLCertificateKeyFile /etc/pki/tls/private/indico.key
    <Directory "/opt/indico">
        WSGIProcessGroup WSGIDAEMON
        WSGIApplicationGroup %{GLOBAL}
        Options FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>

</VirtualHost>
`
I'm running indico on Centos7.2, so you may need to modify the location of your ssl certificate.
Also, is mod_wsgi installed and enabled on your machine? 
Hope this helps you.
