### ISSUE TITLE
Abstract sending confirmation e-mail 

### ISSUE THREAD

**Issue by thebadan** [indico/indico#2265]
Indico 1.2.1rc5

In the email confirmation of the abstract  submission  links to the abstract are sent in the following form:

Abstract submitted: &#60;https://indico.ujk.edu.pl/event/0/call-for-
abstracts/my-abstracts&#62;.

Status of your abstract: &#60;https://indico.ujk.edu.pl/event/0/call-for-
abstracts/4/&#62;.

As the results they are wrongly interpereted (cutted) by an email software.

Abstract submitted: [https://indico.ujk.edu.pl/event/0/call-for-](https://indico.ujk.edu.pl/event/0/call-for-)
abstracts/my-abstracts>.

Status of your abstract: [https://indico.ujk.edu.pl/event/0/call-for-](https://indico.ujk.edu.pl/event/0/call-for-)
abstracts/4/>.

**Comment by ThiefMaster** [comment]
This does not sound like an Indico issue but rather like an issue with a bad email client which breaks links instead of keeping them intact even if it'd result in an overly long line.

**Comment by thebadan** [comment]
I have checked this with different clients (MS Outlook, Windows Live and my mobile phone AquaMail Pro). The result is the same.

**Comment by OmeGak** [comment]
Fixed in #2672
