### ISSUE TITLE
Allow combining IP-based protection with an ACL

### ISSUE THREAD

**Issue by ThiefMaster** [indico/indico#2281]
This is useful in case people want to allow unrestricted access from within the institution's network but also let people from outside access the event as long as they authenticated.

`CHG34230`

**Comment by DirkHoffmann** [comment]
Yes! I upvote.
Obviously the two conditions should be disjunctive (logical OR), i.e. IP or user id, not IP and user id must be fulfilled to give access (read or write in case of user id).

**Comment by ThiefMaster** [comment]
This is done in v1.9.8

**Comment by DirkHoffmann** [comment]
Very good! I am eager to test it.
