### ISSUE TITLE
Radio button label not clickable (in Move Timetable Entry window)

### ISSUE THREAD

**Issue by SebastianLopienski** [indico/indico#2286]
In the event management area -> Timetable -> Move Timetable Entry window, labels of radio buttons are not clickable. So when I want to move a contribution to another session or to the top level timetable, I have to click on the small radio button (less convenient) rather than anywhere on the radio button or label (more convenient). It would be a nice enhancement if the labels were clickable, too. Thanks for considering.

**Comment by mic4ael** [comment]
We have addressed this issue in the latest release. Now the whole row is clickable (no need for checkboxes) which makes things much more easier for a user.

**Comment by SebastianLopienski** [comment]
Thx, nice!
