### ISSUE TITLE
error when auto-merging a pending user when adding an email

### ISSUE THREAD

**Issue by ThiefMaster** [indico/indico#2287]
RHUserEmailsVerify:

```python
if existing and existing.is_pending:
    logger.info("Found pending user %s to be merged into %s", existing, self.user)
    merge_users(existing, self.user)
    flash(_("Merged data from existing '{}' identity").format(existing.email))
    existing.is_pending = False
```

The problem here is that a pending user might not have a first/last name set, but not having names is only permitted for pending users. We can probably solve this with a simple

```python
existing.first_name = existing.first_name or self.user.first_name
existing.last_name = existing.last_name or self.user.last_name
```

It would be good to test this though (create a pending user with no names manually via the shell, then add this user's email to your own user and it should fail when doing the merge).

**Comment by florv** [comment]
Fix included in v1.9.6 branch.
