### ISSUE TITLE
Abstract submission confirmation email and line wraps

### ISSUE THREAD

**Issue by amnr** [indico/indico#2292]
Indico sends abstract submission confirmation with wrapped links
("Abstract submitted" and "Status of your abstract" fields).
This is because Python's textwrap.TextWrapper() breaks long words (here: links)
right after hyphen even if break_long_words=False.

Debian 8.3
Python 2.7.9
Indico 1.2.1rc5
File: MaKaC/webinterface/rh/CFADisplay.py

**Comment by OmeGak** [comment]
Fixed in #2672
