### ISSUE TITLE
Individual reminder emails

### ISSUE THREAD

**Issue by nop33** [indico/indico#2318]
Currently, the reminder emails are sent by including all the recipients in the `BCC` field. We need to reconsider this approach and maybe send one email per recipient, using the `TO` field instead, since the implementation causes issues to some mailing list servers.

**Comment by mlassnig** [comment]
Hello, I've recently seen a similar problem, as we typically put mailing lists (egroups) as destinations for the reminders. Turns out that this information is then lost, and this breaks the email filters for the egroups (which are typically done like `if "To:" == <egroup> then move to <folder>`. Thanks.

**Comment by artlbv** [comment]
Same here, the absence of the To:filed brakes our discourse email filter
![image](https://user-images.githubusercontent.com/4972492/132198839-5e481e16-5158-4431-9d9a-6a5001beff36.png)

**Comment by ThiefMaster** [comment]
To be fair, I don't think sending event reminders to a discourse mail-in address makes much sense...

**Comment by artlbv** [comment]
> To be fair, I don't think sending event reminders to a discourse mail-in address makes much sense...

Well, with the move from Hypernews to discourse this is what we'll have to live with in CMS. 

Personally I prefer calendar notifications for events (which is why I subscribe to the indico category ics), but some people only live within email.

**Comment by ThiefMaster** [comment]
I think a good option for this particular usecase would be to use the Indico API to check for upcoming events and then use that data to notify people using whatever way they prefer (could be discourse, mattermost, email, etc)

**Comment by artlbv** [comment]
So the built-in reminder functionality is for who them? for events with registered users?

**Comment by ThiefMaster** [comment]
Its primary goal is to send emails to humans... and there it's typically not a problem to use BCC - many newsletters etc do that as well.

That said, I think sending emails to individual recipients would probably make sense nontheless; we do it in many other places as well...

**Comment by camclean** [comment]
For us, the best way to consistently send meeting announcements is through the indico reminders. What is the problem with changing indico to use the `TO` field?

**Comment by ThiefMaster** [comment]
BCC: Indico sends one email, the mail server distributes it to the individual recipients. Also just one email in the indico event log
To: Indico sends n emails. Also n emails in the indico event log.

I think the logging part is in fact the main reason we did not already change this for Indico 3.0... we'll have to find some way to collapse those entries (or just accept that it;'s a bit spammy in the log)

**Comment by artlbv** [comment]
Hi again, I wonder why I see different behaviour of the `To:` field from different indico events.

How is it still possible to get the `To:` field properly filled?
![image](https://user-images.githubusercontent.com/4972492/134142043-be316283-99cf-43c1-a5c2-714025484b44.png)

**Comment by ThiefMaster** [comment]
Can you include links to the Indico events in question so I can check the logs? (feel free to DM them to me on Mattermost (`@amonnich`) if you don't want to post them publicly).
