### ISSUE TITLE
Clone a locked event

### ISSUE THREAD

**Issue by indico-bot** [indico/indico#232]
``` yaml
# Ticket imported from Trac
# Reported by: dmartinc
```

Users should be able to clone already locked events. The newly cloned event should not be locked.

Use case: My event is finished, so I lock it. However I need to create a very similar one for next month. It would be nice to be able to clone it without the need to ask the category manager to unlock it.

**Comment by DirkHoffmann** [comment]
Is it possible that this bug has just reappeared in the latest stable version?
BTW, how can I find out which version I am using? (http://indico.cta-observatory.org)

When the event is locked, the "clone" dialog pops up, but it is stuck in the first "tab" (select number of clones). When I unlock it, everything goes well (as in previous versions, I think).

**Comment by ThiefMaster** [comment]
https://github.com/indico/indico/blob/2.1-maintenance/indico/modules/events/management/controllers/cloning.py#L153 so it should work fine...

do you get a javascript error? (check your browser's dev tools / console)

regarding the version, you can check in the admin area (shown on the community hub page where the data we crawl is listed)

**Comment by DirkHoffmann** [comment]
No JS error in Firefox 52.8.0 console.

And although you may then have the version information anyway, here it is for reference:
    Server default language (en_GB)
    Indico version installed (2.1.1)
    Python version used (2.7.12)
    Postgres version used (9.6.9)
    Operating system used (Linux Ubuntu 16.04)
    Debug mode (disabled)

**Comment by ThiefMaster** [comment]
Fixed in a4179d3c52
