### ISSUE TITLE
Add an abstract to more than 1 session

### ISSUE THREAD

**Issue by nop33** [indico/indico#2323]
Abstracts can only be added to 1 session, following the principal that 1 abstract will be presented only once during a conference. However there's the case where this is not true and an abstract might have a second talk. A user recently requested this, writing the following:

> For several conferences, we offer the poster presenters to give a so-called “mini-oral”, which is a 2 minute “teaser” describing their poster. We do this since several years and this is a great success, since it give especially students the chance to talk in front of the whole audience, even if they only have a poster.
> 
> For that to work with indico, we have to put the abstract into two sessions, first into the poster session and second into the mini-oral session. This is not strictly 1:1 since not every poster presenter is willing to give a mini oral.

**Comment by ThiefMaster** [comment]
We discussed this a few times, also in the context of JACoW and came to the conclusion that this would add a huge amount of complexity, and cloning individual contributions is the way to go instead.
