### ISSUE TITLE
Author and co-author linked to the same EventPerson

### ISSUE THREAD

**Issue by nop33** [indico/indico#2346]
Although we have several client-side validation mechanisms to avoid adding the same person as a author and co-author in the same abstract submission, it seems that there are some unwanted workarounds where this is made possible (author and co-author with the same email address). This leads to an IntegrityError when trying to accept the abstract and convert it into a contribution.

A workaround that works is:

1. add a person as a primary author
2. modify their email to something temporary
3. add another user as a co-author
4. modify their email to match the original email of the primary author
5. modify the email of the primary author back to the original

**Comment by pferreir** [comment]
Is this really worth a GH issue? We're going to rewrite this anyway.

**Comment by OmeGak** [comment]
Not so easy to spot the problem when an error report comes in. I fixed it in d6fed40cbd787d319c8c17ac255841df5bbf5110.
