### ISSUE TITLE
Indico use Acitve Directory users,authenticate using Active Directory

### ISSUE THREAD

**Issue by liuqing820105** [indico/indico#2357]
Hello there

Anyone could give me an instruction on indico user management  using external database,the Microsoft Active Directory ;
      
We prefer using our current Active Directory database for authentication users and let users using Active Directory Account to manage their lectures,setting priviledges on created lectures,rather than using local database;
My email address is liuqing820105@gmail.com
      
Sincerely

**Comment by pferreir** [comment]
This is meant to be used as a bug tracker, so please join the administrators mailing list if you need help setting up Indico with AD:

https://simba3.web.cern.ch/simba3/SelfSubscription.aspx?userHasAccount=false&groupName=project-indico-administrators
