### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'root'

### ISSUE THREAD

**Issue by liuqing820105** [indico/indico#2371]
When i client paticipants-->add-->indico users ,
the web page is dead,and i recieve an error report message in my email box;

```
2016-04-28 15:14:54,553 indico.wsgi - ERROR app.py:164 -- 'NoneType' object has no attribute 'root'
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/Flask-0.10-py2.6.egg/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.6/site-packages/Flask-0.10-py2.6.egg/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python2.6/site-packages/indico-1.2.1rc5-py2.6.egg/MaKaC/services/interface/rpc/json.py", line 111, in process
    result = ServiceRunner().invokeMethod(str(requestBody["method"]), requestBody.get("params", []))
  File "/usr/lib/python2.6/site-packages/indico-1.2.1rc5-py2.6.egg/MaKaC/services/interface/rpc/process.py", line 158, in invokeMethod
    _endRequestSpecific2RH(False)
  File "/usr/lib/python2.6/site-packages/indico-1.2.1rc5-py2.6.egg/MaKaC/services/interface/rpc/process.py", line 174, in _endRequestSpecific2RH
    minfo = info.HelperMaKaCInfo.getMaKaCInfoInstance()
  File "/usr/lib/python2.6/site-packages/indico-1.2.1rc5-py2.6.egg/MaKaC/common/info.py", line 512, in getMaKaCInfoInstance
    root = dbmgr.getDBConnection().root()
AttributeError: 'NoneType' object has no attribute 'root'

Additional information:
Request: 7f209976f290
URL: http://indico.sinap.ac.cn/services/json-rpc
Endpoint: api.jsonrpc
Method: POST
Params: {'userIds': [{'_type': 'Avatar', 'name': 'liuqing_11 LIUQING_11', 'firstName': 'liuqing_11', 'title': '', 'affiliation': 'na', 'familyName': 'liuqing_11', 'fax': '', 'id': '6', 'phone': '', 'address': '', '_fossil': 'avatar', 'email': 'liuqing_11@163.com'}], 'confId': '6'}
User: <Avatar(3, TIAN, gexuan)>
IP: 10.10.5.242
User Agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 5.1; Trident/4.0; .NET CLR 2.0.50727; .NET CLR 3.0.04506.648; .NET CLR 3.5.21022; InfoPath.2; .NET4.0C; .NET4.0E; .NET CLR 3.0.4506.2152; .NET CLR 3.5.30729)
Referer: http://indico.sinap.ac.cn/event/6/manage/participants/
```

**Comment by pferreir** [comment]
Are you able to execute `indico_shell` from the command line? Are there any errors?

**Comment by liuqing820105** [comment]
Thank you for your reply,
Yes ,i can run indico_shell
and here is some infomation when executing it.
###################################################################
[root@indico ~]# indico_shell
/usr/lib/python2.6/site-packages/indico-1.2.1rc5-py2.6.egg/MaKaC/common/__init__.py:30:
DeprecationWarning: MaKaC.common.Configuration is deprecated; use
indico.core.config instead
  from .Configuration import Config
+ MaKaC : MaKaC base package
+ Conference
+ Category
+ ConferenceHolder
+ CategoryManager
+ AvatarHolder
+ GroupHolder
+ HelperMaKaCInfo
+ PluginsHolder
+ Catalog
+ IndexesHolder
+ Config
+ minfo : MaKaCInfo instance

indico 1.2.1rc5

>>>

**Comment by pferreir** [comment]
OK, there's an Exception happening somewhere, and it's being caught [by a handler that is not logged](https://github.com/indico/indico/blob/v1.2/indico/MaKaC/services/interface/rpc/process.py#L158). It still seem weird. Is there anything else of interest in `indico.log`?

Maybe you can try to apply [this patch](https://gist.github.com/87197956d9478d32f7aacd4be91483a5) and check what shows up in `indico.log`?

**Comment by pferreir** [comment]
Closing due to lack of response.
