### ISSUE TITLE
Room Booking: Intelligent search of rooms

### ISSUE THREAD

**Issue by jbenito3** [indico/indico#238]
``` yaml
# Ticket imported from Trac
```

> 2) When searching for rooms:
> Say I want to organise a meeting every day at 11-12.30 for the next 2 months and I need video:
> If I search for a room there's obviously not a single room that's available those whole 2 months period so the search just returns 0.
> Ideally I would like it to return a list where each day I would have a room but not necessarily the same one.
> One could ask it to maximise the number of meetings in a single room, or minimise the total number of rooms used, or some other clever algorithm I'm sure you can come up with better than I can
> 
> If that would be too difficult, maybe it could return the room with the largest number of matches and then tell me that some of the meeting days haven't got a room, then I could try again with the remaining days etc until I get all meetings with rooms.
> 
> Maybe there's a clever way of doing this that I'm not aware of...

**Comment by pferreir** [comment]
Already partially solved by "Plan B".
