### ISSUE TITLE
Room Booking: allow time changes in ongoing bookings

### ISSUE THREAD

**Issue by pferreir** [indico/indico#2394]
Right now, if someone tries to change a booking that has already "started", they'll be greeted with an error message telling them they can't. That's because we don't want people to basically "rewrite" history and mess with stuff that has already happened.

On the other hand, this represents lost time to the user, who will have to create a new booking from scratch. I suggest that we:
- Ask the user whether they want a new booking to be created, which will use the new date/time;
- If the user is OK with that, we'll cancel all remaining occurrences of the original booking and create a new one containing the modified version of those.

**Comment by OmeGak** [comment]
Related SNOW ticket `CHG34305`.
