### ISSUE TITLE
Problem with "To be corrected" state

### ISSUE THREAD

**Issue by ioclaudio** [indico/indico#2405]
I have a problem with the paper reviewing process of Indico 1.2.

I created a new conference and I enabled the paper review process as "content and layout revision". The problem is that when the referee submits  the paper as "To be corrected" (final assessment) the paper doesn't go in that state but it loses all the data associated (history,referee,content reviewer, layout reviewer) and goes in the state "Paper not yet submitted".
The states "accepted" and "rejected" seem to work in the right way.

How can I debug this problem?
I've tried to start with a new Zodb, but the problem still remains.
I think it is a workflow problem.

Thank you 
Claudio

**Comment by ThiefMaster** [comment]
Most likely fixed in 2.x
