### ISSUE TITLE
Add dedicated contribution/session page in meeting-type events

### ISSUE THREAD

**Issue by OmeGak** [indico/indico#2411]
Related SNOW ticket `CHG34309`.

Contributions and sessions have dedicated pages only within conference-type events. This is a problem specially for long meetings when someone wants to share particular contribution in it. We should provide a nice looking page that matches the style and some easy way to linking to it.

**Comment by adavidzh** [comment]
IMO a simple "right-click copy-link" workflow would work wonders. Thanks for considering this request.

**Comment by pferreir** [comment]
I agree we could have links to contributions (maybe HTML fragments?) but I'm not very convinced about having multi-page meetings. Meetings are supposed to be single-page, and if something more complex is needed there is also the conference layout.

**Comment by pferreir** [comment]
I'm closing this ticket since we've already implemented fragment-style links in the meantime. That should solve the linkability issue.
