### ISSUE TITLE
Export files' restrictions with the API

### ISSUE THREAD

**Issue by switowski** [indico/indico#2414]
Hi Indico team,

as I discussed with @pferreir , if you could, please, add the restrictions of files to the export API (just a flag `restricted/public` or something like that) that would be awesome. We need this information to set the same files restrictions on CDS.

**Comment by ThiefMaster** [comment]
@switowski I guess that's all you need?

**Comment by switowski** [comment]
@ThiefMaster yes, thank you :smile:
