### ISSUE TITLE
No jdoe in config templates at http://indico.readthedocs.io/en/latest/installation/

### ISSUE THREAD

**Issue by vgvassilev** [indico/indico#2417]

**Comment by vgvassilev** [comment]
Also after creation of indico in sites-available one should enable it. If it is renamed to indico.conf, a2ensite picks it up. In this case the docs can be simplified to just adding a command a2ensite (for unix).

**Comment by vgvassilev** [comment]
On default apache installations one needs to enable ssl: `a2enmod ssl`

**Comment by pferreir** [comment]
Already fixed in master. We could backport to 1.2 too, but seems pretty minor.

**Comment by pferreir** [comment]
> Also after creation of indico in sites-available one should enable it. If it is renamed to indico.conf, a2ensite picks it up. In this case the docs can be simplified to just adding a command a2ensite (for unix).

I agree about renaming the file to `*.conf`, but `a2ensite` is Debian-specific. In RedHat-based systems you don't need to run any command to have the config file read by Apache.

Same goes for `a2enmod`. It may even be enabled by default in some systems.

**Comment by vgvassilev** [comment]
Ok, sounds good. Just wanted to let you know what difficulties I see when trying to install it.

**Comment by pferreir** [comment]
Sure, thanks a lot! I hope that 2.0 will be much easier to play with (Docker!).

**Comment by vgvassilev** [comment]
Looking forward to it.
