### ISSUE TITLE
Survey export issues

### ISSUE THREAD

**Issue by pferreir** [indico/indico#2443]
A couple of fixes for the CSC:
 * Sorting seems to be broken (we should show the results in proper order);
 * If possible, it would be nice to include the session name as a prefix of each question (since otherwise it may be impossible to differentiate them). Or at least some sort of ID that lets them see what the result actually relates to.

**Comment by ThiefMaster** [comment]
For clarification, this is about the XLSX (and possibly also CSV) export.

**Comment by pferreir** [comment]
> and possibly also CSV

Yeah, CSV too. I think it would make no sense to have only XSLX behave correctly.

**Comment by ThiefMaster** [comment]
Assuming the bug is in `generate_spreadsheet_from_survey` and not the spreadsheet util it'll be fixed in both places anyway ;)
