### ISSUE TITLE
Static assets reference incorrect URL

### ISSUE THREAD

**Issue by kwierman** [indico/indico#2448]
I'm serving an Indico instance from wasabi.physics.unc.edu/indico

The installation is located as /opt/indico.

However, javascript assets keep trying to access incorrect paths. For instance, if I try to access 

http://wasabi.physics.unc.edu/indico/event/1/

Then get redirected to a login page, the login redirects me to:

http://wasabi.physics.unc.edu/event/1/

Is there something in the installation that can account for this that is not in the documentation?

**Comment by pferreir** [comment]
Which version is this? Most servers serve Indico with no prefix, so it's possible that there is a problem that went unnoticed. We should definitely update the docs as to not advise the usage of a prefix. But if we can't serve it from `/indico`, then it's a bug.

**Comment by kwierman** [comment]
If I use `pip freeze`, I get: `indico==1.9.7`. It seems to only be affected by serving from this path. If it makes any difference, I'm using `Server version: Apache/2.4.16 (Unix)` as a server.

**Comment by pferreir** [comment]
OK. This is one of the (several) reasons why releases in the 1.9.x branch are not considered production-ready. If this is meant for production, please use the latest release of the 1.2.x branch. I'll keep the ticket open so that we fix this before 2.0, however.

**Comment by ThiefMaster** [comment]
We should probably try to get rid of all the absolute URLs for 2.0, i.e. use a BASE_URL only when we have to build a URL outside a request context (celery etc.).

**Comment by ThiefMaster** [comment]
I think we've fixed this at some point during 1.9.x
