### ISSUE TITLE
Meetings: allow event organizer to choose between `First name Last name` or `Last name, First name`

### ISSUE THREAD

**Issue by pferreir** [indico/indico#2455]
Apparently, there are meetings that require a less informal way of specifying participants. The idea would be to configure (under Layout?) whether the names of participants should be displayed in one way or another (and sorted accordingly).

**Comment by ThiefMaster** [comment]
Should this affect only participants or also e.g. speakers?

**Comment by pferreir** [comment]
If we're going to change it, I'd do it consistently. I don't think it's useful to have `DOE, John` on the list of participants and then `John Doe` as a speaker.
