### ISSUE TITLE
Better handling of pending submitters (e-mails)

### ISSUE THREAD

**Issue by pferreir** [indico/indico#2461]
We're not sending any e-mails to contribution submitters/speakers who have no Indico account. However, instead of just doing that as in the past (implicitly), I suggest:
- Showing a warning message when a someone who has no account is added as a speaker. Said message should direct the user to the "Roles" page;
- Adding an action box at the top of the "Roles page", with a button that sends out a batch "invitation to create account" mail to all pending event/contribution submitters. The e-mail could be customizable and based on a sensible default.

This would provide managers with some flexibility concerning the timing of those e-mails, as well as their content.

(A useful addition could be the date of the last sent invitation, if any.)
- [x] Disabling automatic e-mail currently sent when an event speaker is added
- [x] Warning if speaker with submission rights doesn't have Indico account (flash message)
  - [x] Events
  - [x] Contributions
- [x] Add placeholders to e-mails in "roles" page

**Comment by pferreir** [comment]
We could have a list of "canned" messages in the mail sending dialog on the "roles" page. Not sure what other messages we should have, though.

**Comment by DavidAndreev** [comment]
So I finished adding a button and placeholders to email, but I like the idea of showing the date if we have sent the invitation already, because now there is still that warning for each user even if we have sent the invitation already, so I will look into that
