### ISSUE TITLE
Better time/duration widget for contributions

### ISSUE THREAD

**Issue by pferreir** [indico/indico#2462]
The fact that Indico is used mostly by people who are presumably good at maths is not enough to justify that our current duration widget can work either in minutes or hours, but never in both.

![screen shot 2016-06-10 at 15 38 12](https://cloud.githubusercontent.com/assets/2699/15966010/5d75be04-2f21-11e6-8141-6713be03ab9b.png)

It would be better to just allow both hours and minutes, so that people don't need to mentally figure out how many minutes 1h15m corresponds to.

**Comment by ThiefMaster** [comment]
In newdle we adapted the rc-time-picker for it which works pretty well. We could probably do the same here.
