### ISSUE TITLE
Registrants PDF book: add visual separators and/or section names

### ISSUE THREAD

**Issue by SebastianLopienski** [indico/indico#2472]
Could the PDF Registrants Book (with details of people registering to an event) include visual separators (e.g. horizontal lines) to separate fields coming from different sections of the registration form? 

Additionally, section titles could also be made visible in the PDF (e.g. at/next to these visual separators)?Otherwise, how do I know, other than from the order of the fields, whether a "city" field comes from "Personal details/birth place" section; or from "Current address" section; or from "Where did you study" section etc.)

If you consider implementing this, I'm happy to give feedback to your first prototypes. Thanks!

**Comment by SebastianLopienski** [comment]
Dear colleagues, do you have any news concerning this issue? We will soon again need to export registrants list to PDF books, and this enhancement would greatly help us in the selection process. Thanks in advance!

**Comment by pferreir** [comment]
No news for this or #2473. We're still very busy with the last round of the DB migration, unfortunately.
