### ISSUE TITLE
EventPerson linked to wrong user in migration script

### ISSUE THREAD

**Issue by OmeGak** [indico/indico#2489]
We have found cases of `EventPerson` with an email that doesn't match that of the `User` it's linked to. It seems this was caused by the migration script since all occurrences are on events from before the migration that migrated `EventPerson` or clones of those. This should be fixed before the release of **v2.0**.

This query returns all affected `EventPerson`s linked to the wrong `User`.

``` sql
SELECT ep.id, ep.event_id, ep.email, e.title
FROM events.persons ep
WHERE ep.email != '' AND ep.user_id IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM users.emails WHERE user_id = ep.user_id AND email = ep.email
);
```

---

Additionally, I propose adding a DB trigger on `INSERT` and `UPDATE` on `events.persons` that fails in case the email associated to the event person doesn't match any of those associated to the user.

---

Finally, we should think about how to prevent or deal with cases where we can end up in this state. This can rightfully happen when removing an email from a `User` associated to the `EventPerson` and then adding that same email to another `User`.

**Comment by ThiefMaster** [comment]
The migration works fine and I think we fixed the source of the problem in 9aa92c445 and e9f92cf26
