### ISSUE TITLE
Add option to mark "Presentation type" abstract field as mandatory

### ISSUE THREAD

**Issue by nop33** [indico/indico#2495]
Currently, the "Presentation type" field (created by the contributions type) cannot be marked as mandatory and users fall back to the workaround of creating a custom abstract field for that. That's not a good workaround though, since the contributions type generated field is well integrated with the rest of the system providing extra features, whereas the custom fields don't.

**Comment by nop33** [comment]
Change request: `CHG34343`

**Comment by ThiefMaster** [comment]
good idea, be added to `abstracts_settings` / `AbstractSubmissionSettingsForm`
`contrib_type_required` or something like that.

it should be False by default and i'd disable it or fail validation if you enable it without having contribution types defined

**Comment by ThiefMaster** [comment]
I went for failing validation. That way it's clear why you cannot require a contribution type compared to hiding/disabling the field where it'd be unclear why it's not available (or that such an option even exists in case of hiding)
