### ISSUE TITLE
Encoding problems in Jinja translatable strings

### ISSUE THREAD

**Issue by nop33** [indico/indico#2505]
When the language of Indico is set to Spanish, any page with the switch widget fails to load with this error:

```
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range(128)
```

The error happens in the line

```
{%- set on_label = _('Yes') if on_label is none else on_label -%}
```

of the switch widget template. This is because `Yes` in Spanish is `Sí`.

**Comment by mic4ael** [comment]
That is weird, because I am testing it right now and it seems to work fine. Both locally and on indico.cern.ch

**Comment by nop33** [comment]
in lcagenda it still fails: https://agenda.linearcollider.org/user/preferences/ <https://agenda.linearcollider.org/user/preferences/>. But it’s true that it’s weird, I reproduced it on my machine the other day.. and on indico@cern too. On the devel branch today it works though.

**Comment by nop33** [comment]
Correction: Still fails in devel:
```
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range(128)
```

**Comment by OmeGak** [comment]
This is actually affecting to any translatable block.

```jinja
{% trans foo=some_nasty_ünicode_string %}
    {{ foo }}
{% endtrans %}
```

I'm surprised it doesn't go :volcano: way more often.

**Comment by ThiefMaster** [comment]
python 2 issue
