### ISSUE TITLE
Make "author list" look good in large events

### ISSUE THREAD

**Issue by pferreir** [indico/indico#2523]
The Author list (List of Contributions) currently looks pretty awful when:
- There are many authors (large events)
- The affiliations/names are too long (add ellipsis?)

![screen shot 2016-07-18 at 10 54 02](https://cloud.githubusercontent.com/assets/2699/16909946/e6c036f4-4cd5-11e6-8d27-2e1989796e27.png)

**Comment by matason** [comment]
Hey @pferreir, were you thinking of a JavaScript approach to trim the text (and display on hover) or perhaps something else? Are there any examples elsewhere in Indico where you're doing this kind of thing?

**Comment by pferreir** [comment]
We're doing it in other places (list of registrants?) We normally use `text-overflow: ellipsis`, it's not mandatory that users be able to see the full university name using this dialog.

**Comment by matason** [comment]
Thanks, that sounds good, I'll get it implemented.
