### ISSUE TITLE
mail sending operation failed

### ISSUE THREAD

**Issue by andiri** [indico/indico#2527]
Dear Expert,

I am completely new to python and just starting setup an indico page.
I hope I could find a help here concerning the issue I faced.

I have installed indico (1.2.1rc7) on CentOS 7.2.1511 by using easy_install (setuptools 24.0.3)
Python that I am using is 2.7.5-34.el7 which is the default installation.

Everything has gone fine until I tried to create a user account to start with creating a event.
Sending an activation mail is not working properly.

Here are the snippet of indico.log and indico-error.log

indico.log
>
2016-07-20 10:33:24,869  ERROR    7fe9b9703750  indico.mail               Mail sending operation failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/indico-1.2.1rc7-py2.7.egg/MaKaC/webinterface/rh/base.py", line 536, in process
    GenericMailer.flushQueue(True) # send emails
  File "/usr/lib/python2.7/site-packages/indico-1.2.1rc7-py2.7.egg/MaKaC/common/mail.py", line 63, in flushQueue
    cls._send(mail)
  File "/usr/lib/python2.7/site-packages/indico-1.2.1rc7-py2.7.egg/MaKaC/common/mail.py", line 119, in _send
    server=smtplib.SMTP(*Config.getInstance().getSmtpServer())
  File "/usr/lib64/python2.7/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib64/python2.7/smtplib.py", line 315, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib64/python2.7/smtplib.py", line 290, in _get_socket
    return socket.create_connection((host, port), timeout)
  File "/usr/lib64/python2.7/socket.py", line 571, in create_connection
    raise err
error: [Errno 111] Connection refused

indico-error.log
>
[Wed Jul 20 10:33:10.915624 2016] [:error] [pid 19423]   stacklevel=1,
[Wed Jul 20 10:33:24.872305 2016] [:error] [pid 59717] Traceback (most recent call last):
[Wed Jul 20 10:33:24.872419 2016] [:error] [pid 59717]   File "/usr/lib64/python2.7/logging/handlers.py", line 928, in emit
[Wed Jul 20 10:33:24.873156 2016] [:error] [pid 59717]     smtp = smtplib.SMTP(self.mailhost, port, timeout=self._timeout)
[Wed Jul 20 10:33:24.873249 2016] [:error] [pid 59717]   File "/usr/lib64/python2.7/smtplib.py", line 255, in __init__
[Wed Jul 20 10:33:24.873328 2016] [:error] [pid 59717]     (code, msg) = self.connect(host, port)
[Wed Jul 20 10:33:24.873383 2016] [:error] [pid 59717]   File "/usr/lib64/python2.7/smtplib.py", line 315, in connect
[Wed Jul 20 10:33:24.873490 2016] [:error] [pid 59717]     self.sock = self._get_socket(host, port, self.timeout)
[Wed Jul 20 10:33:24.873555 2016] [:error] [pid 59717]   File "/usr/lib64/python2.7/smtplib.py", line 290, in _get_socket
[Wed Jul 20 10:33:24.873657 2016] [:error] [pid 59717]     return socket.create_connection((host, port), timeout)
[Wed Jul 20 10:33:24.873734 2016] [:error] [pid 59717]   File "/usr/lib64/python2.7/socket.py", line 571, in create_connection
[Wed Jul 20 10:33:24.873812 2016] [:error] [pid 59717]     raise err
[Wed Jul 20 10:33:24.873894 2016] [:error] [pid 59717] error: [Errno 111] Connection refused
[Wed Jul 20 10:33:24.873940 2016] [:error] [pid 59717] Logged from file base.py, line 539

And a runtime warning keeps being repeated as follows:
>
[Wed Jul 20 10:32:08.038060 2016] [:error] [pid 59743] /usr/lib/python2.7/site-packages/pkg_resources/__init__.py:187: RuntimeWarning: You ha
ve iterated over the result of pkg_resources.parse_version. This is a legacy behavior which is inconsistent with the new version class introd
uced in setuptools 8.0. In most cases, conversion to a tuple is unnecessary. For comparison of versions, sort the Version instances directly.
 If you have another use case requiring the tuple, please file a bug with the setuptools project describing that need.
[Wed Jul 20 10:32:08.038162 2016] [:error] [pid 59743]   stacklevel=1,

Would you please guide me to sort out this problem?

Best regards,
Sang-Un

**Comment by mic4ael** [comment]
I think you didn't correctly configure your SMTP server which should handle e-mail sending. If your goal is to set up a development Indico instance I would recommend to install [maildump](https://github.com/ThiefMaster/maildump) and edit your `etc/indico.conf` appropriately.

**Comment by andiri** [comment]
Actually, SMTP server was running since I can send a message by using mail (mailx) command manually.

The problem was not to configure correctly SMTP configuration in indico.conf e.g. the port number (8025 -> 25, the default one).

Thanks a lot for the help!
