### ISSUE TITLE
Avoid duplicated entries in person link widget

### ISSUE THREAD

**Issue by nop33** [indico/indico#2541]
The person link widget returns an `IntegrityError` (`duplicate key value violates unique constraint "uq_contribution_person_links_person_id_contribution_id"`) when an avatar and a user with the same email are added:

``` python
[{
    "_type": "EventPerson",
    "email": "same@email.edu"
    "id": 2706141,
    "user_id": 12345,
    ...
}, {
    "_type": "Avatar",
    "email": "same@email.edu",
    "id": 12345,
    "identifier": "User:12345",
    ...
}]
```

**Comment by OmeGak** [comment]
I thought we had fixed this like twice already. :\

**Comment by ThiefMaster** [comment]
I think @OmeGak and me fixed this a few weeks ago
