### ISSUE TITLE
Keep submission rights after deleting speaker

### ISSUE THREAD

**Issue by jbenito3** [indico/indico#2559]
If I edit a contribution in order to delete a speaker with submission rights, that speaker is automatically removed from the submitter list. Although I agree this seems logical, there are situations in which I would prefer to keep the submission rights to that person, while he is not the speaker anymore. For instance, in my section meetings I keep changing the speaker, but there is a set of people that I want to keep with submission rights always so they can edit the minutes anyway.

If you agree with this, a possible solution could be: when a speaker with submission rights is deleted, show a message saying "Submission rights also deleted" followed by an option "keep them".

cc @indico/development-team

**Comment by plourenco** [comment]
I'm not sure this is still applicable. We can keep any user with submission rights as long as it remains in one of the existing roles. If this restriction no longer proves useful, we can re-open this to consider removing it.
