### ISSUE TITLE
Indico not polling RAVEM after connecting/disconnecting a room

### ISSUE THREAD

**Issue by renefs87** [indico/indico#2561]
Hi,

I noticed some days ago that after connecting to a room, Indico is not polling RAVEM to check if the status of the room is updated.

- **Before**: Indico was polling about 5 times RAVEM to get the updated status (to display the disconnect button in the case of a connection or the connect button in case of disconnection).

- **After**: From RAVEM logs, I cannot see that polling anymore. On the best scenario, Indico checks just one time the status of the room. The result is that sometimes the button "popup" displays "Unable to connect. Timeout while contacting the room. Please wait a moment and refresh the page to try again." even if the room is connected/disconnected properly. (e.g. on 5-1-001).

Cheers!

**Comment by pferreir** [comment]
Moving this to the [internal ticketing system](https://gitlab.cern.ch/indico/indico-plugins-cern/issues/8).
