### ISSUE TITLE
Creating the root category

### ISSUE THREAD

**Issue by danmichaelo** [indico/indico#2566]
Hi, I'm trying to install the latest master. I understand that it's not supported, but I wanted to give it a try. So I figured out I should first set up the postgres db and add two extensions:

```
CREATE DATABASE indico WITH OWNER indico ;
\connect indico
CREATE EXTENSION unaccent ;
CREATE EXTENSION pg_trgm ;
```

Then I ran:

```
$ indico db prepare
$ indico admin user_create
...
$ indico admin user_grant 1
```

Now it almost worked, but the start page gave "Page not found":

<img width="680" alt="skjermbilde 2016-08-14 kl 21 17 57" src="https://cloud.githubusercontent.com/assets/434495/17651313/9ed30d0e-6264-11e6-8af2-c1d0ff28a540.png">

Looking around, I couldn't find a way to create a new category from within the web interface, so I had a look at how the `user_create` command worked instead and tried to create a category from the `indico shell`:

```python
from indico.core.db import db
from indico.core.db.sqlalchemy.util.session import update_session_options
from indico.modules.categories import Category
from indico.modules.categories.operations import create_category

update_session_options(db)

cat = Category.get_root()

db.session.add(cat)
db.session.commit()
```

and it worked!

<img width="690" alt="skjermbilde 2016-08-14 kl 21 25 31" src="https://cloud.githubusercontent.com/assets/434495/17651352/a90cdfec-6265-11e6-860a-7e4e7b54f138.png">

But is there a more proper way to create the root category?

**Comment by ThiefMaster** [comment]
Ah, I see the problem. For the category display pages we use this code so the root category is not created automatically:

        self.category = self._category_query.filter_by(id=category_id, is_deleted=False).one_or_none()

Eventually (in 2.0) we'll create it during `indico db prepare` but for now your way is fine.

We could probably go for this workaround to avoid the problem:

```diff
diff --git a/indico/modules/categories/controllers/base.py b/indico/modules/categories/controllers/base.py
index 40004d1..63fe52e 100644
--- a/indico/modules/categories/controllers/base.py
+++ b/indico/modules/categories/controllers/base.py
@@ -40,7 +40,10 @@ class RHCategoryBase(RH):
         category_id = request.view_args['category_id']
         self.category = self._category_query.filter_by(id=category_id, is_deleted=False).one_or_none()
         if self.category is None:
-            raise NotFound(_("This category does not exist or has been deleted."))
+            if category_id == 0:
+                self.category = Category.get_root()
+            else:
+                raise NotFound(_("This category does not exist or has been deleted."))
```

**Comment by ThiefMaster** [comment]
Fixed, together with a few other issues related to creating the root category (that broke e.g. the settings page of the root category or creating events).

**Comment by danmichaelo** [comment]
Perfect, thanks!
