### ISSUE TITLE
Using non-ascii characters in abstract causes incorrect text length calculation when Submit button is pressed

### ISSUE THREAD

**Issue by agajania** [indico/indico#2584]
Indico version = 1.2.1rc7

We had a couple of users unable to submit their abstacts.

One user's abstract text included a non-ascii apostrophe character (’).  He was unable to submit his abstract.  When he pressed the submit button, Indico would go back to the Submit Abstract form.  It would not show an error and would not save the abstract.

There is a maximum length for abstracts is set to 1500 characters.

I found that if I shortened his abstract by about 10 characters, then it could be submitted successfully.  

Furthermore, I found that if I replaced the non-ascii apostrophes with ascii apostrophes, then the allowed length of the text would be closer to 1500 characters.

**Comment by ThiefMaster** [comment]
This is most likely caused by the fact that certain length checks are applied to UTF8 strings where some of the non-ascii characters are use than one character. Linebreaks might also count as two chars (`\r\n`)

**Comment by ThiefMaster** [comment]
Quite sure that this is fixed since 1.9.9 as we use unicode in the backend.
