### ISSUE TITLE
Optimizations in "Today's events"

### ISSUE THREAD

**Issue by pferreir** [indico/indico#2593]
This page is still excruciatingly slow to the common user. We should check whether we can save some time by adoption a strategy similar to what we are doing now with livesync.

The idea would be to go down the category tree and retrieve all elements that are inheriting straight from the "root" (i.e. category being rendered). That can be easily done with `get_protection_parent_cte()` ([example](https://github.com/indico/indico-plugins/blob/v1.9.8/livesync/indico_livesync/simplify.py#L97)). Furthermore, all public records underneath could also be included right away. Only stuff whose protection has been overridden (as "restricted") has to be ACL-checked.

**Comment by ThiefMaster** [comment]
e494c71 already skips all the access checks in the "event" detail level and 1fa191e skips access checks for  events with no sessions/contribs to show in the other detail levels.

But avoiding more ACL checks (or rather avoiding going up the chain) is still a good idea of course.
