### ISSUE TITLE
Move small forms in event management to dialogs

### ISSUE THREAD

**Issue by OmeGak** [indico/indico#2596]
Let's keep navigation shallow in the event management area.
These are some forms we can move to a dialog:

---
**Core:**
- [x] Reminders
- [x] Surveys
- [x] Registration tickets -> split in two (configuration/qr-code)
- [x] VC rooms

----
**Plugins:**
- [x] Chat rooms

**Comment by pferreir** [comment]
What are we moving exactly? The whole page?
E.g. In reminders, doesn't it make more sense to have it in a standalone page?

**Comment by DavidAndreev** [comment]
Not the whole page, only the form you fill in when you create new reminder or if you edit it. Cause it used to be like a separate page for it and now its only just a dialog where you fill in the form. Same for the surveys, chat, etc.
