### ISSUE TITLE
Link material - make URL visible to the user

### ISSUE THREAD

**Issue by SebastianLopienski** [indico/indico#2599]
As a user, how can I know what is the URL behind a link material? When I hover my mouse over the link, the popup just repeats the link material's _name_ (not very useful), and the browser's status bar shows the URL of Indico's redirection, but not the final URL. 

![image](https://cloud.githubusercontent.com/assets/2960711/18451742/74981e22-7938-11e6-8728-39201b15d82f.png)

For usability, but also security reasons, I believe it would be better if the popup contains the final URL instead of the link's name. (BTW, wasn't that the case some time ago?)

**Comment by ThiefMaster** [comment]
In case of protected link materials (I remember at least one case where someone did not want the link to be visible to anyone but people with access to the material itself) showing the link would be counter-productive.

And performing an access check for each link material when displaying the page to determine whether to show the URL would likely slow things down...

**Comment by SebastianLopienski** [comment]
Of course protected links must not be displayed to unauthorized users. I would never suggest it.

I see three possibilities (but maybe there are more...):
* display unprotected URLs; and also protected URLs, if the user is authorized - best in terms of usability, but if you say there is a performance penalty, then it's up to you to decide
* display only unprotected URLs; hide all protected URLs, even if the user is authorized - not ideal, but perhaps a good balance between usability and performance?
* hide all URL (as it is now) - bad for usability, and also for security (the user clicks without knowing where it will take him/her)

IMHO, the last (current) option is the worst for the users.

**Comment by ThiefMaster** [comment]
done in #4718 - not sure why this issue wasn't auto-closed..
