### ISSUE TITLE
Improve layout of i-forms by adding a corner message for "Save"

### ISSUE THREAD

**Issue by nop33** [indico/indico#2605]
The "Save" button is quite hidden, especially when the `i-form` contains fieldsets.
A solution to emphasize the fact that the form needs to be saved is to add a persistent **corner message** (as in the timetable changes) every time something in the form changes (similar to `data-disabled-until-change`) with a link to save the form.

The corner message could be enabled using a `data` attribute in the form element.

**Comment by nop33** [comment]
SNow ticket: `CHG34404`

**Comment by OmeGak** [comment]
Sticky footer with save button, maybe?

**Comment by nop33** [comment]
I proposed this to @pferreir and the resolution of our discussion was to add a corner message.

**Comment by OmeGak** [comment]
Isn't that quite an uncommon pattern?
