### ISSUE TITLE
Event overview: Inherit icon from parent categories

### ISSUE THREAD

**Issue by nop33** [indico/indico#2607]
In the event overview page, the icons next to the events are missing, as well as the list of categories (to which the listed events belong too) under the Legend sidebar.

The problem is that categories do not inherit the icon from their parents.

Depending on what's less expensive we could either use something similar to `own_no_access_contact` and `no_access_contact` or query the inherited icon information separately just in the overview RH (e.g. using a CTE returning the inherited `icon_metadata` and the `id` from the category where it originates from).

**Comment by nop33** [comment]
Related ticket: `CHG34405`

**Comment by pferreir** [comment]
@ThiefMaster, isn't this solved?

**Comment by ThiefMaster** [comment]
Yes, just not merged into master yet
