### ISSUE TITLE
indico_initial_setup needs sudo

### ISSUE THREAD

**Issue by fortizmu** [indico/indico#2610]
Hello,

I'm trying to deploy indico under a cloud server within a virtualenv, where all the setup requirements are available.
"easy_install indico" seems to do its job.
 When running indico_initial_setup, then I cannot do sudo because my user is not in the sudoers.

$ indico_initial_setup
- EGG found at /home/fortizmu/webapps/indico/venv/lib/python2.7/site-packages/indico-1.2.1rc9-py2.7.egg... unconfigured
  No previous installation of Indico was found.
  Please specify a directory prefix:

You now need to configure Indico, by editing indico.conf or letting us do it for you.
At this point you can:

  [c]opy the default values in etc/indico.conf.sample to a new etc/indico.conf
  and continue the installation

  [A]bort the installation in order to inspect etc/indico.conf.sample
  and / or to make your own etc/indico.conf

What do you want to do [c/a]? c
Copying Indico tree...
/home/fortizmu/webapps/indico/venv/lib/python2.7/site-packages/indico-1.2.1rc9-py2.7.egg/MaKaC/consoleScripts/../../bin -> ./bin
/home/fortizmu/webapps/indico/venv/lib/python2.7/site-packages/indico-1.2.1rc9-py2.7.egg/MaKaC/consoleScripts/../../doc -> ./doc
/home/fortizmu/webapps/indico/venv/lib/python2.7/site-packages/indico-1.2.1rc9-py2.7.egg/MaKaC/consoleScripts/../../etc -> ./etc
/home/fortizmu/webapps/indico/venv/lib/python2.7/site-packages/indico-1.2.1rc9-py2.7.egg/MaKaC/consoleScripts/../../htdocs -> ./htdocs
Creating wsgi symlink... ./htdocs/indico.wsgi
done!
Creating directories for resources... done!
Upgrading indico.conf... done!

We cannot find a configured database at ./db.

  Do you want to create a new database now [Y/n]? Y

Where do you want to install the database [./db]?
uid/gid not provided. Trying to guess them... found apache(48) apache(48)

We need to 'sudo' in order to set the permissions of some directories...
[sudo] password for fortizmu:

I've tried to move forward my omitting the sudo command in function _checkDirPermissions (in file installBase.py).
The script then runs until the end:

Congratulations!
Indico has been installed correctly.

```
indico.conf:      ./etc/indico.conf

BinDir:           ./bin
DocumentationDir: ./doc
ConfigurationDir: ./etc
HtdocsDir:        ./htdocs
```

For information on how to configure Apache HTTPD, take a look at:

http://indico.readthedocs.org/en/latest/installation/#configuring-the-web-server

Please do not forget to start the 'taskDaemon' in order to use alarms, creation
of off-line websites, reminders, etc. You can find it in './bin/taskDaemon.py'

If you are running ZODB on this host:
- Review ./etc/zodb.conf and ./etc/zdctl.conf to make sure everything is ok.
- To start the database run: zdaemon -C ./etc/zdctl.conf start

When trying to do that
$ zdaemon -C ./etc/zdctl.conf start

then there is the message:
Error: only root can use -u USER to change users

Is there a workaround for this?
Can indico only be installed and deployed as "root"?

As mentioned in the beginning, I can setup a venv where all the needed components (Python, Apache, 
mod_wsgi) are available.
For example, within the same server I run applications based on similar technologies (e.g. Plone CMS).

I very much appreciate your comments.

Thank you in advance!
Kind regards,
Francisco

**Comment by SysAd-WI** [comment]
I installed indico as root. But the "indico_initial_setup" doesn't create the database-files (Data.fs, etc.):

    Creating directories for resources...  done!
    Upgrading indico.conf... done!

    We cannot find a configured database at /opt/indico/db.

    Do you want to create a new database now [Y/n]? Y

    Where do you want to install the database [/opt/indico/db]? /var/www/indicoenv/indico/db
    uid/gid not provided. Trying to guess them...  found apache(48) apache(48)

    We need to 'sudo' in order to set the permissions of some directories...

    Congratulations!
    Indico has been installed correctly."

Everything else seems okay. Any suggestions?

**Comment by ThiefMaster** [comment]
The database files should be created the first time you start ZODB (using the `zdaemon` command)

**Comment by SysAd-WI** [comment]
Thank you for the quick reply and for your help. 

Now, I can't access the webinterface because the database "indico" doesn't exist. Can't find anything about db-initialization for indico in the wiki. Did you?

    An unexpected error occurred.

    (psycopg2.ProgrammingError) FEHLER: Schema »indico« existiert nicht LINE 2: FROM indico.settings ^     
    [SQL: 'SELECT indico.settings.id AS indico_settings_id, indico.settings.module AS   
    indico_settings_module,....

**Comment by ThiefMaster** [comment]
Oh I see, you are using the code from `master` - this is actually a much newer version that's not officially released yet. It runs on a mix of two databases while we are getting rid of ZODB.

It's recommended that you install 1.2.1 for now and then upgrade one 2.0 is out (which will be Postgres-only). FWIW, the (bleeding-edge / unstable) `devel` branch will already be using Postgres only (without any ties to ZODB) as of next week the latest. However, that  branch is (as the name indicates) under heavy development so we cannot recommend it for any production use at the moment!

If you do want to go along with master/1.9.9: Run `indico db prepare` to create the database structure in Postgres.

**Comment by cederom** [comment]
I have commented out the sudo portion from the installer script and INDICO installed fine. Then I am starrting the zdaemon with a script and WebGUI appears. I have problem with WSGI though and the stiff folders location aka `htdocs` instead `public` as my proovider (DreamHost) requires. I have tried different configurations but none of them work except initial start site..

**Comment by hmissi** [comment]
$indico db prepare
Required Postgres extensions missing: pg_trgm, unaccent
Create them using these SQL commands (as a Postgres superuser):
  CREATE EXTENSION pg_trgm;
  CREATE EXTENSION unaccent;

... still have the same error 
An unexpected error occurred.

(psycopg2.ProgrammingError) ERREUR: le schéma « indico » n'existe pas LINE 2: FROM indico.settings ^ [SQL: 'SELECT indico.settings.id AS indico_settings_id, indico.settings.module AS indico_settings_module, indico.settings.name AS indico_settings_name, indico.settings.value AS indico_settings_value \nFROM indico.settings']

:( ?

**Comment by ThiefMaster** [comment]
Did you run `indico db prepare` again after creating the extensions?

**Comment by hmissi** [comment]
yep !

**Comment by ThiefMaster** [comment]
What output did you get from `indico db prepare`?

**Comment by hmissi** [comment]
just this 
# indico db prepare
Required Postgres extensions missing: pg_trgm, unaccent
Create them using these SQL commands (as a Postgres superuser):
  CREATE EXTENSION pg_trgm;
  CREATE EXTENSION unaccent;

**Comment by ThiefMaster** [comment]
OK, that sounds like you didn't run these commands in the same database indico uses - extensions are added to a specific database, so if you were connected to a different one they aren't available in the indico db

**Comment by hmissi** [comment]
now i got this :(

```
 indico db prepare
Creating tables
Traceback (most recent call last):
  File "/usr/bin/indico", line 11, in <module>
    load_entry_point('indico==1.9.9', 'console_scripts', 'indico')()
  File "/usr/lib/python2.7/site-packages/indico-1.9.9-py2.7.egg/indico/cli/manage.py", line 52, in main
    manager.run()
  File "/usr/lib/python2.7/site-packages/Flask_Script-2.0.5-py2.7.egg/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/usr/lib/python2.7/site-packages/Flask_Script-2.0.5-py2.7.egg/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "/usr/lib/python2.7/site-packages/Flask_Script-2.0.5-py2.7.egg/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/indico-1.9.9-py2.7.egg/indico/cli/database.py", line 80, in prepare
    db.create_all()
  File "/usr/lib/python2.7/site-packages/Flask_SQLAlchemy-2.1-py2.7.egg/flask_sqlalchemy/__init__.py", line 972, in create_all
    self._execute_for_all_tables(app, bind, 'create_all')
  File "/usr/lib/python2.7/site-packages/Flask_SQLAlchemy-2.1-py2.7.egg/flask_sqlalchemy/__init__.py", line 964, in _execute_for_all_tables
    op(bind=self.get_engine(app, bind), **extra)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/sql/schema.py", line 3848, in create_all
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1920, in _run_visitor
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1529, in _run_visitor
  File "build/bdist.linux-x86_64/egg/sqlalchemy/sql/visitors.py", line 121, in traverse_single
  File "build/bdist.linux-x86_64/egg/sqlalchemy/sql/ddl.py", line 733, in visit_metadata
  File "build/bdist.linux-x86_64/egg/sqlalchemy/sql/visitors.py", line 121, in traverse_single
  File "build/bdist.linux-x86_64/egg/sqlalchemy/sql/ddl.py", line 767, in visit_table
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 945, in execute
  File "build/bdist.linux-x86_64/egg/sqlalchemy/sql/ddl.py", line 68, in _execute_on_connection
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1002, in _execute_ddl
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1189, in _execute_context
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1393, in _handle_dbapi_exception
  File "build/bdist.linux-x86_64/egg/sqlalchemy/util/compat.py", line 202, in raise_from_cause
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1182, in _execute_context
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/default.py", line 469, in do_execute
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) ERREUR:  le type « jsonb » n'existe pas
LINE 11:  data JSONB NOT NULL,
               ^
 [SQL: '\nCREATE TABLE events.vc_room_events (\n\tid SERIAL NOT NULL, \n\tevent_id INTEGER NOT NULL, \n\tvc_room_id INTEGER NOT NULL, \n\tlink_type SMALLINT NOT NULL, \n\tlinked_event_id INTEGER, \n\tsession_block_id INTEGER, \n\tcontribution_id INTEGER, \n\tshow BOOLEAN NOT NULL, \n\tdata JSONB NOT NULL, \n\tCONSTRAINT pk_vc_room_events PRIMARY KEY (id), \n\tCONSTRAINT ck_vc_room_events_valid_event_link CHECK (link_type != 1 OR (contribution_id IS NULL AND session_block_id IS NULL AND linked_event_id IS NOT NULL)), \n\tCONSTRAINT ck_vc_room_events_valid_contribution_link CHECK (link_type != 2 OR (linked_event_id IS NULL AND session_block_id IS NULL AND contribution_id IS NOT NULL)), \n\tCONSTRAINT ck_vc_room_events_valid_block_link CHECK (link_type != 3 OR (contribution_id IS NULL AND linked_event_id IS NULL AND session_block_id IS NOT NULL)), \n\tCONSTRAINT ck_vc_room_events_valid_enum_link_type CHECK (link_type IN (1, 2, 3))\n)\n\n']

```

**Comment by ThiefMaster** [comment]
You need to have at least postgres 9.4

**Comment by hmissi** [comment]
thnx :) now i have Pg 9.6 
```
indico db prepare
Creating tables
```
ok 

but again 
```
An unexpected error occurred.

(psycopg2.ProgrammingError) ERREUR: droit refusé pour le schéma indico LINE 2: FROM indico.settings ^ [SQL: 'SELECT indico.settings.id AS indico_settings_id, indico.settings.module AS indico_settings_module, indico.settings.name AS indico_settings_name, indico.settings.value AS indico_settings_value \nFROM indico.settings']

Back to the main page

and the tables seems empty 

postgres=# \connect indico
Vous êtes maintenant connecté à la base de données « indico » en tant qu'utilisateur « postgres ».
indico=# SELECT indico.settings.id AS indico_settings_id, indico.settings.module AS indico_settings_module, indico.settings.name AS indico_settings_name, indico.settings.value AS indico_settings_value FROM indico.settings
indico-#

```

**Comment by ThiefMaster** [comment]
Sounds like ownership is messed up somewhere. I'd delete the database, 
recreate it (with the user you'll use for indico being the DB owner), then 
created the extensions using the pg superuser and then running `indico db 
prepare`.

**Comment by hmissi** [comment]
Ok thanks ! but  Its 02:15 am and i will test it tomorrow :p  ..; by the way i am EX technical student at CERN "LHCB" ;)  
have a good night !!

**Comment by hmissi** [comment]
Hi its workiiiiing :)
ALTER USER apache WITH SUPERUSER;

**Comment by ThiefMaster** [comment]
Careful, this is not a good solution. No webapp should have any kinds of superuser rights - even if it's just in the database (actually, a Postgres superuser can execute arbitrary shell commands through the database).

**Comment by hmissi** [comment]
yes yes ;) !
just a last question .... how can i install plugins (search ...)
because the plugins tab show nothing 
thank you !

**Comment by pferreir** [comment]
Please ask this on the mailing list or IRC:
http://indico-software.org/contact/

This is supposed to be an issue tracker, so we'd prefer to keep support elsewhere.
