### ISSUE TITLE
Invalid atom feed

### ISSUE THREAD

**Issue by lucasgautheron** [indico/indico#2614]
Indico can produce invalid category events feeds, as in : 
https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Findico.in2p3.fr%2Fcategory%2F81%2Fevents.atom

Source category : https://indico.in2p3.fr/category/81/

**Comment by pferreir** [comment]
Looks more like an encoding issue than an actual XML validity issue. Which
version is this?

**Comment by lucasgautheron** [comment]
Thanks for your prompt reply. Sure the syntax is correct, but shouldn't Indico enforce the output of feeds with consistent encoding ?

As for what version this is, I am afraid I cannot answer this question myself as a simple user. I will email the maintainer for these information and let you know when I know more.

**Comment by pferreir** [comment]
Sure, that should be properly fixed. Just trying to narrow down the
possible causes.
Thanks for the report!

**Comment by lucasgautheron** [comment]
I was answered the version of Indico used is *1.2*.

**Comment by lucasgautheron** [comment]
I had a very quick check at the code, maybe https://github.com/indico/indico/commit/279c1728ee8e1bc9c4511e3b323d89844a9df696 fixed it already ?

**Comment by pferreir** [comment]
Probably. It would be interesting to check it out once 2.0 comes out.

**Comment by ThiefMaster** [comment]
issue from legacy indico; and we changed libraries once or twice since then, so most likely fixed
