### ISSUE TITLE
Abstract submission confirmation: Long URLs are broken (1.2)

### ISSUE THREAD

**Issue by danmichaelo** [indico/indico#2649]
Indico v1.2.1rc10

In the abstract submission confirmation email, long URLs are broken on hyphen:

```
The submission of your abstract has been successfully processed.

Abstract submitted: <http://some-hostname/event/1/call-for-
abstracts/my-abstracts>.
```

Found out that I could fix this by adding `tw.break_on_hyphens = False` after

https://github.com/indico/indico/blob/v1.2/indico/MaKaC/webinterface/rh/CFADisplay.py#L152

Also, it seems like the wrapping has been removed altogether in 1.9.8, so shouldn't be an issue there.

**Comment by ThiefMaster** [comment]
That whole code has been rewritten in 1.9.x/2.0 so yeah, it won't be a problem anymore in the future.

**Comment by thebadan** [comment]
Thank you! 
Abstract sending confirmation e-mail #2265
Abstract submission confirmation email and line wraps #2292
