### ISSUE TITLE
Can't create/move event in main category when there is others categories

### ISSUE THREAD

**Issue by anton-z-s** [indico/indico#2650]
Indico 1.2rc10
Steps to reproduce: 
scenario 1
1. create category 
2. create event. you can't place the event in main category.

scenario 2
1. create event. when there is no categories, you can place it in main category.
2. create category. the event will be moved in that category.
3. now you can't return to the only-main-category state, because you can't move the event to main category and can't remove the created category since it's the only one left.

When trying to remove last category, it would be great to move all it's events to main category, if there is no nested categories.

**Comment by ThiefMaster** [comment]
Scenario 1 makes perfect sense, you cannot have events and subcategories in the same category at the moment.

Scenario 2 is indeed a bit of an edge case. I think it's very unlikely for indico to be used without categories in the first place, but of course it would be nice to support "going back" without having to delete the event first.

In 1.9.x/2.0 we already rewrote the category management and it's much more flexible, but I think that specific case is still not possible (as we only allow deleting empty categories). However, considering how much of an edge case it is I don't think special handling for it makes much sense. Eventually we'll allow mixing events and subcategories (it's already possible in 1.9.x's backend but we don't allow it in the UI yet) which will make the problem go away anyway.
