### ISSUE TITLE
Make list of e-mails in e-mail dialogs less awful

### ISSUE THREAD

**Issue by pferreir** [indico/indico#2653]
When we're mailing many people, the whole thing becomes giant.

**Comment by ThiefMaster** [comment]
I think it's important that there's still some way to copy all emails. Some people like to use their own email client and just want to copy&paste the email.

**Comment by DavidAndreev** [comment]
Ok so I fixed this in roles page, we can also send emails from registration - participants list, but there we don't show recipients, is that on purpose or is it a bug ?
