### ISSUE TITLE
Start zdaemon on boot

### ISSUE THREAD

**Issue by positroni** [indico/indico#2674]
Hi, 

I would like to be able to start zdaemon when the server reboots.
My server uses systemd so I modified the apache service file in such a way that after systemd launches apache, it start a custom script file.

The content of the script `indico.sh` is

`#!/bin/bash`
`/usr/bin/zdaemon -C /opt/indico/etc/zdctl.conf start`

However it doesn't work, here is the systemd status

`indico.sh[196]: . Unlinking stale socket /opt/indico/db/zdsock; sleep 1`
`indico.sh[196]: No handlers could be found for logger "root"`
`indico.sh[196]: .`
`indico.sh[196]: daemon process started, pid=520`

Even though it says started, the process is not running.

**Comment by pferreir** [comment]
I don't think this is an Indico issue.
As you very well mention, systemd can do that (and should be able to do it correctly). I wouldn't use the same startup script for Apache and ZODB, though.
