### ISSUE TITLE
Allow sub-contributions to be edited from display view

### ISSUE THREAD

**Issue by nop33** [indico/indico#2679]
Adding subcontributions in meetings is very complicated (edit event -> timetable -> select day -> select session -> edit session timetable -> click on contribution -> manage subcontributions -> add subcontribution)

This can be improved by providing a link to manage the subcontributions from within the contribution dialog.

**Comment by ThiefMaster** [comment]
From within the edit dialog? Wouldn't it be better to have a button to edit subcontributions on the display page?

**Comment by nop33** [comment]
Yeah, that's an option as well.

**Comment by nop33** [comment]
![image](https://cloud.githubusercontent.com/assets/1579899/23502075/c6dcada4-ff36-11e6-8ab3-3ecdd88448be.png)

Something like this would be good I believe!
