### ISSUE TITLE
Registration Form: allow users to cancel their registration

### ISSUE THREAD

**Issue by pferreir** [indico/indico#2715]
There's already backend code for this (`Registration.withdrawn`), we have to make it available from the interface. It should be configurable.

**Comment by SebastianLopienski** [comment]
It would be also good to allow event managers to withdraw an application/registration (e.g. one the person withdraws by email to event organizers)

**Comment by brabemi** [comment]
Hi, in my [fork](https://github.com/brabemi/indico/tree/registration_withdraw) i added withdraw button with confirmation popup into registration detail view. Behavior is the same as for modify button.

I will think about how to add withdraw action for event managers

![02](https://user-images.githubusercontent.com/6898184/57967699-5917d200-7962-11e9-9cb0-77cc30dedda6.png)

**Comment by bpedersen2** [comment]
@brabemi : Would you mind to create a pull request?
