### ISSUE TITLE
 button  Class does not work

### ISSUE THREAD

**Issue by luisorellana1234** [indico/indico#2744]
I have an error and I do not know how to fix it in the buttons on the right margin.
![error](https://cloud.githubusercontent.com/assets/16797639/20756339/9f4732ee-b712-11e6-9d47-1dca0be3ce94.JPG)

**Comment by ThiefMaster** [comment]
This looks a lot like the icomoon font wasn't loaded. If the instance is publically available, can you post a link here? Otherwise please check your browser's dev tools / console whether there was an error when loading the icomoon font. It's bundled with Indico so usually it should work.
