### ISSUE TITLE
More IE Bugs

### ISSUE THREAD

**Issue by DavidAndreev** [indico/indico#2749]
Those are the other bugs that I've found in IE, basically any dialog with Save, Cancel button and contribution list.
![contriblist](https://cloud.githubusercontent.com/assets/9071624/20934042/23900262-bbda-11e6-8fbb-c21e76ca2426.png)
![configboa](https://cloud.githubusercontent.com/assets/9071624/20934045/2544de70-bbda-11e6-9cf7-ba87c87d0889.png)

**Comment by nop33** [comment]
![image](https://cloud.githubusercontent.com/assets/1579899/20960484/e8959b86-bc60-11e6-9ef7-87d9995437f9.png)

**Comment by nop33** [comment]
![image](https://cloud.githubusercontent.com/assets/1579899/20960492/f616b9f2-bc60-11e6-83ad-6243da0fb68f.png)

**Comment by nop33** [comment]
I noticed that because the *Save* button is an `<input type="submit" />` element. I would suggest the same fix as to the FF problem (where the `display` property of a `<button>` element cannot be changed).

**Comment by nop33** [comment]
I fixed the bug of the *Save* buttons here: https://github.com/nop33/indico/commit/91909a9f52eb6d4d188f455f196f248cc40d1cea

**Comment by ThiefMaster** [comment]
IE isn't supported anymore
