### ISSUE TITLE
Session always forget room after edit

### ISSUE THREAD

**Issue by positroni** [indico/indico#2752]
Hi,
everytime I edit something for a session, i.e. duration, conveners etc., the field "room" is set to nothing.
The conference I have set up has just a building as main location and each session has its own room.
Is this a normal behaviour or should I fix something?

**Comment by ThiefMaster** [comment]
Does this happen in 1.2.x or 1.9.x?

**Comment by positroni** [comment]
it happens with 1.2.x

**Comment by ThiefMaster** [comment]
legacy bug
