### ISSUE TITLE
ParaFrag instance has no attribute 'width'

### ISSUE THREAD

**Issue by OmeGak** [indico/indico#2762]
Caused by embedded images in markdown.

```markdown
![](http://.../img.png)
```

This seems to be solved in ReportLab `3.3.8`, but it's not yet available in PyPI at this time. Here's the original [issue](https://bitbucket.org/rptlab/reportlab/issues/81/failed-to-access-width-attribute-in) and the [patch](https://bitbucket.org/rptlab/reportlab/commits/a3e48855dd48e69d115e440695d2beff9f77ba6f).

**Comment by ThiefMaster** [comment]
We are using 3.4.0 so it's probably fixed
