### ISSUE TITLE
Missing header toolbar in IE

### ISSUE THREAD

**Issue by DavidAndreev** [indico/indico#2774]
SNOW ticket :  RQF0686991
Probably something with flexbox
![2](https://cloud.githubusercontent.com/assets/9071624/21353436/366678ca-c6c6-11e6-87e2-8c08c871dc6a.PNG)
![1](https://cloud.githubusercontent.com/assets/9071624/21353438/3ad0bcfe-c6c6-11e6-8f70-fe975d872cfb.PNG)

**Comment by ThiefMaster** [comment]
Isn't this already fixed?
