### ISSUE TITLE
No assets on login page

### ISSUE THREAD

**Issue by etemam** [indico/indico#2790]
Hi,

When I use login page built-in indico no js, nor css are loaded and I have the following code:

`<head>
    <title>Indico</title>
    <meta charset="UTF-8">
    <link rel="shortcut icon" type="image/x-icon" href="/images/indico.ico">

    <script>
        var ScriptRoot = "/js";
    </script>

    <script type="text/javascript" src="/assets/i18n/fr_FR.js"></script>
    <script type="text/javascript" src="/assets/js-vars/global.js"></script>

    <script src=""></script>
    <script src=""></script>
    <script src=""></script>
    <script src=""></script>
    <script src=""></script>
    <script src=""></script>
    <script src=""></script>
    <script src=""></script>
    <script src=""></script>
    <script src=""></script>
    <script src=""></script>
    <script src=""></script>
    <script src=""></script>
    <script src=""></script>
    <script src=""></script>
    <script src=""></script>
    <script src=""></script>
    <script src=""></script>
    

    <link rel="stylesheet" type="text/css" href="">
    <link rel="stylesheet" type="text/css" href="">
    

    
    
    <link rel="stylesheet" type="text/css" href="">
    

</head>
`

Can you help?

Thanks

**Comment by ThiefMaster** [comment]
Which Indico version are you using? Also, please paste the output of `pip freeze`

**Comment by etemam** [comment]
Hi,

indico 1.9.9

Here is pip freeze:

`Babel==2.3.4
Fabric==1.13.1
Flask==0.11.1
Flask-BabelEx==0.9.3
Flask-Migrate==1.2.0
Flask-Multipass==0.0.dev0
Flask-OAuthlib==0.9.1
Flask-PluginEngine==0.2.1
Flask-SQLAlchemy==2.1
Flask-Script==2.0.5
Flask-WTF==0.13
Jinja2==2.9.4
Mako==0.9.1
Markdown==2.3.1
MarkupSafe==0.23
Pillow==2.7.0
PyYAML==3.12
Pygments==2.1.3
SQLAlchemy==1.1.4
Sphinx==1.5.1
WTForms==2.1
WTForms-Components==0.10.0
Werkzeug==0.11.10
XlsxWriter==0.9.3
ZConfig==2.9.2
ZODB3==3.10.5
alabaster==0.7.9
alembic==0.6.7
amqp==1.4.9
anyjson==0.3.3
argparse==1.2.1
bcrypt==3.1.0
beautifulsoup4==4.5.1
billiard==3.3.0.23
bleach==1.4.3
blinker==1.4
celery==3.1.23
certifi==2016.9.26
cffi==1.9.1
click==6.6
colorclass==2.2.0
contextlib2==0.5.4
cov-core==1.14.0
coverage==4.2
cryptography==1.7.1
cssmin==0.1.4
decorator==4.0.11
docutils==0.13.1
enum34==1.1.6
flask-marshmallow==0.7.0
freezegun==0.3.7
funcsigs==1.0.2
functools32==3.2.3.post2
hiredis==0.2.0
html2text==2016.5.29
html5lib==0.9999999
httplib2==0.9.2
icalendar==3.11
idna==2.2
imagesize==0.7.1
indico==1.9.9
indico-fonts==1.1
infinity==1.4
intervals==0.8.0
ipaddress==1.0.18
itsdangerous==0.24
jsmin==2.0.2
jsonschema==2.5.1
kombu==3.0.37
lxml==3.4.1
marshmallow==2.10.3
marshmallow-enum==1.0
marshmallow-sqlalchemy==0.12.0
mock==1.3.0
nodeenv==1.0.0
oauth2==1.5.211
oauthlib==2.0.1
paramiko==2.1.1
pathlib==1.0.1
pbr==1.10.0
pojson==0.7
polib==1.0.8
psycopg2==2.6.2
py==1.4.32
pyPdf==1.13
pyScss==1.3.5
pyasn1==0.1.9
pyatom==1.2
pycountry==1.2
pycparser==2.17
pyparsing==1.5.7
pytest==3.0.5
pytest-catchlog==1.2.2
pytest-cov==2.3.1
pytest-localserver==0.3.6
pytest-mock==0.11.0
python-dateutil==2.5.3
python-ldap==2.4.28
pytz==2016.10
qrcode==3.0
redis==2.10.5
reportlab==3.2.0
repoze.sphinx.autointerface==0.8
requests==2.12.4
requests-oauthlib==0.7.0
simplejson==3.10.0
six==1.10.0
snowballstemmer==1.2.1
speaklater==1.3
sqlparse==0.2.2
termcolor==1.1.0
terminaltables==3.0.0
transaction==1.3.0
translitcodec==0.4.0
ujson==1.19
validators==0.11.2
webassets==0.9
wsgiref==0.1.2
zc.lockfile==1.0.0
zc.queue==1.3
zdaemon==3.0.5
zope.event==4.0.0
zope.index==3.6.4
zope.interface==4.3.3
zope.sqlalchemy==0.7.7`

Sincerly

**Comment by ThiefMaster** [comment]
You can either downgrade Jinja to 2.8 (pip uninstall -y jinja2 && pip install 'jinja2==2.8') or update webassets to 0.12.1.

Actually, I'm not sure how you ended up with Jinja 2.9.4 - the requirements.txt in master still specifies 2.8. (2.9 introduced a change that caused a bug in webassets to show up, but it was already fixed in webassets 0.12.1)

**Comment by ThiefMaster** [comment]
FWIW, I would righly recommend to downgrade Jinja for now, since the "Logs" page in the management area of an event is broken in Jinja 2.9.x which still needs to be fixed in master.

**Comment by etemam** [comment]
Thanks!

Downgrade work.

FYI I just do

`pip install -r requirements.txt`

You can close.
