### ISSUE TITLE
Copying timetable between events

### ISSUE THREAD

**Issue by pferreir** [indico/indico#2794]
The title is self-explanatory. This should probably be done from the source event and provide a choice between all events the user has management access to.

Internal reference: `CHG34557`

**Comment by ThiefMaster** [comment]
Would probably make more sense to make the whole cloning logic flexible enough to not fail if the event already contains certain objects (probably that's already the case in new cloners). I.e. instead of selecting a date to clone to you could specify a target event.

**Comment by pferreir** [comment]
I'm not sure how intuitive that would be... but yeah, it's a possibility.

**Comment by ThiefMaster** [comment]
#4533 includes this functionality
