### ISSUE TITLE
Language menu does not appear under Google Chrome

### ISSUE THREAD

**Issue by boileaum** [indico/indico#2800]
On my Mac (OSX 10.12.2), Google Chrome (version 55.0.2883.95 (64-bit)) does not show the language menu (on the right of top black bar). This menu does appear under Safari and Firefox.

**Comment by pferreir** [comment]
That's weird. I have the same browser version/OS. Can you post a screenshot so that we see what it looks like?

**Comment by boileaum** [comment]
Sorry but I've just realized that the language menu location was different once logged as an Indico user: it moves from the top bar to the user drop-down menu...
