### ISSUE TITLE
Bulk abstract acceptance: Contribution type not copied

### ISSUE THREAD

**Issue by ThiefMaster** [indico/indico#2812]
When bulk-accepting abstracts you can currently only select a contribution type used for all the abstracts or none at all. Selecting none should preserve the contribution type selected in the abstract instead of being literally no contribution type.

**Comment by nop33** [comment]
Copy from the Asana task:
> If and only if there are non-judged abstracts proposed for different tracks/contribution types/actions, the dialog in question consists of two options:
Accept everything as it is when it is consensual (abstracts in conflict are skipped, flash message shown);
Select what you want to accept them for (and in this case we could pre-select one of the options if all selected abstracts have it);
This could be achieved using a switch, or radio buttons for that matter.
If there's no disagreement (all abstracts proposed for same contribution type/track and action), then we could pre-fill the information and not provide the switch.
