### ISSUE TITLE
Meeting pages look funny

### ISSUE THREAD

**Issue by ThiefMaster** [indico/indico#2815]
`{% set previous_date = date %}` at the end of a loop to check whether the value changed since the last iteration only worked because of a jinja bug (cross-loop sets were never supposed to work), which has been fixed in Jinja 2.9.

There are currently various workarounds that are more or less ugly (mutable objects with the `do` extension, or the groupby filter), but possibly there will be a clean solution to access the previous loop item in Jinja until 1.9.10 is ready for production.

Related jinja issue: pallets/jinja#641

![funny](https://cloud.githubusercontent.com/assets/179599/22471432/98887486-e7d2-11e6-9d22-dfec085849ca.png)

**Comment by OmeGak** [comment]
A-ma-zing.

**Comment by ThiefMaster** [comment]
Just to keep track of another place where legacy jinja scoping is used: indico/modules/events/timetable/templates/display/administrative/_session_block.html

this one could make use of need the namespace idea suggested in pallets/jinja#641 (or abuse a mutable object for now)

**Comment by ThiefMaster** [comment]
[This change](https://github.com/indico/indico/commit/b8fc322ea0d329f17dfcf0dc22e9ff5cf112e013#diff-c65e603b5fdaf86847b5ffe7fc8852a6) should be reverted once we use a Jinja version containing pallets/jinja#684

**Comment by ThiefMaster** [comment]
c509c68bd should also be updated once Jinja has been updated. In case the commit has is invalid due to a rebase by then, search for templates containing `{% set __ =`
