### ISSUE TITLE
ImportError: No module named indico.web.flask.app

### ISSUE THREAD

**Issue by gabrieletassoni** [indico/indico#2820]
Hi,
I'm trying to install indico in a freshly installed debian jessie, I'm using a virtualenv to keep the python environment needed for indico clean, but, whenever I try to browse to http://serverip/indico, I'm presented with an internal server error, further investigation, in /var/log/apache2/error.log, led me to this error:

```
[Thu Feb 02 17:27:07.029507 2017] [wsgi:error] [pid 13253:tid 140397576640256] [remote 192.168.77.254:512] mod_wsgi (pid=13253): Target WSGI script '/opt/indico/htdocs/indico.wsgi' cannot be loaded as Python module.
[Thu Feb 02 17:27:07.030438 2017] [wsgi:error] [pid 13253:tid 140397576640256] [remote 192.168.77.254:512] mod_wsgi (pid=13253): Exception occurred processing WSGI script '/opt/indico/htdocs/indico.wsgi'.
[Thu Feb 02 17:27:07.030889 2017] [wsgi:error] [pid 13253:tid 140397576640256] [remote 192.168.77.254:512] Traceback (most recent call last):
[Thu Feb 02 17:27:07.030971 2017] [wsgi:error] [pid 13253:tid 140397576640256] [remote 192.168.77.254:512]   File "/opt/indico/htdocs/indico.wsgi", line 20, in <module>
[Thu Feb 02 17:27:07.031172 2017] [wsgi:error] [pid 13253:tid 140397576640256] [remote 192.168.77.254:512]     from indico.web.flask.app import make_app
[Thu Feb 02 17:27:07.031211 2017] [wsgi:error] [pid 13253:tid 140397576640256] [remote 192.168.77.254:512] ImportError: No module named indico.web.flask.app
```

I tried to `python -c " from indico.web.flask.app import make_app"` as a non root user, and it throws the same error; running that same command with _sudo_ (or as root) it won't throw the error.

What can I do to resolve this problem? Which other information can I provide to help in debugging?

Thank you very much.

**Comment by ThiefMaster** [comment]
pretty sure this is no longer relevant 4 years later
