### ISSUE TITLE
Allow abstract withdrawal after abstract acceptance (managers only)

### ISSUE THREAD

**Issue by nop33** [indico/indico#2824]
Allow abstract withdrawal after acceptance (managers only) with a prompt "Withdrawing this accepted abstract will delete its corresponding contribution". As the prompt suggests, the contribution should be deleted in this case.
Make sure that the Withdraw button is disabled with a tooltip suggesting to contact the managers after the abstract reached the 'accepted' state and not visible at all if it reached any other final state.

**Comment by pferreir** [comment]
> will delete it's corresponding contribution

"its"

**Comment by ThiefMaster** [comment]
Fixed in devel.
