### ISSUE TITLE
Show fraction of registrations/capacity in conference page and improve action-box

### ISSUE THREAD

**Issue by nop33** [indico/indico#2830]
### Display number of registrations
It would be useful for the users planning to register to an event to know how many available positions are left. This could fit in the registration action box in the overview page of the conference as well as in the table of the "Available forms" page. An idea is the following one:
![image](https://cloud.githubusercontent.com/assets/1579899/22786339/6125f010-eed8-11e6-8688-569a819be836.png)

### Improve registration action box when there are multiple available forms.

In the following example there are more than one registration forms but because the user registered in one of them, the main conference page has the following action-box:
![image](https://cloud.githubusercontent.com/assets/1579899/22785769/f1acf6cc-eed5-11e6-87e2-78b8d26adee6.png) but clicking on the "See detals" button we arrive at the "Available forms" page.
![image](https://cloud.githubusercontent.com/assets/1579899/22785950/ad919fc8-eed6-11e6-8374-6cf71e038fed.png)
Something like "You have registered for this event, but there are more available registration forms" would have been more suitable in this case.
Also, taking the example above, if the "Moderated" registration form gets closed, the conference page still displays the same action-box as above, but when clicking "See details" you end up in the registration form page in order to submit a registration for the "Not moderated" registration form.

**Comment by nop33** [comment]
Change request: `CHG34569`

**Comment by ThiefMaster** [comment]
This would have to be configurable for sure, not every event wants to expose this information.

**Comment by meluru** [comment]
Should we consider forms that user registered to but they are closed now? Right now when the user has registered but the registration form is not active we don't show any information on the main page.

**Comment by ThiefMaster** [comment]
I would only show it when the button is still active. I think it's not really interesting otherwise..
