### ISSUE TITLE
vidyo: add button to join via vidyowebrtc

### ISSUE THREAD

**Issue by sbinet** [indico/indico#2834]
The desktop version of vidyo on some linux distributions isn't great.

But the webrtc version is fantastic: vidyowebrtc.web.cern.ch

it would be great if one could add a direct link to it, with the vidyo room key pre-filled.

**Comment by pferreir** [comment]
Implemented in indico/indico-plugins#44

**Comment by sbinet** [comment]
hum... there is no commit in that PR indico/indico-plugins#44.

**Comment by ThiefMaster** [comment]
strange. either way, it has been merged. (but it's not active in production yet)
