### ISSUE TITLE
Problem with SSO

### ISSUE THREAD

**Issue by mtorrisi** [indico/indico#2854]
Hello to everyone,

I'm now struggling with another problem with SSO. I installed and configured libapache2-mod-shib2. What happens now is that when I try to login, clicking on `Login with Single SignOn` I can select the Identity Provider, then after I input my credentials I get:
![image](https://cloud.githubusercontent.com/assets/6388887/23369588/29eb5c00-fd12-11e6-82b7-d57498d081a3.png)

If try to login again, after clicking on `Login with Single SignOn` I'm in. So I think the sign in process works.

Do you have any suggestion in what can I check in my configuration?

Thanks in advance.

**Comment by ThiefMaster** [comment]
In 1.9.x/2.0 the authentication system has been rewritten and - if something fails - the errors should be much clearer. If you still need help with using SSO on 1.2, I recommend you to use the [project-indico-administrators](https://simba3.web.cern.ch/simba3/SelfSubscription.aspx?userHasAccount=false&groupName=project-indico-administrators) mailing list.
