### ISSUE TITLE
Problem with PayPal E-Payment plugin - IPN stripping additional parameters from URL

### ISSUE THREAD

**Issue by pmac2193** [indico/indico#2876]
Hi,

we are using Indico 1.2.1rc2 and now we have encoutered problems with IPN - everything worked fine on March 3:

[03/Mar/2017:13:04:19 +0100] "POST /indico/payment?EPaymentName=PayPal&requestTag=params&registrantId=XY&confId=ABCD HTTP/1.1" 200

but started to fail and never returned to success on March 9:

[09/Mar/2017:13:58:45 +0100] "POST /indico/payment?EPaymentName=PayPal HTTP/1.1" 500

(we have no attempts between these two and the 500 is courtesy of skipjack module, not paypal, but the problem is visible - no additional parameters after the first &).

I have found other reports of this problem on stackoverflow:

http://stackoverflow.com/questions/42726992/paypal-ipn-works-not-as-expected/42739322#42739322

http://stackoverflow.com/questions/42669566/querystring-values-removed-from-the-ipn-endpoint-by-paypal

the solution could be in urlencondig or maybe the simple replacing `&` -> `&amp;` for 3 url strings in getFormHTML() in file ./MaKaC/plugins/EPayment/payPal/epayment.py, but I am just the admin of underlying linux, I don't have indico or paypal sandbox to test it.

Is there a chance it will be fixed? I have checked the last 1.2.2rc1 and the code for this plugin is same as in our 1.2.1rc2.

Thanks.

**Comment by ThiefMaster** [comment]
This sound a bit like a bug on PayPal's side to me. A value in a form field should not need to be HTML-encoded (or URL-encoded manually). While our HTML might not be completely valid without using `&amp;` there, browsers handle this fine so the correct URL is submitted to PayPal nonetheless.

Especially considering that one of the SO links you posted mention that only *some* PayPal servers truncate at `&` it sounds very much like an issue on their side...

**Comment by pmac2193** [comment]
Ok, can you please remind PayPal and get them to fix it? Thank you.

**Comment by ThiefMaster** [comment]
most likely fixed in 2.x since we don't include weird querystring params anymore
