### ISSUE TITLE
is there no language pack for asian??

### ISSUE THREAD

**Issue by Sang-Yong** [indico/indico#2878]
Hi, 
Actually to be more capaptablilty... I think indico hompage should support multi language for foreigner.

When I have my own indico main page with no login, on the right-top side of the indico homepage, there are selection options for users. (Timezone / language / username)

In the case of  language option, there are only 3 option. (espanol / english / francais) 

How to set additional languages for asian people?

![image](https://cloud.githubusercontent.com/assets/22361479/23980163/760f3552-0a41-11e7-818f-bd05d3ab223c.png)

**Comment by ThiefMaster** [comment]
Someone would have to translate all strings (thousands!) in Indico to the language they'd want to use. We currently do not have any translations except (partial) french/spanish ones.

You can request the language you need here: https://www.transifex.com/indico/indico/
However, chances are low that there will be such a translation anytime soon unless someone external is willing to contribute one.

**Comment by pferreir** [comment]
@Sang-Yong, the languages that are currently available are English and French (because those are CERN's official languages) and Spanish, since we have a very active community of Spanish-speaking users who regularly contribute translations back to the project.
If we can find a group of people willing to help in any asian (or otherwise) language, we will be glad to help them get started.

**Comment by pferreir** [comment]
@Sang-Yong, I saw you just registered on Transifex and requested to be added to a translation team. Can you please contact us at `indico-team AT cern.ch` so that we can give you a few tips on getting started?
Thanks!

**Comment by Sang-Yong** [comment]
Yes. I think I can help to translate it, but  I dont know how to join it. 
I already requested to be added to a translation team, but there are no answers.
what can I do?
