### ISSUE TITLE
class eventHeaderButtonBar

### ISSUE THREAD

**Issue by luisorellana1234** [indico/indico#2879]
Hello good afternoon I have to change a non visible for those who have not registered in the events that anything of the event classHeaderButtonBar where to modify so does not break the code. regards

Forgive my English.

![image](https://cloud.githubusercontent.com/assets/16797639/23995142/8efca8d6-0a48-11e7-8b2e-0d9871f58d0b.png)

**Comment by ThiefMaster** [comment]
You could use custom CSS but there's no way of making this conditional 
(whether the used is registered or not).
