### ISSUE TITLE
Show review state in abstract list

### ISSUE THREAD

**Issue by ThiefMaster** [indico/indico#2880]
Currently the state is just "Submitted" and there is no way of seeing whether the abstract is completely new, under review or has already been reviewed in all its tracks from the abstract list without going to each abstract's timeline.

**Comment by DavidAndreev** [comment]
Does this mean using `abstract.public_state` instead of normal 'abstract.state' ? In AbstractPublicState we have case of 'awaiting' - like a new abstract and 'under review', so should I add a case for already reviewed on all tracks there ?
