### ISSUE TITLE
how to migrate postgresql db to another pg server?

### ISSUE THREAD

**Issue by infinet** [indico/indico#2907]
We are trying to migragte 1.9.6 to another machine.  pg_dumpall then psql -f xxx.dump doesn't seem to import all data. Run " indico db prepare" then psql -f xxx.dump, then database still incomplete.

**Comment by pferreir** [comment]
We normally use `pg_dump` + `pg_restore`. It should work fine. You **should
not** run `indico db prepare` If you're restoring a dump of an existing
database.

**Comment by pferreir** [comment]
We normally use `pg_dump` + `pg_restore`. It should work fine. You **should
not** run `indico db prepare` If you're restoring a dump of an existing
database.

**Comment by infinet** [comment]
for example, when open event page:
Exception type: 	<class 'sqlalchemy.exc.ProgrammingError'>
Exception message: 	(psycopg2.ProgrammingError) relation "event_registration.forms" does not exist LINE 2.........

That SQL in essence is " select something from event_registration.forms", event_registration.forms does not exist, except if I start with a fresh postgresql installation, run "indico db prepare" first, "psql -f " next. But then comes another problem, the table is there, however, it is empty.

**Comment by infinet** [comment]
Strange, the schema "event_registration" does not exist in the old indico 1.9.6 installation:

```postgres=# \dn
     List of schemas
     Name      |  Owner   
---------------+----------
 attachments   | postgres
 categories    | postgres
 event_surveys | postgres
 events        | postgres
 indico        | postgres
 oauth         | postgres
 public        | postgres
 roombooking   | postgres
 users         | postgres
(9 rows)
```
But the newly installed indico 1.9.6 requires it. ` indico db prepare` creates this schema:
> INFO  [sqlalchemy.engine.base.Engine] CREATE SCHEMA event_registration
