### ISSUE TITLE
RuntimeWarning: You have iterated over the result of pkg_resources.parse_version

### ISSUE THREAD

**Issue by luqeckr** [indico/indico#2920]
this is the error when i try to open http://localhost/indico

> [Mon May 01 02:37:06.770370 2017] [:error] [pid 958:tid 140376230037248] /usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py:183: RuntimeWarning: You have iterated over the result of pkg_resources.parse_version. This is a legacy behavior which is inconsistent with the new version class introduced in setuptools 8.0. In most cases, conversion to a tuple is unnecessary. For comparison of versions, sort the Version instances directly. If you have another use case requiring the tuple, please file a bug with the setuptools project describing that need.  
[Mon May 01 02:37:06.770428 2017] [:error] [pid 958:tid 140376230037248]   stacklevel=1,

i'm using ubuntu 14.04

**Comment by ThiefMaster** [comment]
That's not an error you can safely ignore it.

**Comment by luqeckr** [comment]
well, the page doesn't load though...
what did i miss is that i always focus on apache error log, i just realize
there is log files on /opt/indico/log which solve my problem
the real problem reside in /opt/indico/log/other.log
------------
2017-05-01 08:39:07,529  WARNING  000000000000  ZEO.zrpc                  (962) CW: error connecting to ('::1', 9675): ECONNREFUSED
2017-05-01 08:39:07,532  WARNING  000000000000  ZEO.zrpc                  (962) CW: error connecting to ('::1', 9675): ECONNREFUSED
------------
it means the zodb is not running yet... my fault..

thanks for the clue..
