### ISSUE TITLE
How to migrate database from 1.9.6 to 1.9.9

### ISSUE THREAD

**Issue by sacredfire666** [indico/indico#2936]
Hi, everyone, I update indico from 1.9.6 to 1.9.9, it almost succeed, but when I enter my indico website, it gives an error 
`relation "categories.categories" does not exist `
I think I should migrate the SQLAlchemy DB. How to do that? Use 
`indico db migrate `
or something else? Thanks.

**Comment by ThiefMaster** [comment]
it's `indico db upgrade` (`indico db migrate` is for developers to generate a new revision) - and unless your Indico is empty (no events!) you need to go step by step (ie to 1.9.7, 1.9.8, 1.9.9, 1.9.10) and run the zodbimport scripts that come with each version. sometimes you also need to do partial upgrades (`indico db upgrade <somerevision>`) between the zodb importers.

**Comment by ThiefMaster** [comment]
Maybe these (old) gists help you a bit:

* https://gist.github.com/ThiefMaster/d22df5467d42f6cf795ce1669a93ecf8
* https://gist.github.com/ThiefMaster/bec66c275352d4a81311f872fdd5267e

**Comment by sacredfire666** [comment]
Thanks for your reply. I will have a try.

**Comment by sacredfire666** [comment]
I try to use `indico db upgrade` and it seems like 
`NFO  [alembic.migration] Running upgrade 98f411f40bb -> 134a1c372738, Add currency to registration`
but I get an error
```
sqlalchemy.exc.IntegrityError: (psycopg2.IntegrityError) column "currency" contains null values
 [SQL: 'ALTER TABLE event_registration.forms ALTER COLUMN currency SET NOT NULL']
```
Should I do something first?

**Comment by sacredfire666** [comment]
Actually I came across the same problem https://github.com/indico/indico/issues/2209
First I try to update my indico, but the upgrade of database seems a hard work.
Maybe I can modify indico/modules/events/registration/util.py manually,  and where  is `....../data/cache/*.js` I should delete？ I tried to delete `/opt/indico/cache` , but it doesn't work.

**Comment by ThiefMaster** [comment]
Likely obsolete; if not, migration issues are something for https://talk.getindico.io
