### ISSUE TITLE
PDF files - regenerate them if source file is updated

### ISSUE THREAD

**Issue by pferreir** [indico/indico#294]
``` yaml
# Ticket imported from Trac
```

From [indico:87165]:

''Some of the organizers of "Chamonix 2010" complained about the fact that Indico only generates a PDF once, and doesn't replace it with a new version when a new source file is uploaded.
''

We should study a way of doing this in a safe way (without replacing files that were added by the user).

**Comment by ThiefMaster** [comment]
we don't cache PDFs (anymore?)
