### ISSUE TITLE
Cannot set "Short Display URL" because of "short url tag" conflict error

### ISSUE THREAD

**Issue by micheal-cooper** [indico/indico#2940]
When I try to set the 
General Settings > Short display URL
to anything, for example "test", a dialog box appears which reads, 
"Short URL tag conflicts with an URL used by Indico: 'test'. Please select another one."

This happens regardless of which URL I try to set.

Version:
"The version of this Indico installation is: 1.2.1rc2"

**Comment by ThiefMaster** [comment]
Do you run indico in a subdirectory by any chance (`https://yourhost/indico/...`)?

**Comment by micheal-cooper** [comment]
Yes, it follows the patter
https://sub.domain.jp/indico

Do we have to move the installation to just 
https://sub.domain.jp/
?

**Comment by ThiefMaster** [comment]
it's clearly a bug but if it's a very new installation I'd highly recommend to get rid of the `/indico` part.

as a workaround you could also comment out the check (just search for a part of the error message in the code)

**Comment by micheal-cooper** [comment]
Thank you very much. We have only used it for two events so far, and we used a forward in apache to fix the URL, so we should be able to get rid of the subdirectory.

Thank you.
