### ISSUE TITLE
Registrations export - ordering inconsistent

### ISSUE THREAD

**Issue by SebastianLopienski** [indico/indico#2954]
When I export registrations to a PDF book, and to Excel format, I get different (random?) ordering for two people with the same last name. (Event ID 581756, see the four last names starting with "ku".)

**Comment by ThiefMaster** [comment]
I cannot confirm this. We use the criteria below for all actions in the reglist and when I exported these four registrants to PDF and XLSX I got the exact same order.

    `db.func.lower(cls.last_name), db.func.lower(cls.first_name), cls.friendly_id`

**Comment by SebastianLopienski** [comment]
I don't seem to be able to reproduce it... So let's close the case, and if I observe it again (in a reproducible way), then I'll report again / reopen this issue.
