### ISSUE TITLE
indico setup fails, lots of stuff missing from the instructions, error 500 on webroot after setup

### ISSUE THREAD

**Issue by sylvainfaivre** [indico/indico#2972]
Hi,

I'm trying to setup Indico on Ubuntu 17.04.
I tried first with `easy_install` and it failed, then I found a bug report that said the preferred method is now to use `pip`, so I used `pip` along with the instructions at http://indico.readthedocs.io/en/latest/installation/production/
In part 6, there is no `indico` binary to launch the command `indico setup wizard` so I tried with `./.venv/bin/indico_initial_setup`

It failed with the error : 
```
(.venv) indico@sylvain-pc:~$ ./.venv/bin/indico_initial_setup
* EGG found at /opt/indico/.venv/lib/python2.7/site-packages... unconfigured
No previous installation of Indico was found.
Please specify a directory prefix:
[/opt/indico]: 

You now need to configure Indico, by editing indico.conf or letting us do it for you.
At this point you can:

    [c]opy the default values in etc/indico.conf.sample to a new etc/indico.conf
    and continue the installation

    [A]bort the installation in order to inspect etc/indico.conf.sample
    and / or to make your own etc/indico.conf

What do you want to do [c/a]? c
Traceback (most recent call last):
  File "./.venv/bin/indico_initial_setup", line 11, in <module>
    sys.exit(main())
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/MaKaC/consoleScripts/indicoInitialSetup.py", line 90, in main
    targetDirs = indico_pre_install('/opt/indico', False, existingConfig=existingPath)
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/MaKaC/consoleScripts/installBase.py", line 415, in indico_pre_install
    return fresh_install(defaultPrefix)
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/MaKaC/consoleScripts/installBase.py", line 450, in fresh_install
    shutil.copy(PWD_INDICO_CONF + '.sample', indicoconfpath)
  File "/usr/lib/python2.7/shutil.py", line 119, in copy
    copyfile(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/opt/indico/.venv/local/lib/python2.7/site-packages/etc/indico.conf.sample'
```

So I copied the file there with these commands : 
```
(.venv) indico@sylvain-pc:~$ mkdir -p /opt/indico/.venv/local/lib/python2.7/site-packages/etc/
(.venv) indico@sylvain-pc:~$ cp ./.venv/etc/indico.conf.sample /opt/indico/.venv/local/lib/python2.7/site-packages/etc/
```

Launched the setup again, now it failed with : 
```
(.venv) indico@sylvain-pc:~$ ./.venv/bin/indico_initial_setup* EGG found at /opt/indico/.venv/lib/python2.7/site-packages... unconfigured
No previous installation of Indico was found.
Please specify a directory prefix:
[/opt/indico]: 

You now need to configure Indico, by editing indico.conf or letting us do it for you.
At this point you can:

    [c]opy the default values in etc/indico.conf.sample to a new etc/indico.conf
    and continue the installation

    [A]bort the installation in order to inspect etc/indico.conf.sample
    and / or to make your own etc/indico.conf

What do you want to do [c/a]? c
Copying Indico tree... 
/opt/indico/.venv/local/lib/python2.7/site-packages/MaKaC/consoleScripts/../../bin -> /opt/indico/bin
/opt/indico/.venv/local/lib/python2.7/site-packages/MaKaC/consoleScripts/../../doc -> /opt/indico/doc
/opt/indico/.venv/local/lib/python2.7/site-packages/MaKaC/consoleScripts/../../etc -> /opt/indico/etc
/opt/indico/.venv/local/lib/python2.7/site-packages/MaKaC/consoleScripts/../../htdocs -> /opt/indico/htdocs
Creating wsgi symlink... /opt/indico/htdocs/indico.wsgi
done!
Creating directories for resources...  done!
Upgrading indico.conf... done!
Traceback (most recent call last):
  File "./.venv/bin/indico_initial_setup", line 11, in <module>
    sys.exit(main())
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/MaKaC/consoleScripts/indicoInitialSetup.py", line 114, in main
    gid = wwwGid)
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/MaKaC/consoleScripts/installBase.py", line 503, in indico_post_install
    shutil.copy('%s.sample' % f, f)
  File "/usr/lib/python2.7/shutil.py", line 119, in copy
    copyfile(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/opt/indico/etc/zdctl.conf.sample'
```

Copied that file too : 
`(.venv) indico@sylvain-pc:~$ cp ./.venv/etc/zdctl.conf.sample /opt/indico/etc/zdctl.conf.sample`

Had to copy the files `zodb.conf.sample` and `logging.conf.sample` as I got errors for these too.

Then I also had to give sudo rights to the indico user, and finally was able to complete the installation.

The setup then displays : 
```
For information on how to configure Apache HTTPD, take a look at:
http://indico.readthedocs.org/en/latest/installation/#configuring-the-web-server
```
but there's nothing there for Apache, there is only information about nginx setup.

At the end of part 6, I also had to create the `assets` and `web` folders, as they were not created by the setup.

Finally after starting the services ang browsing to the web root, I got an error 500.

`/opt/indico/log/nginx/access.log` shows : 
`127.0.0.1 - - [16/Jun/2017:10:33:26 +0200] "GET / HTTP/2.0" 500 21 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:54.0) Gecko/20100101 Firefox/54.0"`

`error.log` is empty.

I don't know what to do now...
The `db` folder is empty, is that ok ? I think somewhere along the setup it created a db, but I'm not sure. I couldn't find an equivalent to the `indico db prepare` command specified in the docs.

**Comment by pferreir** [comment]
The instructions you've found relate to version 2.0. You seem to be installing 1.2.x.
I believe the problem is that we haven't yet uploaded a proper 2.0 dev package to PyPI.

**Comment by pferreir** [comment]
OK, I've uploaded the dev package, which means that you can follow the instructions, using:
```
$ pip install indico==1.9.2-dev3
```

The rest of the instructions should work fine.

**Comment by sylvainfaivre** [comment]
This works alright. Just a head's up to whoever may find this, the release number is 1.9.11.dev3.
So use `pip install indico==1.9.11.dev3`

**Comment by pferreir** [comment]
> This works alright. Just a head's up to whoever may find this, the release number is 1.9.11.dev3.
So use pip install indico==1.9.11.dev3

Fixed my comment. Somehow the version of pip I have was smart enough to figure that out.
