### ISSUE TITLE
export indico event reference into calendaring tools

### ISSUE THREAD

**Issue by mariadimou** [indico/indico#3014]
Hi! This is a question:
When synchronising (not downloading) an indico event with a preferred calendar (e.g. the one for Macs) and then change the event in indico (date or title) the change is not reflected in the calendar. Is this an expected behaviour? Example: https://indico.cern.ch/export/event/654666.ics
We made a video about this functionality, so we need to know if this is correct.
Thank you!
Maria

**Comment by ThiefMaster** [comment]
That completely depends on how the calendar application works. If you download a calendar file it won't update, but if you put the URL the calendar application could reload it from time to time. I don't know whether the calendar app on OSX does it or not.

BTW, the GitHub issue tracker is not the best place for questions like this - the Indico channel on CERN mattermost or the #indico IRC channel on freenode would be better places.
