### ISSUE TITLE
Use configurable site title in <title>-

### ISSUE THREAD

**Issue by ThiefMaster** [indico/indico#3018]
We have the setting and currently it's used only in opengraph metadata for events... It would probably make sense to use it in the `<title>` too.

**Comment by nop33** [comment]
Which setting are you referring to?

**Comment by ThiefMaster** [comment]
https://github.com/indico/indico/blob/master/indico/modules/core/settings.py#L23

and it'd probably make sense to use it like this in the page title too: https://github.com/indico/indico/blob/master/indico/web/templates/indico_base.html#L13
