### ISSUE TITLE
Document indico.conf options (RTD docs)

### ISSUE THREAD

**Issue by ThiefMaster** [indico/indico#3024]
Most of the documentation can be taken from indico.conf.sample, but some config options might not be in there even though they could be set (check `default_values` in the `Config` class). Things user pretty much never need/want to change could probably be omitted.

**Comment by pferreir** [comment]
Can't we just present this as a nicely highlighted version of indico.conf.sample?

**Comment by ThiefMaster** [comment]
That would also work, but isn't a rst table nicer? Especially for things that need much more verbosity, such as auth config.

indico.conf.sample could completely go away then - except when you do a non-wizard setup it's not copied/used anymore anyway

**Comment by pferreir** [comment]
I meant something like this: https://webpack.js.org/configuration/#options

**Comment by ThiefMaster** [comment]
Config docs added in 0bc1036e5 - https://docs.getindico.io/en/latest/config/settings/
