### ISSUE TITLE
Payment-Plugin-Options-Overlay not displayed correctly

### ISSUE THREAD

**Issue by Problemkerze** [indico/indico#3032]
Opening the Plugin settings of any Payment Plugin via Administration > Payment reloads an overlay which is draggable but thanks to its fixed with of 320 px it's completely useless.

Workaround: Open the plugin in the background (e.g. middle mouse button) or open it via Administration > Plugins.

Preferred solution: Just open the settings as in Administration > Plugins.

![indico_plugin_popup](https://user-images.githubusercontent.com/30109884/28662200-98ab4318-72b9-11e7-98bd-53d1254aa2e2.PNG)

**Comment by ThiefMaster** [comment]
This is already fixed (37359e03d), just not in a release. For now, open the link in a new tab or from the 'Plugins' page.
