### ISSUE TITLE
Make local groups category-bound

### ISSUE THREAD

**Issue by pferreir** [indico/indico#3040]
This would imply allowing category managers to manage their own groups of users. Current global groups could be tied to the Home category.

There probably should be a switch to disable this server-wide, as to force people to use LDAP groups (e.g. e-groups at CERN).

**Comment by ThiefMaster** [comment]
> There probably should be a switch to disable this server-wide, as to force people to use LDAP groups (e.g. e-groups at CERN).

Maybe a `LOCAL_GROUPS` setting that completely disables local groups (not only making them admin-only like right now), i.e. the group equivalent of `LOCAL_IDENTITIES`?

**Comment by pferreir** [comment]
Yeah, that makes sense to me.

**Comment by ThiefMaster** [comment]
Decided to have "category roles" as a separate principal type and keeping local groups as they are. #4271 tracks adding the category roles.
