### ISSUE TITLE
contributions get shown multiple times if event timezone and display timezone cause day breaks within session

### ISSUE THREAD

**Issue by pseyfert** [indico/indico#3048]
When looking at the [all-days detailed agenda of acat 2017](https://indico.cern.ch/event/567550/timetable/#all.detailed) and set the display timezone to CEST, those contributions which are on the second last day in CEST and the local time zone (i.e. the first contributions on thursday, which still take place on european thursday) get displayed twice - a second time at late european friday. see this [screen cast](http://pseyfert.web.cern.ch/pseyfert/ACAT_daybreak.mp4.webm).
Those contributions get shown only once when picking the local timezone as display timezone.

**Comment by ThiefMaster** [comment]
Possibly the same as #3073

**Comment by pseyfert** [comment]
closing all my cern related issues as won't-pursue-anymore / don't care anymore - regardless of status

**Comment by ThiefMaster** [comment]
I think this may still be relevant for a future timetable rewrite (as a case to keep in mind) so I think it should stay open...

**Comment by pseyfert** [comment]
feel free to reopen such that it doesn't show up in the issues list of my account

**Comment by pferreir** [comment]
@pseyfert you can unsubscribe from notifications for this issue. Would that not be enough?
