### ISSUE TITLE
format_pretty_date return bad french string for today

### ISSUE THREAD

**Issue by rouet** [indico/indico#3050]
Hi apparently format_pretty_date has a bug in french locale.

"Today" should be "Aujourd'hui" and not "Aujourd112017i", see the screen capture of a news.

![capture d ecran 2017-08-29 a 11 54 22](https://user-images.githubusercontent.com/6275566/29815521-32d0cbaa-8cb1-11e7-9009-c9bf46e509aa.png)

I'm not python fluent, so i can't easily propose a fix.

**Comment by ThiefMaster** [comment]
Thanks, also fixed in Transifex now.

**Comment by ThiefMaster** [comment]
In case you need to patch this locally: `'Aujourd'hui` needs to be replaced with `'Aujourd''hui` (double single quote to escape it, otherwise anything after the single quote becomes a date/time format identifier instead of a literal string)
