### ISSUE TITLE
iCal UID is _not unique_

### ISSUE THREAD

**Issue by DirkHoffmann** [indico/indico#3054]
The use of the UID attribute in ical/ics exports is not unique amongst different instances (servers, installations) of Indico. The presently used schema is `indico-event-1234@cern.ch`, whereas it should be `indico-event-1234@mysite` on my site and `indico-event-1234@cern.ch` only on CERN site.
The UID is apparently constructed in two places:
https://github.com/indico/indico/blob/89052368a503f3cf8a68a17126756905d034a22b/indico/web/http_api/metadata/ical.py#L56 
https://github.com/indico/indico/blob/89052368a503f3cf8a68a17126756905d034a22b/indico/modules/categories/serialize.py#L86
This redundancy should probably be removed, as it could easily be forgotten in case of future updates. So I am afraid I am not insider enough to decide what exactly should be done.

**Comment by ThiefMaster** [comment]
Are there any calendaring tools where calendar uids are compared across calendars/sources (ics files etc)? Either way, I agree that `@cern.ch` should not be there. Using the host name of the instance is probably the best option.

**Comment by DirkHoffmann** [comment]
On Sep 3, Adrian wrote:

> Are there any calendaring tools where calendar uids are compared across calendars/sources (ics files etc)?

Zimbra is an example.

Any extraction from Indico should be based on it, unless you want to erase 
systematically all events and recreate them (as Google seems to do).

> Either way, I agree that @cern.ch should not be there. Using the host name of the instance is probably the
> best option.

Yes.
