### ISSUE TITLE
Reminders: Date format not accepted when  re-editing the time

### ISSUE THREAD

**Issue by bpedersen2** [indico/indico#3058]
1) Create a reminder
2) later, revisit it and edit the time (not the date)
3) try to save: Wrong date, possibly causing an date is in the past error.

Date formatting after intial editing:  d/m/yyyy
![screenshot-indico frm2 tum de 2017-09-08 08-29-36](https://user-images.githubusercontent.com/5336494/30198810-17475c66-9470-11e7-8ed2-2e09add0b5e5.png)

Date formatting during re-edit: yyyy/m/d
![screenshot-indico frm2 tum de 2017-09-08 08-30-17](https://user-images.githubusercontent.com/5336494/30198811-17480f8a-9470-11e7-9e06-5ba4f6334a16.png)

While  it can be fixed  byalways touching the date as well, it is a bit annoying and may lead to wrong dates.

**Comment by mvidalgarcia** [comment]
@bpedersen2 I can't reproduce your problem. It's true that, as shown in your screenshots, the date format changes but it works anyway. What OS and browser are you using?

**Comment by bpedersen2** [comment]
This was done with Firefox ESR 45.9.0 on a Linux system.

I tested it with Chromium on Linux as well: The same behavior (with todays date, the reminder date changed to december...

**Comment by bpedersen2** [comment]
for the second line, my field description  was wrong: it is interpreted as:
 yyyy-dd-mm, 
but the value is 
 yyyyy-oldm-oldday

**Comment by ThiefMaster** [comment]
We managed to reproduce it in the meantime (the error did not show up because december isn't in the past, but it did screw up the date - which is actually worse than an error). Anyway, there will be a fix for it soon!
