### ISSUE TITLE
Cannot create users with non-ascii characters

### ISSUE THREAD

**Issue by poikilotherm** [indico/indico#3070]
While trying out SSO Login with a user that has no account, the registration fails due to a non-ascii character in his last name ("ü").

Please see attached error log: [error-indico-umlaut.txt](https://github.com/indico/indico/files/1306892/error-indico-umlaut.txt)

This is a great blocker, please fix ASAP...

**Comment by ThiefMaster** [comment]
I wonder if shibboleth provides a bytestring instead of unicode. Should be easy to fix, Could you try editing this file (inside your python virtualenv)?

https://github.com/indico/flask-multipass/blob/master/flask_multipass/providers/shibboleth.py#L49

Replace 

    attributes = {k: v for k, v in iteritems(request.environ) if k.startswith(self.settings['attrs_prefix'])}

with

    attributes = {k: (v if isinstance(v, unicode) else v.decode('utf-8')) for k, v in iteritems(request.environ) if k.startswith(self.settings['attrs_prefix'])}

**Comment by poikilotherm** [comment]
Bingo! Applying the patch helped. I shall mention that I am not using mod_shib, but mod_auth_mellon. Currently I don't have a possibility to check with mod_shib...

Shall I create an issue at indico/multipass?

Thanks!

**Comment by ThiefMaster** [comment]
I don't think that's needed (but feel free to do so if you want) - I'll commit the fix and release an updated version later.

**Comment by ThiefMaster** [comment]
Flask-Multipass-0.0.dev7 is on PyPI now.
