### ISSUE TITLE
Logout incorrect URL

### ISSUE THREAD

**Issue by sdspacecowboy** [indico/indico#3072]
When I logout of indico I get set to a url that omits the BASE_URL
i.e. 
domain.com/*
instead of
domain.com/BASE_URL/*

**Comment by ThiefMaster** [comment]
which version are you running?

**Comment by sdspacecowboy** [comment]
indico==2.0.dev0

**Comment by sdspacecowboy** [comment]
Also happening on Login. Basically anything dealing with flask multipass omits the BASE_URL

**Comment by ThiefMaster** [comment]
This is strange.. according to the code for logout it should work just fine:

    return multipass.logout(request.args.get('next') or url_for_index(), clear_session=True)

So you are either sent back to the 'next' URL or the indico home page, which does take the base url into account.

**Comment by ThiefMaster** [comment]
@sdspacecowboy, are you using local indico accounts or SSO/OAuth?

**Comment by ThiefMaster** [comment]
Nevermind, found the problem. Our `relative_url` property does not include it so the `next` URL is wrong.

**Comment by sdspacecowboy** [comment]
Many thanks
