### ISSUE TITLE
Session block adjustment: incorrect message wording

### ISSUE THREAD

**Issue by jouvin** [indico/indico#3080]
When ajusting a session block start/end time based on the session block contents, the message incorrectly says that the *session* start/end time will be adjusted instead of the *session block*. Also the expected session block name displayed is the session name (consistent with the wrong wording!) where it should be `session:block`. And there is also a missing space after the session (block) name.

This is confusing but probably easy to fix!

**Comment by ThiefMaster** [comment]
hi, thanks for reporting it. just a small suggestion: in issues related to a message it's good to include that message - that way we can quickly search for it in the codebase ;)

**Comment by ThiefMaster** [comment]
I guess you mean the message in the "fit to content" dialog?

**Comment by jouvin** [comment]
@ThiefMaster sorry, the problem is that I have the French version of the interface, I should configure my browser to run the English one! But yes, this is the "fit to content" message displayed after you click on the "Fit to content" button.

**Comment by mvidalgarcia** [comment]
> And there is also a missing space after the session (block) name.

I can't find it, where do you mean exactly?
