### ISSUE TITLE
Instructions for custom assets 

### ISSUE THREAD

**Issue by sdspacecowboy** [indico/indico#3097]
Can you explain how to get custom html templates, js, css to work? I tried the following in indico.conf but nothing happened:
`CUSTOMIZATION_DIR = '/opt/indico/custom'`

I put my css and js in subdirectories in /custom/

**Comment by ThiefMaster** [comment]
Did you check the guide here (especially which subdirectories you need to create)? https://github.com/indico/indico/blob/master/indico/indico.conf.sample#L374-L401

Also, we can only guess without seeing the structure within your `/opt/indico/custom` folder.

**Comment by pferreir** [comment]
@meluru's [presentation](https://indico.cern.ch/event/614422/contributions/2703408/) at the Indico Workshop 2.0 may be of help:

**Comment by sdspacecowboy** [comment]
@ThiefMaster Yes. Still haven't been able to get it to work =/

My file structure is:
/opt/indico/custom/js/hello.js //hello.js prints hello to the console on everypage

@pferreir Will this work for indico version 1.9.11.dev15?

**Comment by ThiefMaster** [comment]
It'd be easier for us to help you if you published your customization dir in a git repo so we can see what you have there and also explained what exactly you want to customize.

Also, it's not clear from your comment (is "prints hello to the console on everypage" what it does or what it *should* do?) whether your hello.js runs or not.

In any case, did you reload indico after editing the config file? You in development mode (`indico run ...`) it usually happens automatically, in production you need to `touch ~/web/indico.wsgi` or restart uwsgi.

**Comment by dkfz2018** [comment]
hi have the same problem

created a folder structure like : /opt/indico/indico-theme/scss/ ( CUSTOMIZATION_DIR = '/opt/indico/indico-theme/' )
and placed a file the file collaboration.sccs with the content:
```
@import 'base/palette';

div.page.header {
        background-color: $yellow !important;

        .toolbar.global-menu {
                background: #cc6005 !important;
                border-color: #ffffff !important;
        }
```

inside but the color stay the same at indico.dkfz.de

Whats my problem ?

**Comment by ThiefMaster** [comment]
@dkfz2018 Your custom stylesheet is loaded:

https://indico.dkfz.de/static/assets/core/sass/custom_sass_1695e4b8.css

So if it doesn't apply, maybe some of the classes are wrong? Use your browser's developer tools to see if the rules are applied at all or maybe overwritten by another rule that's also marked as !important

**Comment by dkfz2018** [comment]
Hey thanks for the feedback,
i reinstalled indidco and make a fresh start. In the fresh instalaltion it works like expected, maybe a problem was still there from the import of the 1.2 version.

Only the problem with the logo still exist, it won´t load:
CUSTOMIZATION_DIR = '/opt/indico/dkfzdesign'
LOGO_URL = '/static/custom/dkfz_logo_hauptseite.png'

**Comment by ThiefMaster** [comment]
It looks like you have a literal `$CUSTOMIZATION_DIR` in your `LOGO_URL`. Remove that.

Then, once you put the file `dkfz_logo_hauptseite.png` in `/opt/indico/dkfzdesign/static/`, it should work.

**Comment by ThiefMaster** [comment]
can you paste the output of this command?

    ls -al /opt/indico/dkfzdesign/ /opt/indico/dkfzdesign/*

**Comment by dkfz2018** [comment]
/opt/indico/dkfzdesign/static:
total 28
drwxr-xr-x. 3 indico apache  4096 Feb 21 10:22 .
drwxr-xr-x. 4 indico apache  4096 Feb 21 09:14 ..
drwxr-xr-x. 2 indico apache  4096 Feb 21 10:22 custom
-rw-rw----. 1 indico apache 12381 Feb 21 09:02 dkfz_logo_hauptseite.png

LOGO_URL = '/static/dkfz_logo_hauptseite.png'
CUSTOMIZATION_DIR = '/opt/indico/dkfzdesign'

**Comment by ThiefMaster** [comment]
https://indico.dkfz.de/static/custom/dkfz_logo_hauptseite.png currently works, so you need this:

    LOGO_URL = '/static/custom/dkfz_logo_hauptseite.png'

(`/static/custom/` is mapped to `/opt/indico/dkfzdesign/static/`)

**Comment by dkfz2018** [comment]
thx for the help it was not clear for me. This post can be closed.

**Comment by ThiefMaster** [comment]
Well the original issue was by @sdspacecowboy but considering how old this issue is I think we can indeed close it. Generally, usage/administration question (unless it's clearly a bug or feature request) fit much better in our new forum anyway: https://talk.getindico.io/
