### ISSUE TITLE
[Brainstorm] Breadcrumb in contribution and subcontribution editing is inversed

### ISSUE THREAD

**Issue by indico-bot** [indico/indico#310]
``` yaml
# Ticket imported from Trac
# Reported by: dmartinc
```

When modifying a subcontribution, e.g.

http://indico.cern.ch/subContributionModification.py?subContId=0&contribId=0&sessionId=0&confId=38692

Or modifying a contribution, e.g.

http://indico.cern.ch/contributionModification.py?contribId=0&sessionId=0&confId=38692

The breadcrumb is inversed compared to the one used for the categories / events:

It says: contribution1 > session1 > timetable, but it should say timetable > session1 > contribution1.

**Comment by pferreir** [comment]
No longer applies.
