### ISSUE TITLE
Access Key for Uploaded Materials

### ISSUE THREAD

**Issue by sdspacecowboy** [indico/indico#3101]
Hey Guys,

Is there anyway that we can let our users use an access key instead of creating a username/password to access an uploaded file?

Thanks

**Comment by ThiefMaster** [comment]
We only support access keys on the event level.

**Comment by peter-** [comment]
Is there a way to make extended use of the tokens from registration emails, perhaps? Those already allow editing your registration details without (further, beyond the token as part of the URL sent via email) authentication to the system?
(Also, those are already personalised and avoid the sharing of access keys and would therefore integrate better with the ACL system: A GET request with the token request parameter present identifies registered participant.)

Maybe providing a (personalised) link from the registration page to the materials (to carry over the token from the URL sent out via email) plus authorising such requests to the materials if the token is present (and belongs to a registered participant, if that's the configured protection method) would be sufficient for this to work?

Probably not perfect UI-wise (as merely surfing to the materials page wouldn't include your token) but adding a section at the end of the authenticated registration page ("Access materials for this event" or something like that, either always or only when the token is present and valid) seems like a completely acceptable UI for this case, providing personalised, somewhat authenticated and authorised access to protected materials for registered participants, without needing local accounts nor access keys?
