### ISSUE TITLE
Registration form: multiple choice text too short

### ISSUE THREAD

**Issue by jouvin** [indico/indico#3119]
I created a registration form with a multiple-choice field. It seems that the maximum length of a  choice item text is much shorter than it used to be in 1.2 (I have a similar event created a 1.2 and I cannot reenter the values used without having them truncated). Is there a good reason for this change? Is there a way to customize the max length? Or at least to change it without breaking the ability to update to future versions?
If it is too complicate to have this max length customizable, I'd suggest to increase it max lengh by adding allowing at least 20 more characters.

**Comment by ThiefMaster** [comment]
Did the multi-choice field even exist in 1.2? I thought we only added this to replace the old social-events/session field.

Anyway, from what I can see we already had `maxlength: "50"` in v1.2. Of course it's possible that it was simply broken and never applied. I don't think we really need a max length there - we also don't have one in most other places.

**Comment by jouvin** [comment]
As I don't have 1.2 anymore, it is difficult to say how it was implemented. The event is not in our Indico instance but in the CCIN2P3 one, so I cannot even check in my db backup of 1.2. But after conversion/upgrade to 1.9/2.0, it looks as multiple-choice. As I didn't create this 1.2 event, I cannot say how it was created. But you may be right because there is in fact one session matching one entry in the current multiple choice.
BTW, the old session field was an interesting one for some specific use cases, like the one I am working on (but this is a very diverted Indico use case!).
If the limit could be just removed without any special drawback, it may probably be good to remove it. I let you decide!
