### ISSUE TITLE
address and chairperson alignment "broken" after update to 2.0

### ISSUE THREAD

**Issue by Yasharah** [indico/indico#3126]
Hello,
after i upgraded our indico server to the newest version, the alignment of some things changed on the conference theme

before (1.9.11.dev15):
![before](https://user-images.githubusercontent.com/30473222/32009041-2b723fcc-b9ae-11e7-9c9f-b31174505da7.png)

after (v2.0a1):
![selection_001](https://user-images.githubusercontent.com/30473222/32008910-d35be2fc-b9ad-11e7-9b99-d7cfe5aeac74.png)

**Comment by ThiefMaster** [comment]
That looks indeed broken. We'll have a look into it.
