### ISSUE TITLE
Indico check-in app doesnt work anymore

### ISSUE THREAD

**Issue by Yasharah** [indico/indico#3127]
Hello,
after the upgrade to 2.0 the app doesnt seem to work anymore. I tried to add an event with the qr-code like before and nothing happend. I get no error or something like that. It doesnt even ask for the login. 

i thought the app is now activated by default and i dont have to add it to the config file anymore?

**Comment by ThiefMaster** [comment]
You still need to scan the QR code (and possibly remove the event from the app if you had it in there before, with the old oauth app), but then it should work.

Unless we forgot to publish and updated version, which seems to be the case... Hopefully we can fix that tomorrow. ping @pferreir

**Comment by Yasharah** [comment]
okay i tried the new app and i can add the events again, but i cant see the attendees like before (where you could also check-in them by hand) and if i try to scan a ticket qr-code it opens the following page where i can do nothing:
![screenshot_20171026-165738](https://user-images.githubusercontent.com/30473222/32060419-fe0a3398-ba6e-11e7-8b1e-d3270dd010e7.png)

**Comment by ThiefMaster** [comment]
Hi, I just tested it and it works fine for me. Could you try clearing the app data+cache?

**Comment by Yasharah** [comment]
that was it! thank you so much. :)
