### ISSUE TITLE
Wiki pull request

### ISSUE THREAD

**Issue by DirkHoffmann** [indico/indico#3133]
I just saw I had forgotten to request the pull of a very old contribution of mine to the wiki:
Please pull from git@github.com:DirkHoffmann/indico.wiki.git to git@github.com:indico/indico.wiki.git

**Comment by ThiefMaster** [comment]
I just had a look at the diff and it looks like it's only adding a link to a legacy payment plugin (and the link even 404s). Considering that the plugin system completely changed, and anything before 1.2 is completely end-of-life and unsupported (no security updates either), I don't think it's very useful to add this to the wiki now.

**Comment by DirkHoffmann** [comment]
> I just had a look at the diff and it looks like it's only adding a link to a
> legacy payment plugin (and the link even 404s). Considering that the plugin
> system completely changed, and anything before 1.2 is completely end-of-life
> and unsupported (no security updates either), I don't think it's very useful
> to add this to the wiki now.

The link should not 404 after a complete pull of the patch.

The instructions are rather related to paybox than to the Indico version, so 
they may eventually be reused (and hopefully updated!) without to much 
effort or need for adaptation.
