### ISSUE TITLE
Alembic Revision cannot be located 1.9.10.2 ->1.9.11

### ISSUE THREAD

**Issue by knusperman** [indico/indico#3148]
Hey,

we want to move to version 2 of indico and have to get our instance from 1.9.10.2 to 1.9.11. To do so we deployed the new version, deleted temp files and ran pip install -e . .

When running db migrate, we get the following error:
`alembic.util.exc.CommandError: Can't locate revision identified by 'ebd80cb1bb8f'`

However, the revision file exists in our migrations folder. Any ideas?

**Comment by ThiefMaster** [comment]
The command to run is `indico db upgrade`. (`indico db migrate` is a developer command to generate new migration revisions for database changes)

**Comment by knusperman** [comment]
Sorry for that. 

With `db upgrade` the error is still there with the same identifier.

**Comment by ThiefMaster** [comment]
Can you run these commands and post the output?

    pip freeze | grep indico
    python -c 'import indico; print indico.__path__'
    ls -al /opt/indico/.venv/local/lib/python2.7/site-packages/indico/migrations/versions/*.py

**Comment by knusperman** [comment]
```
(indicoenv)indico@D-3110S32:/var/www$ pip freeze | grep indico
-e git+git@wiwi-gitlab.uni-muenster.de:tis/indico.git@968285f9a1a1a38a67f18e013dfbbc5b11bce0ad#egg=indico
indico-fonts==1.1
indico-payment-cern==0.3.1
-e git+https://github.com/indico/indico-plugins.git@5ff1ad6e738d043611aceed7671bda4332404883#egg=indico_payment_manual&subdirectory=payment_manual
-e git+https://github.com/indico/indico-plugins.git@5ff1ad6e738d043611aceed7671bda4332404883#egg=indico_payment_paypal&subdirectory=payment_paypal
```

`(indicoenv)indico@D-3110S32:/var/www$ python -c 'import indico; print indico.__path__'
['/var/www/indicoenv/indico/indico']`

Regarding the last line, I can't find an indico folder in the site-packages... is this maybe because of installing it via `pip install -e .` ?

**Comment by ThiefMaster** [comment]
Ah, didn't know this is a development setup. Thought you are on a production deployment. There's no revision `968285f9...` in the official repo, so it's hard to know what version you are actually using. If I were you I'd checkout the `v1.9.11.dev18` tag, then `pip install -e .` to make sure all dependencies have the right versions.

**Comment by ThiefMaster** [comment]
Also, it might be easier if you joined our IRC channel if you encounter more problems.

**Comment by ThiefMaster** [comment]
Did you manage to update in the end?

**Comment by knusperman** [comment]
Yes, it works. For some reason, there were files missing in the migrations folder. We deleted the folder, uploaded it again and it worked. It was some issue with our last 1.9.11 update I guess.

Thanks!
