### ISSUE TITLE
asset location for mathjax lib / timetable not loading

### ISSUE THREAD

**Issue by cfgmr** [indico/indico#3153]
We are running indico behind a proxy and ran into a problem where the timetable would not load, only the spinner and the 'building timetable' was showing.  The problem was, that the mathjax js files were requested from the internal machine and not from the proxy address. All other assets were loading fine.  

We are running indico v2.0rc1 on CentOS7. 

Below an example of the firefox console log output. I changed the hostnames for clarity: *indico-internal.example.org* is the machine running indico, accessible only via intranet, *indico-external.example.org* is the proxy address accessible from the outside.

```
GET https://indico-external.example.org/assets/js-vars/user.js [HTTP/1.1 200 OK 314ms]
[...]
GET https://indico-external.example.org/images/load_big.gif [HTTP/1.1 304 NOT MODIFIED 31ms]
GET https://indico-internal.example.org/js/lib/mathjax/jax/input/TeX/config.js [155ms]
GET https://indico-internal.example.org/js/lib/mathjax/jax/output/HTML-CSS/config.js [146ms]
GET https://indico-internal.example.org/js/lib/mathjax/extensions/tex2jax.js [146ms]
Laden fehlgeschlagen für das <script> mit der Quelle "https://indico-internal.example.org/js/lib/mathjax/jax/input/TeX/config.js?rev=2.6.1".  timetable:1
Laden fehlgeschlagen für das <script> mit der Quelle "https://indico-internal.example.org/js/lib/mathjax/extensions/tex2jax.js?rev=2.6.1".  timetable:1
Laden fehlgeschlagen für das <script> mit der Quelle "https://indico-internal.example.org/js/lib/mathjax/jax/output/HTML-CSS/config.js?rev=2.6.1".  timetable:1
```
We solved the issue by setting `BASE_URL = 'https://indico-external.example.org'` instead of `'https://indico-internal.example.org'` in the *.indico.conf*. However, it might be a good idea to change the location of the mathjax files so that they are handled in the same way as the other assets. I also wanted to leave this here in case somebody else has similar problems.

**Comment by ThiefMaster** [comment]
`BASE_URL` must always point to the URL used by your users, no matter which URL is used internally (by the load balancers). You also need to set `USE_PROXY = True` and ensure your proxy provides the proper headers (X-Forwarded-For, X-Forwarded-Proto, Host); especially the `Host` header is important and needs to use the external hostname (ie match the one in `BASE_URL`)

**Comment by cfgmr** [comment]
Thanks for the clarification!
