### ISSUE TITLE
Reminders: keep event relative reminders for cloning

### ISSUE THREAD

**Issue by bpedersen2** [indico/indico#3154]
Currently reminders are deleted once they are executed. 
This leads to the effect, that cloning an event where the reminder has expired, will not copy this reminder.
For a 'x hours before event' reminder this is a bit unfortunate.

**Comment by ThiefMaster** [comment]
They aren't deleted and relative reminders are actually cloned. However, we skip the reminder during cloning if it's already in the past.

**Comment by bpedersen2** [comment]
Right, after re-testing it is working again.
