### ISSUE TITLE
Renaming pages should affect headings

### ISSUE THREAD

**Issue by Eising** [indico/indico#3165]
Hi,

As you well know, it is possible to rename things in the menu, for example renaming "Call for Abstracts" to something else, like "Call for Programme" or "Bob" or whatever you like.

This however does only affect the menu entry, and not the heading in the actual page.

I would like to suggest that you implement this for at least the heading also, and if not too difficult, further entries, such as buttons where it applies.

**Comment by ThiefMaster** [comment]
> and if not too difficult, further entries, such as buttons where it applies.

I think that's going into the "overkill" area - for example, "submit abstract" etc can't really be changed since it's a different string, and usually people do use it for abstracts even if the menu is labelled differently.

**Comment by Eising** [comment]
> I think that's going into the "overkill" area - for example, "submit abstract" etc can't really be changed since it's a different string, and usually people do use it for abstracts even if the menu is labelled differently.

That's fair. Fixing the heading alone would remove a bit of confusion I believe.
