### ISSUE TITLE
Request: "Default" themes pinned to the top for event administrators/managers

### ISSUE THREAD

**Issue by RaoOfPhysics** [indico/indico#3166]
This concerns the instance at CERN.

When a user is not signed in or is not the administrator of an event, they are presented with a limited set of "default" themes to skin the event:

<img width="179" alt="firefox - - screen shot 24 nov 2017 at 20 58 36" src="https://user-images.githubusercontent.com/7623019/33222830-668a009a-d15a-11e7-88d7-82b12f6d800c.png">

However, when you log in as an administrator or manager, you see a much longer list:

<img width="215" alt="firefox - - screen shot 24 nov 2017 at 20 56 43" src="https://user-images.githubusercontent.com/7623019/33222833-7db1cfd2-d15a-11e7-83b5-80b50291a2db.png">

Is it possible to show this second list with the "default" themes from the first list pinned to the top and clearly separated (by a line of some sort) from the other options?

Thank you.

**Comment by ThiefMaster** [comment]
That sounds like a good idea! These extra themes are provided by a plugin and there's already a `user_visible` flag that determine whether a theme goes into the short list or not. We could group by events with/without that flag here: https://github.com/indico/indico/blob/master/indico/modules/events/templates/header.html#L41-L42
