### ISSUE TITLE
Customize Empty agenda message

### ISSUE THREAD

**Issue by hormiai76** [indico/indico#3188]
Is is possible to change the meeting.html in order to customize the content of the page if the agenda is empty? 
I think it's a good idea remember to the user to create an agenda using the timetable but some users need an empty content as in the version 1.2 because they attach the agenda in a pdf format.
I would like something like "Use the default contect for empty timetable" or a textarea to write code or leave it empty to have and empty content.
Regards
Alberto

**Comment by ThiefMaster** [comment]
Just FYI, only event managers get this message. Anyone else sees the empty agenda. Also, have you considered using the 'lecture' event type if you do not add an agenda in Indico itself?

**Comment by hormiai76** [comment]
Thank you. If only event manager see this message there is no problem. I'm just started managing Indico at MAX IV so I need to learn about it more and more
