### ISSUE TITLE
Automating user group assignments

### ISSUE THREAD

**Issue by sdspacecowboy** [indico/indico#3202]
Is there a way where for me to configure indico signups so that when a new account is created they are put into a group?

**Comment by pferreir** [comment]
Not automatically. That could be easily done through a plugin, however. I believe the [`users.registered`](https://github.com/indico/indico/blob/master/indico/core/signals/users.py#L25) signal would work.

**Comment by pferreir** [comment]
BTW, if you want to ask questions, the [chat](https://riot.im/app/#/room/#indico:matrix.org) and the [forum](https://talk.getindico.io) are better choices.
