### ISSUE TITLE
References numbers in PDF abstracts missing

### ISSUE THREAD

**Issue by uhuaha** [indico/indico#3203]
When converting abstracts (single abstract and book of abstracts) to a PDF the references numbers go missing. For example:

"This is just an example first sentence [1]. In the second example sentence they showed that ... [2] is ..."

[1] ....
...        <= This line should start with "[2]" but this number is missing and all following numbers as well if there were more than two references. "[1]" is always present though.

We have Indico version 2.0a1. The output of "root@indico:~# tex --version" yields "TeX 3.14159265 (TeX Live 2015/Debian)". Is there a possibility to get the references numbers in the abstracts? Thank you very much for your help.

**Comment by ThiefMaster** [comment]
Could you please provide a non-truncated example to reproduce the issue?

Anyway, guessing from your example: Abstracts use Markdown, so something like  `[1]: foo` declares `foo` as the location for the link `[1]` which would usually be written as `[something][1]` (which would then result in "something" linking to the URL "foo".

**Comment by uhuaha** [comment]
Thanks for your quick answer. Here is a more elaborate case (I copied one of the abstracts from the management area in the "edit contribution" window):

Small clusters in the gas phase are ideal model systems for investigating the fundamental aspects of complex reactions [1,2]. The good control over cluster size, composition, and charge state allows distinguishing the effects of these parameters on the studied reactions. In the high-vacuum conditions of a gas-phase experiment there are no contaminating agents that could affect the reaction mechanism. In addition, for small-sized clusters, ranging from two to a few tens of atoms, direct comparison between experiment and quantum-chemical calculations is possible.
In this talk, I will discuss two examples in which infrared multiple photon dissociation spectroscopy (IRMPD) is used to investigate the interaction of metal clusters with small molecules. First, the adsorption of CO on Mo and Nb doped cationic platinum clusters is studied with the goal to enhance understanding about the CO poisoning effect of Pt catalyst nanoparticles in proton exchange membrane fuel cells. Reactivity measurement in a low-pressure collision cell showed significant reduction in the reactivity of the doped Pt clusters compared to bare Pt clusters, which is attributed to electron transfer from the highly coordinated dopants to the Pt atoms and the concomitant lower CO binding energies [3]. Stretching frequencies of the adsorbed CO molecules reflect dopant-induced charge redistribution within the clusters [4]. 
Second, I will present a study of hydrogen adsorption on the V and Rh doped cationic aluminum clusters. IRMPD spectra, which provide a fingerprint of the hydrogen binding geometry, prove that H$_2$ dissociates upon adsorption for the V doped clusters. Orbital analysis shows that the activation barriers are due to an unfavorable overlap between cluster and hydrogen orbitals [5]. For Rh doped clusters, depending on the cluster sizes, either the H$_2$ binds dissociatively or it adsorbs molecularly in Kubas complexes. This size dependence is not due to kinetic impediment of the hydrogenation reaction by an activation barrier, but to binding energy differences [6].

[1] D. Justes, R. Mitrić, N. Moore, V. Bonačić-Koutecký, A. Castleman, Jr., J. Am. Chem. Soc. 125, 6289 (2003).
[2] S. M. Lang, T. Bernhardt, R. Barnett, U. Landman, Angew. Chem. Int. Ed. 49, 980 (2010)
[3] P. Ferrari, L.M. Molina, V.E. Kaydashev, J.A. Alonso, P. Lievens, E. Janssens, Angew. Chem. Int. Ed. 55, 11059 (2016)
[4] P. Ferrari, J. Vanbuel, N.M. Tam, M.T. Nguyen, S. Gewinner, W. Schöllkopf, A. Fielicke, E. Janssens, Chem. Eur. J. 23, 4120 (2017)
[5] J. Vanbuel, E.M. Fernández, P. Ferrari, S. Gewinner, W. Schöllkopf, L.C. Balbás, A. Fielicke, E. Janssens, Chem. Eur. J. 23, 15638 (2017)
[6] J. Vanbuel, M.Y. Jia, P. Ferrari, S. Gewinner, W. Schöllkopf, M.T. Nguyen, A. Fielicke, E. Janssens, Top. Catal. (2017). https://doi.org/10.1007/s11244-017-0878-x


So, here everything is fine but when I create a PDF from this all numbers [x] starting from [2] in the listed references are missing. [1] is always present though. It seems to me that `pdflatex` may not function correctly. I recently installed latex/texlive as demonstrated in [https://docs.getindico.io/en/latest/installation/latex/](url). Do you guys have an explanation for the observed behaviour? Thanks so much for your help!

**Comment by ThiefMaster** [comment]
OK, I can reproduce this locally:

This output from xelatex seems related (you can find this in /opt/indico/tmp/indixo-texgen-*/ as well)
```
! Illegal unit of measure (pt inserted).
<to be read again>
                   }
l.122 [2]
          S. M. Lang, T. Bernhardt, R. Barnett, U. Landman, Angew. Chem. Int...

! Illegal unit of measure (pt inserted).
<to be read again>
                   }
l.123 [3]
          P. Ferrari, L.M. Molina, V.E. Kaydashev, J.A. Alonso, P. Lievens, ...

! Illegal unit of measure (pt inserted).
<to be read again>
                   }
l.124 [4]
          P. Ferrari, J. Vanbuel, N.M. Tam, M.T. Nguyen, S. Gewinner, W. Sch...

! Illegal unit of measure (pt inserted).
<to be read again>
                   }
l.125 [5]
          J. Vanbuel, E.M. Fernández, P. Ferrari, S. Gewinner, W. Schöllko...

! Illegal unit of measure (pt inserted).
<to be read again>
                   }
l.126 [6]
          J. Vanbuel, M.Y. Jia, P. Ferrari, S. Gewinner, W. Schöllkopf, M.T...
```

I wonder if we need to escape anything in latex when square brackets are involved...

**Comment by ThiefMaster** [comment]
Minimal abstract content to reproduce it:

```
Hello world

[1] foo
[2] bar
```

shows up as

```Hello world
[1] foo
bar
```

---

The full generated LaTeX source of this example is attached: [bug.tex](https://github.com/indico/indico/files/1626651/bug.tex.txt)

**Comment by ThiefMaster** [comment]
This sounds like the problem: https://tex.stackexchange.com/a/49105/1651
