### ISSUE TITLE
Make it easier to add event to cern email calendar

### ISSUE THREAD

**Issue by dajiaonao** [indico/indico#3204]
I wonder if you can add a button in the event page, like the "add to google calendar" in the social section, with which I can add the event to the calendar in my CERN OWA mailbox, better if it can get updated as well when the event is updated.

I used google calendar a lot. A couple of clicks and I get the event in the calendar and available across all my devices. But now I have moved to China.... Using the .ics file need quite more actions.

Even better if you can allow user to choose a favorite calendar from a supported list as default shown in the event page.

Thanks!

**Comment by ThiefMaster** [comment]
This would be handled by marking an event as a favorite, as suggested in #1662 - the "favorite event" functionality would actually be part of Indico itself, while the CERN plugin for the calendar integration would take care of adding favorite events there as well.
