### ISSUE TITLE
Multiple LDAP URL/Server for the same AuthProvider

### ISSUE THREAD

**Issue by dkfz2018** [indico/indico#3223]
Hi,

wasn´t able to implement a second "uri" in the ldap configuration. It would be a huge advantage if you can select to uri (s) for the same AuthProvider so you have a backup at a crash or maintance.

**Comment by ThiefMaster** [comment]
That would be an issue for https://github.com/indico/flask-multipass, but try to separate the URLs with spaces and see if that works: https://mail.python.org/pipermail/python-ldap/2014q2/003370.html

**Comment by dkfz2018** [comment]
spaces doesn´t work it only take the frist entry, but thanks
