### ISSUE TITLE
Moving project to MIT license

### ISSUE THREAD

**Issue by pferreir** [indico/indico#3255]
There is a [detailed explanation on the forum](https://talk.getindico.io/t/adopting-a-permissive-license/239). The main takeaway is:
 * We'd like to change Indico's license from GPLv3 to MIT;
 * The main goal is to clarify the legal status of plugins that are developed but not shared with the community;
 * We believe this will be good for the Indico ecosystem and society as a whole;
 * We intend to release 2.2 as MIT-licensed software;

CCing the contributors I can find on here:

- [x] @bpedersen2
- [x] @jouvin
- [x] @sobolevn
- [x] @openprojects
- [x] @fph
- [x] @shesselbach
- [x] @driehle
- [ ] @SteppingHat
- [ ] @datty
- [ ] @danmichaelo
- [ ] @dabougie
- [ ] @matason

Please let us know whether you'd consent to this move.

**Comment by bpedersen2** [comment]
Yes, that seems indeed a good idea from my side

**Comment by jouvin** [comment]
@pferreir I was not remembering that I contributed once but if it is the case, I'm happy with the move to a permissive license, in principle. I think it is along the lines of the the discussions we had in HSF with licensing, where GPLv3 seems to cause a lot of problems at the end. The choice of MIT is probably not the norm also but is fine as this is probably the simplest/shortest and most permissive license. Have you considered Apache2 which tends to be the most used permissive license today?

**Comment by ThiefMaster** [comment]
@jouvin that's your commit:

e04aff64aa - Upgrade docs: mention --migrate-broken-events (8 months ago)

**Comment by jouvin** [comment]
@ThiefMaster thanks, it's nice to take into account such a small addition!

**Comment by pferreir** [comment]
> Have you considered Apache2 which tends to be the most used permissive license today?

Yes, we have, and the conclusion is that the added value Apache offers is too little to compensate for the lack of simplicity. MIT will be more friendly to spontaneous contributors. There's also the "historical" reason mentioned on the [forum post](https://talk.getindico.io/t/adopting-a-permissive-license/239).

**Comment by sobolevn** [comment]
no problem for me. let it be whatever license you choose.

**Comment by openprojects** [comment]
No problem for me too.


Il 2018-03-05 16:13 Pedro Ferreira ha scritto:

**Comment by fph** [comment]
Green light from me as well (and actually my contribution to Indico is ridiculously small, just a one-line change in the documentation).

**Comment by shesselbach** [comment]
The license change is no problem for me, too.

**Comment by jouvin** [comment]
@pferreir Thanks!

**Comment by driehle** [comment]
I am fine with switching to MIT license.

**Comment by pferreir** [comment]
Addressed by #3483
