### ISSUE TITLE
Include email addresses in non-anonymous survey results

### ISSUE THREAD

**Issue by SebastianLopienski** [indico/indico#3258]
Non-anonymous survey means that users have to be authenticated, and their identities are stored with survey results. But currently, only first and last name are displayed in survey results, and can be exported. Unfortunately, first and last name are not necessarily unique, and also don't allow contacting the users. Please include users email addresses in non-anonymous survey results and export.

**Comment by SebastianLopienski** [comment]
Any progress on this? You marked is as `trivial`, and I believe correctly. It would be great to have it implemented...

**Comment by pferreir** [comment]
We're currently working on a release that is completely unrelated (Room Booking). I'm scheduling this for the release right after.

**Comment by ThiefMaster** [comment]
Moving this back to 2.1 since we had to fix something else in surveys anyway.

**Comment by SebastianLopienski** [comment]
Oh, great! Do you have ETA for deployment @ CERN?

**Comment by ThiefMaster** [comment]
today - just finishing some other stuff to deploy it all together

**Comment by SebastianLopienski** [comment]
👍
