### ISSUE TITLE
Registrations: sorting by date broken

### ISSUE THREAD

**Issue by SebastianLopienski** [indico/indico#3265]
On the "List of registrations" page (https://SERVER/event/XXXXX/manage/registration/YYYYY/registrations/), sorting by a column of type `Date` is broken (the order is not by the date, but seems completely random).

**Comment by bpedersen2** [comment]
I just checked the generated html:
For the system column Regsitration date, that sort fine:
`<th class="i-table tablesorter-header tablesorter-headerUnSorted" data-sorter="text" data-column="5" tabindex="0" scope="col" role="columnheader" aria-disabled="false" unselectable="on" aria-sort="none" aria-label="Registration Date: No sort applied, activate to apply an ascending sort" style="user-select: none;">Registration Date</th>`

For  an extra Date column:
`<th class="i-table tablesorter-header tablesorter-headerAsc header-sort-asc" data-column="8" tabindex="0" scope="col" role="columnheader" aria-disabled="false" unselectable="on" aria-sort="ascending" aria-label="Date for Test: Ascending sort applied, activate to apply a descending sort" style="user-select: none;">Date for Test</th>
`

The main difference is the missing `data-sorter="text"`

Add this fixes it (patch coming)
