### ISSUE TITLE
Registration list: allows sorting or filtering by access control status

### ISSUE THREAD

**Issue by SebastianLopienski** [indico/indico#3267]
(Perhaps relevant for CERN only)

In the new site access control functionality, after granting site access to a person, I see next to their name a green icon (_"Access granted"_) or a yellow icon (_"Needs additional data"_). If the access is not granted, I see a gray icon (_"No access to CERN"_). It would be good to be able to sort by this column, or to filter by the status (e.g. to display only the ones in green).

**Comment by ThiefMaster** [comment]
filtering is very tricky due to the way it's implemented. sorting should be doable though.

PS: this would be better suited in https://github.com/indico/indico-plugins-cern ;)

**Comment by SebastianLopienski** [comment]
For the PS - thanks, indeed, noted for the future. Please feel free to move this issue to indico-plugins-cern (or to delete it, and create a new one in there).

**Comment by ThiefMaster** [comment]
IIRC we added this some time ago
