### ISSUE TITLE
Meta information for schema.org/event is missing or incorrect

### ISSUE THREAD

**Issue by bpedersen2** [indico/indico#3269]
At least googlebot complains that some tags are missing and others use the wrong name:
![screenshot-search google com-2018 03 16-14-55-11](https://user-images.githubusercontent.com/5336494/37524406-a75be36c-2921-11e8-859f-f28bc0068226.png)

**Comment by bpedersen2** [comment]
Need to  retest with 2.1 (this from the production system runnign 2.0.3)

**Comment by pferreir** [comment]
We should definitely fix this.

**Comment by bpedersen2** [comment]
Currently we add the meta info inline, split across the page. 

Shall  we consider switching to providing this information in a single place as json-ld? See ()[https://developers.google.com/search/docs/data-types/event] for an example. Then we could move all this meta-data stuff to a single template fragment.
