### ISSUE TITLE
allow the html-to-pdf conversion when uploading Indico material

### ISSUE THREAD

**Issue by mariadimou** [indico/indico#3271]
Dear Indico developers,
right now, Indico doesn't offer the option to convert an html page to pdf. This would have been useful. 
I tested this via https://indico.cern.ch/event/715317/. See screenshot here for what I got:
![html-to-pdf-convert](https://user-images.githubusercontent.com/26465927/37649798-471f94b6-2c33-11e8-84c5-017cc8840abe.png)

Thank you very much for considering this enhancement request.

Yours ever
Maria

**Comment by bpedersen2** [comment]
Hmm, while it seems a nice feature from a users perspective, I do not think it is a good idea from a n administrators point of view: 

1.  Rendering arbitrary web pages on the server as pdf requires trust in the source page to be safe to render.
2. Rendering arbitrary content may pose copyright problems.

So I think requiring this to be done offline (with the possibility to check the rendered pdf before uploading) looks the better option to me.

**Comment by mariadimou** [comment]
I respect the experts' opinion. Please continue discussing between developers or close this enhancement request, as you see appropriate. Thanks very much for considering it anyway.
Yours
Maria

**Comment by ThiefMaster** [comment]
I agree, not only do most websites look awful when converting them to PDF (or printing them), but it's also pretty much outside the scope of Indico.

If you just want to preserve the content of a website as of a certain date, you could use a service like https://archive.is/ - they create a snapshot of the website and give you a link. I don't know how long they keep them though.
