### ISSUE TITLE
Meeting comments/messages

### ISSUE THREAD

**Issue by pferreir** [indico/indico#3275]
This was suggested by a user (`RQF0964474`) and has already been discussed briefly over the years. Users would like to add some extra information on some meeting pages, e.g. whether a meeting has been adjourned, or cancelled/postponed (see #3199 too).
A simple solution could be to have a "state" field for the event (adjourned, postponed, cancelled...) and an optional message.

**Comment by ThiefMaster** [comment]
This is pretty much the same as #4353 which is part of 2.2 and 2.3.
