### ISSUE TITLE
pdf file vs TEX

### ISSUE THREAD

**Issue by srerasmo** [indico/indico#3282]
Hello,
I have a question, when trying to generate a pdf file. You send me the following error:
Something went wrong,
"LaTeXRuntimeException: Impossible to compile '/opt/indico/tmp/indico-texgen-3GiWlj/report.tpl.tex'. Read '/opt/indico/tmp/indico-texgen-3GiWlj/output.log' for details"

The file "output.log" is empty
Has anyone happened to you or do you know how to solve it?

Regards

**Comment by ThiefMaster** [comment]
Is `xelatex` installed?

**Comment by srerasmo** [comment]
yes, it is installed

**Comment by srerasmo** [comment]
Yes, I restart: 
systemctl restart uwsgi.service httpd.service indico-celery.service

**Comment by srerasmo** [comment]
This is Traceback:
Traceback
---------
Traceback (most recent call last):
  File "/opt/indico/.venv/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/indico/.venv/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/indico/.venv/lib/python2.7/site-packages/indico/web/flask/util.py", line 114, in wrapper
    return obj().process()
  File "/opt/indico/.venv/lib/python2.7/site-packages/indico/web/rh.py", line 270, in process
    res = self._do_process()
  File "/opt/indico/.venv/lib/python2.7/site-packages/indico/modules/events/controllers/base.py", line 63,
in _do_process
    return RHEventBase._do_process(self)
  File "/opt/indico/.venv/lib/python2.7/site-packages/indico/web/rh.py", line 249, in _do_process
    return self._process()
  File
"/opt/indico/.venv/lib/python2.7/site-packages/indico/modules/events/contributions/controllers/display.py",
line 191, in _process
    return send_file('contributions.pdf', pdf.generate(), 'application/pdf')
  File "/opt/indico/.venv/lib/python2.7/site-packages/indico/legacy/pdfinterface/base.py", line 683, in
generate
    pdffile = latex.run(self._tpl_filename, **self._args)
  File "/opt/indico/.venv/lib/python2.7/site-packages/indico/legacy/pdfinterface/base.py", line 749, in run
    raise LaTeXRuntimeException(source_filename, log_filename)
LaTeXRuntimeException: LaTeX compilation of /opt/indico/tmp/indico-texgen-3GiWlj/report.tpl.tex failed

**Comment by ThiefMaster** [comment]
The traceback is not really useful in this particular case.

> Any other log files in that directory? I think LaTeX creates one as well...

**Comment by srerasmo** [comment]
in report.tpl.tex:
fancyfoot[L]{\small \rmfamily \color{gray} \today}
        \fancyfoot[C]{}
        \fancyfoot[R]{\small \rmfamily \color{gray} Página \thepage}
        \newpage
        \fancyhead[L]{\small \rmfamily \color{gray} \truncateellipses{EAV 2018, CINVESTAV Advanced Summer School}{80pt} / Informe de contribuciones}
        \fancyhead[R]{\small \rmfamily \color{gray} \truncateellipses{Name of Plenary Talk 1}{150pt}}
        \phantomsection
        \addcontentsline{toc}{section}{Name of Plenary Talk 1}

**Comment by ThiefMaster** [comment]
Is the latex snipped you posted above everything in `report.tpl.tex` or just a part of it?

---

Try running xelatex manually on the shell, using the following command. Maybe this provides more useful output.

`/path/to/xelatex -no-shell-escape -interaction nonstopmode -output-directory /opt/indico/tmp/indico-texgen-3GiWlj/ /opt/indico/tmp/indico-texgen-3GiWlj/report.tpl.tex`

**Comment by srerasmo** [comment]
Agree, his is the message: 

[root@indico indico]# /opt/texlive/bin/x86_64-linux/xelatex -no-shell-escape -interaction nonstopmode -output-directory /opt/indico/tmp/indico-texgen-3GiWlj/ /opt/indico/tmp/indico-texgen-3GiWlj/report.tpl.tex
/opt/texlive/bin/x86_64-linux/xelatex: error while loading shared libraries: libfontconfig.so.1: cannot open shared object file: No such file or directory

**Comment by srerasmo** [comment]
"/opt/texlive/bin/x86_64-linux/xelatex: error while loading shared libraries: libfontconfig.so.1: cannot open shared object file: No such file or directory"

**Comment by ThiefMaster** [comment]
Try running `/opt/texlive/bin/x86_64-linux/fmtutil-sys --all` (probably as root). According to [another user](https://talk.getindico.io/t/latexruntimeexception-after-upgrade-to-2-0-2/263/5?u=thiefmaster) this helps.

PS: For future questions like this, our forum is actually the better place to ask.

**Comment by srerasmo** [comment]
this does not works :(

**Comment by ThiefMaster** [comment]
Did you also install `libfontconfig1` as mentioned in the forum post?

**Comment by srerasmo** [comment]
I have Centos 7

**Comment by srerasmo** [comment]
Thank you very much! It works now! :-)
