### ISSUE TITLE
Quicker way to edit a conference page

### ISSUE THREAD

**Issue by SebastianLopienski** [indico/indico#3284]
Currently, to edit a conference page (https://indico-server/event/XXXX/page/YYYY-page-name), one has to take several steps/clicks:  Manage -> Menu -> find page -> pen icon. 

It would be nice to have a more straightforward way to edit a page. E.g. if I am manager of the event, currently logged it, I'd be happy to see this "pen" icon on the page itself. 

(Same could apply for other page types, e.g. overview page, timetable etc.)

**Comment by ThiefMaster** [comment]
Fair enough, seems like a good candidate for a pull request if someone is interested in contributing this. A simple version could just load the edit page via ajax-dialog and refresh afterwards.
