### ISSUE TITLE
Badge/Poster designer broken in Safari

### ISSUE THREAD

**Issue by pferreir** [indico/indico#3296]
![image](https://user-images.githubusercontent.com/2699/38367863-1569d342-38e4-11e8-809e-be27328bb63f.png)

Seems like some 3d transform issue.

**Comment by mic4ael** [comment]
Probably related to the last fix which targetted IE11..

**Comment by nop33** [comment]
Hm, what are the steps to reproduce? I don't see any issues on Safari 12.0 (13606.2.11).

![image](https://user-images.githubusercontent.com/1579899/47167743-7d91ca00-d2ff-11e8-9b24-64d7ed1f235e.png)

**Comment by ThiefMaster** [comment]
Maybe safari fixed whatever caused this in the meantime?

**Comment by nop33** [comment]
Can the reporter verify? @pferreir

**Comment by pferreir** [comment]
Works fine on Safari 14.1.1.
