### ISSUE TITLE
Conference timetable with indico style: add a link to event home page

### ISSUE THREAD

**Issue by jouvin** [indico/indico#3297]
Often, people prefer to use the Indico style timetable to the parallel one for conferences without parallel sessions as it is easier to navigate. This removes the conference menu on the left which is fine but has the drawback to remove any link to the event home page. Would it be possible to add a link back to the event page in the timetable in this case?

**Comment by bpedersen2** [comment]
You can do this via template customisation:
locate indico/modules/events/templates/display/compact.html
copy it to custom/core/events/timetable/display/compact.html in your indico root

`@@ -15,7 +15,7 @@
                     </div>
                 </div>
             {% endif %}
-            {{ event.title }}
+            <a href="{{event.url}}">{{ event.title }}</a>
         </div>
         <br/>
`

This snippet would link the title to the 'normal' page. 

@ThiefMaster : Should I create a pull request with this change?

**Comment by ThiefMaster** [comment]
I don't think this is only about the "compact" style but rather using meeting themes for conferences in general. While having a link back sounds like a good idea, I'm not sure how useful it would be in an actual meeting/lecture (the link would point to the current page after all).

**Comment by jouvin** [comment]
@bpedersen2 thanks for snippet, it may help in the short term... but I agree with @ThiefMaster that it would be good if we could ensure that there is always a link back to the main event page from the conference timetables, whatever style is used. At least a useless link is harmless...

**Comment by pferreir** [comment]
This is the good old problem of people "abusing" the meeting layout. Unfortunately, Pandora's box was opened long time ago and it's too late to just kill that possibility. Until we come up with a better conference timetable view, I agree that adding a link back won't hurt.

**Comment by bpedersen2** [comment]
Agreed, this would need to be added to all meeting-like themes if the type is conference.

I think adding it to the header would work universally.
