### ISSUE TITLE
Implement legacy redirects

### ISSUE THREAD

**Issue by pferreir** [indico/indico#3308]
A few I can think of:
 * `/rooms/map` -> `/rooms/book`
 * `/rooms/bookings/search` -> `/rooms/calendar`
 * `/rooms/bookings/search/mine` -> `/rooms/calendar` (w/ filtering options)
 * `/rooms/rooms/search` -> `/rooms/rooms`

**Comment by mvidalgarcia** [comment]
Are we keeping the url_prefix `/rooms`? IMO might be confusing when e.g `/rooms/rooms/`. What about `/roombooking`, `/room-booking` or `/rb`?

**Comment by ThiefMaster** [comment]
:+1: on changing the prefix. `/rooms/rooms` was always rather ugly (not sure why I picked it back then :p)

**Comment by ThiefMaster** [comment]
considering how long the new RB is in production and that we have some legacy redirects i don't think any additional ones are needed
