### ISSUE TITLE
Feature Request: Search by Jupyter / IPython notebooks

### ISSUE THREAD

**Issue by cranmer** [indico/indico#3320]
Now that INDICO can render jupyter (IPython) notebooks natively, it would be nice if one could also search by that as a Result type (similar to PDF, word, powerpoint, etc.

<img width="184" alt="pastedgraphic-2" src="https://user-images.githubusercontent.com/4458890/39002487-ab346c9c-43c6-11e8-99b5-8748eea1f4a5.png">

**Comment by ThiefMaster** [comment]
Search on indico.cern.ch is handled by CERNSearch which is not part of Indico - we only include it as an iframe.

Could you please open a SNOW ticket suggesting the search guys to add this?
