### ISSUE TITLE
Split actions.js and re-organize redux logic

### ISSUE THREAD

**Issue by pferreir** [indico/indico#3327]
Let's split them by functional area instead. Something like:
 ```
 - bookRoom
   - actions
   - reducers
- roomList
   - actions
   - reducers
```

**Comment by pferreir** [comment]
We should also reorganize the flow of actions and figure out where they should be triggered initially.

**Comment by mic4ael** [comment]
Definitely, it is currently visible in the Book Room page where the initial set of rooms is being loaded by the `MapController`.
