### ISSUE TITLE
List of Abstracts: a column with number of reviews

### ISSUE THREAD

**Issue by pferreir** [indico/indico#3345]
![image](https://user-images.githubusercontent.com/2699/39765298-caa4ef5a-52e1-11e8-8465-c7156c1a2c28.png)

In addition to the column "score" we should have something that indicates the number of reviews and, on hover, some more detailed information such whether the reviews are positive or negative and the suggested contribution types.

**Comment by pferreir** [comment]
The same applies to Paper Reviewing.

**Comment by pferreir** [comment]
The same applies to Paper Reviewing.

**Comment by stefanritt** [comment]
I would only use the hover mechanism for some really detailed information. In the column display it would be best to see the suggested contribution type such as "PPO" for two poster type and one oral type or "RRRP" for three rejects and one poster type. This way one can see the overall status without having to hover over each entry, which can be cumbersome for hundreds of abstracts. Then it would be good to sort or filter on those, like show abstracts which got three oral types and no poster type. That helps to identify highly ranked abstracts for oral presentations pretty quickly.

**Comment by mvidalgarcia** [comment]
Should this column be part of the customizable items or fixed?

**Comment by pferreir** [comment]
I think that it would be pretty useless in the customizable items, since it doesn't make much sense to filter by it and i allow it to be hidden.

**Comment by stefanritt** [comment]
Filtering though makes sense. As the program chair, I first want to accept abstracts with the most positive judgements.
