### ISSUE TITLE
Cannot reject a "complete" registration

### ISSUE THREAD

**Issue by SebastianLopienski** [indico/indico#3358]
When I reject a registration with status "completed", its status doesn't change to "rejected" (stays "completed"), and the mail sent also says _"The registration [..] is now completed."_

**Comment by ThiefMaster** [comment]
Nothing should happen at all in this case as you can only reject registrations that are pending (ie approval/rejection because the regform is set to require moderation). If an email gets sent for a completed registration, it's a bug.

**Comment by SebastianLopienski** [comment]
I confirm that the email was sent.
