### ISSUE TITLE
Button create new category not available 

### ISSUE THREAD

**Issue by mgfzemor** [indico/indico#3360]
Hi, I have a problem to create a new category. I'm logged as ADM, but when I click  in manage category the page to create a new category don't appears. Even if I need to split the current category into new categories the button to split is not available (disabled).

**Comment by bpedersen2** [comment]
Currently you can only create categories that either contain only events or only categories (so once you have an event  in a category, you can not create sub-categories there).

If you need to introduce sub-cats, you would first need to move the events  into a (temporary) other category, create the new sub-cats and then move the events back into these new sub-cats.

**Comment by ThiefMaster** [comment]
splitting does that - when selecting all events in the category it'll prompt for only one new category name which will then become the sub category
