### ISSUE TITLE
Implement room coordinate filtering in the backend.

### ISSUE THREAD

**Issue by pferreir** [indico/indico#3364]
This will require as well that the coordinates are stored as numbers instead of text.
For now, some simple `LAT > X and LON > Y and LAT < W and LON < Z` kind of thing should work.

(Once we implement filtering according to distance, we'll have to consider whether we want geographical indices or not. Maybe some good old euclidean geometry is enough for this scale).

**Comment by mvidalgarcia** [comment]
Map bounds are currently being sent to the server side whenever "Search as a I move the map" is enabled or gets checked so the only thing missing is the database level filtering.
