### ISSUE TITLE
Indicate favourite rooms in a clearer way

### ISSUE THREAD

**Issue by pferreir** [indico/indico#3365]
Suggestion from @ThiefMaster:

![image](https://user-images.githubusercontent.com/2699/40176747-b64fe486-59dc-11e8-9d35-c1b8cff2b8e5.png)

(LOL)

**Comment by mvidalgarcia** [comment]
Another suggestion is what we have in the mockups
![image](https://user-images.githubusercontent.com/8863238/40177305-7c141146-59de-11e8-9d0f-d724e294a1e7.png)

**Comment by pferreir** [comment]
@mvidalgarcia but then that'd look a bit funny with the current "overlay" solution for room actions.
