### ISSUE TITLE
Room Booking: Subject modifications of confirmed pre-bookings to acceptance

### ISSUE THREAD

**Issue by mvidalgarcia** [indico/indico#3387]
For a room with pre-booking enabled, when a booking is accepted, the user that booked it can change it to a different date and the booking gets automatically updated.
Since pre-booking is enabled, modifications of these bookings should be subject to acceptance again.

Related incident `INC1693961`

**Comment by pferreir** [comment]
Likewise, if we're changing the date/time of a booking and this booking collides with any existing pre-bookings, we should refuse to do so. Currently, we're just rejecting the pre-bookings, which is not great.
