### ISSUE TITLE
warning/error message updating from 2.1 to 2.1.1

### ISSUE THREAD

**Issue by hormiai76** [indico/indico#3390]
I executed the following command in our test server: **pip install -U --pre indico**
and I got : **indico-migrate 1.0a3 has requirement indico<2.1.dev0,>=2.0rc1, but you'll have indico 2.1.1 which is incompatible.**
Is it an error or I can just skip the warning message and go ahead with the update?
Regards,
Alberto Nardella

**Comment by ThiefMaster** [comment]
You can ignore the warning, since you probably won't run `indico-migrate` again anyway.

Actually, you can `pip uninstall -y indico-migrate` to get rid of it altogether.
