### ISSUE TITLE
Abstracts: Introduce tighter controls on modification

### ISSUE THREAD

**Issue by pferreir** [indico/indico#3431]
Right now, all authors/speakers [can modify an abstract](https://github.com/indico/indico/blob/master/indico/modules/events/abstracts/models/abstracts.py#L652). While this is a sensible default for most events, in larger ones, stricter controls may be required. A good example is the JACoW workflow, according to which:
 * **Speakers** should have submission rights (uploading files);
 * Only **primary authors** should be able to edit the title/description and authors of the abstract;

This should be ideally configurable.

**Comment by ThiefMaster** [comment]
> Speakers should have submission rights (uploading files);

Is this about who gets submission privileges after the abstract has been accepted? Because if yes, I'd say this should be a separate issue since it has nothing to do with editing abstracts.

> Only primary authors should be able to edit the title/description and authors of the abstract;

So simply not giving co-authors any special access on the abstract except being able to see it?

**Comment by pferreir** [comment]
Yeah, that's it, @ThiefMaster
