### ISSUE TITLE
UI string(s) separated in the middle of sentence to make hyperlinks

### ISSUE THREAD

**Issue by omasanori** [indico/indico#3469]
User search dialog has "Suggested users" column. When you have no favorite users, then "There are no suggested users for you at the moment. Why not add some favourites?" message is displayed.

![screenshot of user search dialog](https://user-images.githubusercontent.com/167209/43128151-80c2c68c-8f31-11e8-8c09-5fffd66003f8.png)

The problem is, since the word favourites is a link, the message is split into three parts in the stable branch: "There are ... add some",  "favourites", and "?". I don't know how the new React-based code base treats UI strings, but please make sure to use placeholders like "There are ... some &lt;a href='%s'&gt;favourites&lt;/a&gt;?" instead of splitting them, because some languages like Japanese are Subject-Object-Verb grammar, so we need to write something like "some favourites add".

From translator's point of view, it is much better if the order of placeholders can be swapped, but I don't know React provides such feature.

**Comment by ThiefMaster** [comment]
Once we move this dialog to React or non-legacy code, we will fix this and use a single translatable string for it. Currently this dialog is using ancient legacy JS.

FWIW, we can probably just get rid of this link altogether...

**Comment by ThiefMaster** [comment]
this dialog was rewritten in react
