### ISSUE TITLE
Forms don't validate email

### ISSUE THREAD

**Issue by Marx1st** [indico/indico#3471]
Hi!

I'm not sure if this is intentional or not, but the email field in the registration form does not apply any checks whether the input is a valid email address or not.
This leads to eg. the input of incorrect email addresses while registering for an event, which have to be corrected by hand. 
We use Indico 2.1.2

Regards
Tobias

**Comment by ThiefMaster** [comment]
We do validate it, the validation logic there is just *really* poor... :see_no_evil:
