### ISSUE TITLE
Content-Type is not allowed by Access-Control-Allow-Headers JavaScript Axios call

### ISSUE THREAD

**Issue by rebeccapeltz** [indico/indico#3472]
similar to: https://stackoverflow.com/questions/5027705/error-in-chrome-content-type-is-not-allowed-by-access-control-allow-headers

exact error: 
Failed to load https://apiv2.indico.io/emotion: Request header field Content-Type is not allowed by Access-Control-Allow-Headers in preflight response.

Here's my axios call.  Is this an error that I can fix on the client side?
```
axios.post('https://apiv2.indico.io/emotion', 
      api_key: 'xxxxx',
      data: this.emotion,
      threshold: 0.1
      })
      .then(response => {
      this.posts = response.data
      console.log(this.posts)
      ...
```

**Comment by ThiefMaster** [comment]
this is getindico.io, not indico.io
