### ISSUE TITLE
Session block manager able to reveal whole schedule for day of Session block

### ISSUE THREAD

**Issue by glunardi** [indico/indico#3474]
With a restricted event (CfP still in progress, else,...), a manager assigned to a single Session (and Session Block) can see the schedule for the whole day by mistake.

Steps to reproduce (as a Session manager with no other admin privileges)
 - Go to the top-level timetable,
 - Click on your session block,
 - Click the "Change colour" button,
 - Click any colour,
 - Once it is done processing, it will show the other items on that day.
 - Refresh the page, the other items disappear again

Expected: Only the colour should have changed, the other items in the agenda should not have been shown.

**Comment by glunardi** [comment]
Screenshot with correct view:

![screenshot from 2018-07-25 23-19-48](https://user-images.githubusercontent.com/1667348/43239712-4a3c6d08-9061-11e8-8f2f-28669ef0b021.png)

**Comment by ThiefMaster** [comment]
We will not release any updates for 2.0, but include it in the next 2.1 bugfix release. Probably you can manually apply the fix from #3476 though.
