### ISSUE TITLE
CERN Access: Wrong email notifications

### ISSUE THREAD

**Issue by mvidalgarcia** [indico/indico#3490]
Email notifications always have the ticket PDF attached regardless the ticketing configuration of the registration form.

Steps to reproduce:
1) Create a regform and enable the CERN Access service
2) Go to regform settings and disable options that allow participants to have the ticket
![image](https://user-images.githubusercontent.com/8863238/43845242-d300ac88-9b2b-11e8-983c-d1e9ba4a7b8e.png)
3) Register a participant
4) Grant access to the participant. It will receive and email with the following wrong sentence: 
> Upon reception of this data, you will receive an automatic email, with your access ticket in PDF format and an access code
5) Fill personal data as requested and you'll receive a confirmation email with the ticket attached.

There's also some confusion about the terms 'ticket' and 'badge' that should be better clarified both in the docs and the UI.

**Comment by ThiefMaster** [comment]
Wrong repo ;) https://github.com/indico/indico-plugins-cern
