### ISSUE TITLE
Booking API gives ambiguos username (even with example from docs)

### ISSUE THREAD

**Issue by stephangoedecke** [indico/indico#3496]
Hi Indico-Team,

I tried to use the HTTP API with the room booking feature, but booking a room does not work:
`curl --data "username=jdoe&from=2018-12-30T21:30&to=2018-12-30T22:15&reason=meeting&location=TIZ&roomid=1&ak=xxx" 'https://10.xx.xx.xx/api/roomBooking/bookRoom.json' -k
`
gives me
`{"_fossil":"hTTPAPIError","message":"Ambiguous username (5 users found)","_type":"HTTPAPIError"}`

The system was installed according to the installation guide, timestamp-feature has been disabled.

**Comment by ThiefMaster** [comment]
Are you using multiple identity providers in indico.conf (or did you in the past)? I just checked the code and we use this query to search for the user:

    users = User.find_all(~User.is_deleted, Identity.identifier == username).all()

Try running it in `indico shell` to see which users you get:

```
for user in User.find_all(~User.is_deleted, Identity.identifier == username):
    print user, user.identities
```

**Comment by ThiefMaster** [comment]
Are you using multiple identity providers in indico.conf (or did you in the past)? I just checked the code and we use this query to search for the user:

    users = User.find_all(~User.is_deleted, Identity.identifier == username)

Try running it in `indico shell` to see which users you get:

```
for user in User.find_all(~User.is_deleted, Identity.identifier == username):
    print user, user.identities
```

**Comment by stephangoedecke** [comment]
Hi Adrean, thank you for your support - I ran the command and it gives me five users as output (redacted due to privacy reasons):
`In [7]: for user in User.find_all(~User.is_deleted, Identity.identifier == "jdoe"):print user, user.identities
<User(1, xxx.xxx-xxx@xxx.com): "XXX XXX-XXX"> InstrumentedSet([<Identity(1, 1, indico, xxx)>])
<User(3, xx.xxx@xxx.com): "Webex Teams"> InstrumentedSet([<Identity(3, 3, indico, xxx)>])
<User(4, jdoe@example.com): "jdoe jdoe"> InstrumentedSet([<Identity(4, 4, indico, jdoe)>])
<User(2, test1@example.com): "test1 test1"> InstrumentedSet([<Identity(2, 2, indico, test1)>])
<User(0, None): "Indico System"> InstrumentedSet([])
`
The jdoe-User is not redacted.
I am not using multiple identity providers and did not use them as the system is a brand new greenfield approach exaktly built after the documentation for Ubuntu/Production Environment.

**Comment by ThiefMaster** [comment]
Oh, I think i see the problem. The query is missing a JOIN so it finds all users. I guess you are the first one to actually use this API (it was initially meant for a service at CERN to book a room on the fly by swiping your employee ID card in the room itself, but that never happened in the end). ;)

Try adding a `_join=User.identities` to the` .find_all()` call arguments.

**Comment by stephangoedecke** [comment]
The fix brought the whole thing a little bit further, but now it ends with a 500 Server error. The log says
`2018-08-20 16:28:42,960  ERROR    9b093b1e661849b4  indico.flask              can't set attribute
Traceback (most recent call last):
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/indico/web/http_api/handlers.py", line 222, in handler
    res = hook(user)
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/indico/web/http_api/hooks/base.py", line 194, in __call__
    is_response, resultList, complete, extra = self._perform(user, func, extra_func)
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/indico/web/http_api/hooks/base.py", line 169, in _perform
    resultList, complete = self._performCall(func, user)
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/indico/web/http_api/hooks/base.py", line 155, in _performCall
    res = func(user)
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/indico/modules/rb/api.py", line 227, in api_roomBooking
    reservation = Reservation.create_from_data(self._room, data, user)
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/indico/modules/rb/models/reservations.py", line 366, in create_from_data
    setattr(reservation, field, data[field])
AttributeError: can't set attribute
`

**Comment by ThiefMaster** [comment]
Try removing these two lines. We changed them to properties at some point after we made a link to an existing indico user for each booking required (before that a booking used freeform text for the user a booking was made for):

```
'contact_email': self._params['booked_for'].email,
'contact_phone': self._params['booked_for'].phone,
```

**Comment by stephangoedecke** [comment]
Thank you - the booking API is working correct now.

Would be sad if that API would go away as there are only a few open source booking system that offer an API for room booking.

**Comment by ThiefMaster** [comment]
Would be interesting to know about your usecase for the API. Maybe you want to post something on how you use it in [our forum](https://talk.getindico.io/)?

Anyway, since we are moving the room booking system to react in 2.2, it'll be very easy to provide an API since the new room booking frontend itself is also API-based.
