### ISSUE TITLE
Hide materials that the visitor cannot see

### ISSUE THREAD

**Issue by mpounsett** [indico/indico#3504]
Indico allows for materials to be restricted so that they can only be viewed by certain users.  But, it still shows the existence of those materials to everyone, even guests (unauthenticated visitors).  This results in un-viewable material being indexed in search engines, etc.  

Indico should only show links to material in the Timetable if the visitor is able to view the material.

**Comment by ThiefMaster** [comment]
If you create a folder you can configure it to be hidden to anyone with no access.
