### ISSUE TITLE
Registering multiple attendees at the same time

### ISSUE THREAD

**Issue by Yasharah** [indico/indico#3512]
Hello,
we have one “problem” with indico at the moment and that is that we host multiply family events a year, where one person should be able to register himself and his family members with one registration, because the kids often dont have an emailaddress of their own. We want to see that one person registered 4 attendees and those 4 tickets should be substracted from the total ticket contingent. Is this somehow possible at the moment?

**Comment by olifre** [comment]
We do have a similar requirement, In our case, the use case is also to register families for outreach events. 
Additionally, this would be interesting to register, for example, attendants with spouses (for a workshop dinner, bus for transportation, accomodation).

**Comment by olifre** [comment]
I believe that has been implemented in 3.2 via the "Accompanying Persons" registration form field, which offers the option:
"Accompanying persons count against registration limit"

**Comment by ThiefMaster** [comment]
Indeed!
