### ISSUE TITLE
Error when going to booking page, then landing, then back

### ISSUE THREAD

**Issue by ThiefMaster** [indico/indico#3539]
Open `https://.../rooms-new/book?recurrence=single&number=1&interval=week&sd=2018-09-18&st=13%3A00&et=14%3A00`, then click on "Room Booking" to get to the landing page.

> Warning: `<Route>` elements should not change from uncontrolled to controlled (or vice versa). You initially used no "location" prop and then provided one on a subsequent render. browser.js:49
> Warning: `<Route>` elements should not change from controlled to uncontrolled (or vice versa). You provided a "location" prop initially but omitted it on a subsequent render.

Then use the browser's back button to go back to the booking page. This triggers an API request with a null `end_dt` failing with 422

**Comment by mic4ael** [comment]
What is the point of this conditional rendering? That seems to be the problem for the warning that we get. Rendering it unconditionally removes the problem.

```
{!isInitializing && (
    <>
        <Route path="/book" render={({location, match: {isExact}}) => (
            filtersSet
                ? (
                    <BookRoom location={location} />
                ) : (
                    isExact ? <Landing /> : <Redirect to="/book" />
                )
        )} />
        <Route path="/rooms" component={RoomList} />
        <Route path="/blockings" component={BlockingList} />
        <Route path="/calendar" component={Calendar} />
    </>
)}
```

**Comment by mic4ael** [comment]
Hm, replacing it with something like `<Route path="/rooms" render={() => !isInitializing ? <RoomList /> : null} />` helps.
