### ISSUE TITLE
Cannot add external user to event ACL

### ISSUE THREAD

**Issue by ThiefMaster** [indico/indico#3562]
We did not support this in the past, but with the new ACL widget we allow selecting external users, but saving the entry fails:

> Id 'cern-ldap:loremipsumloremipsum' is not a number and allow_pending=False

Let's either

- disable searching externals or
- allow saving such users

I'm inclined to go for the second option, since it's clearly useful in some cases, e.g. this:

> but i want to import contacts because i nead to restrict the access to a a conference to a group of users, so i need to have these users defined...

**Comment by pferreir** [comment]
If there is no inconvenience to saving those users, I can't see why not. The only issue I can see is pending identities remaining stale whenever an identity manager is removed from the config. But that doesn't seem like a big deal to me.

**Comment by culpinnis** [comment]
Thanks for your very fast reply :) !
For me, it is not working yet. 
![image](https://user-images.githubusercontent.com/2099798/50971494-67ea0600-14e4-11e9-94b1-9cb6eafb1212.png)

Could it be, because the access to the created lecture is (still) restricted to organisational persons? - it is located in a testing category until it will be publicly available.
Best wishes
Chris

**Comment by ThiefMaster** [comment]
OK indeed, the bug is there as well. I'm *very* surprised nobody else noticed this...

**Comment by ThiefMaster** [comment]
Found the problem, it was broken during a refactoring in 683efb9ff80. I don't think we'll make a new 2.1.x release just for this but you could easily apply the fix manually.

- Speakers/Chairpersons: c6d1b7a
- ACLs: 048ec5e

If you want to patch the file(s) manually, you can edit `/opt/indico/.venv/lib/python2.7/site-packages/indico/...` and reload/restart uwsgi once you are done.

**Comment by culpinnis** [comment]
Okay great! I will apply the fix manually. 

Best wishes & many thanks
Chris
