### ISSUE TITLE
Validate email addresses in contribution csv import

### ISSUE THREAD

**Issue by ThiefMaster** [indico/indico#3568]
Currently we don't, and if someone mixes up e.g. affiliation and email that results in very messy data.

`import_contributions_from_csv` already has some checks, but it's missing one using `validate_email`. Note: The email is optional, so we should only validate it if it's not empty.

**Comment by zilehuda** [comment]
working on it (Y)

**Comment by zilehuda** [comment]
Can you please explain more about your issue ? on which file / module you are using `import_contributions_from_csv`

**Comment by ThiefMaster** [comment]
Nice! If you have any questions feel free to join our IRC channel (#indico on freenode) or ask here.

Also, to test it, you might want to install Indico locally - instructions on how to setup a local development environment can be found [here][1].

Regarding your second comment: A quick search shows that the function is defined in `indico/modules/events/contributions/util.py`.
To actually use it from the UI, you need to create an event (type "conference"), then go to the "Contributions" page in the management area, and click on "Import".

[1]: https://docs.getindico.io/en/latest/installation/development/

**Comment by ThiefMaster** [comment]
@zilehuda: In case you are still working on this: Someone else provided a PR for it yesterday, so this issue is now solved.
