### ISSUE TITLE
can't build dirhtml after fresh install

### ISSUE THREAD

**Issue by bjb** [indico/indico#3583]
I wanted to try indico first time - git cloned indico, made a pythonenv for it called "INDICO", ran pip install -r requirements.txt.  Then tried to enter docs directory and make dirhtml (same happens for make html):

<pre>
(INDICO) bjb@bee:~/work/mojatatu/admin/2018/indico/indico/docs$ make dirhtml
sphinx-build -b dirhtml -d build/doctrees   source build/dirhtml
Running Sphinx v1.8.1

Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/usr/local/pythonenv/INDICO/local/lib/python2.7/site-packages/sphinx/config.py", line 368, in eval_config_file
    execfile_(filename, namespace)
  File "/usr/local/pythonenv/INDICO/local/lib/python2.7/site-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "/usr/local/pythonenv/INDICO/local/lib/python2.7/site-packages/six.py", line 709, in exec_
    exec("""exec _code_ in _globs_, _locs_""")
  File "<string>", line 1, in <module>
  File "/home/bjb/work/mojatatu/admin/2018/indico/indico/docs/source/conf.py", line 20, in <module>
    import sphinx_rtd_theme
ImportError: No module named sphinx_rtd_theme

make: *** [Makefile:47: dirhtml] Error 2
</pre>

I have a debian stretch system, and I have python-dev and python-sphinx ( 1.7.9-1) installed.    The python version in the virtualenv is Python 2.7.14+.

I think requirements.txt should pull in what I need to build the docs.  I cannot find anything called "sphinx_rtd_theme" by using pip search.  I did install a couple of other packages with rtd in the name but it didn't help ( lsst-dd-rtd-theme==0.2.1, stsci-rtd-theme==0.0.1).

**Comment by ThiefMaster** [comment]
`pip install sphinx_rtd_theme` if you want to build the docs. If this fixes it for you, feel free to send a PR adding the package to `requirements.dev.txt`.

PS: You can use https://docs.getindico.io/en/latest/ if you just want to read the docs. No need to build them yourself.

**Comment by bjb** [comment]
Thank you.  I was able to install sphinx_rtd_theme using pip ... not sure why I could not see that name with pip search but the install worked.  Now it fails with a whole bunch of "WARNING: autodoc: failed to import module u'modules.users.util' from module u'indico'; the following exception was raised:
No module named indico".  Do I have to somehow install indico before making docs?
