### ISSUE TITLE
Need a mechanism that returns the child categories of a category or a field that in the events that contain the caller category.

### ISSUE THREAD

**Issue by sboutas** [indico/indico#3595]
Indico doesn't provide an API that you can get the subcategories of a category. For example a category C has two childs C1 and C2 and child C1 has two more C1-1 and C1-2.

It would be nice if we had an API that when you query it with category C you get all the subcategories in it (C1, C1-1, C1-2 and C2). Also when you query with C1 only should give you C1-1 and C1-2 etc.

When you query Indico with a category to get events, the API will return you all the events from this category and its subcategories. The thing is that the Event has a field with its ID and its category's id but not the category id that you initially made the query.

For example if you query Indico with category C it will return you events from categories C1, C1-1, C1-2 and C2. The events from C1-1 will be tagged with category id C1-1 and not C even if the query was made for the parent category C. There should be another field which will include the category id that made the call (in this case C).

That is a very important feature. Imagine having a set of audiences and each audience has many Indico categories under it. When you pull events you can tag them with an audience based on the audience categories. But if the returned events they don't have the category that made the call (the parent one) but only the subcategory id where they belong you can't tag them with an audience. You have to include all the subcategories in your audience which can be hundreds in some cases and it won't be easily maintainable since you can't keep an eye always what other subcategories might added under the parent category and if you miss them you can't tag the new events with the audience.

The solution will be either to provide a new field in the events that includes the category id that made the call or to provide an API that when you query indico with a category id it returns all the children.

The easiest solution will be the addition of the new field that includes the category id that made the call. The second solution with the API will require extra development from the user side to use the information provided.

**Comment by ThiefMaster** [comment]
> The easiest solution will be the addition of the new field that includes the category id that made the call.

But this is information you have on your side when making the call, don't you? Or are you doing a single call with multiple category IDs so you cannot know from which of these categories the event is?

**Comment by ThiefMaster** [comment]
I just remembered that we include `additionalInfo.eventCategories` in the output when exporting events from categories. Can you check if this already includes the information you need?

**Comment by sboutas** [comment]
Yes I am making a single call with multiple categories. The events returned
don't have the parent category id but the category id that they belong to.
It would be great if they could also have a field with the parent category
id who made the call.

**Comment by sboutas** [comment]
Unfortunately this doesn't help. It has to be either a call to the API that returns the subcategories of the category that you requested or the called category id to be included in the events as field.

**Comment by pferreir** [comment]
@sboutas I'm not sure I'm understanding. This endpoint returns the events within a category, each one pointing to its own direct parent sub-category, and then a map of all the subcategories within the originally requested category. It works OK also when you request more than one category at once. Isn't this enough to figure out which high-level category any of these events belong to?

Or maybe you're not using the `/export/categ/xxx-xxx-xxx.json` endpoint but something different which doesn't export this data?

**Comment by sboutas** [comment]
@pferreir actually you are right. I can work with this information. Thank you @ThiefMaster !
