### ISSUE TITLE
Add Room statistics

### ISSUE THREAD

**Issue by pferreir** [indico/indico#3617]
Currently missing, as you can see:

![image](https://user-images.githubusercontent.com/2699/47300721-7a5b4e80-d61d-11e8-99a6-22dd2f7c25e1.png)

Important statistics:
 * % occupancy of room (during working hours as defined by `Location.working_time_periods`) in the last 7, 30 and 365 days (or similar);
 * Number of bookings this week/month/year;
 * Any other ideas?

**Comment by mvidalgarcia** [comment]
Popularity? Like the position in a ranking of the most booked rooms. This value could be also taken into account to sort the room results if needed.
