### ISSUE TITLE
Take `booking_limit` setting into account

### ISSUE THREAD

**Issue by ThiefMaster** [indico/indico#3630]
Return the value in `RHConfig` and then prevent ranges exceeding that number of days from being selected in the date picker.

We can also fail API requests exceeding this limit to avoid very slow/expensive queries.

**Comment by pferreir** [comment]
After discussion with @ThiefMaster and @panagiotappl, the conclusion is that the easiest way to implement this is probably to have a maximum number of occurrences and check it both on the client and server. That would be:
 * for daily bookings, an easy calculation of day difference (weekends excluded);
 * for recurring bookings, we could use `rrule` (client and server).

**Comment by ThiefMaster** [comment]
when using a rrule on the client let's be careful about the special case for monthly repetition:

https://github.com/indico/indico/blob/master/indico/modules/rb/models/reservation_occurrences.py#L135-L161

**Comment by pferreir** [comment]
Duplicate of #3567
