### ISSUE TITLE
Registration: unregister

### ISSUE THREAD

**Issue by SethosII** [indico/indico#3650]
There is currently no way for a normal user to unregister. They have to write to the event managers and they have to remove them by hand and write to them.

It would be great if there was a way for a normal user to unregister from an event in case of some impedement. Also an automated mail when someone is removed would be useful.

This is also needed for a waiting list, see https://github.com/indico/indico/issues/3036.

**Comment by kingspride** [comment]
Hello, this was brought up today at our institute - will this get implemented sometime or is it already?
would be really handy.

thanks

**Comment by ThiefMaster** [comment]
withdrawing your registration has been implemented in #4585
