### ISSUE TITLE
Static image assets missing from pip package?

### ISSUE THREAD

**Issue by kav2k** [indico/indico#3657]
Following install instructions from https://docs.getindico.io/en/latest/installation/production/debian/nginx/ to the letter, static assets (images) are missing from the installation.

In fact `/opt/indico/web/static/` (referenced by nginx config) isn't created at all.

**Comment by ThiefMaster** [comment]
If you are doing a production setup, use https://docs.getindico.io/en/stable/installation/production/debian/nginx/ - you used the docs for the upcoming version.

**Comment by kav2k** [comment]
Thanks, my bad.
