### ISSUE TITLE
ElasticTimeline: add data for days in-between

### ISSUE THREAD

**Issue by pferreir** [indico/indico#3667]
Example:

![image](https://user-images.githubusercontent.com/2699/48903645-6a24d200-ee5c-11e8-80c2-50d1afa3eeb2.png)

We should have the booking data for all displayed days. It could somehow be shown in some kind of paler color or with some transparency.

**Comment by ThiefMaster** [comment]
Is is really that useful to have by default? Unless I need to resolve conflicts I'd probably think why I see all this extra noise. Also, it'd make the monthly view much slower - and especially in that view there would me much more noise than useful information.
