### ISSUE TITLE
Free Text (Label) in Registration not shown in Modification

### ISSUE THREAD

**Issue by knusperman** [indico/indico#3682]
**Describe the bug**
When placing a label (free text) in a registration form it is only shown at the registration itself, but when I want to modify the registration, I do not see the label. Likely this bug has appeared in 2.1.x, because I am almost certain that in 2.0.x it worked.

**To Reproduce**
1. Create an event and a registration form
2. Add a "free text" aka label field to it 
3. Open up the registration and register (you will see that your label is there)
4. Modify the registration afterwards (no label there) 

I also checked it on the sandbox.getindico.io

**Expected behavior**
I expect the label to be also present when being in modification mode. The whole point of it is to allow resubmitting information as a registrant, therefore I do not only need the modifiable fields but also the labels that have some reason to be there (e.g. stating "please only choose type x, when you are under 18...) 

**Screenshots**
<img width="997" alt="screenshot 2018-12-04 at 18 30 30" src="https://user-images.githubusercontent.com/7829685/49460985-f20ec280-f7f2-11e8-968d-d355d822ad73.png">
<img width="800" alt="screenshot 2018-12-04 at 18 30 59" src="https://user-images.githubusercontent.com/7829685/49460987-f2a75900-f7f2-11e8-9fa2-b95fca118b44.png">

**Comment by ThiefMaster** [comment]
Looks like a bug I introduced 3y ago in fc5ec8e8983. Will be fixed in 2.1.5 which will be released within the next days.
