### ISSUE TITLE
Link room booking to event/contribution/session block

### ISSUE THREAD

**Issue by mvidalgarcia** [indico/indico#3707]
This issue is part from #3693 
- Update `Reservation` model to add `contribution_id` and `session_block_id`
- URL query parameters that allow linking the booking to an event, contribution or session block
- Display appropriate information in the book a room modal indicating the that the booking is going to be linked
- Only allow linking bookings to event managers
- Display appropriate info in the booking modal ("This booking is linked to foo event")

**Comment by pferreir** [comment]
Related to #1314.
