### ISSUE TITLE
Set uniform, consistent color code for bookings and other timeline elements

### ISSUE THREAD

**Issue by ThiefMaster** [indico/indico#3710]

**Comment by ThiefMaster** [comment]
The cancel action for bookings is currently gray. What about yellow/danger?
Actually I wonder if reject/cancel should even have different colors.. both are basically the same except that they are done by different people, and except admins nobody can do both.

**Comment by ThiefMaster** [comment]
Should occurrences of a prebooking in the booking details view use the prebooking style?

**Comment by meluru** [comment]
> The cancel action for bookings is currently gray. What about yellow/danger?
> Actually I wonder if reject/cancel should even have different colors.. both are basically the same except that they are done by different people, and except admins nobody can do both.

I'd keep different colors. it's good to know which occurrences/bookings you cancelled yourself and which were rejected by somebody

> Should occurrences of a prebooking in the booking details view use the prebooking style?

I think yes, it's good to be consistent.
