### ISSUE TITLE
Default indico logo image in header and footer not displaying (404)

### ISSUE THREAD

**Issue by selloween** [indico/indico#3729]
**Describe the bug**
Default indico logo image in header and footer not displaying (404)
Looking in the web inspector the image paths seam to be wrong.

**To Reproduce**
1. Go to 'homepage'

**Expected behavior**

Should be:
`<img src="/static/images/indico_small.png" class="footer-logo" alt="Indico">`

is:
`<img src="/images/indico_small.png" class="footer-logo" alt="Indico">`

**System details**
- Indico version installed (2.1.6)
- Python version used (2.7.12)
- Postgres version used (9.6.11)
- Operating system used (Linux Ubuntu 16.04)

**Comment by ThiefMaster** [comment]
The URL is correct. That's why there are aliases in the config:

```nginx
# nginx
location ~ ^/(css|images|js|static(?!/plugins|/assets|/themes|/custom))(/.*)$ {
  alias /opt/indico/web/htdocs/$1$2;
  access_log off;
}
```

```apache
# apache
AliasMatch "^/(css|images|js|static(?!/plugins|/assets|/themes|/custom))(/.*)$" "/opt/indico/web/htdocs/$1$2"
```

When using the dev server there's also an alias in the code for it.

So if you get a 404 please check your webserver log; maybe something is wrong with your aliases.

**Comment by selloween** [comment]
Thx for your fast reply and the hint. 

You are right my aliases in the config were wrong. I copy pasted them from the installation guide.
Nevertheless the images folder is located in htdocs and not in htdocs/static. 

However the fonts directory is located in htdocs/fonts. I had to change the alias and move the images folder into static. Now it's working.

***Was:***
  ```
location ~ ^/(images|fonts)(.*)/(.+?)(__v[0-9a-f]+)?\.([^.]+)$ {
    alias /opt/indico/web/static/$1$2/$3.$5;
    access_log off;
  }
```

***Now:***
  ```
location ~ ^/(images|fonts)(.*)/(.+?)(__v[0-9a-f]+)?\.([^.]+)$ {
    alias /opt/indico/web/htdocs/static/$1$2/$3.$5;
    access_log off;
  }
```

**Comment by ThiefMaster** [comment]
This sounds like you were mixing up the stable/latest install guides. For 2.1 you need stable: https://docs.getindico.io/en/stable/installation/production/centos/nginx/

**Comment by selloween** [comment]
Looks like it. My bad. Thanks for helping out anyway.
