### ISSUE TITLE
Properly check override permissions in get_rooms_conflicts

### ISSUE THREAD

**Issue by mvidalgarcia** [indico/indico#3762]
Similar to what was done in `search_for_rooms` in #3745

**Comment by ThiefMaster** [comment]
This is used in two places btw:

- suggestions
- timeline

I think it only makes sense for the timeline to send whether godmode is enabled - for finding possible suggestions I would never take admin privs into account. Not worth the extra complexity IMO.

**Comment by ThiefMaster** [comment]
(wth who though it'd be a good idea to put a close button right next to "go to issue" in the boards?!)
