### ISSUE TITLE
Add a "back to top" tooltip

### ISSUE THREAD

**Issue by pferreir** [indico/indico#3763]
The new burotel requires a lot of scrolling across rooms/desks. People who are not that mouse-friendly may have a bad time rolling their mousewheels for Kilometers at at time.
I am thinking of a discrete tooltip in the bottom right corner, which when clicked scrolls back up. But suggestions are welcome.
This could be interesting for the core system.

**Comment by mvidalgarcia** [comment]
I think what you mentioned is a common pattern in websites. Something like this.

![image](https://user-images.githubusercontent.com/8863238/53348414-4bcae880-391b-11e9-8ab4-bf7469118dd1.png)

Do we want this in all scrollable pages? And do we want if for the core in the end?

**Comment by pferreir** [comment]
I think it doesn't hurt to have it in the core system. And I like that pattern.
