### ISSUE TITLE
Add a "default group" option

### ISSUE THREAD

**Issue by pferreir** [indico/indico#3766]
Users who always book desks for the same experiment do not need to change their initial experiment/group selection at all. They would be very happy if we could make things easier for them.

I can see this done two ways:
 * a profile setting;
 * just a localStorage-saved setting;

![image](https://user-images.githubusercontent.com/2699/52647398-ed4a4700-2ee4-11e9-8d0c-69b7717cd918.png)

**Comment by ThiefMaster** [comment]
Sounds like a good use case for a UserSetting. Doesn't even need to be in the user profile (but could be, we have signals for it that are used e.g. in the outlook plugin), since it could be updated whenever you search, assuming that's the default you want the next time.
