### ISSUE TITLE
Force to use 24 hour format in Registration form

### ISSUE THREAD

**Issue by mvala** [indico/indico#3799]
**Describe the bug**
When creating form for registration and i add "DATE" field. It show in US time format with AM/PM. Is it posible to force to use 24 hour format?

**To Reproduce**
1. Go to 'Registration and add DATE field'
2. Add new registration

**Expected behavior**
Users would see 24 hour format in registration field

**Comment by ThiefMaster** [comment]
I think we're using an `<input type=time>` field there - and unfortunately certain browsers really like to use 12h format there...

In case you are using firefox, here's an issue I opened about it a year ago: https://bugzilla.mozilla.org/show_bug.cgi?id=1425218
Especially the last comment there is very interesting. From what I understood, someone using German Firefox on German Windows gets 24h for example (if that's how it's configured in the OS), but as someone using English Firefox on German Windows, I have to override this by setting `intl.regional_prefs.use_os_locales` to true in about:Config.

FWIW, while this logic seems strange, I guess it means that most Firefox users get the default format as configured for their language in the operating system's settings.

**Comment by mvala** [comment]
I am using firefox and when i have en_GB locale on my system, it shows 24 h format. When en_US then 12h format. When using Russian (it should have 24h format), but in indico 12h format. Very strange. Is it possible to force it for whole indico instance?

**Comment by ThiefMaster** [comment]
No, this is up to the browser...

**Comment by mvala** [comment]
I see. Then is it possble to add default value 00:00:AM. Becase "--:--:--" Doesn't explain too much. Or at least put placeholder there.

**Comment by ThiefMaster** [comment]
I think that way the risk of people just leaving the default value would be somewhat high

**Comment by mvala** [comment]
And placeholder with time example?

**Comment by mvala** [comment]
Sorry, i meant tooltip

**Comment by ThiefMaster** [comment]
I think we removed all `<input type="time">` fields some time ago, so this should be obsolete.
