### ISSUE TITLE
Changes in menu entry not saved if pressed during editing of source code

### ISSUE THREAD

**Issue by jan-busa** [indico/indico#3805]
When I edit some text in Menu Entry Settings (like Announcements or Information for conference participants), I usually enter new text, then I press button Source to edit manually html code and then I press button Save, which closes Editor but the changes ARE NOT saved. In order to save my changes I have to click again the Source button to see the non-html version of the page and only then press the Save button.

What I expect is that either it should not be possible to press Save button when directly editing html, or the changes should be saved. As a side note on this, when I directly press Source and start straight with changes of html, than the button Save stays disabled as I didn't do any changes, but I think this is desired behavior.

I think, our current version of Indico is 2.1.7.

**Comment by ThiefMaster** [comment]
Indeed, you need to switch back to WYSIWYG mode before the source changes are taken into account.

That's CKEditor's behavior and AFAIK it can't be changed. I don't think it has any callback when entering/leaving source mode, so we can't easily disable the save button while in source mode either.
