### ISSUE TITLE
Filter users on Participants List

### ISSUE THREAD

**Issue by jan-busa** [indico/indico#3806]
We would like to have on our conference Participants List visible to all. Unfortunately with new GDPR rules participants have the right to request not to be visible on this list. Therefore we need some way to create a Participants List which contains only persons that comply to some filter (e.g., during Registration agreed for their names to be shown). Of course I can filter users as administrator, then download this list as csv/pdf and upload it back to the site but I don't think this is a proper approach.

I have noticed, that as administrator in the List of registration I can create a filter with what I need and I can also get a link to the current setting of the filter. Maybe the easiest way would be to allow to a general user to visit such link. Only downside I see (as user), that then the users should not see the participants ID, which is added automatically when such filter is created.

**Comment by ThiefMaster** [comment]
Already planned - see #1415:

> A mechanism whereby users consent explicitly to having their name listed on the public "List of Participants" (only if the organizer wants the list to be visible);
