### ISSUE TITLE
Installing indico - httpd.service failed to start - 

### ISSUE THREAD

**Issue by zmohamoud** [indico/indico#3808]
httpd.service - The Apache HTTP Server
   Loaded: loaded (/usr/lib/systemd/system/httpd.service; disabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Wed 2019-03-06 20:44:31 UTC; 4min 43s ago
     Docs: man:httpd(8)
           man:apachectl(8)
  Process: 17817 ExecStop=/bin/kill -WINCH ${MAINPID} (code=exited, status=1/FAILURE)
  Process: 17816 ExecStart=/usr/sbin/httpd $OPTIONS -DFOREGROUND (code=exited, status=1/FAILURE)
 Main PID: 17816 (code=exited, status=1/FAILURE)

Mar 06 20:44:31 ip-10-200-136-68.ec2.internal systemd[1]: Starting The Apache HTTP Server...
Mar 06 20:44:31 ip-10-200-136-68.ec2.internal systemd[1]: httpd.service: main process exited, code=exited, status=1/FAILURE
Mar 06 20:44:31 ip-10-200-136-68.ec2.internal kill[17817]: kill: cannot find process ""
Mar 06 20:44:31 ip-10-200-136-68.ec2.internal systemd[1]: httpd.service: control process exited, code=exited status=1
Mar 06 20:44:31 ip-10-200-136-68.ec2.internal systemd[1]: Failed to start The Apache HTTP Server.
Mar 06 20:44:31 ip-10-200-136-68.ec2.internal systemd[1]: Unit httpd.service entered failed state.
Mar 06 20:44:31 ip-10-200-136-68.ec2.internal systemd[1]: httpd.service failed.

**Comment by ThiefMaster** [comment]
Check the error logs; the output there isn't really useful.

Also, please use our forum for this kind of question: https://talk.getindico.io/
