### ISSUE TITLE
Timeline hours in the `Sticky` filter bar

### ISSUE THREAD

**Issue by pferreir** [indico/indico#3819]
We should see whether this is feasible.

![image](https://user-images.githubusercontent.com/2699/54348716-eb8db380-4649-11e9-8c04-a73689c21521.png)

(sorry for the mediocre mock-up)

**Comment by ThiefMaster** [comment]
This sounds pretty tricky/messy since I think the timeline is much deeper than the filter bar.

**Comment by pferreir** [comment]
Too complicated indeed. Closing for now.
