### ISSUE TITLE
Handle conflicting pre-bookings.

### ISSUE THREAD

**Issue by pferreir** [indico/indico#3825]
We do not currently render the conflicts between overlapping pre-bookings, despite the fact that they may indeed overlap.
We had that in the previous interface.

Tasks: 
- Display conflicting pre-bookings as available when searching just with a warning (in book room dialog) that there are conflicts (similar to the "some occurrences will be skipped"): something like "conflicting pre-bookings will be rejected" if you **book** and "there are other pre-bookings overlapping" if you also just **pre-book**.
- Allow creating overlapping pre-bookings
- When one of the overlapping pre-bookings gets confirmed, cancel the remaining one.
- Display in calendar pre-booking conflicts differently ("Conflict between pre-bookings")

**Comment by ThiefMaster** [comment]
> Allow creating overlapping pre-bookings

Already the case I think

> When one of the overlapping pre-bookings gets confirmed, cancel the remaining one.

I believe `Reservation.accept()` does that.
