### ISSUE TITLE
Provide a way to edit room ACLs

### ISSUE THREAD

**Issue by pferreir** [indico/indico#3827]
Easy on the backend, the hard part is the frontend. We need something like the PermissionsField in react.

So basically a way to add users/groups to an ACL and selecting which permissions each entry has.

**Comment by ThiefMaster** [comment]
The new react `PrincipalListField`, once merged, may provide a good basis for this. When implementing it, please try to avoid adding all this extra complexity to the field itself but rather wrap it or add props to customize relevant parts.
