### ISSUE TITLE
Admin Area: Manage locations - delete/edit/create

### ISSUE THREAD

**Issue by pferreir** [indico/indico#3830]
This is still unimplemented.

![image](https://user-images.githubusercontent.com/2699/54351015-db2c0780-464e-11e9-86a8-544b5a33b7fd.png)

**Comment by ThiefMaster** [comment]
Since we hard-delete here, I think deleting a location should only be possible if it has no rooms. Yes, this is more work for a user who wants to delete a location, but chances are good people do not want to delete locations with active rooms.
