### ISSUE TITLE
VC Assistance: migrate existing reservations

### ISSUE THREAD

**Issue by mvidalgarcia** [indico/indico#3854]
With reservations that have a linked event, we can just link the new request to the corresponding event.
As for reservations with no associated event, we should just dump a list of those so that the VC support team can handle them by hand.

**Comment by mvidalgarcia** [comment]
[Migration script](https://gist.github.com/mvidalgarcia/71feb75e6f29d6585b02145694828f42)

**Comment by ThiefMaster** [comment]
Closing since there's nothing to merge
