### ISSUE TITLE
Registration Form not processed apparently because of http 

### ISSUE THREAD

**Issue by elamibru** [indico/indico#3860]
**Describe the bug**
Hello, 
We have installed Indico on a development server (having an URL starting with https://) in order to prepare and test it before passage to production.  We configured some events (conference and meeting), where we would like that the participants register themselves. However, we encounter the following issue with the Registration Form: when someone tries to register as a participant into an event (as a guest, as a registered user, and even as an administrator), nothing happens : the filled in data is lost. 
The Debug Console indicates us that the Query associated with the Submit button is of type POST and has an URL starting with http://, and we cannot understand why. We suppose that the Query is rejected by the browser (because of the http:// instead of https://), and the form data do not reach the server actually, thus the registration is not considered.
Could someone please help us to solve this issue, such as to have a well-functioning Registration Form ? 
Should you need some complementary information, please do not hesitate to contact me.
Thank you,
Best regards,
Mihaela

**To Reproduce**
1. Go to a specific event (e.g. a conference or a meeting)
2. Click on 'Register for the event"
3. Fill in the registration form
4. No message appears, but the form to be filled in again. 
5. Click on F12 (to display the debugging console) and thent to Network tab : the information provided above is retrieved
6. Click on 'List of participants' in the menu. You can see that you are not among the participants
7. As administrator, click on "Registration", "Participants" : the new registration is not present
8. Moreover, if you try to add manually (in this administration area) the new participant, the filled in data is not considered neither.

**Expected behavior**
 have a well-functioning Registration Form

**Comment by ThiefMaster** [comment]
You need to make sure the `BASE_URL` in the indico config file is correct (don't forget to reload/restart uwsgi after editing it).

**Comment by elamibru** [comment]
Hello,
Thank you for your reply. I can confirm you that the BASE_URL is correctly set up on the https-based site address, and that I have already restarted (multiple times) uwsgi service, alonside with httpd and celeri-indico services. The Form remains un-responsive to our tentatives of registering into an event.

**Comment by ThiefMaster** [comment]
Do you have a link to the instance?

**Comment by elamibru** [comment]
Hello,
Thank you for your availability to check our Web site.
However, the link is not accessible from the exterior of our institution, since Indico is installed on a development server. Please find some screenshots and the configuration file (without passwords) at the address [](https://nextcloud.isae.fr/s/L7Aqo6QzGZZoyF2). If it is possible for you, we could use a remote desktop application (such as AnyDesk) and the phone to take a look to our Indico Web site from my machine. Please let me know if it is possible for you to find a timeslot on Monday, at your convenience starting with 1pm CET. 
The trials that we have done today are :
- cleaning out the indico cash directory, since there were some generated Javascript file
- trying to understand how it is generated the HTLM Form associated with the Registration, form where the “action” and the “post-url” attributes are set up on a HTTP URL (see Registration Form_html element.JPG) => not succeeded
- dropping the entire database, as well as  cleaning out all the content of indico directory in order to restart from scratch
- reinstalling Indico => similar unsuccessful results
Should you need any other details, please do not hesitate to contact me,
Best regards,

**Comment by ThiefMaster** [comment]
i don't see any attachments. maybe you could post in our forum - https://talk.getindico.io/ - and attach the files and the information there? this would be a better place for your question anyway.

**Comment by elamibru** [comment]
Sorry, I missed to mention the address with attached files. It is : https://nextcloud.isae.fr/s/L7Aqo6QzGZZoyF2
Can you confirm you can access it ? If yes, I think to not duplicate the issue on the forum, except if you tell me it is better.
Thank you

**Comment by elamibru** [comment]
Hello,
OK, I finally opened an issue also on the Indico Forum : https://talk.getindico.io/t/registration-form-not-processed-apparently-because-of-http/1095
Thank you for your suggestion,
Hoping to recevive some help,
Mihaela

**Comment by ThiefMaster** [comment]
https://talk.getindico.io/t/registration-form-not-processed-apparently-because-of-http/1095/16?u=thiefmaster
