### ISSUE TITLE
Granular authorization

### ISSUE THREAD

**Issue by deesto** [indico/indico#3871]
As far as I can see, from the documentation and from experience, it is not possible to authorize the management of user groups to a member of that group, nor for event or category managers to create and maintain user groups. Would it be possible to implement authorization for groups, a bit more granular than the all-or-nothing method of only the site admin being able to administer user groups?

**Comment by ThiefMaster** [comment]
Duplicate of #3040 I think.

**Comment by deesto** [comment]
Yes, thank you.
