### ISSUE TITLE
Clarify what the date that shows up at the top of registration form means

### ISSUE THREAD

**Issue by pferreir** [indico/indico#3909]
As of now we're showing the date that registration opens. The way it is currently displayed may make it seem like it is the actual date of the event.

![image](https://user-images.githubusercontent.com/2699/56805175-7c020b00-6828-11e9-943d-3ebcafedbbb2.png)

I see two options that are not necessarily exclusive:
 * Showing the date of the event;
 * Say something like "Registration open from..."

**Comment by ThiefMaster** [comment]
We did some changes related to this in #3451 (only in master)
