### ISSUE TITLE
Edit booking: Conflicts in past occurrences

### ISSUE THREAD

**Issue by mvidalgarcia** [indico/indico#3980]
**Describe the bug**
When editing booking (only dates), conflicts with past occurrences show up.

**To Reproduce**
1. Create recurrent booking that starts in the past and ends in the future
2. Cancel one of the past occurrences
3. Create a single booking when the occurrence in step 2 was
4. Edit the recurrent booking so the end date is later in the future
5. A conflict shows up where the cancelled occurrence was, in the past date of the _Booking after changes_ calendar

**Expected behavior**
Edit should happen without any conflict.

**Screenshots**
Take into account the date this issue was created (21/06/2019) as it's the date this screenshot was taken and it's relevant to understand the result.
![Screenshot from 2019-06-21 17-07-15](https://user-images.githubusercontent.com/8863238/59932417-66374d80-9447-11e9-9373-e6892cc8ebcd.png)

**Comment by mic4ael** [comment]
Was the occurrence cancelled manually by the user or cancelled as a result of a conflict with another booking?

**Comment by ThiefMaster** [comment]
I think the behavior should be the same in either case.
