### ISSUE TITLE
Need to be able to edit abstracts that have been judged

### ISSUE THREAD

**Issue by graeme-a-stewart** [indico/indico#3984]
As the Chair of a conference I get requests to update abstracts that have already been judged (correcting mistakes or updating authors). However, once an abstract is judged I am not allowed to do this. Therefore I am forced to rescind the judgement, make my edit and, carefully, rejudge the abstract in the same way.

I would very much like direct permission to edit as rescinding and rejudging is unnecessary and error prone.

**Comment by ThiefMaster** [comment]
What's the reason for editing the abstract? It is not used for anything once accepted. If the user asks for changes, they should be made to the contribution that was created from the abstract.

**Comment by graeme-a-stewart** [comment]
Ah, so they don't share the text or the author list? That's not really obvious!

**Comment by ThiefMaster** [comment]
When accepting an abstract, everything is copied to the contribution - that's why no editing is possible afterwards, since those edits would not show up in the contribution.

**Comment by graeme-a-stewart** [comment]
OK, that's clearer then and I will close this request.
