### ISSUE TITLE
Mixed content on event registration page

### ISSUE THREAD

**Issue by battosai30** [indico/indico#3994]
**Describe the bug**
A mixed content error is generated when a user try to register on an event, and it leads to a loop on the register page.

My indico instance is behind a reverse proxy (both are hosted on LXC container, managed by Proxmox). Https is handled by the reverse proxy, http is used between reverse proxy and indico instance.

Just to be precise : the language is French for my instance so maybe my traductions are not exact.

**To Reproduce**
1. Select an event
2. Click on 'Participant'
3. Fill inputs zone
4. Clic "register"
5. You're back to the same page, not registered, and a mixed content error is visible on console.

**Expected behavior**
Inscritions working :)

**Screenshots**
![image](https://user-images.githubusercontent.com/5184702/60801031-83be2400-a176-11e9-8654-50d04594da28.png)

**Additional context**

**Comment by ThiefMaster** [comment]
This is a configuration issue. Your Indico instance thinks it's running on HTTP insteadof HTTPS. Your reverse proxy needs to send the `X-Forwarded-Proto: https` header and then everything should work fine!

**Comment by battosai30** [comment]
Wow so quick and so good answer, problem solved !! 

When I will have the time, I will share my experience about Indico behind a reverse proxy (it was not an easy part xD) on a Proxmox system (for example, locales are not generated on LXC container by default, leading to a bad caracter set for Postgres database).

Thanks you a lot :)
