### ISSUE TITLE
Broken link in custom menu if tilte contains Russian letters only

### ISSUE THREAD

**Issue by mvala** [indico/indico#3998]
**Describe the bug**
Broken link in custom menu if tilte contains Russian letters only

**To Reproduce**
1. Create custom menu in conference in (/manage/layout/menu/)
2. "Add page"
3. In title specify Russian letters only.
4. Switch to display view
5. Click on link and one can see that link is  broken

**Comment by ThiefMaster** [comment]
Could you provide an example title that causes the issues? Also, how is it broken? 404? an exception?

**Comment by ThiefMaster** [comment]
This is fixed now (and deployed on the CERN instance). It will be included in the 2.2 release that's coming out soon.

**Comment by mvala** [comment]
Thank you very much
