### ISSUE TITLE
PDF export of contributions is not sorted

### ISSUE THREAD

**Issue by stefanritt** [indico/indico#4005]
**Describe the bug**
When contributions are exported as a PDF, they are not sorted. 

**To Reproduce**
- Go to https://indico.cern.ch/event/727938/manage/contributions/
- Select all contributions (takes some time!)
- Click Export / PDF
- The resulting file is not sorted by ID, nor by Title

**Expected behavior**
- Sorted by ID or by Title

**Additional context**
- Export as XLSX is sorted correctly by ID
- Export as CSV is sorted correctly by ID

**Comment by ThiefMaster** [comment]
This is fixed now (and deployed on the CERN instance). It will also be included in the 2.2 release that's coming out soon.
