### ISSUE TITLE
Names of pending people appearing in some views of the event

### ISSUE THREAD

**Issue by fede-faex** [indico/indico#4017]
**Describe the bug**
I created an event (a conference) and I have some people whose registration is still pending, thus they do not appear in the participant list. Nevertheless, I can read their names in some version of the event, e.g. using the "Indico style" theme.

**To Reproduce**
The event is the following: https://agenda.infn.it/event/18661/
The issue appears in the following ways:
- changing the theme of the event ("Change theme" button in the top-left corner), e.g. to the "Indico style" (https://agenda.infn.it/event/18661/timetable/?view=standard);
- in the page https://agenda.infn.it/event/18661/timetable/?print=1&view=standard which appears as a result searching on Google for the event;
- in the timetable page when the manager of the event chooses some of the themes for it, like the "Indico style".

**Expected behavior**
The names of the pending people should not appear anywhere.

**Comment by ThiefMaster** [comment]
Good point. It makes sense to show e.g. unpaid registrations but pending ones certainly should not be shown there.
