### ISSUE TITLE
New user registration is sexist, defaulting to a selection of "Mr." or "Mrs.", only

### ISSUE THREAD

**Issue by SoftCafe** [indico/indico#4034]
**Describe the bug**
The default prompt for Title during the registration process is "Mr." or "Mrs.".
The is no option for "Dr." or "Ms." or "none.".  That is too primitive for the
21st Century, unless you are interested in only males or their wives. 

**To Reproduce**
Use the Open Source Conference Signup (which has since been corrected):
https://indico.oscw.space/event/3/registrations/2/
Title
(The default, before OSCW's fix was the default: "Mr." and "Mrs.")

**Expected behavior**
I expect the default to work as the fix (as a minimal requirement):
https://indico.oscw.space/event/3/registrations/2/
However, since gender is not a requirement for the OSCW, I recommend 
an N/A (or 'irrelevant') selection be an option.

**Screenshots**

**Additional context**

**Comment by pferreir** [comment]
This is configurable on a per-event basis. Please contact the OSCW organizers directly.

**Comment by ThiefMaster** [comment]
This is the default in Indico when you create a new registration form:

![image](https://user-images.githubusercontent.com/179599/63186958-0a133300-c05e-11e9-90b7-e08a823bcb58.png)

And the event manager can not only customize the list but also disable the field altogether.

PS: This issue could have been written in a much less passive-aggressive ("too primitive", etc.) way.

**Comment by SoftCafe** [comment]
The OSCW rep. responded as follows:

"Hello,

Those values where unfortunately the defaults for indico (the event
management platform we chose to use for OSCW)

Thanks for bringing this to our attention. I just made sure that the
value is not optional and Dr., Ms. are now added on the list.

*Also in the spirit of open source participation, please consider
opening a PR on indico to fix the default options:
**https://github.com/indico/indico*

Regards,

~pierros
"

Re: Your PS:
You are 100% wrong.  I feel twice attacked, adding insult to injury.
It is incumbent upon us all to call out institutional and systemic
discrimination,
especially when such discrimination may prevent the benefits of
collaboration
with our peers, and when such discrimination may prevent fellow
professionals
from participating fully in professional events.

P.S. Secondly, I am shocked that a professional has reduced themselves
to name-calling,
e.g. characterizing a fellow Open Source supporter as "passive-aggressive".

**Comment by ThiefMaster** [comment]
I guess someone accidentally removed those options while setting up the registration form - maybe when trying out the various features etc. I can guarantee you that all the options are available by default (hardcoded) since a LONG time in Indico (you can check the Git history if you want to).
