### ISSUE TITLE
Ability to identify/contact presenters who are not registered for an event

### ISSUE THREAD

**Issue by graeme-a-stewart** [indico/indico#4038]
**Problem**

As the programme committee chair I want to be able to check that all presenters of contributions at my event are properly registered. I would also like to be able to contact presenters who are not yet registered, reminding them to do so.

**Solution**
In the `Contributions` management area the ticket icon could be added when the presenter is registered or a new `registered` column added.

When selecting authors from the `Author List` popup registration status should be shown and it should be possible to select all unregistered speakers, so that a reminder email can be sent.

**Describe alternatives you've considered**
Downloading the CSV of the contributions and the registrations allows some cross-referencing, which we are doing, but it also requires a lot of scripting knowledge and is not suitable for most people.

**Comment by ThiefMaster** [comment]
That's already possible - on the "Participant Roles" page we have an icon indicating whether the person has registered or not:

![image](https://user-images.githubusercontent.com/179599/63436140-790ad600-c428-11e9-9dcb-04507089b914.png)

You can also quickly send an email to selected people from that page.

**Comment by graeme-a-stewart** [comment]
Excellent - that interface I didn't know. Thanks for pointing it out.

**Comment by graeme-a-stewart** [comment]
Just checking this, then my request would be that I can one-click select registered or unregistered individuals. Right now this can only be done with a lot of box by box clicking.

**Comment by ThiefMaster** [comment]
Isn't this what you need? You can customize the email after clicking that button.

![image](https://user-images.githubusercontent.com/179599/63436784-98563300-c429-11e9-8c44-7401a33876d9.png)

**Comment by graeme-a-stewart** [comment]
I don't think so - that seems to be more related to creating indico accounts (at least if you read the hover over text and the template emails). `Send Invitation -> To unregistered users` would be a natural extension addressing the issue.

**Comment by ThiefMaster** [comment]
Ah of course, you are right. This is indeed about account creation. I think adding unregistered users makes sense there.

**Comment by ThiefMaster** [comment]
I think #4337 / #4318 implemented exactly what you are looking for here.
