### ISSUE TITLE
Find alternative to pyatom / werkzeug.contrib

### ISSUE THREAD

**Issue by pferreir** [indico/indico#4046]
With #4045 we replaced (the seemingly defunct) `pyatom` with what seems to be the same module [provided directly by Werkzeug](https://werkzeug.palletsprojects.com/en/0.15.x/contrib/atom/). Unfortunately, this module will also disappear in Werkzeug 1.0.
We should find a viable alternative (even if it means rendering it ourselves, which I'd rather not do).

**Comment by driehle** [comment]
Coul you backport this to 2.1-maintenance as well? Currently, the issue with `pyatom` breaks my Indico 2.1 pipeline. 2.2 and master are not affected, these pipelines work smothely. 

```
ERROR: Could not find a version that satisfies the requirement pyatom==1.4 (from -r requirements.txt (line 11)) (from versions: none)
ERROR: No matching distribution found for pyatom==1.4 (from -r requirements.txt (line 11))
```

**Comment by pferreir** [comment]
Done. Usual PSA about moving to 2.2 as soon as you can 😉

**Comment by pferreir** [comment]
> Could you backport this to 2.1-maintenance as well?

Done. Usual PSA about moving to 2.2 as soon as you can 😉
