### ISSUE TITLE
Add "published" flag to List of Contributions

### ISSUE THREAD

**Issue by pferreir** [indico/indico#4056]
This is a switch that would be visible on the "Contributions" page in management mode. By default it would be in "draft" state. Once all abstracts have been processed and the resulting contributions are ready for display, one would just need to click it. We'd then be in "published" mode, which would activate:
 * the *Contribution List* in display view;
 * the *Book of Abstracts* (also in display view);

The process should be reversible, of course.

**Comment by panagiotappl** [comment]
Can you still see "My Contributions" when the switch is not enabled?
