### ISSUE TITLE
Room booking: canceled bookings still displayed in the main page

### ISSUE THREAD

**Issue by jouvin** [indico/indico#4060]
The main page in the room booking displays the number of booking for the current user. If a booking in the future is canceled it still appears in the list of future booking. IMO, it is unexpected.

**Comment by jouvin** [comment]
To be more precise, I saw that I had a booking that was no needed, so I clicked on the reservation icon and canceled it. After that, refreshing the main page was not enough to get rid of it and the same with another browser. May be some latency...

Anyway I consider it a minor issue...

**Comment by ThiefMaster** [comment]
We reload the stats and upcoming bookings whenever you open the dashboard, so it's very strange that you still see anything cancelled there. Can you check the booking details if that particular occurrence was actually cancelled?

**Comment by jouvin** [comment]
Sorry for the noise... I just made a new test and it worked just as expected... Not sure what I made wrong yesterday but clearly something...!
