### ISSUE TITLE
Room booking: Indico language selection is not taken into account

### ISSUE THREAD

**Issue by jouvin** [indico/indico#4065]
Testing language selection in room booking I realized that it has its own setting, independent of the Indico one you could have made. IMO, it is unexpected. It's good to be able to select the language in the room booking menu but it is unexpected if you already defined a non-default language in Indico main page that the room booking starts in the Indico default language and that you need to select your preferred language again.

**Comment by ThiefMaster** [comment]
The selected language should be shared between all areas of Indico... the code running for the two language pickers in RB and the rest of Indico is actually the same.

**Comment by jouvin** [comment]
Thanks for your answer. I found my mistake, should have checked more... I set the language without being authenticated and then logged in. I didn't pay attention that when logged in, the language is reset to the user preference which by default is probably the instance defaut language and the language selection menu is not at the same place after being logged (it's part of the user menu with the settings...).

It is potentially a little bit misleading but there is probably nothing that can be done. I close this issue.
