### ISSUE TITLE
Room booking: typo in French translation (SearchResultCount.jsx:190)

### ISSUE THREAD

**Issue by jouvin** [indico/indico#4069]
The French message in https://github.com/indico/indico/blob/cebcf67dc090379e1bbd665fe2e9e13ff09edcf8/indico/translations/fr_FR/LC_MESSAGES/messages-react.po#L1934 has a spelling error: `cete interval` should be `cet intervalle`.

**Comment by ThiefMaster** [comment]
This seems to be fixed
