### ISSUE TITLE
Room booking (French): wrong confirmation message when removing a room blocking

### ISSUE THREAD

**Issue by jouvin** [indico/indico#4079]
When you delete the blocking of a room, the confirmation asked in French improperly ask confirmation to suppress a reservation.

This is issue is a placeholder, I don't know what is the standard workflow. I fixed the problem in transiflex.

**Comment by ThiefMaster** [comment]
No need to open GitHub issues for translation updates. We'll pull the latest translations before the next 2.2.x release.
