### ISSUE TITLE
Room booking: deleting an occurence of recurring reservation is not obvious

### ISSUE THREAD

**Issue by jouvin** [indico/indico#4092]
If you created a recurring reservation and you go to the booking calendar view, select an occurence that you want to delete and click the "Cancel booking" button, you get the message:

> Are you sure you want to cancel this booking? This will cancel future occurrences of this booking.

which let think it will delete the occurence you selected and all the following when it fact it delete the whole booking (all occurences). This is misleading and probably the date of "this booking" should be displayed in the message or the message should be more clear that it will delete all the occurences in the booking.

If in fact, you want to delete one specific occurence, you cannot do it from this button but you have to first click "See on timeline" and then select the occurence you want to delete. It is far from obvious if you never did it. IMO, it should either be better exposed or their should be some text in the windows explaining what to do for the different kind of deletions.

**Comment by pferreir** [comment]
Someone (internal ref. `RQF1484646`) suggested that we include direct links to cancel occurrences in our reminder e-mails.

**Comment by jouvin** [comment]
It would be a good addition, I agree. But is not a replacement for my suggestion as sometimes you want to cancel an occurrence before receiving the remainder.

**Comment by jouvin** [comment]
It would be a good addition, I agree. But is not a replacement for my suggestion as sometimes you want to cancel an occurrence before receiving the remainder.

**Comment by pferreir** [comment]
> But is not a replacement for my suggestion as sometimes you want to cancel an occurrence before receiving the remainder.

Agreed!
