### ISSUE TITLE
indico i18n compile-catalog error if nplural=1 (for zh_TW)

### ISSUE THREAD

**Issue by fweng322** [indico/indico#4113]
**Describe the bug**
I'm setting up an indico instance and translate it into zh_TW locale.  In zh_TW the plural form is defined as:

`"Plural-Forms: nplurals=1; plural=0;\n"`

When I added zh_TW/LC_MESSAGES/ under indico/translations/ , put the po file in it and run

`indico i18n compile-catalog`

it gave me these error messages:

```
$ indico i18n compile-catalog
error: indico/translations/es_ES/LC_MESSAGES/messages.po:2640: placeholders are incompatible
error: indico/translations/es_ES/LC_MESSAGES/messages.po:2648: placeholders are incompatible
error: indico/translations/zh_TW/LC_MESSAGES/messages.po:736: unknown named placeholder u'count'
error: indico/translations/zh_TW/LC_MESSAGES/messages.po:841: unknown named placeholder u'n'
error: indico/translations/zh_TW/LC_MESSAGES/messages.po:1500: unknown named placeholder u'count'
error: indico/translations/zh_TW/LC_MESSAGES/messages.po:10106: unknown named placeholder u'num'
```

In the po:736, 841, 1500, 10106 they all are messages containing plural forms.  For example:
```
#: indico/modules/api/templates/admin_settings.html:14
#, python-format
msgid ""
"There is currently <strong><a href=\"%(url)s\">one active API key</a></strong"
"> in the system."
msgid_plural ""
"There are currently <strong><a href=\"%(url)s\">%(count)s active API keys</a"
"></strong> in the system."
msgstr[0] ""
"目前此系統中有 <strong><a href=\"%(url)s\">%(count)s 個作用中的 API 金鑰</a></strong>。"
```

Since nplural in zh_TW is 1 and plural=0, we have only msgstr[0], but in msgid there is no %(count)s so it throws error.  The mo file was generated anyway.

**To Reproduce**
1. Add messages.po file to translations/zh_TW/LC_MESSAGES
2. source .venv/bin/activate
3. in Indico home page, run `indico i18n compile-catalog`
4. See error messages

**Expected behavior**
It should accept po files with nplural=1.

**Screenshots**

**Additional context**
I'm running Indico v2.2.4 on Debian buster using nginx, following the installation instructions from
https://docs.getindico.io/en/latest/installation/production/debian/nginx/

Now my instances does not show traditional Chinese messages but I can select language as zh_TW.  Not sure if it is because of the errors.

**Comment by fweng322** [comment]
You can get po file for zh_TW here:
https://pastebin.com/scTvP6fF

**Comment by ThiefMaster** [comment]
As long as a .mo file is successfully created, those errors can be safely ignored. It's just that the utils that compile the po file don't understand the placeholder format there for some reason.

**Comment by ThiefMaster** [comment]
Can you confirm that the .mo file is working fine regardless of these errors? In that case we can close the issue.

**Comment by fweng322** [comment]
Translated strings were shown so I think yes, .mo file works.  Just that I haven't tested those problematic (plural_form) strings yet.
