### ISSUE TITLE
Save button not enabled when adding a room in a location

### ISSUE THREAD

**Issue by fweng322** [indico/indico#4115]
**Describe the bug**
In the room booking system, add a room in a location.  In the "Add Room" dialog there are some fields marked with red asterisk which is required.  However the save button would not be enabled even all the fields were filled.  I also *need to* fill both "Longitude" and "Latitude" then the save button will be enabled, and will keep enabled even I remove the value in Longitude and Latitude.

**To Reproduce**
1. Go to Room booking system
2. Click on 'Administration'
3. Click on a pre-defined location and click "Add room"
4. In the "Add Room" dialog the save button is disabled until I fill both Longitude and Latitude

**Expected behavior**
I should be able to save the room without filling the Longitude and Latitude

**Screenshots**
![image](https://user-images.githubusercontent.com/179599/67635434-8f6d5c00-f8c7-11e9-9eec-84e52ada30c6.png)

**Comment by ThiefMaster** [comment]
Longitude/Latitude should be optional unless you fill out one of them, then both are required (since having just one value makes no sense). So indeed a bug...

**Comment by fweng322** [comment]
> Probably we need to set those two fields to `null` explicitly in the [`initialValues` used when creating a new room](https://github.com/indico/indico/blob/master/indico/modules/rb/client/js/common/rooms/RoomEditModal.jsx#L1018), since they otherwise default to `undefined`.
> 
> Do you want to test if defaulting to `null` fixed this and if it does, send a Pull Request for it (against the `2.2-maintenance` branch)?

Sorry I didn't notice these messages.  Do I still have to test it?

**Comment by ThiefMaster** [comment]
Nope, I fixed it a few minutes ago; it will be included in 2.2.5.
