### ISSUE TITLE
Create backend to receive new revisions.

### ISSUE THREAD

**Issue by pferreir** [indico/indico#4131]
The endpoint should receive:
 * the UUIDs of files to be added/replaced/deleted;
 * the target state ("Assigned" or "Requires confirmation". We should check its validity, of course);

This action can be triggered:
 * by the author/submitter
 * by an editor (it will then trigger to "requires confirmation")

**Comment by ThiefMaster** [comment]
We can probably have all the add/replace/delete logic client side and just include the final list of files in the request
