### ISSUE TITLE
Room booking 2.2.4: admin override required for adding a room

### ISSUE THREAD

**Issue by jouvin** [indico/indico#4153]
I wanted to add a room with our 2.2.4 version and I was unable to save the new room after entering its parameters until I enabled the admin override. I've the feeling that it was not like this in the first 2.2 versions. And IMO it is unexpected that if you use the Administration menu which is accessible only to Room Booking admins if I'm right, your administration privilege is not honoured without activating it explicitely. Did I do something wrong?

**Comment by ThiefMaster** [comment]
Are you sure you aren't encountering the bug fixed in #4115 instead?

**Comment by jouvin** [comment]
You are right... as usual! I just tested again. I probably added the latitude and longitude after activating the admin override, thus my mistake. I was pretty sure I tried it before but probably I did something wrong.
