### ISSUE TITLE
Improve "comments" input.

### ISSUE THREAD

**Issue by pferreir** [indico/indico#4172]
We currently have a dropdown to specify the visibility of a comment:

![image](https://user-images.githubusercontent.com/2699/69327019-25896d80-0c4d-11ea-9acf-6d121b37b9fa.png)

The mockups suggest another strategy:

![image](https://user-images.githubusercontent.com/2699/69326876-dc391e00-0c4c-11ea-9d71-4a189ebd11a7.png)

We should check which option is best and come up with something user-friendly.

**Comment by ThiefMaster** [comment]
I don't think it makes much sense to show it on the unexpanded version though...

**Comment by pferreir** [comment]
> I don't think it makes much sense to show it on the unexpanded version though...

Yes, I agree.
