### ISSUE TITLE
File Type Manager: handle publishable types

### ISSUE THREAD

**Issue by pferreir** [indico/indico#4205]
There should be a minimum of a publishable type. This means that we shouldn't allow the last publishable type to be deleted or unset.

There should be some way to (un-)set a publishable type. Something similar to a checkbox for each list entry could be an option. Otherwise, a field with a list of publishable types could also work (as long as it cannot be set to empty).

**Comment by panagiotappl** [comment]
> There should be some way to (un-)set a publishable type. Something similar to a checkbox for each list entry could be an option. Otherwise, a field with a list of publishable types could also work (as long as it cannot be set to empty).

There is a way to (un-)set publishable types. 
![image](https://user-images.githubusercontent.com/17234430/73187655-0661fd00-4122-11ea-9e3d-187dd3175b67.png)
Do you mean there should be an extra interface for that?

**Comment by ThiefMaster** [comment]
I think for now it's enough if we fail the (server-side) validation when unsetting the last publishable file type.
