### ISSUE TITLE
When cloning registration forms, check-in status gets cloned too

### ISSUE THREAD

**Issue by pferreir** [indico/indico#4208]
**Describe the bug**
The states of participants seem to be cloned along with the participants themselves.

**To Reproduce**
1. Create an event
2. Add some participants and set their check-in status
3. Clone the event

**Expected behavior**
The check-in state should have been reset.

**Comment by pferreir** [comment]
It looks as if we should also blacklst `checked_in` and `checked_in_dt` [here](https://github.com/indico/indico/blob/master/indico/modules/events/registration/clone.py#L110). Actually, maybe having some whitelisting logic would be better here? Or if we want to play it safe, both of them and an error in case not all object attributes are covered.

**Comment by ThiefMaster** [comment]
I think only whitelisting is likely to result in bugs in the future, while the combined solution will probably result in someone adding a column and then not updating it there, causing an error the first time a registration gets cloned... OTOH you are right that having both + the error would be the safest option.

Personally I'd just add the two columns to the blacklist and rely on developers / code reviewers thinking about cloning when adding some new column to the `Registration` model in the future in case it shouldn't be cloned (but most likely it's something we do want to clone anyway).
