### ISSUE TITLE
Progamme codes: Add placeholder to define number of id digits

### ISSUE THREAD

**Issue by meluru** [indico/indico#4220]
Allow defining how many digits should id placeholder have and add zeros to small numbers. For example if digit number is defined as 3 the code for contribution id 2 should be 002

**Comment by ThiefMaster** [comment]
I think this can be easily done using `ParametrizedPlaceholder` for the `id` placeholders: If you use `{id}` normally, it just uses the number itself, and if you use e.g. `{id:3}` it will pad it accordingly
