### ISSUE TITLE
Main Category doesn't use category description, inconsistent behavior

### ISSUE THREAD

**Issue by brittyazel** [indico/indico#4231]
The main (root) category seems to always have the description:
"Welcome to Indico. The Indico tool allows you to manage complex conferences, workshops and meetings.
To start browsing, please select a category below."

This is confusing, as you can add a custom title and description to the root category, however those seem to just be ignored. Weirdly though, setting a Logo on the main category does put the logo in the correct location.

It would be fantastic if the parent category would use the custom description that I have set instead of the default (above), though if this is impossible it would make it more clear if the option to edit the description of the main category were disabled.

**Comment by ThiefMaster** [comment]
The custom title shows up in the breadcrumbs; the only place I could imagined to show it on the home page would be in place of "Main categories", but this could look a bit strange in the breadcrumbs etc then where people are used to "Home". The title shown there is also dynamic depending on whether we have subcategories or not:

```jinja
{% if category.is_root and category.children %}
    {% trans %}Main categories{% endtrans %}
{% elif category.is_root %}
    {% trans %}All events{% endtrans %}
{% else %}
    {{ category.title }}
{% endif %}
```

OTOH, just using the title would allow people to be more flexible there, and I guess everyone could find something that fits nicely both there and in the breadcrumbs.

---

For the description I think it could indeed be nice to allow customization. The disadvantage is that you lose i18n by making it customizable unless we keep the "hardcoded" (and translated) default but show the custom description only if there is one.

---

Another option would of course be to just hide the description field for the root category so it cannot be edited at all.

**Comment by pferreir** [comment]
I agree with @ThiefMaster. I'd prefer to show the default description if there's none set, so that i18n works in that case.

**Comment by ThiefMaster** [comment]
hm for the title we'd also lose i18n unless we hardcode "Home" (or whatever the default is) to keep using the dynamic titles and only override it if you change it to something else...
