### ISSUE TITLE
Pillow does not yet support Python 3.8

### ISSUE THREAD

**Issue by Jurggernaut** [indico/indico#4240]
I like to provide information about an issue with the installation of indico.

While Pillows now support python 3.8, when installing indico using >pip install indico command, the installation will uninstall it and try to install a version of pillows that does not support python 3.8

![image](https://user-images.githubusercontent.com/22760778/72401981-94d09900-3788-11ea-9b30-462a98c5c043.png)

Hope this information will help. Thank you.

**Comment by mic4ael** [comment]
Hey, Indico is using Python 2.7 only at the moment and is not fully ready for a migration to Python 3.x.

**Comment by ThiefMaster** [comment]
Also, we do not support Windows at all.

**Comment by ThiefMaster** [comment]
You are also in the wrong repo: This is the https://getindico.io project (pypi package: `indico`), but you are trying to install `indicoio`, which is https://indico.io (we have **nothing** to do with them, they just got the nice .io domain before us...)

**Comment by pferreir** [comment]
> Also, we do not support Windows at all.

WSL should work in principle, though. We never tested it, however.

**Comment by ThiefMaster** [comment]
yeah, wsl works (i tested it a while ago) - but certainly nothing I'd ever use in production

**Comment by Jurggernaut** [comment]
Understood, thanks. Issue has been closed
