### ISSUE TITLE
Link favorites back to Avatars

### ISSUE THREAD

**Issue by pferreir** [indico/indico#427]
``` yaml
# Ticket imported from Trac
```

Favorite users are not taken into account i.e. for merges, causing situations of inconsistency. One of the reasons for this is that there is not registry of links between Avatars and favorites lists (`linkedTo`).
The idea would be to:
- Create such links;
- Change the "user merge" code in order to change the avatars from the favorites as well;

**Comment by ThiefMaster** [comment]
Obsolete since 1.9.3
