### ISSUE TITLE
Unlisted events

### ISSUE THREAD

**Issue by pferreir** [indico/indico#4294]
Every Indico event is by definition tied to a category. While this is supposed to promote the publication of events, it has also had the not-so-nice side-effect of encouraging people to just dump their events wherever they can (e.g. category "Conferences" in `indico.cern.ch`).
One of the things which is also frustrating about events having to be in a category is that they are visible from the beginning. Even if they are still "under construction", they remain visible.

## Proposal
Indico events should by default belong into a "private" area of their owner. The creator should still be able to change the ACLs (even though they won't respect the permissions of any category). Then, whenever the event is ready, the owner will be able to move it to an actual category and thus make it visible. This could then, in the future, be extended into a further moderation step in which the category managers are supposed to vet the event before it's incorporated into the category.

**Comment by ThiefMaster** [comment]
Sounds very good, and the "by default belong into a private area" could be a simply as making the category field when creating an event optional (maybe with some better UI to make it clear that you can clear the preselected category).

Since we have enumerable event IDs, we should probably also make it very clear that (unless the event is explicitly set as protected), the event cannot be considered secret/private. A header bar could be a good option for this.

**Comment by ThiefMaster** [comment]
I think we have two somewhat separate parts here that can be implemented one by one

## Backend support and fixes

- support events with no category / category_id in the DB (nullable column)
- make sure that everything still works fine in those events, and features that really depend on a category (and thus break) are disabled (can be tested by manually removing the category from an event via `indico shell`)

## Updating existing UI

- support creation of such events (as mentioned in the previous comment)
- clearly indicate in the event that it is unlisted
- add a way to add an unlisted event to a category (maybe similar to how we handle moving events)

## Listing unlisted events

- create mockups for an area listing your own unlisted events (part of the dashboard? new page)
- create said area based on the mockups

**Comment by pferreir** [comment]
Here's a mockup I made some time ago for an internal document:

![image](https://user-images.githubusercontent.com/2699/94426977-aaf37d80-018e-11eb-973f-27adf5610f0c.png)

(could be a basis for discussion)

**Comment by ThiefMaster** [comment]
note: the livesync plugin most likely also need to be updated; we can probably handle it as if an event is in a blacklisted category if there is no category, and then use the "moved" logic which creates a `ChangeType.published` when it gets added to a category

so whoever works on this should have a `debug` livesync agent created so they notice any errors in livesync code when dealing with events with a None category
