### ISSUE TITLE
Closer link between Paper Peer Reviewing and Paper Edtiting

### ISSUE THREAD

**Issue by ThiefMaster** [indico/indico#4303]
There should be a way to (automatically?) pass a paper from layout editing to peer reviewing ("paper reviewing") (or was it vice versa? to be confirmed when we have access to the flowchart for this again...)

**Comment by pferreir** [comment]
![image](https://user-images.githubusercontent.com/2699/79847144-9a5d0100-83bf-11ea-9180-b1490f62d653.png)
