### ISSUE TITLE
Display contributions for which none of the presenters is registered

### ISSUE THREAD

**Issue by meluru** [indico/indico#4318]
The idea is to provide a way for an event manager to see for which contributions none of the presenters have registered for the event and provide an easy way to contact them. 

This could be done by adding a 'presenter registered' column in the List of Contributions and a filter. 'Author list' button might be enough to be able to mail them.

**Comment by ThiefMaster** [comment]
I guess this would be similar to the ticket icon we show in participant roles, except on the contribution level?

**Comment by meluru** [comment]
Yes, that's exactly it. With the additional filter

**Comment by ThiefMaster** [comment]
I guess authors (that aren't selected as speakers) would be completely ignored in this check?

**Comment by meluru** [comment]
They want to have this option to avoid no-shows, so I think ignoring the authors is ok.

**Comment by ThiefMaster** [comment]
I guess this also encourages people to mark the correct people as the speaker ;)
