### ISSUE TITLE
Paper editing: Making changes not conform with filenameTemplate will still create entry in timeline

### ISSUE THREAD

**Issue by Leats** [indico/indico#4362]
**How to recreate:**

1. Add a filename template in Paper Editing
2. In the timeline of paper editing, try to "Make changes"
3. Try to upload a file not conforming to the filename template (a warning should be displayed)
4. Add a comment and confirm
5. The comment and an entry `Editor has made some changes to the paper` should appear with the old, conform file on it

Instead of this the confirm button should not be clickable at all or there should be some kind of error displayed when trying to confirm the wrong file.

**Comment by ThiefMaster** [comment]
I think the best option would be to mark the file manager field as invalid (like we do for missing required file types) while there's an error message visible, and require the user to actively acknowledge (and hide) it.
