### ISSUE TITLE
Editing setup: teams

### ISSUE THREAD

**Issue by ThiefMaster** [indico/indico#4377]
- Split `EditableEditorPermission` into three separate permissions for the editable types
- Add a page for assigning the editors for the event (can probably use one of our ACL widgets that lets you assign permissions? maybe a filtered version of the one we use on the event protection page that only shows editing-related permissions?); but better ideas are welcome of course!

**Comment by panagiotappl** [comment]
Since we might move the entire `Editing` page to React Components, isn't it better to use a completely new React Component for the Editor Permissions as well?

**Comment by ThiefMaster** [comment]
Maybe you can reuse the react component we use when assigning room permissions?

**Comment by panagiotappl** [comment]
I believe this is a better solution, yeah. I prefer to re-use an already existing component (maybe with some tuning) than create a completely new one for permissions again.
