### ISSUE TITLE
Replace <input type="time"> fields with text-based fields

### ISSUE THREAD

**Issue by pferreir** [indico/indico#4399]
The way browsers handle time fields is not consistent across vendors and creates lots of problems especially to people on Edge, who have to deal with an awful built-in time picker widget.
Additionally, these widgets rely on the system locale, which may differ from the Indico locale.

We should replace these with a widget which is easy to use and based on whatever locale is selected in Indico.

**Comment by ThiefMaster** [comment]
The problem with making it anything but a plain `hh:mm` in 24h format is that we then need some extra javascript to convert and store the real value in a hidden field. :/

Would be interesting to see if there are any decent time pickers out there; I don't think the one we did for room booking is sufficient for the other cases where we use time fields right now.

**Comment by ThiefMaster** [comment]
We also have one such field in the registration form (legacy angular code), so using anything halfway decent there may be hard... not sure if you can e.g. safely render a react component in there.
