### ISSUE TITLE
Abstract Submission: add current user as author/speaker by default?

### ISSUE THREAD

**Issue by jgrigera** [indico/indico#4406]
When adding a new abstract there are some use cases where it would be best to have the current user added by default as the author/speaker, to avoid the user having to search for her/himself. 

Could you give me any tips as on how this could best be implemented? I bet there is a moment when the RH creates an Abstract object, but not sure.

**Comment by ThiefMaster** [comment]
I think this would be something to best implement client-side, some kind of "add myself" button in the field where you add authors/speakers.

There might already be an issue for it (but I couldn't find it) since it somehow sounds familiar...

**Comment by jgrigera** [comment]
Thanks @ThiefMaster ! Actually that was a good suggestion, in case you wish to merge or for future reference this is how we did it (not sure if there is an easier way to do the user search though). Fullname is probably safe to remove - I used for debuggin purposes:


[indico-addmyself.diff.txt](https://github.com/indico/indico/files/4487686/indico-addmyself.diff.txt)

**Comment by ThiefMaster** [comment]
A pull request would be better than a link to a patch. And ugh, having to call a legacy API isn't amazing... I wonder how much data we really need - some is in the global `Indico.User` so I'd rather expose some more there for now instead of adding a new place where a legacy API gets called.

**Comment by jgrigera** [comment]
Sure, happy to do a pull request if this is a feature you would consider. Only reason to post the diff was that one can do just by patching files that live in customization_dir.

As for the API: no clue as to what would work best, does not look neat to us but this is literally the first time we look at indico code. We used the legacy API because the person list uses it, and there was no easy way to provide the object it uses. Maybe we can just send this and you can find a better way to write buttonAddMyself.click?

**Comment by ThiefMaster** [comment]
That's exactly why I suggested a PR - it's much easier to use the comment/review features there to discuss implementation details there.

**Comment by jgrigera** [comment]
Great - I will do asap
