### ISSUE TITLE
User profile "title" is not pre-filled in personal data of registration forms

### ISSUE THREAD

**Issue by OmeGak** [indico/indico#4409]
**To Reproduce**
1. Set a title in your user profile
2. Navigate to an open registration form with the default "personal data" section enabled. 
3. Observe that the "Title" is not pre-filled. 

**Expected behavior**
I expect the "Title" field in personal data section of registration forms to be pre-filled with the user's profile title.

**Comment by ThiefMaster** [comment]
Works fine for me in master...

**Comment by OmeGak** [comment]
Tried on a clean install and works fine. Must have been some quirk added by the plugin.
