### ISSUE TITLE
Editing: Notifications

### ISSUE THREAD

**Issue by ThiefMaster** [indico/indico#4437]
Send email notifications on various events happening to an editable

- No message customizations or settings to enable/disable emails
- Plaintext emails are probably enough
- Send notifications on all **relevant events** to the people for **whom they matter**
  - new comment by submitter -> notify editor
  - new comment by editor -> notify submitter
  - judged by editor -> notify submitter
  - new revision uploaded by submitter -> notify editor
  - revision changes made by editor -> notify submitter who made the previous revision
  - revision changes approved/rejected by submitter -> notify editor (the currently assigned one and the one who was assigned for that particular revision in case they are different)
  - Anything else? TBD

Corner cases mentioned in MM chat:
- user is not an editor nor a submitter for the editable (!can_perform_submitter_actions, !can_perform_editor_actions): send emails to both the submitter of the revision and the editor of the editable
- same if he's both?
- user is not an editor for the editable: send the email to the submitter of the revision
- user is not a submitter for the editable: send the email to the editor of the editable

**Comment by panagiotappl** [comment]
What about the case where a submitter has to "confirm/reject the changes made by the editor on an Editable" ?

**Comment by ThiefMaster** [comment]
Yes, this indeed needs a notification! I'd say it should be sent to whoever created the previous revision this those are the most likely person to approve/reject it.

**Comment by panagiotappl** [comment]
Should there also be a notification to the editor when the submitter approves/rejects the changes?

**Comment by ThiefMaster** [comment]
Yes, I think that makes perfect sense. In this particular case I would email both the currently-assigned editor and the editor who created the revision with the changes in case they aren't the same.

**Comment by panagiotappl** [comment]
I noticed that revision changes done by the editor fall into the "editor reviewed revision" category.  Should there be different emails between the editor making changing and any other action taken by the editor. IMO, it should be a general email which informs the user that a review has been made by the editor.

**Comment by ThiefMaster** [comment]
I think in principle it'd be nice to mention what change was made, but I'm fine with a generic email linking to the revision for now (we can always improve it later!)
