### ISSUE TITLE
Database error for update_event(update_timetable=True) with a modified end_dt

### ISSUE THREAD

**Issue by marengeti** [indico/indico#4442]
Calling the operation utility update_event() and then doing a db session commit() fails with the database error below, when:
- the data dict contains an entry for `end_dt` that is different than what is defined on the event instance
- the operation param `update_timetable=True`
Even with all sessions (and timetable_entries, blocks, etc) in the event fall strictly within the would-be `start_dt` and `end_dt`.

```
*** DatabaseError: (psycopg2.DatabaseError) Timetable inconsistent
DETAIL:  Entry ends after the event
CONTEXT:  PL/pgSQL function events.check_timetable_consistency() line 102 at RAISE

(Background on this error at: http://sqlalche.me/e/4xp6)
```

To illustrate this by way of a workaround -- the following code succeeds in modifying the event's end_dt value when a valid different value is passed in as part of the data dict:
```
        update_timetable = True 
        if 'end_dt' in data and event.end_dt != data['end_dt']:
            update_timetable = False
        update_event(event, update_timetable=update_timetable, **data)
        db.session.commit()
```

There is a more elaborate explanation, and specific case example, here:
https://talk.getindico.io/t/database-error-for-update-event-evt-update-timetable-true-data-with-a-changed-end-dt/1805

**Comment by ThiefMaster** [comment]
Based on the forum discussion this wasn't really a problem on Indico's side.
