### ISSUE TITLE
Editing: Contact editors

### ISSUE THREAD

**Issue by ThiefMaster** [indico/indico#4444]
This can be done similar to what we have in the paper reviewing module. Let's see if we can easily reuse something from there.

**Comment by panagiotappl** [comment]
Should we also allow to contact categories, event roles and groups through this?

**Comment by ThiefMaster** [comment]
That's a good question... may be VERY spammy (especially since we need to resolve group members to email them), but if used in a reasonable way (ie not adding a group with thousands of people) then maybe it'd be a good thing to have.

@pferreir?

**Comment by pferreir** [comment]
What do you mean with "categories"?
I think contacting groups/roles is useful, but we should probably add a confirmation step with the amount of people who are going to be "spammed".

**Comment by ThiefMaster** [comment]
"category roles" i guess

**Comment by ThiefMaster** [comment]
> but we should probably add a confirmation step with the amount of people who are going to be "spammed"

Showing the number of people the mail will be sent to would indeed be nice.

**Comment by pferreir** [comment]
> "category roles" i guess

Ah right, thanks.
