### ISSUE TITLE
Integration of Jitsi Meet for  video-conferencing events

### ISSUE THREAD

**Issue by jeanfrancis** [indico/indico#4451]
Would be great to have the Integration of Jitsi Meet for video-conferencing events

**Comment by ThiefMaster** [comment]
Videoconferencing service integration is implemented using plugins, so anyone can create their own plugin to integrate e.g. with Jitsi Meet.

As someone who likes free and open services: I would love to see such a plugin developed and released as Open Source. If you or someone at your organization is interested in doing this, we'll gladly answer any questions you may have regarding this (in our IRC/Matrix chat or the forum).

But we do not use Jitsi Meet at CERN so we cannot spend resources on implementing a plugin that we have zero need for ourselves. Sorry.
