### ISSUE TITLE
Link opening from apps

### ISSUE THREAD

**Issue by andrzejnovak** [indico/indico#4493]
Sorry, if this is not the right place to post this, but link-click from a PDF or a PowerPoint to a file that is gated by auth fails, but pasting the exact same link to browser works fine.  (Auth was done prior to both links)

**Comment by ThiefMaster** [comment]
That sounds like a problem with your PDF viewer. We have zero influence on what other clients do - if they don't open the URL directly in a browser but try to do *something* with them first (maybe resolving redirects?), there's nothing we can do...

**Comment by andrzejnovak** [comment]
I guess you are right, it seems to be a MS problem (powerpoint, skype mobile), acrobat and desktop skype are fine..
