### ISSUE TITLE
Limit visibility of pages to registered participants

### ISSUE THREAD

**Issue by dev-zero** [indico/indico#4507]
**Is your feature request related to a problem? Please describe.**

We have information (like the links to Zoom or Slack) which we would like to make available only to the registered participants of a conference. So far I was unable to figure out how to do this.

**Describe the solution you'd like**
In the *menu* settings one can change the visibility in general. Here I would expect to be able to apply ACLs.

**Describe alternatives you've considered**
My current workaround is a hidden page I'm going to share via e-mail.

**Comment by ThiefMaster** [comment]
This will most likely be available in 2.3 due to #4499 (already merged) and #4505 which would let you add a material restricted to registered participants.

We could also consider adding a setting to the upcoming Zoom plugin to show the details only to registered participants (cc @pferreir)

**Comment by pferreir** [comment]
That's a good idea, indeed.

**Comment by ThiefMaster** [comment]
Actually after reading this again it sounds like this is really for custom pages. This won't be available in 2.3 - but at least when it's just a sensitive link then #4505 will give you an alternative way of doing what you want.

Not so sure about adding ACLs for custom pages... especially if it's not just for all custom pages but individual custom pages...

In any case that,d be something for a later version, not for 2.3.

**Comment by pferreir** [comment]
As @ThiefMaster has said, this will already be covered by #4505. It might be interesting to have such an option for Zoom links once we have a working Zoom plugin. I'll close this ticket, feel free to follow the progress on #4505.

**Comment by dev-zero** [comment]
> Actually after reading this again it sounds like this issue is really about custom conference pages. This won't be available in 2.3 - but at least when it's just a sensitive link then #4505 will give you an alternative way of doing what you want.

Well, it wasn't just a link, but a simple HTML page with instructions plus a link.

@pferreir this isn't about Zoom particularly, just in this example I wanted to distribute some information/guidelines plus a Zoom link. Next time it might be Jitsi instead, who knows.

Looking at #4505 it does not seem to solve my problem, since it is only for material/the link.

**Comment by pferreir** [comment]
OK, let's do it like this then: let's add a config flag to custom pages, something called "Registrants Only" or similar, and which will limit the visibility of the page to conference registrants.
