### ISSUE TITLE
Moment locales are incompatible with python's babel

### ISSUE THREAD

**Issue by plourenco** [indico/indico#4541]
When using a translation such as `zh_CN.GB2312`, the code `zh_Hant_TW` will not be recognized by moment, causing it to import the wrong locale.

![image](https://user-images.githubusercontent.com/12183954/87763163-9ef55200-c814-11ea-8299-9a41dca420ff.png)

Would be great to also fall back to the default locale in case this happens again.

Few comments from a discussion on this:
> Don't think we can rely on the dynamic import inside setMomentLocale there since we may have code that runs before the async import finishes, and thus needs those locales to be available from the beginning.

> We could try to load the locale before anything loads. the problem is we don't remember where not having the locale available from the beginning would cause problems (Something like `jquery ui datepickers`, `category overview` - there are only very few left)

**Comment by ThiefMaster** [comment]
To add details from that discussion:

We have two places where we set the moment locale: `setMomentLocale` (async dynamic import) and in `indico_base.html` (sync, for legacy-ish code). The latter relies on [explicit hardcoded imports](https://github.com/indico/indico/blob/ba16b8b847449be85d8d8cbf138a1f5da5420f9c/indico/web/client/js/jquery/index.js#L15-L18) of the moment locales needed.

We don't know for sure which places really need the locale to be loaded at import time, but *I think* that jQuery UI datepickers are one of the cases that do. At least when running code on page load that does something with moment before passing data to the datepickers.
