### ISSUE TITLE
Add "track group prefix" in missing places

### ISSUE THREAD

**Issue by pferreir** [indico/indico#4544]
These are only some examples:

## Contribution list (management, picker)

![image](https://user-images.githubusercontent.com/2699/87937020-2bfa0e80-ca94-11ea-930d-1a7faa8a6eb3.png)

## Contribution list (display)

![image](https://user-images.githubusercontent.com/2699/87936938-0d941300-ca94-11ea-9503-e8d1998f5493.png)

##  Contribution display

![image](https://user-images.githubusercontent.com/2699/87937050-3d431b00-ca94-11ea-9f92-7c2d68892000.png)

## Contribution PDF

![image](https://user-images.githubusercontent.com/2699/87937065-459b5600-ca94-11ea-9f01-003c5b80a6ec.png)

Since the prefix + track name can become quite long, we could use tooltips in web interfaces. In PDF files, there is more space available, so it should be OK to include the full string.

**Comment by ThiefMaster** [comment]
We have various `*title_with_group` properties in Track which can probably be used in some of these places.
