### ISSUE TITLE
Direct creation of sub-category in event-populated category

### ISSUE THREAD

**Issue by DirkHoffmann** [indico/indico#4549]
Disclaimer: I think this request had been made a long time ago and actually thought that it was implemented. So it is possible that this is rather a regression report, or the feature has been removed (or rejected) for some good reason.

Presently it is not possible to create a sub-category inside another category, if it contains already an event. The workaround is to create a new category _somewhere else_, then move all events from the present category to that new (sub-)category, move the new sub-category into the original category. Then you can create more sub-categories, dispatch events into them etc.

A "direct creation" of a category in an already event-populated category, which suggests to move all existing events into the new sub-category, would be more convenient.

NB: This is different from the request to _mix_ categories and events in the same category, which was mentioned in IWS 2.0.

**Comment by ThiefMaster** [comment]
It's already possible by selecting all events and using the "split category" option. It's not just very obvious that this works. ;)

PS: We already have a card for allowing the mix of events and categories in the 3.0 project board: https://github.com/indico/indico/projects/5#card-41067410 I think with that change we will allow creating subcategories regardless of the existence of events, but we could add a "move all events in there" checkbox.

**Comment by DirkHoffmann** [comment]
Great! I even had used that split option in the past, and it is documented [here](https://learn.getindico.io/categories/about/). :sob: 


> but we could add a "move all events in there" checkbox.

Yes, please. This split action is frequent enough to help users save some time with it.
