### ISSUE TITLE
Improve registration withdrawals

### ISSUE THREAD

**Issue by ThiefMaster** [indico/indico#4588]
Now that #4585 is merged, there are some improvements we can make to this feature:

- Allow users to restore their withdrawn registration during modification/registration period (whatever deadline is later)
- Allow event managers to withdraw a user from the management view (no bulk action needed)
- Add email notifications, especially when the event manager withdraws

**Comment by Leats** [comment]
Allowing users themselves to restore their withdrawn registration leads to the problem that we don't know what the state was before. In addition, there would need to be a differentiation whether a user has withdrawn themselves or whether they withdrew on their own (which should be the only case they can restore their withdrawal).
