### ISSUE TITLE
Exposing the event's keywords in the API

### ISSUE THREAD

**Issue by chernals** [indico/indico#4598]
This is a feature request to include the keywords of an event to the API. 

At the moment the keywords are seldom used, but when using the API that would be a solid use case, for example to refine the classification of events within a single category.

See the discussion on discourse: https://talk.getindico.io/t/event-keywords-in-the-export-api/1889/2

**Comment by ThiefMaster** [comment]
Just like a wrote on the forum, I think this is a good idea - if you want to send a PR please go ahead (also add a changelog entry to CHANGES.rst in that case)

**Comment by chernals** [comment]
See PR 4599.

Is it that simple?

**Comment by ThiefMaster** [comment]
Yep, indeed that simple :)
