### ISSUE TITLE
OAuth no longer works due to flask_multipass update

### ISSUE THREAD

**Issue by kadet1090** [indico/indico#4602]
**Describe the bug**
Recently `flask_multipass` version 0.3 was released, and it breaks support for `oauth`. It's probably due to more general authlib usage but no clear migration guide is present and it present version on install. We can stick with 0.2.2 version of `flask_multipass` or create oauth provider based on `authlib` to support existing configurations.

```
Traceback (most recent call last):
  File "/opt/indico/indico.wsgi", line 9, in <module>
    application = make_app()
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/indico/web/flask/app.py", line 333, in make_app
    multipass.init_app(app)
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/indico/core/auth.py", line 69, in init_app
    super(IndicoMultipass, self).init_app(app)
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/flask_multipass/core.py", line 75, in init_app
    state.auth_providers = ImmutableDict(self._create_providers('AUTH', AuthProvider))
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/flask_multipass/core.py", line 453, in _create_providers
    cls = resolve_provider_type(base, settings.pop('type'), registry)
  File "/opt/indico/.venv/local/lib/python2.7/site-packages/flask_multipass/util.py", line 152, in resolve_provider_type
    raise ValueError('Unknown type: ' + type_)
ValueError: Unknown type: oauth
```

**To Reproduce**
1. Have `oauth` configured as in https://flask-multipass.readthedocs.io/en/latest/quickstart/#external-provider-login
2. Do a clean install of indico
3. Try to run

**Expected behavior**
It should run cleanly on older config.

**Additional context**
We've got integration with our SSO via oauth and it breaks our build system which sometimes redownloads all packages due to workspace wipeout.

**Comment by ThiefMaster** [comment]
How did you end up with 0.3? I'm pretty sure we require `<0.3` in the indico package?

**Comment by kadet1090** [comment]
It's `>=0.2,<0.4-dev` not `<0.3`

**Comment by ThiefMaster** [comment]
But that's in master. In 2.2.8 we have `Flask-Multipass>=0.2,<0.3-dev`: https://github.com/indico/indico/blob/v2.2.8/requirements.txt#L46

**Comment by kadet1090** [comment]
We needed to fork because we wanted to add custom language to our installation - as far as i know there is no other possibility to to that? And due to that we landed on master version without really noticing it - thanks for pointing that out, I'll rebase our changes to stable tag. 

And just for the future, is there maybe any instruction regarding migration to new multipass version? Because doc seems to be outdated.

**Comment by kadet1090** [comment]
Thank you very much for assistance :) Everything is working fine now. Also it'd be nice if you added also how to disable certificate validation for new versions of multipass into documentation (basically you need to set `CURL_CA_BUNDLE=""` env variable).

Regarding translation - we're using polish translation from transifex and plan to finish it up so it can be added into next release.

**Comment by ThiefMaster** [comment]
Disabling certificate verification is a bad idea, so I don't think documenting this makes much sense.

**Comment by kadet1090** [comment]
It makes sense for development purposes.
