### ISSUE TITLE
Q: Need for i18n of this code

### ISSUE THREAD

**Issue by DirkHoffmann** [indico/indico#4607]
Does the word "English" have to be translated really in this place?
https://github.com/indico/indico/blob/2a1ffb33b880ff6fe881ccd58cfce70e0aaee502/indico/web/templates/_session_bar.html#L166

If it has to, I wonder if there is a more intrinsic way to do that than providing _n_ translations in PO files for _n_ languages of Indico.

**Comment by ThiefMaster** [comment]
No, but this particular case should never happen anyway... it only applies if for some reason Indico has no locales available at all.
But since the language is always English in this case translating it makes no sense.
