### ISSUE TITLE
Start using the user's profile picture in more places

### ISSUE THREAD

**Issue by ThiefMaster** [indico/indico#4625]
We now have a proper `picture_url` for every user which will serve a default icon (colored bg + initial) or a custom picture/avatar. Currently this is only used in the user dashboard, but we can now start using this in other places as well.

Look for `avatarBgColor` in the code to find those places!

**Comment by pferreir** [comment]
It would be nice to also add the pictures in the list of participants of a meeting (as long as the list is visible, obviously).

**Comment by Leats** [comment]
> It would be nice to also add the pictures in the list of participants of a meeting (as long as the list is visible, obviously).
@pferreir Did you mean this here? Because I'd worry that the profile pictures would be too small.
![Bildschirmfoto 2020-12-16 um 09 57 06](https://user-images.githubusercontent.com/23189858/102326772-1f1b1180-3f85-11eb-9f95-f6ad7c63cfb7.png)
Otherwise, maybe in the participant list of a conference?

**Comment by pferreir** [comment]
Yeah. We'd probably have to make those bigger...

**Comment by ThiefMaster** [comment]
not sure how that would look like for larger meetings with more than a handful of participants :/ doing it on the participant list for a conference would be easier for sure since we have a proper table there
