### ISSUE TITLE
Error LaTeX, when creating book-of-abstracts.pdf

### ISSUE THREAD

**Issue by Afif0708** [indico/indico#4633]
**ERROR**

There was an error when creating book-of-abstracts.pdf, the log file says File 'xparse-generic.tex' was not found, but in the installation directory texlive The file 'xparse-generic.tex' is already installed in / opt / texlive / texmf- dist / tex / latex / l3packages / xparse / xparse-generic.tex

**File Log**

> his is XeTeX, Version 3.14159265-2.6-0.999992 (TeX Live 2020) (preloaded format=xelatex)
entering extended mode
(/opt/indico/tmp/indico-texgen-P56jKn/book_of_abstracts.tex
LaTeX2e <2020-02-02> patch level 5
L3 programming layer <2020-09-06>
(/opt/texlive/texmf-dist/tex/latex/base/book.cls
Document Class: book 2019/12/20 v1.4l Standard LaTeX document class
(/opt/texlive/texmf-dist/tex/latex/base/bk11.clo))
(/opt/texlive/texmf-dist/tex/latex/geometry/geometry.sty
(/opt/texlive/texmf-dist/tex/latex/graphics/keyval.sty)
(/opt/texlive/texmf-dist/tex/generic/iftex/ifvtex.sty
(/opt/texlive/texmf-dist/tex/generic/iftex/iftex.sty)))
(/opt/texlive/texmf-dist/tex/latex/hyperref/hyperref.sty
(/opt/texlive/texmf-dist/tex/generic/ltxcmds/ltxcmds.sty)
(/opt/texlive/texmf-dist/tex/generic/pdftexcmds/pdftexcmds.sty
(/opt/texlive/texmf-dist/tex/generic/infwarerr/infwarerr.sty))
...
...
...
(/opt/texlive/texmf-dist/tex/generic/stringenc/stringenc.sty)
(/opt/texlive/texmf-dist/tex/latex/rerunfilecheck/rerunfilecheck.sty
(/opt/texlive/texmf-dist/tex/latex/atveryend/atveryend.sty)
(/opt/texlive/texmf-dist/tex/generic/uniquecounter/uniquecounter.sty)))
(/opt/texlive/texmf-dist/tex/latex/amsfonts/amssymb.sty
(/opt/texlive/texmf-dist/tex/latex/amsfonts/amsfonts.sty))
(/opt/texlive/texmf-dist/tex/latex/amsmath/amsmath.sty
For additional information on amsmath, use the `?' option.
(/opt/texlive/texmf-dist/tex/latex/amsmath/amstext.sty
(/opt/texlive/texmf-dist/tex/latex/amsmath/amsgen.sty))
(/opt/texlive/texmf-dist/tex/latex/amsmath/amsbsy.sty)
(/opt/texlive/texmf-dist/tex/latex/amsmath/amsopn.sty))
(/opt/texlive/texmf-dist/tex/latex/fontspec/fontspec.sty
(/opt/texlive/texmf-dist/tex/latex/l3packages/xparse/xparse.sty
(/opt/texlive/texmf-dist/tex/latex/l3kernel/expl3.sty
(/opt/texlive/texmf-dist/tex/latex/l3backend/l3backend-xetex.def))
**! LaTeX3 Error: File 'xparse-generic.tex' not found.**
For immediate help type H <return>.

**Comment by ThiefMaster** [comment]
This is a bug in TeXLive. See my [Stack Exchange post](https://tex.stackexchange.com/a/563985/1651) and the mailing list thread linked there for details.

As a workaround until updated TeXLive packages are available you can apply this patch ([details](https://tug.org/pipermail/tex-live/2020-September/046141.html)):

```patch
diff --git a/indico/legacy/pdfinterface/latex_templates/inc/document.tex b/indico/legacy/pdfinterface/latex_templates/inc/document.tex
index c3fea25f31..21bc90be27 100644
--- a/indico/legacy/pdfinterface/latex_templates/inc/document.tex
+++ b/indico/legacy/pdfinterface/latex_templates/inc/document.tex
@@ -1,3 +1,4 @@
+\expandafter\let\csname file_input:n\endcsname\input
 \JINJA{block document_class}
     \documentclass[a4paper, 15pt]{article}
 \JINJA{endblock}
```
