### ISSUE TITLE
Link to CERN values returns "Not found"

### ISSUE THREAD

**Issue by SeanDS** [indico/indico#4636]
The readme says "We follow CERN's Values and the principles established by CERN's Code of Conduct.". Unfortunately the [link to the values](https://hr.web.cern.ch/content/cern-values-0) is a 404, at least as of writing. If I didn't know any better, I might think that CERN lacks values. ;-)

**Comment by ThiefMaster** [comment]
Looks like someone didn't setup a redirect when restructuring that site... :/
