### ISSUE TITLE
Reservation system - Get front more versatile

### ISSUE THREAD

**Issue by battosai30** [indico/indico#4637]
Hi,

**Describe the solution you'd like**
I'm working in a fablab and we discovered during Covid lockdown that the room reservation system is really convenient to manage other ressources like, in our case, machine reservations (so a member of our association is able to reserve a 3D printer or a laser cutter for example). 

The only thing that's really missing is that the front could not be easily changed to manage other ressources than rooms. 

So for us the need is simple : in the top bar and other menus after, we would like to see "Machine reservation" instead of "Room reservation", but I guess other users would like something else as the system is able too manage almost anything :) 

**Describe alternatives you've considered**
Manually edit code to make a static modification (but would be broken during each upgrade)

Thanks for your work and regards

**Comment by ThiefMaster** [comment]
Hi, you may be able to use a plugin to override these parts. Have a look a our [burotel plugin](https://github.com/indico/indico-plugins-cern/tree/master/burotel) which is used on a standalone indico instance at CERN for desk reservation, and we basically override the room booking module in there and many titles are paremetrized so you could probably used a dumbed-down version of that plugin which doesn't contain most of the burotel logic (like only allowing full-day bookings) but still overrides some of the strings.
