### ISSUE TITLE
Homogenise msgid strings to AE

### ISSUE THREAD

**Issue by DirkHoffmann** [indico/indico#4639]
As a matter of fact, Indico codebase and base textstrings have been mostly written in in American English (as opposed to British Englsh, [read more](https://www.boredpanda.com/british-american-english-differences-language/). As a consequence, the basic (untranslated) version of Indico is **en_US in general, but not always**. (An [en_GB section on Transifex](https://www.transifex.com/indico/indico/translate/#en_GB) was opened recently to provide a BE version of Indico.) 
The issue is to make all translatable text in Indico correct en_US, as it is presently a mixture of BE and AE writing. This is particularly important, because the (untranslated) base textstrings of Indico are used as identifiers (**msgid**) for the translation via PO/MO files. Hence they have an impact on _all_ translated languages, when they are updated. An appropriate automatic method to avoid too much overhead for each translator group should be applied.

From earlier exchanges about the topic, for reference:
> Organize (https://www.merriam-webster.com/dictionary/organise)
> Synchronize, authorize, customize and so on, and their derivatives.
> 
> Then there are "center" (centre), "gray" (grey) and "color" (colour) for example.
> 
> I am not sure about "convener" (convenor), which seems to be a matter of taste rather than geography.
> 
> Programme / program.

The proposal is to finish the cleanup by Indico 3.0.

**Comment by ThiefMaster** [comment]
> base textstrings have been mostly written in in American English

I disagree with this, except for a few cases they msgids are mostly british english ;)

And I think "organize" is one of the cases where even the brits aren't clear on what they prefer ;) https://www.learnenglish.de/mistakes/isevsize.html
