### ISSUE TITLE
Removing entry of Division from Room Details does not work

### ISSUE THREAD

**Issue by dirks** [indico/indico#4640]
**Describe the bug**
The entry of the non mandatory field Division from the room details can not be removed.

**To Reproduce**
1. Go to the 'Edit Room Details' of a room that contains Division information.
2. Remove the Entry.
3. Click Save.
4. The message "Room has been successfully updated." appears
5. The old value of division is back again (both in the edit view and the room list)

**Workaround**
As a workaround I inserted a non breaking space (U+00A0) via copy paste into the field, as a normal white space does not work. The division field disappears from the room list and the division field in the edit dialog is now empty. Not sure if this behavior is an additional bug.

**Expected behavior**
The old value of division is removed when cleared in the edit room details form and saved.

**Additional context**
indico 2.2.8 is installed via pip.

**Comment by ThiefMaster** [comment]
I can't reproduce this in 2.3 - please upgrade and see if it works for your in that version.
