### ISSUE TITLE
Enforce password complexity requirements for local accounts

### ISSUE THREAD

**Issue by ThiefMaster** [indico/indico#4645]
Also see the discussion [here](https://talk.getindico.io/t/password-complexity/1957).

Right now Indico only checks for >=5 chars, which allows for terrible passwords like `12345` (or really anything else that's just 5 characters...). Many Indico instances use SSO where this won't be used at all (since Indico doesn't handle passwords there), but when using local accounts there's currently no way to enforce somewhat secure passwords.

I see two possible solutions here:

- We add something basic in the core, such as "at least 8 chars, and unless it's longer than 16 chars, require two different types of characters". I don't think this needs to be configurable. If NIST or any other well-trusted source for password-related recommendations has suggestions on the lengths, let's follow those.

- We simply add a signal that is called when validating passwords (ie during local account creation and password change/reset). It's then up to a plugin to implement e.g. the rules above and/or something more fancy such as a check against the [HIBP pwned password list](https://haveibeenpwned.com/API/v3#PwnedPasswords) - the API for this doesn't seem to be require a (paid) API key.

When going for the plugin solution, we could add a basic plugin in the default `indico-plugins` meta package so people can easily enable it.

**Comment by pferreir** [comment]
https://pages.nist.gov/800-63-3/sp800-63b.html#-511-memorized-secrets
