### ISSUE TITLE
Do not hotlink Google Calendar button from Google servers

### ISSUE THREAD

**Issue by ThiefMaster** [indico/indico#4660]
https://github.com/indico/indico/blob/ea19a33f2414c51a62bae5cd896f7220d3a0820a/indico/modules/events/templates/footer.html#L48

Let's serve this image from indico instead like we do for all our own images. No need to give Google data for everyone opening an event page (unlike the social media stuff, this image is not lazy-loaded since it's just an img tag).

**Comment by ThiefMaster** [comment]
If someone wants to do this for Hacktoberfest, look how we are embedding images in other templates (search for `assets.image`). Since indico is a bit heavy to setup just for a small change like this feel free to create a PR w/o testing this. Figuring out the path where to store the image should be easily possible by looking where the other images we have are located.

**Comment by pret3nti0u5** [comment]
Hey, I would like to try this. Could you please assign this to me?

**Comment by ThiefMaster** [comment]
Sure!

**Comment by pret3nti0u5** [comment]
Also, should I save the image with any particular name or anything works?

**Comment by pret3nti0u5** [comment]
Got it, I'll get to it.

**Comment by pret3nti0u5** [comment]
Opened a PR #4661. Let me know if any further edits are required!
