### ISSUE TITLE
installation of indico 2.0  and indico-migrate is broken

### ISSUE THREAD

**Issue by speedytom** [indico/indico#4665]
**Describe the bug**
I am running on UBU 18.04:

```
(.venv) root@indico2:~# cat /etc/os-release 
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

I need upgrade from version 1.2 to 2.3. I follow manuals from here:
https://docs.getindico.io/en/stable/installation/upgrade_legacy/

```
root@indico2:~# pip install 'indico<2.1'

Collecting celery==4.1.0
  Downloading celery-4.1.0-py2.py3-none-any.whl (400 kB)
     |████████████████████████████████| 400 kB 8.2 MB/s 
Collecting enum34
  Using cached enum34-1.1.10-py2-none-any.whl (11 kB)
Collecting mock==2.0.0
  Using cached mock-2.0.0-py2.py3-none-any.whl (56 kB)
ERROR: Could not find a version that satisfies the requirement pyatom==1.4 (from indico<2.1) (from versions: 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.7, 0.0.8, 0.0.9, 0.0.10)
ERROR: No matching distribution found for pyatom==1.4 (from indico<2.1)

(.venv) root@indico2:~# pip install indico-migrate
Collecting bleach==2.1.3
  Using cached bleach-2.1.3-py2.py3-none-any.whl (28 kB)
Requirement already satisfied: ipaddress in ./.venv/lib/python2.7/site-packages (from indico<2.1.dev0,>=2.0->indico-migrate) (1.0.23)
Requirement already satisfied: pytz in ./.venv/lib/python2.7/site-packages (from indico<2.1.dev0,>=2.0->indico-migrate) (2020.1)
Requirement already satisfied: enum34 in ./.venv/lib/python2.7/site-packages (from indico<2.1.dev0,>=2.0->indico-migrate) (1.1.10)
Collecting mock==2.0.0
  Using cached mock-2.0.0-py2.py3-none-any.whl (56 kB)
ERROR: Could not find a version that satisfies the requirement pyatom==1.4 (from indico<2.1.dev0,>=2.0->indico-migrate) (from versions: 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.7, 0.0.8, 0.0.9, 0.0.10)
ERROR: No matching distribution found for pyatom==1.4 (from indico<2.1.dev0,>=2.0->indico-migrate)
```

**To Reproduce**
A reproduction of this error is obvious.

It seems similar to this:
https://github.com/indico/indico/issues/4046

**Comment by ThiefMaster** [comment]
See https://talk.getindico.io/t/error-using-indico-migrate-to-migrate-from-indico-1-2/1518/2 for a workaround.

**Comment by speedytom** [comment]
It works thanks, but I met this problem:
Collecting validators>=0.5.0 (from WTForms-Components==0.10.3->indico<2.1.dev0,>=2.0->indico-migrate)
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/d9/1f/27dff5c1ea8f36865a179581dea4f75d1ab52cd8f32ee527a592b6558b55/validators-0.17.0.tar.gz
validators requires Python '>=3.4' but the running Python is 2.7.17

**Comment by ThiefMaster** [comment]
`pip install -U pip setuptools` - most likely your pip version is too old to understand python-requires metadata on packages (which is used to hide python3-only packages from older python versions)

**Comment by speedytom** [comment]
It is better. I got an another error:
o-migrate
  Attempting uninstall: ZODB3
    Found existing installation: ZODB3 3.10.7
    Uninstalling ZODB3-3.10.7:
      Successfully uninstalled ZODB3-3.10.7
  Attempting uninstall: marshmallow
    Found existing installation: marshmallow 2.21.0
    Uninstalling marshmallow-2.21.0:
      Successfully uninstalled marshmallow-2.21.0
ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.

We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.

indico 2.0.3 requires requests==2.18.4, but you'll have requests 2.24.0 which is incompatible.
indico 2.0.3 requires zope.interface==3.8.0, but you'll have zope-interface 4.3.2 which is incompatible.

**Comment by ThiefMaster** [comment]
I'd recreate the virtualenv; with the outdated pip you probably already got some packages not matching the versions indico wants. alternatively, you can just `pip uninstall -y requests zope.interface` and then install indico again so it can pull in the correct versions...

**Comment by speedytom** [comment]
I suppose I fixed by this:
root@indico2:~# pip install --upgrade pip
root@indico2:~# pip install indico-migrate --use-feature=2020-resolver

**Comment by ThiefMaster** [comment]
yeah, sounds reasonable.

PS: you shouldn't be doing this as root! but if this is just a throwaway VM for the migration and not the one you want to use to run indico 2.3 in production, it doesn't really matter

**Comment by speedytom** [comment]
I am using separate VM for migration (indico2). I created rsync from production machine(indico). I created zfs snashot for indico2 too. 
There is any reason why I should use virutalenv in produciton?

**Comment by speedytom** [comment]
My plan is to switch IP address from indico to indico2. Thanks for your answer.

**Comment by ThiefMaster** [comment]
Without virtualenv you have to install everything as root and you mess up your system python environment with all the indico stuff.

just to be clear: we do not support non-virtualenv deployments. they may work, and if you have good linux and python knowledge you may succeed, but you are mostly on your own. The setups we fully support are the ones [listed in the docs](https://docs.getindico.io/en/stable/installation/production/).

**Comment by speedytom** [comment]
OK. I see I should install under the indico account. Thanks for answer.
