### ISSUE TITLE
How to group session contributions in detailed view

### ISSUE THREAD

**Issue by davidlange6** [indico/indico#4691]
**Describe the bug**

we have a relatively simple conference event with two parallel sessions.  When putting in contributions, we noticed that the detailed view does not keep contributions in one session together int the same column. Eg see the screenshot.

We can "fix" by removing gaps in the timetable. However, are there other approaches we can use to keep the contributions in a session in the same column with parallel sessions?

**To Reproduce**
https://indico.cern.ch/event/941278/timetable/#20201123.detailed
and change the Geant4 talk to be 20 minutes long..

**Expected behavior**
contributions in a session should appear in the same column

**Screenshots**

<img width="773" alt="Screen Shot 2020-10-30 at 3 03 02 PM" src="https://user-images.githubusercontent.com/5042883/97715038-3334ad80-1ac2-11eb-9613-c75b76ee9c21.png">

**Additional context**

**Comment by ThiefMaster** [comment]
Assigning session codes usually helps with this issue.

**Comment by davidlange6** [comment]
Yes, that helps - I'm onto the next oddity  (which is thanks to an oddity in our agenda)
