### ISSUE TITLE
Anonymous votes can be re-submitted by the same user

### ISSUE THREAD

**Issue by plourenco** [indico/indico#4693]
Anonymous votes are implemented as truly anonymous, in the sense that not only the event managers can't see who has voted, but also no information related to the participants is stored.

For that reason, when a survey is created as anonymous and restricted to logged-in users, if one decides to refresh his session, he will be able to vote again. This is a complicated trade-off as the definition of anonymous means no information that can trace back to the original author.

## A few alternatives

A balanced solution would be to store a list of participants that voted but without any means to match each vote to a specific author. Keeping the surveys anonymous up to a certain extent, where these risks should be acknowledged by the event managers.

Another solution would be to store them but exclude the database from the secrecy of survey answers.

A third solution would be to hash a unique participant attribute, moving the coefficient of secrecy to our secret key.

**Comment by ThiefMaster** [comment]
I'd just get rid of anonymity on the database level... this feature is not meant for elections etc. anyway, and someone with server access can already correlate logs (or edit the code) to break anonymity...
