### ISSUE TITLE
Corner case cancelling full booking - misleading description of behaviour

### ISSUE THREAD

**Issue by pferreir** [indico/indico#4719]
**Describe the bug**
When cancelling a full booking which has started already, Indico indicates that it's going to remove all the occurrences, but then removes all occurrences minus one.

**To Reproduce**
1. Create a booking which spans over 8 days. Make it so that it starts exactly today;
2. Cancel the booking;
3. Indico will ask you if you want to delete the 8 occurrences - do so;

**Expected behavior**
All occurrences should go away (or Indico should let me know that one of the occurrences will stay nonetheless).

**Screenshots**

![image](https://user-images.githubusercontent.com/2699/99969736-2c384c80-2d9b-11eb-93fc-f5e8d7aa6694.png)
![image](https://user-images.githubusercontent.com/2699/99969761-322e2d80-2d9b-11eb-9d6f-b4e7d0c18c73.png)

**Additional context**
This is was tested on Burotel. If it doesn't happen in vanilla Indico, then we should move it to the relevant repo.

**Comment by plourenco** [comment]
I tried to reproduce this in vanilla with 8 occurrences but all of them were cancelled.
