### ISSUE TITLE
Allow customization of the subject of the reminder send by email

### ISSUE THREAD

**Issue by vlimant** [indico/indico#4727]
**Is your feature request related to a problem? Please describe.**
I am sending the reminder to basecamp that expects the subject to start with "Discussion:" hence I'd like to be able to customize the subject of the reminder email.

**Describe the solution you'd like**
Under the popup to edit the reminder, being able to customize the subject would be great with available %title %date %time tokens for example, defaulting to "[Indico][Event Reminder]%title (%date, %time)"

**Describe alternatives you've considered**
there's no alternative that I can think of.

**Comment by ThiefMaster** [comment]
If you want to change it globally for your instance then you can use [template customizations](https://docs.getindico.io/en/stable/config/settings/#customization) to override the `events/reminders/emails/event_reminder.txt` template:

```
{% extends '~events/reminders/emails/event_reminder.txt' %}
{% block subject_prefix %}Discussion:{% endblock %}
```

This would replace the `[Indico]` from the original template with `Discussion:`.

I don't think this is something that's important enough to make configurable on the event level; if you want to integrate Indico with some other service, the proper solution to inform it about events would be writing a plugin for it.

**Comment by vlimant** [comment]
thanks for the pointer to customize the instance. too bad we cannot do that easily on cern indico.
