### ISSUE TITLE
Participant roles: filter view by (un)registered status

### ISSUE THREAD

**Issue by pferreir** [indico/indico#4763]
Right now there is no way to get a list, for instance, of all authors who have not registered yet.

An idea would be to add an "Unregistered users" option in here:

![image](https://user-images.githubusercontent.com/2699/105024003-e373db80-5a4b-11eb-98e6-f85ec54c36e7.png)

**Comment by pferreir** [comment]
As @ThiefMaster has already pointed out on Mattermost, we have this option here:

![image](https://user-images.githubusercontent.com/2699/105025662-ee2f7000-5a4d-11eb-91e6-e24f9d772d1b.png)

We should discuss whether the option should be moved to the "participant roles" page or just kept in both places.

**Comment by ThiefMaster** [comment]
Having it in both places probably makes sense - no need to take it away elsewhere IMO.
