### ISSUE TITLE
iCalendar export: default rely on value types

### ISSUE THREAD

**Issue by dilyanpalauzov** [indico/indico#4783]
Per https://tools.ietf.org/html/rfc5545#section-3.8.2.4 the default value type for DTSTART, DTEND and DTSTAMP is DATE-TIME.

Calling https://indico.geant.org/export/categ/0.ics returns:
```
DTSTART;VALUE=DATE-TIME:20190616T050000Z
DTEND;VALUE=DATE-TIME:20190620T153000Z
DTSTAMP;VALUE=DATE-TIME:20210217T082500Z
```

In order to reduce the amount of transferred data remove the `;VALUE=DATE-TIME` string, as it is implicit.

**Comment by ThiefMaster** [comment]
We use the [icalendar](https://pypi.org/project/icalendar/) library; I don't think it has an option for this. Maybe you want to open an issue on [their issue tracker](https://github.com/collective/icalendar) instead, or even send a PR to improve this? :)

**Comment by dilyanpalauzov** [comment]
Moved do https://github.com/collective/icalendar/issues/318.
