### ISSUE TITLE
Include Logo and Color in iCalendar export

### ISSUE THREAD

**Issue by dilyanpalauzov** [indico/indico#4787]
My reading of the code is that indico/modules/events/ical.py converts the event data to iCalendar .  The manual https://learn.getindico.io/conferences/custom_layout/ says that events can have logo and color.

Please extend the iCalendar export to include:
* the Logo, ideally as [IMAGE;VALUE=URI](https://tools.ietf.org/html/rfc7986#section-5.10) property, but alternatively as ATTACHMENT
* the [COLOR](https://tools.ietf.org/html/rfc7986#section-5.9) property.

For the latter, the RFC says this must be CSS3 name, but to my knowledge any software understands colour also as RGB value. In any case https://gitlab.gnome.org/GNOME/evolution/-/commit/736a5a3251a553de8f demonstrates how to convert RGB to the closest CSS3 color name.

**Comment by ThiefMaster** [comment]
I'm not sure how useful including the color is. As a user I would NOT expect the theme of an event affect how it looks like in my calendar.

**Comment by dilyanpalauzov** [comment]
The data is eventually imported by “Calendaring Software” like DAVx⁵.  In the example of DAVx⁵ it has an option to ignore the server-set event colour, if the user wants so.
