### ISSUE TITLE
When no materials can be downloaded for an event, hide the download link

### ISSUE THREAD

**Issue by dilyanpalauzov** [indico/indico#4793]
I click on https://indico.cern.ch/event/1009231/ to “Download materials” and get forwarded to https://indico.cern.ch/event/1009231/attachments/package .  Then I try to download “everything” and the system says “everything” ⇔ “nothing”.

**Comment by ThiefMaster** [comment]
While I get your point, I don't think the overhead of querying whether any materials exist (and possibly checking if the user has access to them as well!) whenever someone loads the event page is worth it. After all, people usually just use that link if you know there are materials you want to download...
