### ISSUE TITLE
iCalendar export: utilize RRULE for repeating events

### ISSUE THREAD

**Issue by dilyanpalauzov** [indico/indico#4795]
https://indico.cern.ch/event/955058/ and https://indico.cern.ch/event/955061/ are apparently the same thing.

Rather than generating distinct iCalendar file each thing, group both events into a single iCalendar file containing RRULE property.

**Comment by ThiefMaster** [comment]
There are no repeating events per se - each event has its own data. So adding rrules instead of keeping each event separately in the database would add a lot of complexity.
