### ISSUE TITLE
Multi-select of participants not possible (any more)

### ISSUE THREAD

**Issue by DirkHoffmann** [indico/indico#4806]
**Describe the bug**
https://indico.cta-observatory.org/event/*/manage/registration/*/registrations/ does not allow to add multiple users from the "favourites" list in the "add Indico user" dialogue (started from Register::IndicoUser dropdown menu).

**To Reproduce**
1. Go to https://indico.cta-observatory.org/event/*/manage/registration/*/registrations of your favourite test event (after activating participant registration eventually).
2. Click on 'Register', then 'Indico User`
3. Click on one user in the list of favourite users. 
4. Try to add a second (and third), e.g. by Ctrl-click
5. The first selected user is unselected. This did not happen before.

**Expected behavior**
This did not happen in Indico 1 and before, probably I also used in earlier Indico 2 version, I do not remember exactly.
I see no reason to remove the multi-select feature. Or did I miss how it works now (not Ctrl-click anyway)?

**Comment by ThiefMaster** [comment]
There should be 3 options on the drop-down: new user, existing user, multiple users. Only the last one should let you choose multiple users (since it skips showing the full registration form but only uses the users' basic personal data)

**Comment by DirkHoffmann** [comment]
> There should be 3 options on the drop-down: new user, existing user, multiple users. Only the last one should let you choose multiple users (since it skips showing the full registration form but only uses the users' basic personal data)

As usual, you are completely right. (The very different dialogues for single and multi Indico users are just an esthical point, not worth a bug report.) Sorry for the noise!
