### ISSUE TITLE
indico-plugins does not include all the plugins

### ISSUE THREAD

**Issue by andriish** [indico/indico#4849]
Hi all,

recently I was  updating indico  to 2.3.x and after reading the docs I had an impression that 
the package indico-plugins contain *all* the plugins from the indico-plugins project.

But actually it is not the case. It would make sense to emphasize it in the documentation.

Best regards,

Andrii

**Comment by ThiefMaster** [comment]
Which plugins are you missing? It contains plugins that are in a stable and usable state...

**Comment by ThiefMaster** [comment]
That's still beta. But probably we should make a stable release soon..

**Comment by andriish** [comment]
Ok, thanks for the explanation. I will test it a bit in the next days.

**Comment by ThiefMaster** [comment]
The zoom plugin is now included in the latest version of the plugin package.
