### ISSUE TITLE
New search: Search only within a category

### ISSUE THREAD

**Issue by ThiefMaster** [indico/indico#4876]

**Comment by javfg** [comment]
There are two parts to this issue:

1. Creating a `/category/<int:category_id>/search`, which shows a search page just like `/search`, and limits the output to the given category.
2. Adding a popup to the search field in the category view page (`/category/<int:category_id>`), which tells the user his search will be limited to that category, and allows him to search globally. This can be similar to GitHub's search in a repo:
![image](https://user-images.githubusercontent.com/6058151/115897016-4bc3c600-a45c-11eb-84fc-dbdf0ece85f2.png)
