### ISSUE TITLE
Paper Editing UI: Misleading "refresh" symbol next to uploaded file name

### ISSUE THREAD

**Issue by Oblynx** [indico/indico#4941]
**Describe the bug**

After uploading my paper I clicked the "refresh" symbol ([similar to this](https://cdn2.vectorstock.com/i/1000x1000/39/96/refresh-or-reload-symbol-blue-circular-arrow-vector-21433996.jpg)) that appeared next to my file, thinking that clicking that button was needed to actually upload the file. Instead, that was an "undo" button that restored the old version of my paper.

This behavior was counterintuitive _for me_ and the UI didn't lead me to do the right thing. Of course it's a totally subjective matter and maybe other people don't have the same misconception.
I'm suggesting better communication in the UI of the consequences of my actions.

**To Reproduce**

**Expected behavior**
A feedback box with a message describing the result of my action, such as "File restored".

**Comment by ThiefMaster** [comment]
hm, aren't we showing a confirmation prompt when trying to undo?

**Comment by Oblynx** [comment]
Unless I missed it... I can't reproduce because I can only upload when requested by the reviewer.

**Comment by Oblynx** [comment]
You could also have a confirmation "file uploaded". I don't think I would have made this assumption in that case.

**Comment by ThiefMaster** [comment]
OK, to summarize the clarifications we did on Mattermost:

- This is about Editing, not Reviewing
- It's about the little "undo" icon in the file manager
- **I think the best solution would be to add a tooltip (SUI `Popup`) indicating what those icons do. This can probably be done nicely on the `FileAction` component**
