### ISSUE TITLE
Make it less likely to accidentally create mixed categories

### ISSUE THREAD

**Issue by ThiefMaster** [indico/indico#4971]
Currently it's really easy to accidentally create events in the root category if creation there is not restricted or you are an admin/manager as it's pre-filled (while previously you were forced to actively pick a category).

To improve this:

- Show a warning in the event creation dialog when a category is selected which contains subcategories but no events
- Do not pre-fill the root category if it contains subcategories and no events

For the second point, check the `single_category` logic in `RHCreateEvent` - it probably just needs to be adapted

**Comment by tomasr8** [comment]
Should we prefill categories other than root that have no events but have subcategories?

**Comment by ThiefMaster** [comment]
check my comment in our MM channel ;)

(the root category is most important though because people tend to open indico and then click "create event", w/o going into any subcategory)
