### ISSUE TITLE
User search dialog: allow full row to be clicked

### ISSUE THREAD

**Issue by pferreir** [indico/indico#4973]
As of now, the only way to select a user in the search dialog is to click the "plus" icon. This is seen as confusing by some users (me included). It would be nice to accept a click on the whole row.

<img width="767" alt="image" src="https://user-images.githubusercontent.com/2699/123962840-2a2e1000-d9b2-11eb-8de4-c4f3248e40d6.png">

**Comment by ThiefMaster** [comment]
Maybe some hover effect on the full tow would be helpful as well.. otherwise I'd probably think that it's not intentional but rather a bug if the whole row reacts to clicks
