### ISSUE TITLE
Editing: change "List" icon

### ISSUE THREAD

**Issue by pferreir** [indico/indico#4974]
Change "List" icon in Editing settings

<img width="596" alt="image" src="https://user-images.githubusercontent.com/2699/123964755-12578b80-d9b4-11eb-8478-16fefbb8e3df.png">

For the sake of consistency/intuitiveness, it should be:

<img width="82" alt="image" src="https://user-images.githubusercontent.com/2699/123964679-fbb13480-d9b3-11eb-91fe-88e14fb7a6dc.png">

**Comment by ThiefMaster** [comment]
that one is already done (#4972)

(sorry, forgot to mention that)

**Comment by pferreir** [comment]
> (sorry, forgot to mention that)

No problem!
