### ISSUE TITLE
Timetable: add warning in case of draft mode

### ISSUE THREAD

**Issue by pferreir** [indico/indico#4977]
We have a "Draft" switch in the list of contributions, which decides whether the Timetable is published or not.

![image](https://user-images.githubusercontent.com/2699/123974449-e55ba680-d9bc-11eb-900a-e326130b53a8.png)

This is at times confusing for users. One nice improvement would be to add a warning at the top of the "Timetable management" page, something like "The timetable is in draft move". (followed by a "publish it" button)

**Comment by ThiefMaster** [comment]
Should we show the same toggle like on the contribution page? or a link pointing there to keep the actual widget in one place?

**Comment by pferreir** [comment]
> Should we show the same toggle like on the contribution page? or a link pointing there to keep the actual widget in one place?

I would even just add a button which enables it when clicked.

**Comment by tomasr8** [comment]
Can we simply show the same warning which is on the settings page?
(Together with the link to the contribution page)

![image](https://user-images.githubusercontent.com/8739637/124135218-e60b4000-da83-11eb-95d8-00aabbf45704.png)

**Comment by ThiefMaster** [comment]
sounds reasonable to me, but we could also go for a "Publish now" button (maybe in both places?)
