### ISSUE TITLE
Unlisted events: UI Mockups

### ISSUE THREAD

**Issue by javfg** [indico/indico#4990]
This is a subtask for https://github.com/indico/indico/issues/4294.

# UI Mockups for unlisted events

According to https://github.com/indico/indico/issues/4294, there are 3 changes to make in the user interface to accommodate unlisted events:

1. The dashboard must include a list of unpublished events belonging to the user. Entries must contain a 'Publish' button.
2. When creating an event, the category field must be optional, and by default show 'No category', specifying that the event will not be published.
3. The event management view for an unpublished event must show a 'Publish' button. The button will take the user to a category selection dialog similar to the one in event creation.

@pferreir has built a mockup of point 3 already:

![94426977-aaf37d80-018e-11eb-973f-27adf5610f0c](https://user-images.githubusercontent.com/2699/124566988-d739da00-de43-11eb-9bd2-d3747c490e9b.png)

The task for this issue is to create mockups for points 1 and 2.

Following @ThiefMaster's advice, we are using [Balsamiq Wireframes](https://balsamiq.com/wireframes/) for this, as we have licences for the software.

**Comment by ThiefMaster** [comment]
> When creating an event, the category field must be optional, and by default show 'No category', specifying that the event will not be published.

I think it would make sense to have some kind of widget where it's clear what you are doing - so not just "not selecting a category" but rather ticking a "Create as unlisted event" checkbox *or something like that*.

**Comment by javfg** [comment]
### 1. Create event dialog
#### 1.1. Using a button group
| Listed | Unlisted |
| ------- | ------- |
| ![Create event dialog (listed) buttongrp](https://user-images.githubusercontent.com/6058151/124724777-93f76e00-df0c-11eb-8b0f-4fee73a2a622.png) | ![Create event dialog (unlisted) buttongrp](https://user-images.githubusercontent.com/6058151/124725008-cbfeb100-df0c-11eb-843c-90882007022c.png) |

#### 1.2. Using an on/off toggle
| Listed | Unlisted |
| ------- | ------- |
|![Create event dialog (listed) onoff](https://user-images.githubusercontent.com/6058151/124725203-fbadb900-df0c-11eb-88da-55e4744adaa5.png)| ![Create event dialog (unlisted) onoff](https://user-images.githubusercontent.com/6058151/124725218-fd777c80-df0c-11eb-9da1-da7ae3a334b0.png)|

#### 1.3. Using flowing buttons and text
| Listed | Unlisted |
| ------- | ------- |
| ![Create event dialog (listed) text](https://user-images.githubusercontent.com/6058151/124725301-0cf6c580-df0d-11eb-8511-41c94d7266d0.png) | ![Create event dialog (unlisted) text](https://user-images.githubusercontent.com/6058151/124725316-0f591f80-df0d-11eb-87ec-55d2e2203d0e.png) |

### 2. Dashboard
| 1. Original |
| ------- |
| ![Dashboard](https://user-images.githubusercontent.com/6058151/124725618-47606280-df0d-11eb-8126-39fe0c9d49b6.png) |

| 2. Alternative arrangement |
| --- |
| ![Dashboard alt](https://user-images.githubusercontent.com/6058151/124726832-68758300-df0e-11eb-9b8b-62568e526bc3.png) |

---

Any ideas are welcome! Also, wording changes (not sure about 1.1 especially).

**Comment by ThiefMaster** [comment]
Looks nice! I don't think publishing an unlisted event is an action that should happen from the dashboard - I'd rather have people go to the event's management area where they see any warnings etc. which may be displayed there.

**Comment by javfg** [comment]
> Looks nice! I don't think publishing an unlisted event is an action that should happen from the dashboard - I'd rather have people go to the event's management area where they see any warnings etc. which may be displayed there.

Good idea. The button could take you to the management area instead, maybe changing the wording in it.

**Comment by javfg** [comment]
As we decided in the zoom meeting, selected mockups are:

### 1. Create event dialog
#### 1.1. Using a button group
| Listed | Unlisted |
| ------- | ------- |
| ![Create event dialog (listed) buttongrp](https://user-images.githubusercontent.com/6058151/124724777-93f76e00-df0c-11eb-8b0f-4fee73a2a622.png) | ![Create event dialog (unlisted) buttongrp](https://user-images.githubusercontent.com/6058151/124725008-cbfeb100-df0c-11eb-843c-90882007022c.png) |

and

### 2. Dashboard
| 2.1. Original |
| ------- |
| ![Dashboard](https://user-images.githubusercontent.com/6058151/124725618-47606280-df0d-11eb-8126-39fe0c9d49b6.png) |
