### ISSUE TITLE
Non-localized Dear in password recovery e-mail

### ISSUE THREAD

**Issue by vaclavstepan** [indico/indico#5010]
**Describe the bug**
When recovering password, most of the e-mail is localized, but "Dear" stays put.
It seems to come from indico/web/templates/emails/base.txt or indico/web/templates/emails/base.html.

So, you get something like:

_Dear Václav,
Wygląda na to, ze zapomniałeś swojej nazwy użytkownika lub hasła._

**To Reproduce**
1. Switch to non-english language
2. Log out of Indico
3. On login, choose password recovery and send yourself the e-mail.

**Expected behavior**
It's all in the chosen language.

**Comment by ThiefMaster** [comment]
nice catch, fixed

**Comment by vaclavstepan** [comment]
Thank you :-)
