### ISSUE TITLE
Parts of the registration form are not localized

### ISSUE THREAD

**Issue by vaclavstepan** [indico/indico#5012]
**Describe the bug**
Parts of the registration form and e-mails do not reflect language settings (tried Spanish, French, Czech). These are:
- *Field names* (e.g. First name, …) – they seem defined in Transifex, but not translated in the form. I understand that mess will occur universally, when someone defines a new unknown field.
- If the registration is done by manager, there is a section called "Email notification"
- Last two lines in the registration form:
```
(All the fields marked with * are mandatory)
Register
```
- In the e-mail sent with registration details, part of the text is hardcoded, seems to come from modules/events/registration/templates/emails/registration_creation_to_registrant.html

**To Reproduce**
1. Login as Indico user
2. Click on Registration
3. Fill it
3. Scroll down.
4. See error, read mail, see error

**Expected behavior**
Register button text and the note before it should be localizable.

**Comment by ThiefMaster** [comment]
I'm afraid that's most likely going to be a "wontfix" for now...

We have i18n markers in the legacy Angular code, but nothing that extracts those strings. And considering that we will get rid of the AngularJS code (and rewrite it in react) in a future version, it's unlikely that we'll spend the (significant) effort of adding i18n support to this legacy code.

**Comment by vaclavstepan** [comment]
Ok, understood, thank you. We'll fix it locally now and look forward to future.
