### ISSUE TITLE
Generating an additional histogram in the Stats page of a registration form

### ISSUE THREAD

**Issue by narnaud1974** [indico/indico#5030]
Hello,

I'm using Indico v2.3.5 at my home institution. I would like to know if there is a way to customize the "Stats" button in Organization/Registration. Currently (by default) it shows the number of registrations, the number of days left to register and the number of countries from where the participants come. And below there is an histogram showing the number of registrants per country. Our registration form includes a field called "Collaboration": is there a way to have an histogram automatically generated for that additional field as well? If not, I'll export the registrant spreadsheet and create that histogram by hand.

Thanks in advance,

Nicolas

**Comment by javfg** [comment]
There is no user-facing way to add a custom field to the registration stats. Making that stats page more customisable might be an interesting feature for the future.

For now, you will have to generate the histogram by hand.

**Comment by javfg** [comment]
By the way, in the future, you should ask this kind of questions in the forum: https://talk.getindico.io/. It will be much easier for you to get proper responses in there instead, as they will reach more people.
