### ISSUE TITLE
List of abstracts: filters are not well defined (missing "no value")

### ISSUE THREAD

**Issue by t4nec0** [indico/indico#5033]
**Bug Description**
_It's not possible to filter the of abstracts according to some fields where no values are wanted._

**To Reproduce**
Let's say that the admin adds a custom field (not visible to submitters) called "abstract state" for a custom workflow that enhances the Indico built in. For the sake of simplicity I consider here a radio button called "**Abstract QA**" with only one value: **Yes**. This is editable only by the admin, so by default this field will have no value at submission type.

Let's say that we have 100 abstracts submitted. The admin wants to "pre-accept" them by editing them and setting the "Abstract QA" field. This admin edits 80 abstracts and sets this field to YES, then stops. 
**Please note that at this editing stage the Abstract QA field actually has two values, even if only one was set**: "_No selection_" and "_Yes_":

![Selection_014](https://user-images.githubusercontent.com/6997171/128531406-c47dea52-f199-4321-b7d6-115314740e4c.png)

The day after, they want to QA the remaining 20 so they want to filter out all the other 80. They:

1. go to Manage Abstracts
2. click on _Customise list_
3. try to select the one that still have NOT selected a Yes in Abstract QA:
![Selection_014](https://user-images.githubusercontent.com/6997171/128531575-fddbb32b-e817-4273-b750-20f6bd8d5c14.png)
4. realise that it's **not possible to only list those that have NOT the "Yes" value in this field**.

**Expected behavior**
Have a "No selection" option in the filter.

**Additional context**
Please note that the logic of other multi-value fields is not correct either: as an example, consider the abstracts state.
By default **all abstracts are shown**. By entering the "Customise list" panel and opening the _State_ field, **no options are selected** which should mean "do not show any". If I select one, I only get that state. Idem for two. If I select all of them, I get back "any state", like when no state is selected. This means we have two possibilities for one filter (any) and no possibilities for another (no value for that field).

**Expected behavior**
By default that field filter should have *all options* selected. By deselecting all of them we'll get the abstracts with "no value" for that field. Or, different option, include a fictitious _value_  "no selection" like in the abstracts editing. 
The two areas should at least be consistent.

**Comment by ThiefMaster** [comment]
I disagree on selecting everything by default; but adding a "no value" fikter (additional checkbox) sounds like a very good idea! And it will be more flexible than "deselect everything" because it will allow you to filter e.g. by no value OR some specific other value at the same time.
