### ISSUE TITLE
Not notification when reset approval

### ISSUE THREAD

**Issue by jbtwist** [indico/indico#5036]
**Describe the bug**
When a registration what has been already approved or rejected is reset by a manager, the system it is not sending any email to the user. This can cause confusion to the users because they can think they are approved to an event who they are not. 

However, the system is sending an email to the user when has withdrawn it's own apply.

I'm not 100% sure if this is the way the system it's suposed to work, but it has non-sense in my eyes, and this problem has a really easy solution.

**To Reproduce**
1. Go to any event which registrations needs approval from managers.
2. Add a registration.
3. Approve or reject it, it will send an email.
4. Reset that registration, it won't send an email.
5. Withdraw that registration, it will send an email.

**Expected behavior**
In my opinion, when you set as pending an event, it should send the same email as when you register and you are pending from approval.

**Screenshots**
![image](https://user-images.githubusercontent.com/11741165/129216813-e61f6429-8cad-4673-885e-1f9eace0d411.png)
![image](https://user-images.githubusercontent.com/11741165/129216666-c6ee7304-4851-4412-b4ad-1afce80fbfa5.png)
**No image for reset approval**
![image](https://user-images.githubusercontent.com/11741165/129216950-f848fb08-5c45-4fb6-b577-db4349dee4ba.png)

**Additional context**

**Comment by jbtwist** [comment]
I didn't noticed at the message, tyvm then.

**Comment by javfg** [comment]
Hey @jbtwist!

The idea behind this is:

* Approval and rejection are regular actions which usually do not require any special communication with the registrant. An automated email with a standard message is sent.
* Reset is a special action which normally requires the conference manager to already be in contact with the registrant, or to contact him with additional information.

Hope this clears it up.

**Comment by jbtwist** [comment]
Ok, so it is designed that way, then I guess it is not an issue, tyvm
