### ISSUE TITLE
Markdown not used in generation of the PDF version of Scientific Programme

### ISSUE THREAD

**Issue by vaclavstepan** [indico/indico#5043]
**Describe the bug**
Markdown is not rendered in the PDF version of the Scientific Programme page.

**To Reproduce**
1. In Management area, create a track and enter Markdown code into its description
2. In Display view, click the PDF icon on the Scientific Programme page.
3. Scroll down to place where your rendered Mardown code would be.
4. See the Markdown source code, not its rendered version.

**Expected behavior**
The Markdown should be interpreted.

**Comment by ThiefMaster** [comment]
Is there any particular markdown that doesn't work? We do limit the tags (and exclude e.g. links - don't ask me why), but when I tested with basic stuff such as `**bold**` text it worked fine. I don't see any case where raw markdown source would remain in the PDF.

**Comment by vaclavstepan** [comment]
When inserted in the introductory text for scientific programme, markdown works.
But when markdown is inserted in a description of a track it fails.
For example, this fails, resulting in [this](https://indico.ujf.cas.cz/event/2/program.pdf).

```
*Odborný garant:* Radoslav Bohm, Anna Jelínek Michaelidesová

Sekce je věnována biologickým účinkům záření. Ionizující záření může být nebezpečné, ale může být využité i pro dobré účely, jako je radioterapie, zobrazovací modality v medicíně, sterilizace lékařského či potravinářského materiálu, a mnoho dalšího. Do této sekce patří tedy vše co se týká ionizujícího záření s ohledem na jeho biologické působení. Ať už to jsou nízké dávky či vysoké, ať už to byly bakterie, buňky či celé živé organismy, tvůj příspěvek nás rozhodně zajímá.    

**Zvaná přednáška: About translational radiooncolgy – past, present, future**
*Antje Dietrich*

Antje Dietrich je vědeckým koordinátorem German Cancer Center partner site Dresden a senior PostDoc v laboratoři profesorky Mechthild Krause v OncoRay – National Center for Radiation Research in Oncology. Její výzkum se zaměřuje hlavně na protonovou radiobiologii. Její současné vědecké projekty se zabývají radiačně indukovanému poškození mozku a charakterizací nádorového mikroprostředí v preklinických modelech. 
![](/event/2/images/31-Antje_Dietrich.jpg)

In the lecture, I will give an overview about translational research in radiation oncology and how models and research questions changed in time. I will show clinical examples leading from large trials, testing one new drug, to so called basket trials in the area of precision medicine. In addition, I will discuss the development of preclinical radiooncological research touching classical models and assays and introduce some of the state-of-the-art research which can be realized using advanced in virtro models, precise image-guided small animal irradiation workflows, heterogeneous tumor cohorts as well as preclincial radiomics-approaches.
```

**Comment by ThiefMaster** [comment]
Oh, in the track description. Hadn't tested that. If we render markdown there in the HTML views, then we should indeed support it in the PDF as well.
