### ISSUE TITLE
TypeAhead Widget not working with some Validators, like HiddenUnless

### ISSUE THREAD

**Issue by jbtwist** [indico/indico#5048]
**Describe the bug**
When you combine TypeAhead Widget with attributes for validators added at render_field function, it won't work because those validators won't be added 

**To Reproduce**
1. Go to any registration form (in my case, I went to RegistrationFormForm)
2. Add a first (A) StringField with HiddenUnless validator and TypeaheadWidget
3. Add a second (B) StringField only with HiddenUnless validator
4. Activate the field that triggers the HiddenUnless, it will only work on B.

**Expected behavior**
I expect the HiddenUnless validator (and other extra validators) to work in combination with Typeahead widget.

**Screenshots**
![image](https://user-images.githubusercontent.com/11741165/130426378-0acd5409-b088-454a-9e5f-3969e9b78c57.png)
![image](https://user-images.githubusercontent.com/11741165/130426268-30742d8f-a0d9-4f5b-9f13-d53d6d96d432.png).

**Additional context**
I'm not sure if this issue is afecting to more widgets. For example I think it is afecting to the ckeditor_widget, but I have not tested it.

**Comment by ThiefMaster** [comment]
I don't think we are using this combination anywhere in Indico, are we? The client-side validators that add magic like HiddenUnless are somewhat fragile when it comes to non-standard fields (anything that's not a standard form field but makes heavy use of JS), so unless this is breaking anything in the core I think it's unlikely that we are going to fix this (but a PR is welcome as long as it's not likely to break anything)

**Comment by jbtwist** [comment]
Yes, I was preparing the PR that fix this, I don't think It will break anything because it is mostly copied from the Date-Widget logic, and it would fix an Issue at the UN side.

**Comment by ThiefMaster** [comment]
OK, thanks! Please open the PR against the `3.0.x` branch.

**Comment by jbtwist** [comment]
I cannot push a new branch to the proyect, can you tell me why can't I and how to add my PR then please?

![image](https://user-images.githubusercontent.com/11741165/130431224-820088a4-d19d-4fb9-949c-b696888aff9f.png)

**Comment by ThiefMaster** [comment]
We're using the standard workflow pretty much all projects on github uses, so you need to fork the repo and push the branch to your fork...

**Comment by jbtwist** [comment]
oh, ok, tyvm
