### ISSUE TITLE
Add ability to issue attendance+presentation certificates

### ISSUE THREAD

**Issue by agbuckley** [indico/indico#5060]
Many funders require a conference-issued certificate of attendance & presentation, perhaps with specific requirements such as "conference headed paper" and "organiser signatures". The closest Indico comes to this is the Badge system, but this does not have access to the participant's presentation(s) title, type, or date. This information is available for each contribution individually in the Contributions list, but this does not meet some funders' requirements of heading, signature, etc.

It would be ideal if there was a built-in Certificates facility that could be enabled, to provide each attendee with a certificate PDF customisable by the meeting organisers to add signature images etc. if necessary. Much of the backend could presumably be shared with the badge facility, just extended to include the contribution details currently available via the Contribution pages. I expect that a certificate _per contribution_ would also be acceptable, provided the heading / signature customisations are possible.

As certificates are essentially a personal document for the contributor, I would not think this should be publicly available -- either generate+email-able via the registration / contributor lists, or accessible specific to the user's Indico login.

**Comment by EISSeuropa** [comment]
Hi! Any news on this?

**Comment by ThiefMaster** [comment]
The one I mentioned in my last commit is currently on our roadmap for 3.3 this summer.

**Comment by EISSeuropa** [comment]
Great news, thank you! Any idea on the release window?

**Comment by ThiefMaster** [comment]
"this summer" ;)

**Comment by EISSeuropa** [comment]
Haha got it. Do you know if it will work for past events as well, or only new ones?

**Comment by ThiefMaster** [comment]
I don't see any reason why it would not work in past events

**Comment by EISSeuropa** [comment]
That's great, thank you for all your answers!

**Comment by ThiefMaster** [comment]
This is part of the upcoming v3.3 release (#5123)

**Comment by DeMiro5001** [comment]
Hello, I couldn't find in the docs how to create presentations certificates nor in the placeholders lists.
Thanks for your help

**Comment by ThiefMaster** [comment]
See https://learn.getindico.io/document_templates/about/
