### ISSUE TITLE
Link leading to nonexistent page in indico/web/templates/forms/markdown_widget.html

### ISSUE THREAD

**Issue by vaclavstepan** [indico/indico#5064]
**Describe the bug**
When submitting new abstract, the user is shown a hint that "You can use Markdown and LaTeX math formulae." And the LaTeX link points to a nonexistent page, because the MathJax documentation evolved and now the page doesn't exist.

The nonexistent link is in `indico/web/templates/forms/markdown_widget.html` points to `https://docs.mathjax.org/en/latest/tex.html#supported-latex-commands` – but it should point to `https://docs.mathjax.org/en/latest/input/tex/macros/index.html` or more generally to `https://docs.mathjax.org/en/latest/input/tex/index.html`.

**To Reproduce**
1. Open abstract submission workflow
2. On the right of the Abstract submission workflow there is an info icon - when you click on it, a hit appears with two links.
3. Click on the LaTeX link
4. See the message about non-existent link appear.

**Expected behavior**
A link should point to a HTML page that exists.

**Additional context**
MathJax documentantion has been restructured and now the link should point elsewhere.

**Comment by ThiefMaster** [comment]
Would you like to send a PR (for the 3.0.x branch) to fix this? No need to install Indico to it; it's just updating the URL anyway..

https://docs.mathjax.org/en/latest/input/tex/macros/index.html like a good choice; it's similar to the [old page](https://web.archive.org/web/20170705052121/https://docs.mathjax.org/en/latest/tex.html#supported-latex-commands) whose link broke during one of the last years...

**Comment by vaclavstepan** [comment]
Yes, I'll submit a PR.

**Comment by ThiefMaster** [comment]
Thanks! closed by #5065
