### ISSUE TITLE
Partially missing localization strings in abstract.tex

### ISSUE THREAD

**Issue by vaclavstepan** [indico/indico#5067]
**Describe the bug**
When user locale is set non-english, PDF generated for an abstract from the list of abstracts contains several strings that aren't translated. Namely: "Abstract ID", "Track Classification", "Submitted by".
(Also, the date of submission is in en_GB, not localized.)

It seems the strings are referenced in the template `indico/legacy/pdfinterface/latex_templates/inc/abstract.tex` but not present in Transifex - so probably never defined for translation?

**To Reproduce**
1. In a conference with abstract submission workflow setup, submit an abstract
2. Set the Indico user language to Polish
3. In the list of abstracts, open the abstract and click the PDF icon and download the abstract PDF
3. See that theses field titles (mentioned above) will remain untranslated

**Expected behavior**
Even these strings should reflect the user choice of language.

**Comment by ThiefMaster** [comment]
Maybe we forgot to include .tex files for i18n extraction...

**Comment by vaclavstepan** [comment]
Many strings are translated, only few are not.

**Comment by ThiefMaster** [comment]
Yes, strings that are already extracted because they are used elsewhere work fine.

**Comment by vaclavstepan** [comment]
Thank you, yes, the strings are available in Transifex now. 
In the submitted by line, the date still stays untranslated, probably this is a different issue.

**Comment by ThiefMaster** [comment]
Yeah. very similar to #5059 i'd say. Maybe leave a comment in there to point this out?
