### ISSUE TITLE
Localization: Country names

### ISSUE THREAD

**Issue by vaclavstepan** [indico/indico#5070]
**Describe the bug**
When registration includes list of contry names, it uses English versions of their names.
For an event held in a different language this is unpleasant.

**To Reproduce**
1. Create a conference with a participant registration
2. In participant registration form, see the values in the Country drop down menu

**Expected behavior**
Country names should respect the event language.

**Comment by ThiefMaster** [comment]
Hm, tricky one. We get those country names from [pycountry](https://pypi.org/project/pycountry/) but AFAIK it only contains the English names.

The only solution I see there is generating a file with all the country names wrapped as translatable strings so they can get extracted for translation...

**Comment by vaclavstepan** [comment]
I see. In the documentation of pycountry, there is a part dedicated to translating - from the example it seems that the library can do it. Would that be usable?

See Locales section at https://pypi.org/project/pycountry/

--
Department of Radiation Dosimetry, Nuclear Physics Institute of the CAS, Prague, Czech Republic

**Comment by ThiefMaster** [comment]
Oh nice, hadn't noticed that. That should make things much easier for sure.

**Comment by pferreir** [comment]
I don't think `pycountry` is even needed. You have all that information already in `babel`. e.g.:

```python
In [40]: from babel import Locale

In [41]: cs_CZ = Locale('cs', 'CZ')

In [42]: cs_CZ.languages['gsw']
Out[42]: 'němčina (Švýcarsko)'

In [43]: cs_CZ.languages['pt']
Out[43]: 'portugalština'
```

**Comment by ThiefMaster** [comment]
For the country name you probably want `get_current_locale().territories.get(x)` with a fallback to the untranslated name (e.g. for custom countries defined via `CUSTOM_COUNTRIES` or countries that no longer exist (e.g. SU = Soviet Union))

**Comment by tomasr8** [comment]
The babel `Locale.territories` also include things like continents and regions. The continents can be easily flitered out since they don't use the alpha-2 codes, but then there are things like `EU - European Union` and `EZ - Eurozone` (seems weird, didn't find a mention of this in iso3166). Should we keep it in the list?

**Comment by ThiefMaster** [comment]
You'd still get the list from pycountry.. babel would just be used to look up a translated name.. Something like this:

`{code: locale.territories.get(code, name) for code, name in get_countries().items()}`
