### ISSUE TITLE
"Convener" tag name not localizable

### ISSUE THREAD

**Issue by vaclavstepan** [indico/indico#5073]
**Describe the bug**
The reviewing area shows labels "Reviewer" and "Convener" where appropriate for a given user, so it's clear who can handle what in which track. For some reason, the string "Convener" is not localizable via Transifex - search for it returns nothing.
"Reviewer" is there just fine.

**To Reproduce**
1. Create a conference with tracks
2. Try to assign roles to the users using the Roles in abstract submission setup
3. Switch to some other localization, like Turkish
4. See the "Convener" string stand out in the page.

**Expected behavior**
"Convener" string should be localizable.

**Comment by ThiefMaster** [comment]
Could you add a screenshot? I'm not sure where exactly the untranslatable string is...

**Comment by vaclavstepan** [comment]
Yes, please see [here](https://linux.fjfi.cvut.cz/~w/convener.png).
