### ISSUE TITLE
Adding many authors (~30) in abstract submission makes reordering extremely slow 

### ISSUE THREAD

**Issue by klieret** [indico/indico#5082]
**Describe the bug**

**To Reproduce**

1. Go to an abstract submission page
2. Add around 30 authors
3. Try to move a single author up or down the list

**Expected behavior**

Authors just reorders

**What happens instead**

Dragging the author works until you release your mouse upon which the page slows down so much that firefox shows the following warning

**Screenshots**

![image](https://user-images.githubusercontent.com/13602468/132982313-37a9b004-39a1-4b3a-89ba-9e90863cbbec.png)

**Additional context**

Firefox 78.0.2 (64-bit)

**Comment by klieret** [comment]
Moving an author to the co-authors shows similar behavior.

**Comment by plourenco** [comment]
Thanks! I can confirm this is a problem. I'm tagging it to be addressed in #5209

**Comment by plourenco** [comment]
Fixed in #5209
