### ISSUE TITLE
Expose attachments checksums in the export API

### ISSUE THREAD

**Issue by avivace** [indico/indico#5084]
The `/export/event/` endpoint seems to not mention any kind of checksum for the attached files.

As I understood from the [AbstractFile](https://docs.getindico.io/en/stable/api/abstract/?highlight=hash#indico.modules.events.abstracts.models.files.AbstractFile.md5) model, you do already compute and save MD5 checksums. If this is consistent through all the attached files in events, would it be possible to expose this information in the API?

**Comment by avivace** [comment]
This would also make possible to find duplicates in attachments, since files with the same names are allowed.
E.g. on "ilcagenda", record 1049, has files with same name in the same directory/level, so there's no way from the API to understand if it's just a duplicate or they are actually duplicate entries (in that case they are actually slightly different files).

**Comment by ThiefMaster** [comment]
Yes, we store an md5 hash for all attachments, so we could indeed include this in the APIs. Would you like to send a PR for this? I think including the `attachment.file.md5` in `_build_attachment_api_data` is all that's needed.

**Comment by avivace** [comment]
> Yes, we store an md5 hash for all attachments, so we could indeed include this in the APIs. Would you like to send a PR for this? I think including the `attachment.file.md5` in `_build_attachment_api_data` is all that's needed.

Sure, I can take a look
