### ISSUE TITLE
Export API not exposing attachments details for some type of events

### ISSUE THREAD

**Issue by avivace** [indico/indico#5087]
Normally, e.g. event 810687, the `/export/event/<event>` API endpoint returns a result where the `folders` and `material` keys expose every attachment URL.

However with events like 947805 the same endpoint returns no mentions whatsoever of the attached files..

Are only a subset of "events" supported by the `export` endpoint? Are we expected to query the API in some other ways for the other type of events?

**Comment by ThiefMaster** [comment]
You need `?detail=contributions` there because the attachments are not linked to the event itself but to the contributions. Or even better, `?detail=subcontributions` in case some events use subcontributions as well.

**Comment by avivace** [comment]
> You need `?detail=contributions` there because the attachments are not linked to the event itself but to the contributions. Or even better, `?detail=subcontributions` in case some events use subcontributions as well.

Thanks. Is there a way I can understand when I should use `contributions` or `subcontributions`? 
In the response of the query without `detail` I don't see any indication of the fact that event is using contribution or subconstributions..

Or is it safe to always use `subcontributions` to get everything that is available?

**Comment by ThiefMaster** [comment]
you can always use subcontributions, it's the most verbose level that includes everything
