### ISSUE TITLE
API: /export/event returning empty response for restricted events

### ISSUE THREAD

**Issue by avivace** [indico/indico#5089]
I generated an API Token granting all the select-able scopes. Trying to get details about event `1024767` just returns an almost empty response.

```python
import requests
url = "https://indico.cern.ch/export/event/1024767.json?detail=subcontributions&occ=yes&pretty=yes"
headers = {"Authorization": "API_Token"}

r = requests.get(url, headers = headers)

r.json()
```

Response:

```python
{'count': 0,
 'additionalInfo': {},
 'ts': 1631715349,
 'url': 'https://indico.cern.ch/export/event/1024767.json?detail=subcontributions&occ=yes&pretty=yes',
 'results': [],
 '_type': 'HTTPAPIResult'}
```

Is there something wrong in how I am building the request?

**Comment by ThiefMaster** [comment]
Does the user the token belongs to have access? Does it also happen if you specify `Authorization: Bearer <token>` (just in case you forgot the "Bearer " in the header)?

**Comment by avivace** [comment]
My bad: classic scope was missing (`legacy_api`)
