### ISSUE TITLE
In room booking show equipment information in room details

### ISSUE THREAD

**Issue by kastanas** [indico/indico#5098]
When looking at the list of rooms in the room booking module it is possible to filter rooms
based on the equipment present. However once a room is selected and we go to the room
details there is no way to see the list of equipment there (other than going to the room edit
menu, but that is not available to everyone).

Would it be possible to have a list of the room's equipment visible, e.g. under the room name
and room information, e.g. in the bottom left corner in the attached screenshot. NB: This is
based on a version 2.3.5 server, apologies if this is already fixed in version 3.

Many thanks in advance.

Best regards,
Alex Kastanas

**Comment by ThiefMaster** [comment]
For now you can define Features - those are shown in the room details dialog (and when hovering them the equipment types that provide the feature in this room are shown in a tooltip).

PS: In 3.0 the behavior is the same, but you should upgrade nonetheless ;)

**Comment by kastanas** [comment]
Ah! I see, many thanks for the super fast answer! In that case I believe this is already covered.
Version 3 upgrade is in the pipeline (and is looking very nice BTW with upgrades to python 3
and moving to newer versions of postgres).

**Comment by kastanas** [comment]
Unfortunately it is not entirely clear how to use features, as I am able to define them, but
cannot assign them to a room (only able to assign equipment). Is there perhaps some
documentation on how this feature should be used?

**Comment by ThiefMaster** [comment]
Features are always provided by equipment. For example, you could have a "Projector" feature and "4:3 Projector" and "16:9 Projector" equipment types. You'd then assign the feature to all equipment types that should provide it:

![image](https://user-images.githubusercontent.com/179599/134496295-4627ba04-8a5c-4bf0-95e6-95f4f84f4266.png)

So as soon as a room has any of those equipment types, it will have the feature.

**Comment by ThiefMaster** [comment]
Related forum thread where I posted some more screenshots regarding features etc: https://talk.getindico.io/t/2-x-how-to-see-room-attributes-and-equipments/2389/2?u=thiefmaster

**Comment by kastanas** [comment]
I see, that's a very nice solution! Many thanks!
