### ISSUE TITLE
An option to delete the "Call for abstracts" workflow

### ISSUE THREAD

**Issue by andriish** [indico/indico#5109]
Hi all,

It would be nice to have  an option to delete the "Call for abstracts" workflow.

**Describe the solution you'd like**
A button "delete this workflow" for "Call for abstracts"

**Describe alternatives you've considered**
Switching the event type from "Conference" to "Lecture"  and back deletes the workflow.
But this is inconvenient for conference managers.

Best regards,

Andrii

**Comment by ThiefMaster** [comment]
What's the usecase for this? You can already disable the whole feature (advanced -> features) in your event.
