### ISSUE TITLE
Add a z-index field in Poster and Badge Designer

### ISSUE THREAD

**Issue by SegiNyn** [indico/indico#5117]
**Is your feature request related to a problem? Please describe.**
This feature allows the badge designer to order how items on a badge/poster are printed using the z-index value 

**Describe the solution you'd like**
In the Poster and Badge Designer page, include a field, 'z-index' which would allow to set the z-index value of the items on a badge. This value will be used to order the display of the items so that items with a lower z-index value would appear behind items with a higher z-index value.  
<img width="355" alt="Screenshot 2021-10-11 at 11 57 06" src="https://user-images.githubusercontent.com/54508387/136800518-e129f41c-c3a6-46b2-9416-63d7d40f3fdb.png">
<img width="347" alt="Screenshot 2021-10-11 at 11 55 41" src="https://user-images.githubusercontent.com/54508387/136800535-950fa489-9f14-449e-aa77-762cec09aacd.png">

<img width="343" alt="Screenshot 2021-10-11 at 11 59 53" src="https://user-images.githubusercontent.com/54508387/136800549-e9997eed-3eb3-43cd-a6b4-4e6a0b19d7e7.png">

**Comment by ThiefMaster** [comment]
Hi, are you sure this is really an issue in upstream Indico? Unless I'm mistaken, we do not have background colors or additional image fields - and with just plain text fields, having a configurable z-index doesn't seem to have any benefit (as overlapping text will look terrible no matter what)

**Comment by OmeGak** [comment]
As discussed offline, we will finally:
1. Allow configuring a background color in text elements (transparent by default).
2. Not expose element depth as raw z-index but, rather, as "move forward/backward" buttons, like in vector graphics programs.

**Comment by ThiefMaster** [comment]
closed by #5139
