### ISSUE TITLE
The "cancelled" tag should appear in weekly summaries.

### ISSUE THREAD

**Issue by pkoppenb** [indico/indico#5140]
The meeting https://indico.cern.ch/event/985098/ is cancelled, and so is https://indico.cern.ch/event/982577/.

In the former, the "cancelled" label was set, while in the latter the meeting title was hacked to include the word "CANCELLED".

When I go to the weekly digest at https://indico.cern.ch/category/6734/overview?period=week I see the latter being cancelled but there's no notice for the former. This discourages the use of labels. 

Similarly, in my google calendar only the latter is clearly visible as cancelled.

![Screenshot from 2021-11-03 09-37-07](https://user-images.githubusercontent.com/14927192/140030184-30dc5e3a-2f92-412d-a1e4-a39a98e2ac91.png)

I think the cancelled label should appear in all summary pages next to the title.

**Comment by ThiefMaster** [comment]
Sound like a good idea!
