### ISSUE TITLE
Let event managers see timetable etc. while in draft mode

### ISSUE THREAD

**Issue by ThiefMaster** [indico/indico#5141]
Instead of completely rejecting access to the timetable (and other pages that are affected by draft mode), let's show show a message box indicating that it's currently restricted to managers because of draft mode.

**Comment by leoredi** [comment]
I love that this issue for you is "trivial"

**Comment by fer-rum** [comment]
Since there is a successful MR for this, should this issue be closed?

(Or is there any reason, this is kept open on purpose?)

**Comment by ThiefMaster** [comment]
nope just forgot it
