### ISSUE TITLE
indico event reminder: iCalendar file

### ISSUE THREAD

**Issue by annamanou** [indico/indico#5166]
**Is your feature request related to a problem? Please describe.**
The iCalendar file does not include the videoconference connection details.

**Describe the solution you'd like**
I would like to have in my calendar invite the connection details of the event.

**Comment by ThiefMaster** [comment]
How are you getting it? Are you authenticated? Because I'm pretty sure we are adding it as long as you are authorized to see the passcode..

**Comment by annamanou** [comment]
Yes, I am authenticated.

**Comment by pferreir** [comment]
It's the file which comes in the registration e-mail, not the one you download from the event.

**Comment by ThiefMaster** [comment]
I think we should pass `skip_access_check` through to `generate_event_component` and the `metadata_postprocess` signal and skip the usual access check in the Zoom plugin if that flag is set. It's probably reasonable to assume that recipients of event reminders should get a proper Zoom connection link if the event organizer decided to include it in the reminder email anyway..
