### ISSUE TITLE
email message reading "event will start" is not appropriate for past events

### ISSUE THREAD

**Issue by paolini** [indico/indico#5182]
**Describe the bug**

**To Reproduce**
Add an event in the past and send a reminder to yourself

**Expected behavior**
The email text should read "the event [...] has taken place on [...]"

**Comment by ThiefMaster** [comment]
Do you have a particular usecase for sending reminders that are in the past? I believe we don't even allow to create reminders with an absolute time that's in the past...

**Comment by paolini** [comment]
After the conference has been completed I would like to inform the participants that some more material is available (e.g. pictures, slides, etc). I'm not sure if the reminder is the correct tool to achieve this, but I see no other mean to send an email to all participants. I use the reminder with type "send immediately".

**Comment by ThiefMaster** [comment]
The reminders are not really meant for this; you may want to use the email functionality in the registration module or the contribution list..

**Comment by paolini** [comment]
I'm not able to find the "email functionality". In fact I was expecting to find it in the registration module. I'm currently using indico v2.3.5

**Comment by ThiefMaster** [comment]
If you go to the list of registrants and select some, there's an action "send emails" (or something like that).

PS: That version is outdated; you should upgrade to v3 as soon as possible.

**Comment by paolini** [comment]
Now I see it! Thanks.
