### ISSUE TITLE
Include more filters in the list of editables

### ISSUE THREAD

**Issue by plourenco** [indico/indico#5188]
**Is your feature request related to a problem? Please describe.**
The list of editables currently has no filters. Not only when navigating through it, but also while using the future "Get Next Paper" it can become complicated for editors to select one just by scrolling.

**Describe the solution you'd like**
It would be interesting if the list of editables had more filters such as contribution attributes (programme code) and tags.

In the same way, we could simplify this process by merging "Get Next Paper" with the list, making the former an option of the latter.

**Comment by tgbaron** [comment]
Also filtering by "My assigned papers" would be very nice for an editor
