### ISSUE TITLE
Privacy dashboard: new React widget for multiple URLs

### ISSUE THREAD

**Issue by tomasr8** [indico/indico#5206]
Separate issue based on https://github.com/indico/indico/pull/5196#discussion_r765754870

Replace `MultipleItemsField` in privacy dashboard with a custom React widget.
Contrary to the current behavior for a single notice, the title should not be required.
For subsequent notices, both title and the URL should be required.

![](https://user-images.githubusercontent.com/8739637/145197506-f4fce70c-3bf6-45fa-862a-a1aebb972738.png)

**Comment by ThiefMaster** [comment]
A nice way of showing this could be to initially just show a text field for the URL, and once you add a second item it turns into a widget where you have to provide both title and URL.
