### ISSUE TITLE
[Feature] Allow to use `{site}` in `room_name_format`

### ISSUE THREAD

**Issue by olifre** [indico/indico#5226]
The placeholder `{site}` can not be added to `room_name_format`. Checking the code, the placeholder `{site}` is not in the list of placeholders:
https://github.com/indico/indico/blob/beca2a26e649b2548aeb7fa9740e1fd24314c8b0/indico/modules/rb/models/locations.py#L50

For rather distributed organizations, adding `{site}` to the pattern would be extremely helpful.

**Comment by ThiefMaster** [comment]
Sounds reasonable, on a quick look I can't see any reasons against supporting `site` there as well.
