### ISSUE TITLE
Restrict custom pages to speakers only

### ISSUE THREAD

**Issue by kiden** [indico/indico#5261]
We need to provide information like zoom login details, speaker protocols, etc. to our speakers. This information evolves over the course of an event, so we want to provide it on a web page - which we can continuously update - rather than in a series of emails.
We don't want anyone else to access this information; only the speakers.

What we'd like is to be able to put this information on custom pages and restrict access to 'speakers only'.
For the menu there are two options
1. show the menu link to all users, but when a non-authorised user clicks the link then display a page with message saying something like "the content of this page is for speakers only (and maybe a suggestion to login if not already logged in). if you are a speaker and think you should have access please contact <event contact>"
2. show the menu link only to logged in users who are also confirmed speakers
(this might cause some users to get in touch asking "where has the menu gone?" if they forget to log in first)
I think there are usability pros and cons to both options (and maybe some others options I haven't considered)

We have tried series of emails but speakers end up confused if they accidentally don't check the latest one.
We have tried using custom pages, hiding them in the menu, and sending the link by email to speakers. Problem is they keep losing the link and have to ask for a reminder, often in the middle of an event when everyone's busy/stressed. Plus it's not secure - non-speakers could potentially get hold of the link and read and use the content.
What we're doing at the moment is publishing this content on our Confluence wiki instead and restricting it to the event speakers, which involves manually creating a corresponding group of speakers on Confluence and manually keeping it synchronised with the list of speakers on Indico. This also suffers from the problem described above: we have to email them the link and they can't easily find it again when they need it. Plus it means we're storing content across multiple system when it feels like it should be kept together.

**Comment by ThiefMaster** [comment]
This will be included in v3.2 :)

**Comment by kiden** [comment]
Just doing a bit of housekeeping and realised I never said thank you...

Thank you! :)
