### ISSUE TITLE
Registration field "choice" resets input type on edit

### ISSUE THREAD

**Issue by graeme-a-stewart** [indico/indico#5267]
When editing a "Choice" field in a registration form, the "input type" always resets to "drop down", even if it was previously "radio group"

**To Reproduce**
1. Add a Choice field in a registration form
2. Set the input type to "radio group" and save
3. Now edit with "configure field"
4. The "input type" will be reset to "drop down" if other changes are saved

**Expected behavior**
Editing a Choice field should not change the input type, unless this is explicitly switched by the user

**Context**
Behaviour observed with the current production Indico at CERN, `v3.1.1-pre`

**Comment by ThiefMaster** [comment]
We're rewriting the registration form management using React in v3.2, so all these weird bugs from the legacy AngularJS UI will be fixed there. I think I even noticed this particular bug when testing things a few weeks ago...

**Comment by graeme-a-stewart** [comment]
Thanks @ThiefMaster - good to know it's in hand!
