### ISSUE TITLE
Add tar to list of packages needed for installing Indico on Cent OS

### ISSUE THREAD

**Issue by bkmgit** [indico/indico#5278]
**Describe the bug**
The documentation should include tar to in the list of packages on Cent OS since this is needed to untar the Python archive

**To Reproduce**
Follow installation steps from https://docs.getindico.io/en/stable/installation/production/centos/nginx/ on Rocky Linux 8.5 until `pyenv install 3.9.x`. One then gets the following error message:
```
BUILD FAILED (Rocky Linux 8.5 using python-build 20180424)

Inspect or clean up the working tree at /tmp/python-build.20220309161609.52300
Results logged to /tmp/python-build.20220309161609.52300.log

Last 10 log lines:
/tmp/python-build.20220309161609.52300 ~
/opt/indico/.pyenv/plugins/python-build/bin/python-build: line 427: tar: command not found
```

**Expected behavior**
When the tar package is installed one should get
```
Downloading Python-3.9.10.tar.xz...
-> https://www.python.org/ftp/python/3.9.10/Python-3.9.10.tar.xz
Installing Python-3.9.10...
Installed Python-3.9.10 to /opt/indico/.pyenv/versions/3.9.10
```

**Screenshots**
NA

**Additional context**
Tested on Rocky Linux 8.5. Expect similar behavior on other RHEL derivatives.

**Comment by ThiefMaster** [comment]
Yikes, there are centos distributions which don't include `tar` by default.... just our of curiosity... docker image? I can't believe a "normal" distribution doesn't come with tar.

Anyway, pull request welcome if the package name is fine and works on centos7 as well (since the guide is the same)! :)

**Comment by bkmgit** [comment]
https://github.com/indico/indico/pull/5279
