### ISSUE TITLE
Update Certbot documentation

### ISSUE THREAD

**Issue by bkmgit** [indico/indico#5280]
**Describe the bug**
Documentation at https://docs.getindico.io/en/stable/installation/production/centos/nginx/#optional-get-a-certificate-from-let-s-encrypt is outdated. The current recommendation is to install certbot using snap https://eff-certbot.readthedocs.io/en/stable/install.html

**To Reproduce**
On Rocky Linux 8.5 on gets
```
yum install -y python-certbot-nginx
Last metadata expiration check: 1:11:34 ago on Wed 09 Mar 2022 04:45:26 PM UTC.
No match for argument: python-certbot-nginx
```
Compare https://docs.getindico.io/en/stable/installation/production/centos/nginx/#optional-get-a-certificate-from-let-s-encrypt  and https://eff-certbot.readthedocs.io/en/stable/install.html

**Expected behavior**
Certbot should install

**Screenshots**
NA

**Additional context**
NA

**Comment by ThiefMaster** [comment]
Wow, they ask people to use snapd for this... is this typically installed on servers? Seems like massive overkill to make people install snapd just to run certbot!

**Comment by bkmgit** [comment]
There are alternatives such as https://github.com/acmesh-official/acme.sh - maybe it is better to document one of the alternatives?

**Comment by ThiefMaster** [comment]
Yes.. there are quite a few. Personally I use *dehydrated* on my own servers.

Ideally we should pick something that's

- well-maintained
- easy to set up (the docs target people who don't have much knowledge in setting up linux servers - those who do usually won't need documentation on how to use let's encrypt to begin with)
- comes with a cronjob to keep the certificate up to date
- easy to install (apt/yum package preferred, curl-to-sh pipe would be OK-ish as well I guess)

**Comment by bkmgit** [comment]
The ACME protocol looks like it will persist https://www.ietf.org/blog/acme/ - maybe it is best to use this directly? An example Python implementation is available in [acme-tiny](https://github.com/diafygi/acme-tiny). [Dehydrated](https://github.com/dehydrated-io/dehydrated) is also a shell script, so preferable to Certbot. [Caddy](https://caddyserver.com/) has certificate renewal built in, but probably significant effort to shift to that. Something simpler is [Lego](https://github.com/go-acme/lego). May also be worth documenting [Zerossl](https://zerossl.com). [Sewer](https://github.com/komuw/sewer) can be installed using pip and [uacme](https://github.com/ndilieto/uacme) has been packaged for Ubuntu, could be added to CentOS/Rhel and similar.

**Comment by bkmgit** [comment]
[CertMagic](https://github.com/caddyserver/certmagic) is used for [Caddy](https://caddyserver.com/).  It is packaged for:
- [Fedora and is in EPEL](https://koschei.fedoraproject.org/package/golang-github-mholt-certmagic)
- [Ubuntu 22.04](https://packages.ubuntu.com/golang-github-caddyserver-certmagic-dev)
- [Debian Bookworm](https://packages.debian.org/golang-github-caddyserver-certmagic-dev)

**Comment by bkmgit** [comment]
@ThiefMaster Dehydrated is in both [EPEL](https://packages.fedoraproject.org/pkgs/dehydrated/dehydrated) and [Ubuntu](https://packages.ubuntu.com/jammy/dehydrated) repositories.  Based on your experience, if you think most users would be ok with it, can document it. Otherwise would suggest [sewer](https://github.com/komuw/sewer) or [acme-client-portable](https://sr.ht/~graywolf/acme-client-portable/) which have command line interfaces, though these would need to be packaged for EPEL.
