### ISSUE TITLE
Canceled label should cancel any future reminder email as well

### ISSUE THREAD

**Issue by leoredi** [indico/indico#5285]
I apply the cancel label to cancel an event at X hour.
At X+10 minutes hour the reminder email of the even is sent anyway.
Therefore to cancel an event properly I would need to both apply the label and cancel my self the email reminder.

A simple solution would be for the label to trigger the cancellation of any future reminder.

**Comment by ThiefMaster** [comment]
Labels are just text without any semantics atm. So we'd need to introduce some setting (for admins) to give semantics to some labels, such as "event does not happen".
