### ISSUE TITLE
Lightweight registrations / accompanying persons

### ISSUE THREAD

**Issue by duartegalvao** [indico/indico#5312]
This is a new field type; the settings should be:

- max number of people to add in a registration
- the standard places limit (one person = place)

When adding a new accompanying person we should only ask for basic data (first+last name), nothing else. We don't want to add fancy field customization there (for now).

Storage would be just a JSON array containing objects in the normal field data.

**Comment by ThiefMaster** [comment]
I think @javfg started working on this, wasn't he?
