### ISSUE TITLE
Security policy mentions 2.x versions, that 3.x is under development

### ISSUE THREAD

**Issue by mthaddon** [indico/indico#5328]
**Describe the bug**

The `SECURITY.md` file in the source for indico currently says:
```Once version 3.0 (currently under development) is out```

However, https://docs.getindico.io/en/stable/changelog/ shows that 3.1 was released on Jan 11th, 2022.

**Comment by ThiefMaster** [comment]
[b9e3462](https://github.com/indico/indico/commit/b9e3462770579cea8604c84c64faab2bfe30f2b8)
