### ISSUE TITLE
Access to badge design of a deleted category

### ISSUE THREAD

**Issue by vasantvohra** [indico/indico#5329]
Reporting a hot bug, without much code scraping:
- Create a SubCategory
- Create a new badge from designer
- You'll have link something like, http://127.0.0.1:9000/category/2/manage/designer/4/
- Delete the subcategory
- if you refresh the page http://127.0.0.1:9000/category/2/manage/designer/4/, the page is still accessible.

Probably, something needs to be fixed on check_access or process_args. Once I have time will open PR by tomorrow :)

**Comment by ThiefMaster** [comment]
Yeah, missing an `if self.target.is_deleted: raise NotFound` in `SpecificTemplateMixin`...
