### ISSUE TITLE
Make builds from release tarballs possible

### ISSUE THREAD

**Issue by andriish** [indico/indico#5341]
**Is your feature request related to a problem? Please describe.**
Building of indico wheels from the release sources is not possible.
The reason is the multiple calls to 'git' in the build scripts, i.e. the build scripts assume the build happens always in a git repository.

**Describe the solution you'd like**
Be able to build indico wheels from the sources.

**Describe alternatives you've considered**
There are two solutions: either to update build scripts or to include .git repository into the release tarballs. The second seems to be an easier solution.

Best regards,

Andrii

**Comment by ThiefMaster** [comment]
We do not provide sdist/release tarballs... those are repo snapshots github always shows for a release, they are not something that people should work.

**Comment by andriish** [comment]
Hi @ThiefMaster ,

actually, the repo snapshots are fine apart from some minor tweaks that disable any calls to 'git' commands.
I will have a look if one can make any sense out of that.

Best regards,

Andrii

**Comment by andriish** [comment]
I think this was done in https://github.com/indico/indico/pull/5514.
