### ISSUE TITLE
Error when user double clicks "Create my Indico Profile" when creating new account 

### ISSUE THREAD

**Issue by SegiNyn** [indico/indico#5342]
**Describe the bug**
A database error occurs when a user clicks on the "Create my Indico Profile" button more than once 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'http://127.0.0.1:9000/register/'
2. Input an email address to get verification link
3. Click on the link sent and input user details
4. When done, double click on "Create my Indico Profile" 
5. See error 

**Expected behaviour**
The action should not be called again when the button is clicked for the second time, we could disable the button after the first click. 

**Screenshots**
<img width="1379" alt="Screenshot 2022-05-12 at 14 22 58" src="https://user-images.githubusercontent.com/54508387/168075219-a933616f-1b46-48c2-9b5b-5ee5f996a922.png">

**Comment by ThiefMaster** [comment]
Maybe users shouldn't doubleclick the button. ;)

But you're right, disabling it seems like a good idea.

**Comment by SegiNyn** [comment]
Okay, I'll open a PR for it.
