### ISSUE TITLE
Python 3.10 not supported

### ISSUE THREAD

**Issue by arturo-seijas** [indico/indico#5364]
**Describe the bug**
When installing indico `pip install indico` with python 3.10.4 pip fails with the following error:

```
ERROR: Ignored the following versions that require a different python version: 3.0 Requires-Python ~=3.9.0; 3.0.1 Requires-Python ~=3.9.0; 3.0.2 Requires-Python ~=3.9.0; 3.0.3 Requires-Python ~=3.9.0; 3.0rc2 Requires-Python ~=3.9.0; 3.1 Requires-Python ~=3.9.0; 3.1.1 Requires-Python ~=3.9.0
ERROR: Could not find a version that satisfies the requirement indico (from versions: 1.2.1rc5, 1.2.1rc7, 1.2.1rc9, 1.2.1rc10, 1.2.1rc11, 1.2.1, 1.2.2rc1, 1.2.2, 3.0rc1)
ERROR: No matching distribution found for indico
```

**Expected behavior**
It is my understanding that Indico should be compatible with versions 3.9.x onwards

**Comment by ThiefMaster** [comment]
Currently only 3.9 is supported. We'll probably support (and possibly even require) 3.10 in version 3.2 or 3.3. At least a few months ago some dependencies were not compatible with 3.10; I'll have to re-check if that's still the case.
