### ISSUE TITLE
Translatability missing

### ISSUE THREAD

**Issue by DirkHoffmann** [indico/indico#5369]
This is kind of the opposite of #4609: Strings that _should_ be i18n'd, but actually are not.

One example is [Personal Data in the Registration form](https://github.com/indico/indico/blob/a73b3f23261f373effcf2408abedfc59818306d4/indico/modules/events/registration/util.py#L313)

I will try to collect some more into this report and submit a PR. (Still have to learn how to do it correctly in your PR workflow, I think.)

**Comment by ThiefMaster** [comment]
Your example is a tricky one, because we cannot assume that the event's language will be that of the person creating the registration form. So until we have a setting to set the default event language, I don't think we should mark this string for translation.

**Comment by DirkHoffmann** [comment]
Point taken for log messages (and similar occurences), of course!

Actually these texts in the registration form are something that was requested in Transifex. Probably the user already had a better overview than me.
From a quick assessment of the above screenshot:

- **Personal Data** (like **Inscription**)  shoulde be translatable.
- "Field Names" (**First Name**, **Last Name**, …) can be defined by the creator of the registration form anyway.
- The text **All [the] fields marked with…** should be translated according to user (registrant) preferences (Do you know where that is defined? I did not find a single occurence of this string in the master branch source code.)
- as should be the **Register** button.

**Comment by ThiefMaster** [comment]
> Personal Data (like Inscription) shoulde be translatable.

Section titles can be changed by the manager (just like field titles)

---

Anything else in the registration form: We completely rewrote the registration form in 3.2 (have a look on preprod :)). The old one basically didn't do much i18n even for static/hardcoded text. The new one should properly apply i18n to all those texts - you can test on indico-preprod, I deployed the (fully updated) french translation there, so if you switch to french you can easily see if any of the hardcoded strings lack i18n integration.

**Comment by DirkHoffmann** [comment]
I see. The registration form can become a completely German (or other language) form now.
![image](https://user-images.githubusercontent.com/1778649/173993642-749ff5e2-369c-43f5-ad50-6f361b2bac94.png)
