### ISSUE TITLE
EmailBackend cannot be changed via configuration variable

### ISSUE THREAD

**Issue by Moist-Cat** [indico/indico#5375]
**Is your feature request related to a problem? Please describe.**
During development is easier to make tests sending the emails to stdout, instead of using a real SMTP server so it would be beneficial to be able to change it.

**Describe the solution you'd like**
Add a configuration variable called `EMAIL_BACKEND` which defaults to `indico.vendor.django_mail.backends.smtp.EmailBackend`.
Is really a small change; I already have it working in my fork.

**Comment by ThiefMaster** [comment]
Any reason against using maildump as a "real" SMTP server as suggested in the dev setup docs? This is much more convenient to read the emails sent to it than just dumping raw mail content to stdout.

**Comment by Moist-Cat** [comment]
Yeah, but that would add aditional dependiencies and I would have to read even more docs before starting to make changes which have nothing to do with emails. So I thought it was overkill to use yet another tool when I could just dump them in console for now like I would do with Django.

**Comment by ThiefMaster** [comment]
It's as simple as `pipx install maildump` (which installs it in an isolated virtualenv) and starting it :)

Anyway, feel free to send a PR, it's not something I plan to implement but if there's a good PR for it I won't be opposed to merging it.
