### ISSUE TITLE
`setup.py build`: Several translation errors

### ISSUE THREAD

**Issue by paulmenzel** [indico/indico#5378]
Running `setup.py build` shows 21 translation errors:

    $ git log --no-decorate --oneline -1
    b732cbe299 Remove trailing whitespace
    $ python setup.py build
    running build
    error: indico/translations/zh_Hans_CN/LC_MESSAGES/messages.po:986: unknown named placeholder 'count'
    error: indico/translations/zh_Hans_CN/LC_MESSAGES/messages.po:1128: unknown named placeholder 'n'
    error: indico/translations/zh_Hans_CN/LC_MESSAGES/messages.po:1892: unknown named placeholder 'count'
    error: indico/translations/zh_Hans_CN/LC_MESSAGES/messages.po:2945: unknown named placeholder 'count'
    error: indico/translations/zh_Hans_CN/LC_MESSAGES/messages.po:2951: unknown named placeholder 'count'
    error: indico/translations/zh_Hans_CN/LC_MESSAGES/messages.po:3848: unknown named placeholder 'tpls_count'
    error: indico/translations/zh_Hans_CN/LC_MESSAGES/messages.po:5536: unknown named placeholder 'count'
    error: indico/translations/zh_Hans_CN/LC_MESSAGES/messages.po:6656: unknown named placeholder 'missing_groups'
    error: indico/translations/zh_Hans_CN/LC_MESSAGES/messages.po:6662: unknown named placeholder 'missing_groups'
    error: indico/translations/zh_Hans_CN/LC_MESSAGES/messages.po:6858: unknown named placeholder 'count'
    error: indico/translations/zh_Hans_CN/LC_MESSAGES/messages.po:9365: unknown named placeholder 'count'
    error: indico/translations/zh_Hans_CN/LC_MESSAGES/messages.po:10795: unknown named placeholder 'count'
    error: indico/translations/zh_Hans_CN/LC_MESSAGES/messages.po:11812: unknown named placeholder 'num'
    error: indico/translations/zh_Hans_CN/LC_MESSAGES/messages.po:12257: unknown named placeholder 'total'
    error: indico/translations/zh_Hans_CN/LC_MESSAGES/messages.po:13092: unknown named placeholder 'count'
    error: indico/translations/zh_Hans_CN/LC_MESSAGES/messages.po:13699: unknown named placeholder 'count'
    error: indico/translations/zh_Hans_CN/LC_MESSAGES/messages.po:13987: unknown named placeholder 'count'
    error: indico/translations/zh_Hans_CN/LC_MESSAGES/messages.po:14243: unknown named placeholder 'count'
    error: indico/translations/zh_Hans_CN/LC_MESSAGES/messages.po:14963: unknown named placeholder 'count'
    error: indico/translations/zh_Hans_CN/LC_MESSAGES/messages.po:15282: unknown named placeholder 'count'
    error: indico/translations/zh_Hans_CN/LC_MESSAGES/messages.po:16577: unknown named placeholder 'count'
    21 errors encountered.
    […]

**Comment by ThiefMaster** [comment]
They can and should be ignored. I had a look some time ago and they are harmless. Apparently they show up because Chinese has no plural forms.

PS: Do not run `setup.py build` directly - use `python ./bin/maintenance/build-wheel.py indico` instead.
