### ISSUE TITLE
Run setup wizard without interactive prompts

### ISSUE THREAD

**Issue by paulmenzel** [indico/indico#5379]
Currently, it looks like, Indico’s setup wizard can only be run interactively. There is a [script/hack](https://github.com/slaclab/indico-slac/blob/master/indico-worker/indico-wizard.py) to work around that, and which is used to build a Docker image.

Is there a way to just edit configuration file?

**Comment by ThiefMaster** [comment]
For any kind of automated setup I would simply create the directories and config files manually.

The wizard is just there to make setting up Indico easier regardless of linux knowledge (and with lower risk of people making typos etc). But if you know what you are doing, there's no strong reason to use the setup wizard

**Comment by paulmenzel** [comment]
Thank you for the prompt reply. Makes sense. Are the directories and configuration file format documented?

**Comment by ThiefMaster** [comment]
all the config options are documented here: https://docs.getindico.io/en/stable/config/settings/
the directories are not "directly" documented, but in the end you just have to point these config options to empty directories: https://docs.getindico.io/en/stable/config/settings/#directories

the config file is executed as Python code so anything that's valid python will work in there.

**Comment by paulmenzel** [comment]
For the record, the wizard outputs the lines below at the end:

```
Creating /project/indico/indico/cache
Creating /project/indico/indico/web
Creating /project/indico/indico/log
Creating /project/indico/indico/archive
Creating /project/indico/indico/tmp
Creating /project/indico/indico/etc
Creating /project/indico/indico/etc/indico.conf
Copying /project/indico/home/src/indico/indico/logging.yaml.sample -> /project/indico/indico/etc/logging.yaml
Linking /project/indico/indico/web/static -> /project/indico/home/src/indico/indico/web/static
Copying /project/indico/home/src/indico/indico/web/indico.wsgi -> /project/indico/indico/web/indico.wsgi
Linking /project/indico/home/.indico.conf -> /project/indico/indico/etc/indico.conf
```
