### ISSUE TITLE
upgrade-python fails (v3.0.3)

### ISSUE THREAD

**Issue by adamboutcher** [indico/indico#5383]
**Describe the bug**
indico setup upgrade-python fails.

**To Reproduce**
1. Upgrade from version 3.0.3 to "latest" following your guide.
2. Run `indico setup upgrade-python`
3. Fails with `FileNotFoundError: [Errno 2] No such file or directory: 'pyenv'`

**Expected behavior**
It to complete

**Additional context**
The directory should be .pyenv not pyenv

**Comment by ThiefMaster** [comment]
This sounds more like the `pyenv` command is not available in your environment...

**Comment by adamboutcher** [comment]
Ah ha! Yes!
```
export PATH="/opt/indico/.pyenv/bin:$PATH"
```

Fixed it, it's not auto-imported from the .bashrc when you su - indico, might need some tweaks to the docs to add it into the path.
