### ISSUE TITLE
Categories not showing up when creating an event from the homepage

### ISSUE THREAD

**Issue by avivace** [indico/indico#5388]
If I try to create an event from the home page (https://indico.cern.ch/), clicking on Create Event -> Meeting the only possible categories shown under "Choose a category" are Directorate under Home.

![image](https://user-images.githubusercontent.com/14352721/175497125-f180501c-ac96-4e91-bea1-cc8333fa0f58.png)

This behaviour changes depending from which page I'm creating the event from. E.g. if I try to create an event from https://indico.cern.ch/category/2/ I can select the "TEST" category, but only that one, and if I try to go "up a level" in the cateogry browser, I'm again stuck with only Home -> Directorate

**Comment by ThiefMaster** [comment]
I can't reproduce it even when impersonating your account on Indico... In any case, I'll contact you on mattermost so we can look into what may be causing this weird problem for you.

**Comment by ThiefMaster** [comment]
Broken adblocker rule; not a bug :)
