### ISSUE TITLE
User Management/Users: Claims there are two users despite only one being there

### ISSUE THREAD

**Issue by paulmenzel** [indico/indico#5394]
$ git log --no-decorate --oneline -1
    c6b5a3042a Fix showing nonbookable period outside admin UI

With the admin account going to *User Management* → *Users*, it says:

> There are 2 users, 0 of which are deleted

To my knowledge there is only one account though. (LDAP setup is still in the works.)

**Comment by ThiefMaster** [comment]
There's always a system user (id 0), so if you have an account as well -> 2 users
