### ISSUE TITLE
Allow event administrator to change visibility of registration for official meeting (no user consent)

### ISSUE THREAD

**Issue by Feandil** [indico/indico#5411]
**Is your feature request related to a problem? Please describe.**

I'm the chair of an official meeting which is tracking the attendance of its members through indico (and minutes).
Our standard workflow was:

- Before the meeting takes place, all expected participants are registered in the event, but the visibility is set to hidden. This is easily maintained by cloning the meeting with participants (before doing modifications).
- After the meeting took place, we modify the registration to match the attendance and published the attendance on the event.

Since the recent "privacy" update, this is not possible any more and we get an error message saying that visibility can only be changed if there is no registration.

**Describe the solution you'd like**

Allow to change the visibility of registration if there was no user-entered registration and they are all managed by the admins of the event (potentially with a privacy warning): this publication is not based on the user consent but on the Organisation's best interest (into tracking who took what decision when and who was aware of them). The attendance is also published in the minutes anyway...

**Describe alternatives you've considered**

We could change our workflow, but that would have side effects:

- Have the visibility set to public from the very beginning: Wrong information will be displayed on the meeting before it's fixed with the real attendance after the meeting (unless there is a way to automatically hide attendance before the meting)
- Enter the attendance after the meeting, with the privacy settings set to public: need to re-enter all participants for all meetings... 

**Additional context**

Minor detail: the error message is not added on the right line ;)
![Screenshot Registration Privacy Management Indico](https://user-images.githubusercontent.com/1488247/178687528-279bab29-763c-489d-bfac-ad5c4d26559e.png)

**Comment by ThiefMaster** [comment]
#5416 "fixes" this; "registrations" created by an event manager and not through the user-facing registration form are now excluded from this check. They are "participations" and not "registrations" anyway, even though technically that's the same...
