### ISSUE TITLE
Add ability to message authors/speakers from contribution or abstract lists

### ISSUE THREAD

**Issue by agbuckley** [indico/indico#5423]
**Is your feature request related to a problem? Please describe.**

I find myself needing to message groups of conference participants from the abstracts or contribution lists, and in particular selected or filtered subsets of those lists -- those with a talk type including posters, or plenary vs parallel, for example. This includes needing to message those who are not (yet) registered. At present I can only find an option to email from the Registrations list.

I'm posting this from the experience as an organiser, but it would also be very useful for track conveners to be able to do the same, at least for abstracts applied or abstracts & contributions assigned to their track.

**Describe the solution you'd like**

"Actions" drop-downs at the top of the Abstracts and Contributions lists, with an "Email" action, equivalent to the one in the Registrations list. Maybe being able to select on whether to email all listed authors or just the presenter(s).

Also a version of the same in the views available to track conveners.

**Describe alternatives you've considered**

At present (I think) I have to click on the edit button for each contribution I want to contact, manually copy the email addresses out of the presenter details and into an email client, and send outside Indico (and from my own rather than the conference address).

**Comment by ThiefMaster** [comment]
Check the "author list" button above the contribution/abstract list in the management area. You can email people from there.

**Comment by agbuckley** [comment]
Aha, thanks. Perhaps this can be signposted better? In the registration list, the Actions button is reasonably clear, and clicking it gives an immediate drop-down with the email action on display. In the Contributions view, I had no idea what Author List would show, and as a button rather than drop-down menu it feels a more "risky" thing to click without knowing what it'll do! Unifying the interface between the different ways to message participants would help. But thanks again for pointing out the way.

Is there a way for less privileged track-conveners to do the same thing? I can't see it from their view.

**Comment by ThiefMaster** [comment]
No, I don't think conveners have such an option.

**Comment by agbuckley** [comment]
Can we repurpose this ticket into adding such a feature for them? It's key that conveners can message the contributors to their tracks/sessions.

**Comment by ThiefMaster** [comment]
Not trivial. Right now all the email logic assumes that anyone in the event is fair game (because a manager can manage everyone there anyway). When extending this to session coordinators/managers, this suddenly needs to include checks whether all people selected for notifications are not only within the event but also linkd to a contribution in a session the user can manage.

However, feel free to open a new ticket nonetheless to keep track of the suggestion (I think that's better than repurposing an existing one). No promises that it happens any time soon though...
