### ISSUE TITLE
Modify string for the description of the fields.

### ISSUE THREAD

**Issue by SEHARSHAHZAD** [indico/indico#5440]
**Change string under the registration form management area for the fields **
The following two strings describing the field must be replaced:

1. Publish registrations
2. Publish number of registrations
The existing description is "Registrations from this form will be displayed **in** the event page" & "Number of registered participants will be displayed **in** the event page". The preposition "**in**" must be replaced by "**on**".

**To Reproduce**
1. Go to 'https://v2-reg-demo.unog.ch/event/396/manage/registration'
3. Under the list of registration forms, click on '**Manage**'
4. Click on Edit in front of the General settings
5. Scroll to the fields "Publish registrations" & "Publish number of registrations"
6. See the error in the description of the aforementioned two fields.

**Expected behavior**
The description string preposition must be replaced from "in the event" to "on the event page" for both fields.

**Screenshots**

![2022-08-05_152535](https://user-images.githubusercontent.com/88734005/183086910-08ef9e6d-6489-4468-9dd1-da886c6a564e.png)

**Comment by ThiefMaster** [comment]
The first one on longer exists in 3.2 (so if you are on an older version please fix it in your fork); I'll fix the second one in master (3.2).

PS: IF you are one of the developers working on UN Indico, please send PRs for trivial changes such as this one. It's more useful than just an issue, and doesn't take much longer.
