### ISSUE TITLE
indico doesn't work with latest python-ldap

### ISSUE THREAD

**Issue by SethosII** [indico/indico#5452]
**Describe the bug**
Support for `OPT_X_TLS` was removed in `python-ldap` [version `3.4.2`](https://github.com/python-ldap/python-ldap/blob/master/CHANGES#L11-L12). Therefore login with LDAP breaks.

**To Reproduce**
1. install latest `python-ldap`
2. try to login with an LDAP account
3. See error 

**Expected behavior**
There should be a note about the required  version of `python-ldap` or the LDAP integration should be updated to work with the latest and upcoming `python-ldap` releases.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/4445745/184325527-59a6718f-d2f1-4502-bba2-6522f3bd79e3.png)

**Comment by ThiefMaster** [comment]
We will bump the flask-multipass pin in the next Indico release (3.2). For now simply downgrade python-ldap manually.
