### ISSUE TITLE
Closed/Open tag in front of Event title 

### ISSUE THREAD

**Issue by SegiNyn** [indico/indico#5454]
A way to see if an Event is 'open' or 'closed' from the category event list page e.g. 'https://sandbox.getindico.io/category/1/'

We propose to include 2 tags in front of the event title on that page. 
1. Open, if there's any registration form that is open
2. Closed, if all registration forms are closed
3. No tag at all if there's no registration form

Example of the closed tag:
<img width="369" alt="Screenshot 2022-08-16 at 14 12 13" src="https://user-images.githubusercontent.com/54508387/184876680-ce3782a8-a8fa-4436-a74f-c57b2f50c3f1.png">

**Comment by ThiefMaster** [comment]
I don't think the label is very clear - sounds more like a closed/restricted event...
So I think I'd rather have you contribute a template hook and add it in your own plugin...

FWIW, the only way I could imagine accepting this upstream is when there's *only* a label in case of an open registration ("Registration open" label), but certainly not for a closed one (IMHO that just adds a lot of noise)...

**Comment by SegiNyn** [comment]
Okay, in that case I think we'll contribute a template hook for it instead

**Comment by OmeGak** [comment]
Our need is to add the `CLOSED` tag but I could anticipate this would not be interesting upstream unless we add also an `OPEN` tag. Since we are going to make a contribution upstream, would it then be welcome to add an `OPEN` tag with a block so that we can override it for both `OPEN`/`CLOSED` tags?

**Comment by ThiefMaster** [comment]
I think just "open" is not that clear (open to what? public access? registration open?)...

**Comment by SegiNyn** [comment]
Registration open, if there's any registration form that is open.

**Comment by SegiNyn** [comment]
@ThiefMaster, should we go ahead with the Registration open tag?

**Comment by ThiefMaster** [comment]
So we're not completely sure what's the best UI to show this (label may be a bit bulky, icon is unlikely to be clear enough, and in case of a label it probably needs to be clickable - but should that go to the registration page or event page itself?). We'd also probably want this to be configurable (opt in) on the category level. And of course the queries need to be done in a way that it doesn't add O(n) extra queries.

Hence, for now it's probably best if you just do it on your side based on what you need, and just contribute the block or template hook upstream.

**Comment by SegiNyn** [comment]
Okay then, thanks for the assessment.
