### ISSUE TITLE
Filter out non ticket templates 

### ISSUE THREAD

**Issue by SegiNyn** [indico/indico#5459]
**Describe the bug**
Non ticket templates can be selected in the 'Configure ticketing system' section

**To Reproduce**
1. Go to 'http://127.0.0.1:8000/event/<id>/manage/registration/
2. Click on 'Manage' to manage a registration form 
3. Click on 'Configure' to configure the ticketing system
4. Enable tickets, In the list to select a ticket template, all templates are listed including non ticket templates 

**Expected behavior**
The list of templates should be limited only to ticket templates, proposal is to add `and tpl.is_ticket` at:
https://github.com/indico/indico/blob/master/indico/modules/events/registration/forms.py#L321 
If accepted, I'll open a PR for it. 

**Screenshots**
<img width="845" alt="Screenshot 2022-08-19 at 18 37 40" src="https://user-images.githubusercontent.com/54508387/185881162-4b5b98d5-c4a5-49b0-b46d-4f73cdc5b1c8.png">

**Comment by ThiefMaster** [comment]
Not really a bug. IMHO There's generally nothing wrong with using a "non-ticket" template here, in case you do not care about QR codes (this is what determines if a template is considered ticket or badge).

I realize that this thing is a bit confusing, with the ticket/badge differentiation...

**Comment by SegiNyn** [comment]
Yes it doesn't cause a problem in Indico core

But it is affecting Approvals in our plugin because of a check where we make a decision based on if the template is a ticket or a badge.

**Comment by ThiefMaster** [comment]
You can include custom logic when this form gets validated. See [here](https://github.com/indico/indico-plugins-cern/blob/master/cern_access/indico_cern_access/plugin.py#L321) for an example where we use the form validated signal to restrict what can be selected in that dropdown.

**Comment by SegiNyn** [comment]
Okay, thank you very much 🙏
