### ISSUE TITLE
Workflow for creating an event for unauthorized users

### ISSUE THREAD

**Issue by paulmenzel** [indico/indico#5469]
Using Indico 3.2.2, the permissions for a category are set to only allow creating events for authorized users. Non-administrators still see the *Create event* button, and only get informed about the missing permissions after filling out the form, and trying to create the event.

**Comment by ThiefMaster** [comment]
The reason for this is that they could change the category from within the event creation dialog...
But indeed, we could check this on the fly and show a message straight away.
