### ISSUE TITLE
potential problems with 'Book of Abstracts'

### ISSUE THREAD

**Issue by bbb-user-de** [indico/indico#5474]
Abstract submission in a language other than english (user gui) will process the PDF with the translation of 'Book of Abstracts'

proposal:
indico/legacy/pdfinterface/latex_templates/book_of_abstracts.tex

do not transalate 'Book of Abstracts'

**Comment by ThiefMaster** [comment]
We can use `with force_locale(None): ...` when rendering the template to avoid using a translation. That way we'll be able to easily integrate it with an "event langauge" in the future without having to re-add i18n markers to the templates.

**Comment by bbb-user-de** [comment]
@ThiefMaster 👍
