### ISSUE TITLE
AttributeError: "comment" while creating an user from the administrator interface

### ISSUE THREAD

**Issue by Moist-Cat** [indico/indico#5490]
**Describe the bug**
AttributeError: "comment" while creating an user from the administrator interface

**To Reproduce**
1. Go to Administration/Users/
2. Click on Create New Account

**Expected behavior**
The form to create an user.

**Additional context**
1. I solved it commenting `del self.comment` at line 131 in the AdminAccountRegistrationForm in [src/modules/users/forms.py](https://github.com/Moist-Cat/indico/blob/master/indico/modules/users/forms.py#L131). But I'm almost sure this will break something else. (I ran all the tests and everything is green, though)
2. The tests are all green.
3. I noticed this error:
`socket.gaierror: [Errno -2] Name or service not known`
In the traceback. I think it was trying to dump the error via email. Perhaps it's related to the issue.

I assume this comment field is's the result of #4819, yes?

VERSION: indico-3.2-dev
COMMIT: 298061152fe58bdb2f6fc0757b4ff2cc494d3e0c

I see now that this line does not appear in the master branch.

**Comment by ThiefMaster** [comment]
I think removing the line is fine and the correct fix. We moved the user-facing account creation to React+Marshmallow so the WTForm is no longer used for it and thus a comment field no longer exists there.

**Comment by Moist-Cat** [comment]
Alright, thanks. I didn't want to delete it without knowing why was it there in the first place.

**Comment by ThiefMaster** [comment]
Will you send a PR for this fix? In any case I'll reopen the issue since this is clearly a bug which needs to be fixed. If you send a PR (just removing that one line + a "Fix error on admin user creation" changelog entry w/ reference to this issue, the PR and credits to you) would be sufficient) that'd be great, but otherwise I can do it myself as well..

**Comment by Moist-Cat** [comment]
The master branch shouldn't have this bug because that line was already removed. It was probably a temporary workaround. The fix would be updating to the latest 3.2-dev master.

https://github.com/indico/indico/blob/master/indico/modules/users/forms.py#L133

**Comment by ThiefMaster** [comment]
Ah indeed. since we release 3.2 in the meantime you can also just use that release in case you do not have customizations (if you do, rebase to master of course, or 3.2.x if we branched out by the time you do it).
