### ISSUE TITLE
Indico with Python 3.11

### ISSUE THREAD

**Issue by andriish** [indico/indico#5515]
An attempt to build indico (3.2) for Python 3.11 fails.

**To Reproduce**
Try to build Indico for 3.11. An error

```
building assets
Error: building assets failed
...

 File "/usr/lib64/python3.11/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
sqlalchemy.exc.InvalidRequestError: When initializing mapper mapped class Contribution->contributions, expression '(PaperRevision._contribution_id == Contribution.id) & (PaperRevision.state == PaperRevisionState.accepted)' failed to locate a name ("name 'PaperRevisionState' is not defined"). If this is a class name, consider adding this relationship() to the <class 'indico.modules.events.contributions.models.contributions.Contribution'> class after both dependent classes have been defined.
Traceback (most recent call last):
...
subprocess.CalledProcessError: Command '['/usr/bin/python3', 'bin/maintenance/dump_url_map.py', '--output', '/home/user/Projects/indico-rpms/python-indico/3.2/rpmbuild/BUILD/indico-3.2/url_map.json', '--force']' returned non-zero exit status 1.
```
appears and it seems the problem is in indico/modules/events/contributions/models/contributions.py in this block of code

```py
    _accepted_paper_revision = db.relationship(
        'PaperRevision',
        lazy=True,
        viewonly=True,
        uselist=False,
        primaryjoin=('(PaperRevision._contribution_id == Contribution.id) & (PaperRevision.state == {})'
                     .format(PaperRevisionState.accepted)),
    )
```
When I remove the second part of the expression
```py
    #: The accepted paper revision
    _accepted_paper_revision = db.relationship(
        'PaperRevision',
        lazy=True,
        viewonly=True,
        uselist=False,
        primaryjoin=('(PaperRevision._contribution_id == Contribution.id)'),
    )
```
 things are fine and I'm able to build Indico for Python 3.11.

**Expected behavior**
Should work, as Python 3.10 and 3.11 are not that different

**Additional context**

Just in caee: the environment I use to build Indico is a singularity container with Fedora 37 and  the following config
```
Bootstrap: docker
From: fedora:37
%post
    dnf -y install dnf* rpm-build git wget sed createrepo
    dnf -y copr enable averbyts/IR 
    dnf -y install indico-devel
%environment
    export LC_ALL=C
%runscript
    date
```

Best regards,

Andrii

**Comment by ThiefMaster** [comment]
Typically this kind of error is highly import-order-dependent. The problem comes from the marshmallow model schemas we are using. Merely defining such a schema triggers sqlalchemy's configure_mappers logic, so if that happens before all the necessary models have been included, this error can happen.

I'm not sure why the import order suddenly changes in Python 3.11 though...

**Comment by andriish** [comment]
Could one replace the last expression with something more explicit, like 
'& (PaperRevision.state == PaperRevisionState(Accepted) )'  to avoid "format" ?
Sorry, I'm not actually familiar with the syntax that should be there ...


Andrii
