### ISSUE TITLE
cast type error on migrating db 3.1 --> 3.2

### ISSUE THREAD

**Issue by pvdabbeele** [indico/indico#5521]
A type cast error occurs when migrating Indico DB 3.1 to 3.2

Given a PostgreSQL database, with initial data:

CREATE TABLE logs (
    id integer NOT NULL,
    ....
    meta jsonb NOT NULL,
    ....

On running `indico db upgrade`, the upgrade fails on the following error:
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade xxxxxx -> yyyyyy,
....
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.CannotCoerce) cannot cast type jsonb to integer

More detailed::

def upgrade():
    op.add_column('registrations', sa.Column('created_by_manager', sa.Boolean(), nullable=False,
                                             server_default='false'), schema='event_registration')
    op.alter_column('registrations', 'created_by_manager', server_default=None, schema='event_registration')
    op.execute('''
        UPDATE event_registration.registrations reg
        SET created_by_manager = true
        FROM events.logs lo
        WHERE
        lo.realm = 2 AND
        lo.module = 'Registration' AND
        lo.summary LIKE 'New registration: %' AND
        lo.meta ? 'registration_id' AND
        reg.id = (lo.meta -> 'registration_id')::int;
    ''')

Results in:

psycopg2.errors.CannotCoerce: cannot cast type jsonb to integer
LINE 10:         reg.id = (lo.meta -> 'registration_id')::int;

**Comment by ThiefMaster** [comment]
You need to use an up to date Postgres version (at least Postgres 11) as recommended in the 2-to-3 upgrade guide:

> There are no changes that require the newer Postgres version immediately, but we no longer test on versions older than Postgres 12, and thus can give you no guarantees that things will keep working on older versions such as 9.6.

in fact shortly after 3.2 we updated this (not visible in the "stable" docs yet) to confirm that there is indeed such a breakage on older versions:

> As of Indico 3.2, the upgrade will fail on Postgres 10 and older.

If you cannot update on short notice, you can comment out the `op.execute()` call; it'll just skip flagging some of the existing registrations as "created by manager" which is unlikely to be a problem.
