### ISSUE TITLE
Add Link: add warning to indicate file won't be copied

### ISSUE THREAD

**Issue by pferreir** [indico/indico#5551]
The "Add link" option in the Material Editor was initially created as a way to link to web pages:

![image](https://user-images.githubusercontent.com/2699/197214256-2e4f7ae3-bfa9-4f48-aaf5-5c3b5e09e7ac.png)

In the meantime, linking directly to files has become popular, and it may not be clear to some users whether this operation, being in the "Material Editor", will copy the file over or just add a link. It would be good to add some warning message, perhaps something like:

"Please note that this action will only create a link to the file, and it will not be copied to Indico. The file might be modified or deleted outside of Indico."

**Comment by glpatcern** [comment]
And maybe add something like "If you're linking a CERNBox file, consider attaching it with the `From CERNBox` button" ;-)
