### ISSUE TITLE
The cancelled flag does not appear in reminder e-mails

### ISSUE THREAD

**Issue by pkoppenb** [indico/indico#5554]
I added the cancelled flag to meeting https://indico.cern.ch/event/1165478/ . This flag nicely appears on the title and on the weekly summary of meetings, but not in the reminder e-mail. Hence everyone gets a reminder e-mail about a cancelled meeting. 
I reported this to indico-support, but was told it's not a bug and I should delete the reminder e-mail. That's not what I want as I do want to remind people that the meeting is cancelled.

**Describe the solution you'd like**
I would like the keyword "cancelled" to appear in the e-mail title.

**Describe alternatives you've considered**
Alternatively I could change the title of the meeting to Cancelled: DPA WP3 (offline analysis tools) meeting, which is what many people do, and then the e-mail would have a self-explanatory title. But that defeats the point of the cancelled flag.

**Comment by ThiefMaster** [comment]
Agreed, including the event label in the event title in reminder emails seems like a good idea.
