### ISSUE TITLE
PersonLinkField does not prefill title/phone/address when editing people

### ISSUE THREAD

**Issue by tomasr8** [indico/indico#5590]
#### Missing title
To reproduce:
- Use `Add myself` to add yourself to the list of people
- Click on `Edit person` (pencil icon)

The title should be prefilled in the form, but the title field is empty. This one is because `Indico.User` does not have the title.

#### Missing phone/address
To reproduce:
- Use `Search` to add a user
- Click on `Edit person` (pencil icon)

Address and phone is missing here because the `PrincipalsMixin` doesn't serialize them.

It might be worth to reuse the `UserSchema` for these to avoid inconsistencies.

**Comment by ThiefMaster** [comment]
The search doesn't include address/phone on purpose. This is not data we want to return there.
