### ISSUE TITLE
Line breaks in description are ignored in reminders

### ISSUE THREAD

**Issue by jhyeon** [indico/indico#5611]
**Describe the bug**
Indico v3.2.1 and newer ignores line breaks and paragraph changes in the description block of reminder emails.  This problem did not occur with version 3.2 and earlier.

**To Reproduce**
1. Create an event with a multi-line/multi-paragraph description, e.g.:
```
<p>
    Title: Lecture I
</p>
<p>
    Speaker: Speaker I (Institute I)
</p>
<p>
    Abstract: First things first.
</p>
```
if viewed as a html source.
2. Add a reminder
3. Tick the __Include description__ option
4. __Preview email__
5. The description block displays the above three paragraphs in a single line:
```
Description
-----------

Title: Lecture ISpeaker: Speaker I (Institute I)Abstract: First things first.


Note
----
======== zoom connection =============================================

Link, meeting ID and passcode are available on the indico page.

======================================================================

--
Indico :: Email Notifier
```

**Expected behavior**
Indico v3.2 would format the description block like:
```
Description
-----------

Title: Lecture I

Speaker: Speaker I (Institute I)

Abstract: First things first.
```

**Additional context**
The note block is still intact.

**Comment by ThiefMaster** [comment]
OK, that's actually a very interesting bug. The code we use to get a simple plaintext version of the event description never converted paragraphs or html linebreaks to `\n` linebreaks. However, the new CKEditor version we updated to in 3.2 apparently normalizes the HTML source and discards "unnecessary" linebreaks from the submitted value.

I'll have a look next week, maybe we can use html2text or similar instead...
