### ISSUE TITLE
Import: Make it clear that you cannot import from a different indico URL

### ISSUE THREAD

**Issue by ThiefMaster** [indico/indico#5619]
See https://talk.getindico.io/t/import-events-from-other-instances/2915/1 for example.

Pasting an event URL is convenient, but we should check not only the ID but also the host - if it doesn't match the current instance URL, a meaningful error should be shown instead of "event does not exist".

Note: This is a very easy task which would be a nice first task for a new team member, so I recommend we leave this open for now.

**Comment by JorgChrist** [comment]
Hey! Can I take up this issue? 
I haven't contributed to indico (or any open-source software for that matter) before and this one looks like a pretty interesting beginning!

**Comment by ThiefMaster** [comment]
Hi, while we appreciate contributions I'd like to give this as a first or second task to our new team member starting in February...
