### ISSUE TITLE
Paragraphs in editors are missing spacing

### ISSUE THREAD

**Issue by kewisch** [indico/indico#5624]
**Describe the bug**
When you write something in a ck editor, e.g. conference description, there is no visible difference between a line break and a paragraph. When you view it in the result, there is however. This is mildly confusing.

**To Reproduce**
1. Create an event with a description. Add some text, a few line breaks, a paragraph
2. Save the description
3. Compare what you see in the editor with the final result

**Expected behavior**
Paragraph spacing in the editor

**Screenshots**
![image](https://user-images.githubusercontent.com/607198/212900832-c2785c21-4a3d-4a0b-a97a-f0d5c65aa01b.png)
![image](https://user-images.githubusercontent.com/607198/212900867-17544fdb-6080-4a45-8589-67407d1b5921.png)

**Additional context**
This apparently goes back to this change https://github.com/indico/indico/commit/1541785758f00be132caaa1bfa53a6d85a3e9045 for IE, which I guess we could revert? At the very least, removing that CSS rule will make it default to semantic-ui's 1em margin-bottom.

**Comment by ThiefMaster** [comment]
Yes I think that commit could be reverted - it was probably used for the legacy registration form which no longer exists anyway..
