### ISSUE TITLE
Notify registration managers when a participant withdraws their registration

### ISSUE THREAD

**Issue by kewisch** [indico/indico#5633]
**Is your feature request related to a problem? Please describe.**
Registration managers, or those who are in the notify list for specific reg forms, get notified on various state changes. However, it appears there is no notification to managers when a registration is withdrawn by a participant.

**Describe the solution you'd like**
An email is sent to registration managers, and registration form notify emails, when a user has withdrawn their registration. 

**Describe alternatives you've considered**
Looking at the list once a day to see who withdrew? ;-)

**Additional context**
It looks like `notify_registration_state_update` is not called in `RHRegistrationWithdraw`, while it is in `RHRegistrationManageWithdraw`. Would it be as simple as adding the call here?

**Comment by ThiefMaster** [comment]
I haven't tested it, but I think this is exactly what's missing there and would be exactly what I'd do to fix it (in fact I looked at the code and only then saw your last part with the proposed solution ;)).

A PR would certainly be appreciated if you'd like to! :)
