### ISSUE TITLE
Allow to use existing redis for tests

### ISSUE THREAD

**Issue by tomako** [indico/indico#5651]
Testing framework uses `redis_proc` fixture (of `pytest-redis` package) for booting up a redis instance using redis executable. 
I'm using redis in container so this fixture is not suitable for me. 

`postgresql` fixture is very similar. It calls pg executables to start pg instance except environment variable `INDICO_TEST_DATABASE_URI` is set. In this case it connects to the existing db. I would like to see a similar solution. 

My suggestion is some rework on the app fixture:
```
@pytest.fixture(scope='session')
def app(request):
    """Create the flask app."""

    redis_cache_url = os.environ.get('INDICO_TEST_REDIS_CACHE_URL')
    if not redis_cache_url:
        redis_proc = request.getfixturevalue('redis_proc')
        redis_cache_url = f'redis://{redis_proc.host}:{redis_proc.port}/0'

    config_override = {
        'BASE_URL': 'http://localhost',
        'SMTP_SERVER': ('localhost', 0),  # invalid port - just in case so we NEVER send emails!
        'TEMP_DIR': request.config.indico_temp_dir.strpath,
        'CACHE_DIR': request.config.indico_temp_dir.strpath,
        'REDIS_CACHE_URL': redis_cache_url,
        'STORAGE_BACKENDS': {'default': 'mem:'},
        'PLUGINS': request.config.indico_plugins,
        'ENABLE_ROOMBOOKING': True,
        'SECRET_KEY': os.urandom(16),
        'SMTP_USE_CELERY': False,
    }
    return make_app(testing=True, config_override=config_override)
```
In fact this is simpler than we have for postgres because there's no need for manipulating redis directly from tests. At least at this moment  so I didn't want to add a separate fixture for that. It can be improved later if needed. 
Anyway I'm happy to contribute with this one or something similar if you think it's needed.

Remark: `pytest-redis` has an additional fixture `redis-nooproc` which does nothing else only compiles this redis URL I would like to put into an environment variable.

**Comment by ThiefMaster** [comment]
Tests should be self-contained - is there any reason why you want to use an existing redis? The only reason why this exists for postgres is that starting a postgres instance has some noticeable overhead, but running redis takes pretty much no time...

**Comment by tomako** [comment]
As I mentioned I use containerized redis (and postgres). I don't have the required binaries installed.

**Comment by ThiefMaster** [comment]
OK fair enough, I didn't realize that you don't have redis installed locally at all. While I may not consider containerizing this particularly useful, I'll accept a PR that adds an env var like you suggest.

**Comment by tomako** [comment]
Thank you @ThiefMaster , PR is sent.
