### ISSUE TITLE
Fixtures in pytest plugin

### ISSUE THREAD

**Issue by tomako** [indico/indico#5690]
The pytest plugin registers only fixtures in `indico.testing.fixtures` package. However there are many others and I would like to have access to them (eg. `indico.modules.rb.testing.fixtures`). Some dummy fixtures would be also useful for us but they may be too specific and created only for inner tests.
Anyway I'm wondering what's the concept regarding these fixtures.

**Comment by ThiefMaster** [comment]
Simply add `pytest_plugins = 'indico.modules.rb.testing.fixtures' ` in the test module where you want to use those fixtures. Same for others.

And of course nothing stops you from adding your own custom fixtures as you need them...

**Comment by tomako** [comment]
Of course I'm adding new ones but I don't want to add the same you have ;)
Oh, is that simple to add them? I thought it should go through the plugin you defined. Let me try then.

**Comment by ThiefMaster** [comment]
If you do it in your plugin you can also just do it there - no need to touch the plugin. It's also very common to just define "local" fixtures in the same file where the tests are that need them.

**Comment by tomako** [comment]
Great! It works. Thanks for the quick response and solution.
