### ISSUE TITLE
Internal search does get None sometimes

### ISSUE THREAD

**Issue by bpedersen2** [indico/indico#5759]
`chain_query` seems to be `None` in some cases:

I one dismisses the error dialog Contributions is empty ( as expected)

```
  File "/opt/indico/.venv/lib/python3.9/site-packages/indico/modules/search/controllers.py", line 60, in _process
    result = search_provider().search(q, session.user, page, type, **params)
  File "/opt/indico/.venv/lib/python3.9/site-packages/indico/modules/search/internal.py", line 75, in search
    pagenav, results = self.search_contribs(query, user, page, category_id, event_id,
  File "/opt/indico/.venv/lib/python3.9/site-packages/indico/modules/search/internal.py", line 267, in search_contribs
    objs, pagenav = self._paginate(query, page, Contribution.id, user, admin_override_enabled)
  File "/opt/indico/.venv/lib/python3.9/site-packages/indico/modules/search/internal.py", line 164, in _paginate
    res = get_n_matching(
  File "/opt/indico/.venv/lib/python3.9/site-packages/indico/core/db/sqlalchemy/util/queries.py", line 172, in get_n_matching
    preload_bulk(objects)
  File "/opt/indico/.venv/lib/python3.9/site-packages/indico/modules/search/internal.py", line 168, in <lambda>
    preload_bulk=lambda objs: self._preload_categories(objs, preloaded_categories)
  File "/opt/indico/.venv/lib/python3.9/site-packages/indico/modules/search/internal.py", line 115, in _preload_categories
    category_ids = set(itertools.chain.from_iterable(id for id, in chain_query))
TypeError: 'NoneType' object is not iterable
```

'https://indico.frm2.tum.de/search/?q=MLZ'

**Expected behavior**
No error

I'll try to create a patch...

**Comment by ThiefMaster** [comment]
I don't see how `chain_query` can be None. I think it's more likely that one of the rows contain `None` for the ID and it fails in the outer iteration... 

It's only the contrib search that fails: https://indico.frm2.tum.de/search/api/search?q=MLZ&type=contribution&type=subcontribution
The more interesting question is why that happens though. Do you have any unlisted events in your database (you can check by querying for events with a None `category_id`)?

**Comment by ThiefMaster** [comment]
Do you have both subcontributions anad normal contributions?
`Contribution.query.count()`
`SubContribution.query.count()`

**Comment by bpedersen2** [comment]
Not for the unlisted event. 

The error surfaces once you have an unlisted event with published(!) contributions. 

chain_query then contains:
```
> /home/resi/pedersen/workspace/indico3dev/src/indico/modules/search/internal.py(116)_preload_categories()
-> if chain_query:
(Pdb) 127.0.0.1 - - [08/May/2023 12:15:05] "GET /search/api/search?q=unlisted&type=attachment&event_id=311 HTTP/1.1" 200 -
(Pdb) chain_query
<indico.core.db.sqlalchemy.util.models.IndicoBaseQuery object at 0x7f053469d250>
(Pdb) chain_query.all()
[(None,)]
```
 
and my fix does not work.  I'll debug this further

**Comment by ThiefMaster** [comment]
I was having a look in the meantime as well, and found the issue. https://github.com/indico/indico/pull/5761 is how I would fix it, since I don't think it's important to return stuff from unlisted events in the search, and supporting this would likely require UI tweaks since currently all results are expected to have a category.

Or do you think it would be better to actually include unlisted events in the search results as well (it'd still do the proper access checks and only show them to people who have access)?

**Comment by bpedersen2** [comment]
I think it is fine to not show unlisted events in the search.
