### ISSUE TITLE
Relative dates in "News" section on start page broken in German translation

### ISSUE THREAD

**Issue by olifre** [indico/indico#5798]
**Describe the bug**
A picture says more than 1000 words:
![Indico_German_Date](https://github.com/indico/indico/assets/166759/b4f7dfb3-561c-4538-80bf-576a52173af1)

It seems the relative date is formatted wrongly, i.e. it reads:
` Veröffentlicht am “53tMESZt3r” Mittwoch `
instead of:
` Veröffentlicht am letzten Mittwoch `

**To Reproduce**
1. Add a news message for which a relative date will be used, e.g. within the last week. 
2. Use timezone `Europe/Berlin`. 
3. Visit Indico start page and select German language. 

**Additional Information**
Using a different timezone, e.g. UTC, yields:
` Veröffentlicht am “53tUTCt3r” Mittwoch `

Switching to English shows:
` Posted Last Wednesday `
as expected.

**Comment by ThiefMaster** [comment]
![image](https://github.com/indico/indico/assets/179599/a4087e03-b8c9-48d7-89fb-eb33fe12065a)

Someone messed up the quotes for what's used in a date format string when translating... I've just fixed it on transifex so it'll be fine in the next release. Let me know if you want/need a wheel to install before that.

**Comment by olifre** [comment]
@ThiefMaster Many thanks! Next release is perfectly fine :+1: .
