### ISSUE TITLE
Registration form is not shown

### ISSUE THREAD

**Issue by skloepp2** [indico/indico#5801]
**Describe the bug**
We are running the latest version of indico 3.2.4.
When you try to register to an event, the form is not shown.
You also cannot edit the registration form in the admin panel, it is also not shown there.
This also happens if I add a completly new event.

**To Reproduce**
1. Go to 'https://events.gwdg.de/event/487/'
2. Click on 'register'
3. No form

**Expected behavior**
The form should show up

**Screenshots**
![image](https://github.com/indico/indico/assets/130590585/822bdfd5-4cd3-4655-ba40-40ea7b284fd2)
![image](https://github.com/indico/indico/assets/130590585/cec7d759-db82-468a-b2dd-51de581f6671)

**Comment by skloepp2** [comment]
Thats weired since we are using the docker container from https://hub.docker.com/r/getindico/indico/tags and did an upgraded inside the container. Anyway thanks for your help the uninstall and reinstall fixed it.

**Comment by ThiefMaster** [comment]
Hmm maybe you did not recreate the container hosting the static files? That would explain your issue!

**Comment by ThiefMaster** [comment]
BTW @skloepp2, you should probably apply the patch from #5799 on your instance. https://events.gwdg.de/event/473/registrations/ is still extremely slow (at least for people who are not logged in).

**Comment by skloepp2** [comment]
> Hmm maybe you did not recreate the container hosting the static files? That would explain your issue!

We mapped the static files folder to a directory of the host. Maybe thats the issue.

> BTW @skloepp2, you should probably apply the patch from #5799 on your instance. https://events.gwdg.de/event/473/registrations/ is still extremely slow (at least for people who are not logged in).

thanks I'll patch them.
