### ISSUE TITLE
Send email: Using {event_link} as URL for link not properly formatted

### ISSUE THREAD

**Issue by paulmenzel** [indico/indico#5858]
Indico 3.2.2

Using *Send email*, in the email body using Ctrl +k to make *Indico-Instanz* a link to `{event_link}`, the link in the resulting email is not properly formatted:

> Über die https://events.hifis.net/e/808 <<a href=>">Indico-Instanz kannst Du Dir die geplante Zeit anzeigen lassen.

From the email message source:

```
=C3=BCr die IT4Science-Days diesen September beim MDC in Berlin-Buch. =C3=
=9Cber die <a href=3D"&lt;a href=3D" title=3D"2. IT4Science-Days 2023">http=
s://events.hifis.net/e/808</a>"&gt;Indico-Instanz kannst Du Dir die geplant=
e Zeit anzeigen lassen. Sollte der Zeit nicht passen, gib uns bitte =C3=BCb=
```

**Comment by ThiefMaster** [comment]
`{event_link}` is already a full link, not just the URL:

```python
class EventLinkPlaceholder(Placeholder):
    name = 'event_link'
    description = _('Link to the event')

    @classmethod
    def render(cls, event, **kwargs):
        return Markup('<a href="{url}" title="{title}">{url}</a>').format(url=event.short_external_url,
                                                                          title=event.title)
```

We could add `{event_url}` as well, but I'm not sure if most users would understand how to use that in the WYSIWYG HTML editor...

**Comment by paulmenzel** [comment]
Thank you again for an answer with the reference to the code. Awesome!

I guess, it’s a documentation problem then. I was wondering why it wasn’t named `event_url`. `event_url` would be useful for people wanting to use another text for the link.

**Comment by ThiefMaster** [comment]
hmm i think in some other place (iirc in one of our custom plugins) we have `{event_link:custom title here}` (or something like that) which then generates the HTML link with a custom title. doing the same here wouldn't be too hard

**Comment by paulmenzel** [comment]
Awesome. Thank you.
