### ISSUE TITLE
Room Booking: Specify daily "reservable" time intervals for Rooms

### ISSUE THREAD

**Issue by pferreir** [indico/indico#591]
``` yaml
# Ticket imported from Trac
```

For each room, there should be a minimum and maximum time available for booking.

```
[...] an option to specify for each room its daily availability for booking: for ex 31-S-023 and 027 would be available for bookings starting between 8:30am and 5:30pm only.
```

(ask Thomas if info is needed)

**Comment by tgbaron** [comment]
I wonder if this ticket is still relevant... the case was raised by the IT secretariat when they needed to provide the keys to the meeting rooms. Now that we have equipped them with e-locks, keys are not needed anymore, except for the IT auditorium... Were there other requests than IT for this?

**Comment by pferreir** [comment]
This is quite old (imported from Trac). I'll close it now, since it doesn't seem relevant indeed.
