### ISSUE TITLE
[Docs] Typo in the installation guide

### ISSUE THREAD

**Issue by tomasr8** [indico/indico#6013]
There's a typo in the translations section of the installation guide: 

https://github.com/indico/indico/blob/8d6cb25248dd00ff7ad32e2eb6ba49a0d6a85884/docs/source/installation/translations.rst?plain=1#L132

This should read `translators` instead of `translaters`.

### How to reproduce

Build the docs locally:
```bash
cd docs
make html
```

Open `build/html/index.html` and go to `Installation guides -> Translations`

(Please don't send patches for this one, I'm saving it for our newcomer ;))

**Comment by Asymtode712** [comment]
I want to fix this. Please assign me

**Comment by tomasr8** [comment]
> I want to fix this. Please assign me

Please reread the description ;) I mentioned this is for a new team member to get them started on something easy.
If you'd like to contribute, there are other places in the docs that can be improved as well :)
