### ISSUE TITLE
Do not cancel past linked bookings when deleting event 

### ISSUE THREAD

**Issue by ThiefMaster** [indico/indico#6032]
This is pointless and spammy. No cancellation should happen at all if the end time of the booking is in the past.

The cancellation logic is in the `_event_deleted` signal in the rb module.

**Comment by gpuligundla** [comment]
Hi @ThiefMaster, can I work on this?

**Comment by ThiefMaster** [comment]
Thanks, but we have a new team member who joined recently and this is a nice task for him.

Out of curiosity, how did you find this issue? Do you use Indico and are watching this repo? Are you searching for issues labelled as [trivial]?

**Comment by gpuligundla** [comment]
Ok, no problem. I filtered through recently updated repos & looked into issues, and I found I could fix this.

Are there any other good first issues or easy ones open to take up? 
p.s: I'm new to open source contribution & looking for repos to work on it

**Comment by ThiefMaster** [comment]
Indico is maybe not the best first/early project to work on. ;)
It's quite big and rather complex.

Personally I'd recommend working on something you benefit from - e.g. something you use where you're missing a feature or encounter a bug.

Otherwise check if any of the big repos in https://github.com/pallets/ have open issues you find interesting.
