### ISSUE TITLE
Not possible to turn off display of academic title

### ISSUE THREAD

**Issue by paulmenzel** [indico/indico#6038]
Using Indico 3.2.8, some contributers/speakers were entered with there academic title, and some haven’t. With the knowledge of that, we would have liked to not display the academic title in the contributions view and calendar at all, or, to avoid this problem in the first place, to not allow to enter that in the first place.

**Comment by vasantvohra** [comment]
test 123

**Comment by ThiefMaster** [comment]
Unless someone has a better idea, I suggest showing the setting into this form for now:

![image](https://github.com/indico/indico/assets/179599/c02bb7da-d654-4104-975b-81a54be05971)
![image](https://github.com/indico/indico/assets/179599/af400b11-9a7c-4e8a-8a99-872d91068766)

The setting could be called "Hide titles" with a description of "When enabled. titles of people will be hidden anywhere in the event." - with that name it also means that you just need to apply this to displaying things, but do not have to hide the ability to enter titles (which could be a plus, but I think it's not the core point of this feature)
