### ISSUE TITLE
Submit New Abstact Form: user forced to re-fill the form when 2+ authors and, speaker or contribution type or track is required but not chosen. 

### ISSUE THREAD

**Issue by baermb** [indico/indico#6043]
When a user goes to submit an abstract and there are two or more authors. If a speaker or a contribution type or a track is required and one is not selected the form fails and the authors list becomes blank with no way to add authors. The user must cancel and re-fill out the form.

**To Reproduce**
1. Allow and Require a speaker and a contribution type and a track in the submission settings.
2. User clicks on 'Submit New Abstract' button
3. Fill in the form with **more than one author**. It does not seem to matter how the authors are entered (manually, search...), just that there are 2 or more. It works as expected with a single author.
4. Do not select one or more of: author as speaker, contribution type, or track.
5. Hit Submit

It will give an error message, but the authors list is empty with no way to add any. The form must be canceled and restarted.

It works as expected with a single author. It also works with multiple authors if none of the above errors occur.

**Expected behavior**
It should give an error message saying a speaker wasn't selected (or contrib. type or track) and let you select one.

**Screenshots**
![screen-speaker-error](https://github.com/indico/indico/assets/20404184/fcd0a14b-b357-4740-b2c5-46653dba2a2a)
![screen-speaker-error-1](https://github.com/indico/indico/assets/20404184/f9662413-e5be-41fb-94df-e6b7279e53f5)

**Additional context**
Indico v3.2.8 running on Debian Bullseye

I have not tried various combinations of speaker/contrib. type/track being required. They were all required on the event where the error appeared.

**Comment by ThiefMaster** [comment]
Is there a JS error in your browser's dev tools when this happens? Usually "widget not rendering" indicates some JS error that broke it (React-based widgets unmount themselves in case of an unhandled error).

**Comment by ThiefMaster** [comment]
OK, looks like this broke in #5835, there's no `name` field in the person data when re-rendering the field after a round-trip to the server (which happens in case of a failed submission), so this code breaks:

```jsx
value={!autoSort ? persons : persons.slice().sort((a, b) => a.name.localeCompare(b.name))}`
```

**Comment by ThiefMaster** [comment]
Foung a possible quick'n'dirty fix, but since it's quite ugly I (or one of my colleagues) will have a closer look one of these days.

**Comment by baermb** [comment]
> Is there a JS error in your browser's dev tools when this happens? Usually "widget not rendering" indicates some JS error that broke it (React-based widgets unmount themselves in case of an unhandled error).

There is, but it looks like you found the same JS error above and tracked it down, e.g.
```
TypeError: e.name is undefined
    value PersonLinkField.jsx:481
    re PersonLinkField.jsx:481
    React 12
    setupPersonLinkWidget jQuery
    <anonymous> line 288 > injectedScript:2
    jQuery 40
    _onOpen main.7bb061f8.bundle.js line 1 > eval:116
    jQuery 8
    open main.7bb061f8.bundle.js line 1 > eval:16
    jQuery 6


```
