### ISSUE TITLE
Convert google slide URLs to PDFs (as with powerpoint etc)

### ISSUE THREAD

**Issue by EdwardMoyse** [indico/indico#6045]
**Is your feature request related to a problem? Please describe.**
People increasingly add presentations as links to google slides. This is bad  as these URLs can expire/be deleted in which case the content is lost. Of course, we can ask speakers to remember to also update a pdf version, but since indico can autoconvert other file formats, it would be great if it could do it for google slide URLs as well.

**Describe the solution you'd like**

Use google API to convert to pdf
```
GET https://www.googleapis.com/drive/v3/files/{fileId}/export
```
as described [here](https://developers.google.com/drive/api/reference/rest/v3/files/export).

where the `{field}` can be extracted from a URL e.g.
```
https://docs.google.com/presentation/d/1kbmidlabdSPHUAgS2sZOCGaMqvCmjSM6Kk2p9LSH3Oo/edit#slide=id.p
```
and the `mimeType` is obviously `application/pdf` e.g. using the URL above:

```
https://developers.google.com/drive/api/reference/rest/v3/files/export?apix_params=%7B%22fileId%22%3A%221kbmidlabdSPHUAgS2sZOCGaMqvCmjSM6Kk2p9LSH3Oo%22%2C%22mimeType%22%3A%22application%2Fpdf%22%7D
```

**Comment by ThiefMaster** [comment]
Does this require a Google API key? In any case, this would probably be pretty easily possible using a plugin.

However, there's always one problem: When to do the conversion? At upload time? At the start/end time of the item (event, contribution, etc.) the link is attached to? What if it changes later?

**Comment by EdwardMoyse** [comment]
This is a good point. There is `watch` [functionality](https://developers.google.com/drive/api/reference/rest/v3/files/watch) but assuming that is too complicated, I would argue that as for powerpoint etc the conversion happens when the file/link is uploaded, so the same should happen here i.e. I would convert when the link is uploaded (possibly with a message explaining the implications). 

Then if the talk is updated, it would be up to the speaker to delete the URL and upload it again (which definitely isn't ideal, but I think it's a lot better than nothing).

**Comment by ThiefMaster** [comment]
At some point I'd still like to make file conversion a first-class citizen (instead of using pretty low-level plugin hooks). So I could absolute imagine a "refresh pdf" at some point and indeed stick with the simple "when adding the link" option for now.

**Comment by ThiefMaster** [comment]
Is this something you would be interested in contributing as a pull request? While not particularly hard I cannot make any promises when we would be able to add this, but if you have Python skills, I could certainly give pointers towards where it could be implemented (in the conversion plugin which already has most of the "infrastructure/scaffolding" necessary for it).

**Comment by EdwardMoyse** [comment]
I was actually wondering if I could contribute to this (I know python), but I would definitely need to be pointed in the right direction.

**Comment by ThiefMaster** [comment]
Awesome!

https://github.com/indico/indico-plugins-cern/tree/master/conversion is the plugin that implements the document-to-pdf conversion.

The `_add_form_fields` method is currently registered in a way that it only adds the option to convert for files but not for links - so I would add a similar field to the `AddAttachmentLinkForm`. The description should be different and mention that only Google Slides can be converted.

Right below that method there's some code to process the value of the field - extending it should be pretty straightforward.
`_attachment_created` and `_after_commit` are where the conversion gets started.  The first method needs to be adapted to handle both the existing 'file with valid extension' case and the new 'google slides link' case. In `_after_commit` you'll need to trigger a new case for the Google links. 

In the new task (just a function decorated with `@celery.task(...)` - see the existing ones - you make the necessary API calls to download the PDF version of the presentation and save it using the `save_pdf` util.

In case Google requires some API credentials for this download (I hope not...), you'll also have to add a new plugin config setting for this. Simply add it to the plugin's `SettingsForm` and `default_settings`.

---

For an indico dev setup we have [this guide](https://docs.getindico.io/en/latest/installation/development/) - after all, you want to be able to test this locally - I can also send you a link to a codimd where I wrote a step by step guide on how to setup an indico dev environment on a CERN openstack VM (works very nicely combined with VSCode remote editing). Ping me on Mattermost (`@amonnich`) if you want me to share the link with you. But a local setup should be fine as long as you use Linux (in principle it should work on a Mac as well)

**Comment by EdwardMoyse** [comment]
Thanks for the links - I'm currently stuck working out how to build the conversion plugin .

My dev directory looks like this:
```
(env) emoyse@Edwards-MBP-10 indico % ls
data			env			indico-plugins-cern	maildump		plugins			src
```
But when i do:
```
(env) emoyse@Edwards-MBP-10 indico % src/bin/maintenance/build-assets.py plugin /Users/emoyse/LocalDocuments/indico/indico-plugins-cern/conversion --dev --watch 
```

I get:
```
(env) emoyse@Edwards-MBP-10 src % bin/maintenance/build-assets.py plugin /Users/emoyse/LocalDocuments/indico/indico-plugins-cern/conversion --dev --watch    
Plugin conversion does not exist
Traceback (most recent call last):
  File "/Users/emoyse/LocalDocuments/indico/src/bin/maintenance/dump_url_map.py", line 62, in <module>
    main()
  File "/Users/emoyse/LocalDocuments/indico/env/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emoyse/LocalDocuments/indico/env/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/emoyse/LocalDocuments/indico/env/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emoyse/LocalDocuments/indico/env/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emoyse/LocalDocuments/indico/src/bin/maintenance/dump_url_map.py", line 54, in main
    rules = get_rules(set(plugins))
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emoyse/LocalDocuments/indico/src/bin/maintenance/dump_url_map.py", line 30, in get_rules
    app = make_app(testing=True, config_override={'BASE_URL': 'http://localhost/',
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emoyse/LocalDocuments/indico/src/indico/web/flask/app.py", line 432, in make_app
    raise Exception('Could not load some plugins: {}'.format(', '.join(plugin_engine.get_failed_plugins(app))))
Exception: Could not load some plugins: conversion
Traceback (most recent call last):
  File "/Users/emoyse/LocalDocuments/indico/src/bin/maintenance/build-assets.py", line 272, in <module>
    cli()
  File "/Users/emoyse/LocalDocuments/indico/env/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emoyse/LocalDocuments/indico/env/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/emoyse/LocalDocuments/indico/env/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emoyse/LocalDocuments/indico/env/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emoyse/LocalDocuments/indico/env/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emoyse/LocalDocuments/indico/src/bin/maintenance/build-assets.py", line 234, in build_plugin
    subprocess.check_call([sys.executable, 'bin/maintenance/dump_url_map.py', '--output', url_map_path,
  File "/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Users/emoyse/LocalDocuments/indico/env/bin/python', 'bin/maintenance/dump_url_map.py', '--output', '/Users/emoyse/LocalDocuments/indico/indico-plugins-cern/conversion/url_map.json', '--plugin', 'conversion']' returned non-zero exit status 1.
```

**Comment by ThiefMaster** [comment]
You first need to `pip install -e ....../indico-plugins-cern/conversion` so the plugin is available in the environment where you also installed Indico.
