### ISSUE TITLE
Option to customise Survey Link Email

### ISSUE THREAD

**Issue by adam-parker1** [indico/indico#6069]
It would be good if there was the option to customise the email message when a survey goes live. 

Similar to what is possible for registration form notifications (with markdown syntax) 
![image](https://github.com/indico/indico/assets/105722748/ea06fb20-eeb5-46a1-be3c-843da46026c5)

Or perhaps somewhere to schedule a post-event email to be sent when a conference has finished, where we could add the survey information and it is automatically sent.

Maybe this is already possible and I missed it but the only option I see is customising https://github.com/indico/indico/blob/4a98ee257daaeb25686e10e6f6a8dc852e1547ac/indico/modules/events/surveys/templates/emails/survey_link_email.html which isn't ideal.  

Maybe a duplicate of #1951 , #788 , #4851

**Comment by ThiefMaster** [comment]
I wonder if we should just get rid of the automated survey notification and add our usual "send email" dialog with a placeholder for the survey link. That way one could open the survey and send the email with whatever customizations they want.

(Survey are actually the only place in Indico where we have an automated email sent at the scheduled opening time of something..)

**Comment by adam-parker1** [comment]
That would work, I would support this idea! I did actually try to send an email and use the {survey_link} placeholder but unfortunately wasn't available there.

Essentially we are setting up an event and wanted to send a post-event email. This would include the survey, closing remarks etc. Doing this manually would be fine if we can use link placeholders (can then also only email those you actually checked-in/attended)
