### ISSUE TITLE
See if we can have an "add to outlook" link like we have for google in the social widget

### ISSUE THREAD

**Issue by ThiefMaster** [indico/indico#6075]
For Google Calendar it's a generic URL that does not require API keys or similar. All the data is passed via query string:

```html
<div class="social-site">
    <a href="https://www.google.com/calendar/event?{{ google_calendar_params|urlencode }}" target="_blank">
        <img src="{{ url_for('assets.image', filename='google_calendar.gif') }}" alt="" border="0">
    </a>
</div>
```

Check if https://outlook.office.com/ has something similar so people can add an event to their Outlook/Exchange Online calendar the same way.

**Comment by jhegeman** [comment]
Some Googling led me to this site:
  https://www.labnol.org/calendar/
which allows one to build 'add calendar' links for various calendar systems.

Without having dug very deeply: the links this tool generates for Outlook 365 seem to work for my CERN Outlook calendar.

I'm having trouble finding an authoritative source of documentation for the URL format, so far.

**Comment by jhegeman** [comment]
This repo seems to answer the 'official documentation' question ;-)
https://interactiondesignfoundation.github.io/add-event-to-calendar-docs/services/outlook-web.html
It also provides some nice unofficial documentation
