### ISSUE TITLE
Add category legend in event calendar view

### ISSUE THREAD

**Issue by OmeGak** [indico/indico#6105]
### Is your feature request related to a problem?

The event calendar view already colors events based on their category. There is no way, however, to know which category the events belongs to.

### Describe the solution you'd like

Add a vertical legend on the sidebar displaying all the categories present in the current month, alongside their assigned color.

### Additional context

The legend in the event calendar view is a stepping stone to a number of improvements, like adding event coloring by location and filtering events in the calendar by category/location. 

This feature request comes inspired by [Perimeter Institute](https://perimeterinstitute.ca/)'s in-house developed calendar view:

<img width="1261" alt="image" src="https://github.com/indico/indico/assets/716307/7b348d86-7739-4df5-812a-a1a9fe9b817c">

**Comment by Moliholy** [comment]
I'm currently working on a similar implementation. Knowing that they could be many categories, clearly the current color palette is not sufficient and we should expand it. Any suggestion on how we could have an arbitrary number of colors?
