### ISSUE TITLE
Show error indicator for Yes/No field in registration form

### ISSUE THREAD

**Issue by lovelysingh7023** [indico/indico#6109]
**Problem with registration form**
Unfortunately, there is no message if you have not answered a mandatory question or, for example, in the case of selection questions with radio buttons, the text appears in red, but unfortunately this does not happen with the mandatory yes/no questions.

**Expected behavior**
There should be any pop-up warning or the red alerts for the required fields so that users can understand why the form is not getting submitted. 

**Screenshots**
<img width="651" alt="Screenshot 2023-12-20 142734" src="https://github.com/indico/indico/assets/154438645/828c8175-ed8b-4d99-8690-95f44c3f3490">

If some suggestions are their kindly answer as soon as possible.

Thank you.

**Comment by ThiefMaster** [comment]
Yes, the usual error indicator is missing for that field. I thought I had created an issue fore this before but apparently I didn't...

It should be handled just like the other fields.

**Comment by lovelysingh7023** [comment]
> Yes, the usual error indicator is missing for that field. I thought I had created an issue fore this before but apparently I didn't...
> 
> It should be handled just like the other fields.

Yeah you are right.
then what is the solution for this?

**Comment by ThiefMaster** [comment]
Obviously the solution is that someone (possibly us, unless someone else is faster in contributing this as a PR) implements this ;)

There's is no workaround in the meantime.

**Comment by lovelysingh7023** [comment]
> Obviously the solution is that someone (possibly us, unless someone else is faster in contributing this as a PR) implements this ;)
> 
> There's is no workaround in the meantime.
:) ok 
thank you dear for the reply.
Hope this issue solves soon.
