### ISSUE TITLE
Documentation changes for EL8 and EL9 using Apache

### ISSUE THREAD

**Issue by adamboutcher** [indico/indico#6137]
**Is your feature request related to a problem? Please describe.**
The current documentation states only nginx is supported however supporting Apache may be possible...

**Describe the solution you'd like**
Updated docs outlining EL8 and EL9 Apache installation..

**Additional context**
The following may be of help:
 Package mod_xsendfile is now in EPEL for EL8 and EL9.

### EL8
A required packages needs a 3rd party repo for EL8 - mod_proxy_uwsgi
```
yum -y install https://extras.getpagespeed.com/release-latest.rpm
yum install -y mod_proxy_uwsgi
```

### EL9
Package  mod_proxy_uwsgi has been merged into a different package
```
yum install -y epel-release
yum install -y httpd-core
```

**Comment by ThiefMaster** [comment]
I'll update the docs for the 3.3 release.

My plan is to to drop anything below the latest RHEL/Alma/whatever 9 and the latest stable Debian + Ubuntu (likely LTS) though. Maintaining docs for legacy OS versions is not really sustainable (even less considering we do not use those old versions ourselves either), so someone who really wants to install Indico on EL8 will need to adapt on their own (which, for someone with the proper technical skills, should not be particularly hard).

**Comment by adamboutcher** [comment]
EL8 isn't really considered legacy if you're talking about Rocky, Alma and Oracle... However I do understand your point.

I don't utilise SAML/Shib; would your suggestion be that nginx is a better choice overall? Maybe if so, the docs could reflect that instead?

**Comment by adamboutcher** [comment]
The SElinux module CIL you provide for Indico doesnt seem to work correctly...

Audit2Why:
```
type=AVC msg=audit(1706014661.402:2538): avc:  denied  { connectto } for  pid=74703 comm="nginx" path="/opt/indico/web/uwsgi.sock" scontext=system_u:system_r:httpd_t:s0 tcontext=system_u:system_r:unconfined_service_t:s0 tclass=unix_stream_socket permissive=0

	Was caused by:
		Missing type enforcement (TE) allow rule.

		You can use audit2allow to generate a loadable module to allow this access.
```
audit2why

If you add the following it then works:
```
(typeattributeset cil_gen_require httpd_t)
(typeattributeset cil_gen_require unconfined_service_t)
(allow httpd_t unconfined_service_t (unix_stream_socket (connectto)))
```

I'm not sure if this is an oversight with with SELinux packages such as httpd booleans etc but this solved the issue for me.

**Comment by ThiefMaster** [comment]
```
(allow httpd_t unconfined_service_t (unix_stream_socket (connectto)))
```

That should be enough. At least that's what I'm using for our production deployment on AlmaLinux 9 and it works fine.
