### ISSUE TITLE
Make the reason for booking a room optional

### ISSUE THREAD

**Issue by OmeGak** [indico/indico#6150]
### Is your feature request related to a problem?
Not all organizations require giving a reason for booking a room. Always requiring a reason forces users to make unnecessary keystrokes that often end up being "ASDF" and the likes.

### Describe the solution you'd like
I can imagine two non-exclusive ways to mitigate this nuisance.

Option 1:
Allow configuring if the reason for booking is mandatory. This could be a per-room, per-location and/or global configuration.

Option 2:
Make the reason for booking optional, or not displayed at all even, when booking a room for an event. In this case it is clear that the booking is made because it's going to be used for a particular event.

---

/cc @dwindibank

**Comment by ThiefMaster** [comment]
I'd make it a global setting. Least amount of work, and probably enough for you guys ;)

Either a checkbox ("Require booking reason", checked by default) or a dropdown ("Always", "Bookings not linked to an event" [too long but you know what I mean], "Never")

**Comment by dwindibank** [comment]
I'd like to go with a drop down of "Never", "Always" for now. 

Then in the future we could add additional options like  "If booking not linked to event" or "Never - unless required by room".
