### ISSUE TITLE
Nested lists no longer indented correctly

### ISSUE THREAD

**Issue by ThiefMaster** [indico/indico#6151]
This comes from one of the PRs that were merged into `a11y` and recently into `master`:

The most problematic place where this happens is in the event description and in minutes:

![image](https://github.com/indico/indico/assets/179599/b3c58786-7e73-4ad2-887e-150e232268a6)
![image](https://github.com/indico/indico/assets/179599/6e48d635-607b-4c69-bef6-d1dc99a7388a)

I'm not sure if one of the existing a11y PRs fixes this, but a separate PR (against `master`) for this would be appreciated because the current state is certainly broken and users will likely complain once we put that live... :/

PS: Another - minor - UI regression which is probably also caused by removing the default list margins is on the event (and category) log pages in management: The "Show...", log item list, and pagination widget are now much more squeezed together.

**Comment by foxbunny** [comment]
FYI: the documentation about the minutes contains a "vide" that is just a screenshot of the video player.

<img width="892" alt="image" src="https://github.com/indico/indico/assets/65413/df259267-9fce-47a2-8b78-720100e0bdaf">
