### ISSUE TITLE
20230630 - API registrants: add registration form ID or per-form endpoint

### ISSUE THREAD

**Issue by micsucmed** [indico/indico#6187]
**Deadline**: 2023-06-30

The endpoint `{{base_url}}/api/events/{{event_id}}/registrants`  does not return the registration form id so it's not possible to distinguish where a person registered (may be in more than one form!)

We ask to add the `registration_form_id` to this export OR to add another endpoint that returns only registrants of that particular form. The URL can be something like `{{base_url}}/api/events/{{event_id}}/registrants/{{registration_form_id}}` and it would return the list of persons that registered only to that `registration_form_id`

**Comment by ThiefMaster** [comment]
Those endpoints are legacy. Can they use the ones @tomasr8 added for the new check-in app which are scoped by regform?

```
/api/checkin/event/<int:event_id>/forms/<int:reg_form_id>/
/api/checkin/event/<int:event_id>/forms/<int:reg_form_id>/registrations/
/api/checkin/event/<int:event_id>/forms/<int:reg_form_id>/registrations/<int:registration_id>
```

The data returned there is quite detailed.

**Comment by tomasr8** [comment]
Yes, those new endpoints are what they should be using. They were originally added for the app but anyone can use them.

**Comment by micsucmed** [comment]
Stefano confirmed the endpoints for the new check-in app can be used for this so I think we can close this issue

**Comment by finn-rm** [comment]
I've been trying to use the `/registrations/` end point but it seems to consistently 502 when trying to get the result for large participant lists (>1000). Interested to see if this is our deployment falling over, or a universal bug.

Any ideas on how I could get around this?

**Comment by ThiefMaster** [comment]
Which exact endpoint do you use? And on which Indico version?

**Comment by finn-rm** [comment]
We are on 3.3.1, and using the `/api/checkin/event/<int:event_id>/forms/<int:reg_form_id>/registrations/` endpoint. 

I can get it to consistently return a valid response for smaller events for what its worth

**Comment by finn-rm** [comment]
Thanks for checking on your side, really appreciate it.

I'll reach out to our DevOps team to see if we can push for a version upgrade. If I still have issues after that i'll comment again, otherwise we can assume all is well :)
