### ISSUE TITLE
Multipass Group with ID

### ISSUE THREAD

**Issue by tomako** [indico/indico#6235]
Hi guys,
I've just noticed in the multipass integration that the Group has only `provider` and `name` property. So [here the locator](https://github.com/indico/indico/blob/master/indico/modules/groups/core.py#L176) uses `name` as `group_id` instead of a real `id`. It seems it assumes the group name is unique however in many cases it is not guaranteed. Exactly as in mine. And as I see in your [`flask-multipass-cern`](https://github.com/indico/flask-multipass-cern/blob/master/flask_multipass_cern.py#L495) package you also have a trade-off.

If I extend the Group class by adding `id` the locator is still using the name. However if the `Group.id` = `Group.name` by default and the locator uses `group.id` that would open the way to use `id` in the URL and for further improvements. It seems it can be backward compatible but you might have better suggestion.

**Comment by ThiefMaster** [comment]
Multipass groups are always identified by name. That's how Flask-Multipass works: A group has a name. which has to be unique within the provider from which it comes.

If something beyond that is needed, it should be handled on the side of a custom multipass plugin.

**Comment by ThiefMaster** [comment]
The main reason why we do not want something like group IDs in Indico is that it'd be extremely fragile: If you replace whatever is backing your groups, you'd end up with IDs that no longer work - while names are much more likely to stay the same.

**Comment by tomako** [comment]
Hmm, I see. It makes a bit harder but indeed I can manage the uniqueness. I also wanted to avoid the extra API call before collecting members of a given group. Then maybe with caching. 
Alright, thanks for the quick response.
