### ISSUE TITLE
Ambiguous "Email" action

### ISSUE THREAD

**Issue by duboism** [indico/indico#6303]
**Describe the bug**
The first entry in the 'Actions' menu in the 'Registration' page is labelled 'Email' while it's used to send email to participants. As far as I can say, even if the context helps, this is a bit weird in English.

However, it's really weird in French (I mainly use this language) where it says "Adresse électronique", literally "email address" (singular). According to my Italian and Spanish colleagues, the respective translation in those languages are weird too.

Note that this is not just a purist issue: this weird phrasing makes hard to find the feature.

I have attached screenshots for those languages (and suggestions below).

**To Reproduce**
1. Go to 'Registration'
2. Click on a registration list
3. Select one or more participants
4. Click on 'Actions'
5. See the first entry

**Expected behavior**

From my understanding and discussion with my colleagues, I would say:
- in English: "Send email"
- in French: "Envoyer un courrier électronique" (to stay coherent with other usages)
- in Italian: "Inviare une email"
- in Spanish: "Enviar un correo electrónico"

Other entries in the 'Action' menu have similar structure.

**Screenshots**

English:
![en](https://github.com/indico/indico/assets/4348913/ac3537d3-22cb-4e99-8e25-57786cce8cf2)

French:
![fr](https://github.com/indico/indico/assets/4348913/75d2e99d-0303-45e7-b38e-c0a84cd660b5)

Italian:
![it](https://github.com/indico/indico/assets/4348913/0ca706d7-3443-4a0b-adad-04945fb722f9)

Spanish:
![es](https://github.com/indico/indico/assets/4348913/11c6943b-ca4d-4cb1-a1a2-e2d6380af03c)

**Additional context**

I don't know much about translations but AFAIK this entry use the "Email" message which is used in several files. Maybe we need to differentiate the email address and the action of sending an email.

Note that there is a "Send emails" message which is almost what we need.

**Comment by ThiefMaster** [comment]
Yeah, we should probably add some i18n context and/or reword it...

**Comment by ThiefMaster** [comment]
I changed it to "Send email".

**Comment by duboism** [comment]
Hum, sorry to react a bit late (you were super quick 👍 ). Unfortunately, I'm not 100% sure that this is enough (at least without a bit of effort on the translations). The French translation of "Send email" is "Envoyer le courriel" (this insists on the fact that the email is already here as in "send the email").

Maybe this is OK in the context where the "Send email" was used before but in the context of the "Action" menu that would be weird (since we will write it).

**Comment by duboism** [comment]
Thanks. I'm sorry I can't help more. I just wanted to point out that maybe we have to distinguish between the two cases as in some languages they might be different.
