### ISSUE TITLE
Room booking: very difficult/impossible to deselect the weekdays to recur by

### ISSUE THREAD

**Issue by alittle60** [indico/indico#6314]
**Describe the bug**
Room Booking
In Recurring booking in Recurring on specific weekdays - very difficult to impossible to deselect the weekdays. If you want the default Wed then no problem, but difficult to deselect Wed or any other day. No problem selecting a weekday.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Start your booking'
2. Click on 'Recurring Booking...'
3. Go to 'Recurring every' and click on the day or days to recur on, e.g. Mon. Then cannot deselect Wed (the default) or any other day you may have selected

**Expected behaviour**
I expected to be able to left click the weekday once to select and deselect. I have tried multiple clicking to no avail.

**Screenshots**
![image](https://github.com/indico/indico/assets/150372105/6dddba8b-fa3f-4518-9d90-30c2ea161980)

**Additional context**
We are seeing this in both Chrome and Firefox

**Comment by GovernmentPlates** [comment]
Hi @alittle60 

Can you please clarify what you are trying to do and what you are expecting to happen?

**Comment by ThiefMaster** [comment]
You cannot deselect the last remaining weekday. Selecting monday first and then deselecting wed should be possible though.

**Comment by alittle60** [comment]
![Indico bug 6314](https://github.com/indico/indico/assets/150372105/3f00f94e-f244-4188-96ab-ef372100a605)

Hi Adrian,
I have sent  you a .gif of the problem. I select the date range and the select Mon. Then you can see me struggling to deselect Wed. I am never able to get less than two weekdays. Hope this helps,
Anne

**Comment by lecabori** [comment]
Yes, it's a css issue. All fixed now, thanks all.
Cheers
