### ISSUE TITLE
Receipt files missing from data export

### ISSUE THREAD

**Issue by tomasr8** [indico/indico#6331]
When using the data export feature, registration documents (receipts, etc..) are currently not included

We'd probably just need to extend this function:
https://github.com/indico/indico/blob/61aacd161af9c64099802e4bb14b06de47af7c75/indico/modules/users/export.py#L167-L173

..and add a new case to the storage path builder:
https://github.com/indico/indico/blob/61aacd161af9c64099802e4bb14b06de47af7c75/indico/modules/users/export.py#L291-L320

**Comment by ThiefMaster** [comment]
I'd separate it into `get_registration_documents`. Also make sure to not include files which aren't `is_published` (those may even be tests a manager did, so I'd treat them just like manager-only fields and exclude them)
