### ISSUE TITLE
profile_registered_admins: Add if it’s a locale profile

### ISSUE THREAD

**Issue by paulmenzel** [indico/indico#6363]
https://github.com/indico/indico/blob/b912aef868eaad469ff7893d22658ca5866a247c/indico/modules/users/templates/emails/profile_registered_admins.txt#L11-L16

It’d be great, if the notification email contained, if it’s a local identity or an external one with the connector, like LDAP.

**Comment by ThiefMaster** [comment]
It's only sent for local identities, since it's generally assumed that LDAP/SSO accounts are properly controlled so the primary usecase (detecting likely spammers / inappropriate accounts) does not apply there:

```py
    if (from_moderation or identity is None or identity.provider != 'indico' or
            not user_management_settings.get('notify_account_creation')):
        return
```

**Comment by paulmenzel** [comment]
Sorry, indeed. Since we enabled local identities, I got this message the first time. First I thought, it was a local identity, but then checked this morning, and the user information showed an external account connected to it. Asking the user, they said, they first registered, but then used LDAP to log in. The user search only found one user though.

**Comment by ThiefMaster** [comment]
Probably it was the same email, so when logging in with LDAP it prompted the user to link the accounts (you can view the user details and check their "Accounts" tab to confirm).
