### ISSUE TITLE
Implement the Hungarian translation

### ISSUE THREAD

**Issue by szabogyula** [indico/indico#6365]
I would like the Hungarian translation to be included in the next release.

How can I achieve this?

**Comment by tomasr8** [comment]
Hi!
We don't have any hard rules for when we add a new official language. If you and the other translators think that the language is ready, we're happy to include it :)
Before that though, I'd suggest having a look at our [demo instance](https://localization-demo.getindico.io/) and making sure that all the main pages are fully translated (I saw a few missing translations) and that there are no typos etc..

**Comment by szabogyula** [comment]
Thank you, it's great 👍 !

We'll make a last sprint and get back to you with a polite request.

**Comment by szabogyula** [comment]
Hi!

All important and relevant translations are ready to launch, so please include the Hungarian language files in the next release.

Thank @szabopanni for your lots of work.

Thank you!

**Comment by tomasr8** [comment]
Thanks! Most of the issues are fixed now. There's only a couple of missing placeholders:

- {count} attachments have been uploaded | A csatolmányok feltöltve
- Email address set as the sender of all notifications sent to users. If empty, then {email} is used. | A felhasználóknak küldött összes értesítés feladójaként beállított e-mail cím. Ha üres, akkor ezt használja.
- We have sent an email to {email}. Please click the link in that email within 24 hours to confirm your new email address. | Elküldtünk egy e-mailt az Ön e-mailjére. Kérjük, hogy kattintson a linkre az e-mailben a következő 24 órán belül, hogy megerősítse az új e-mail címét.
- Login failed: {error} | Sikertelen bejelentkezés
- Must be between {earliest} and {latest}. | {Legkorábbi} és {legkésőbbi} között kell lennie.
- Must be later than {earliest}. | Később kell lennie, mint {legkorábbi}.

**Comment by szabogyula** [comment]
Hi, we fixed these six strings.

Is there any tool that checks these syntax problems in transifex web UI or any handy third-party tool?

**Comment by tomasr8** [comment]
It's all looking good now :)

Transifex should already show these problems with a warning under the translation. I just changed the settings and they should be treated as errors now so in theory it won't let you save broken translations anymore.

You can also filter for translations which have an error or a warning:
![obrazek](https://github.com/indico/indico/assets/8739637/b3c54543-f720-4c1d-8ada-72fef1f115b5)

**Comment by ThiefMaster** [comment]
FYI, I plan on releasing v3.3.3 during one of the next few days.

**Comment by tomasr8** [comment]
Hi @szabogyula @szabopanni! We need some help [cleaning up the Hungarian translation](https://talk.getindico.io/t/help-needed-for-duplicate-translations-in-transifex/3781), if you'd like to help us out or if you know someone who can :slightly_smiling_face:

**Comment by szabopanni** [comment]
Hello! I rewrote all the instances in the log, so it should be all okay now, but please let me know if there are duplicates I missed on the way. For the translation "Title", we use a different word for Salutations and Title (of a paper e.g.) so I left it different based on the context. Thanks!

**Comment by tomasr8** [comment]
Awesome, thanks a bunch! @AjobK could you please check if there's anything in Hungarian that still needs fixing?
