### ISSUE TITLE
Date Field in Registration Form Only Shows Previous and Next 5 years

### ISSUE THREAD

**Issue by aicampbell** [indico/indico#6368]
When trying to use Date field in a registration form for date of birth, users are only able to choose from the previous or next 5 years.

Some people think that you cannot put a date below 2019... which is complicated for a date a birth.

Of course, when you type the date it works. 

Is this normal behaviour or should the list of years be scrollable ?

**To Reproduce**
1. Create a new registration form
2. Add a Date field
3. Try to complete the registration form as a user
4. See problem

**Screenshots**
![IPrpvaJzh3BoeOAE](https://github.com/indico/indico/assets/10201770/ed820bef-9d8a-44ae-8756-e46a33bf4c28)

**Comment by ThiefMaster** [comment]
fixed by #6371 so the solution is to update indico to the latest version :)

![image](https://github.com/user-attachments/assets/cb141b30-6f27-4484-93a4-87a7aae37c5b)
