### ISSUE TITLE
Indico 3.3.2 update problem with Python version

### ISSUE THREAD

**Issue by lovelysingh7023** [indico/indico#6378]
Hello,

### Problem with Python version: -

We are upgrade Indico from v3.2.8 to v 3.3.2, 
We update Debian version 11 to 12, also the Python version 3.9 to 3.12 using following commands 
- pyenv install 3.12
- pyenv global 3.12
and then proceeding further with 
- indico setup upgrade-python --force-version 3.12
it displays an error as: 
![Screenshot 2024-06-06 101442](https://github.com/indico/indico/assets/154438645/61263c73-6a56-46ea-a57b-91bd7c8cc69f)

Afterwords we try to check the Python version and it showed:
**Python version 3.11.2**
![Screenshot 2024-06-06 104006](https://github.com/indico/indico/assets/154438645/4c8048b2-725e-4f75-a402-167d38ee0980)

And now we don't know where the problem is.
Could you please suggest something to solve this issue.
Thank you in advance for your help.

Regards,
Lovely Singh

**Comment by ThiefMaster** [comment]
It sounds like your old Python env is broken (no indico installed in there).

Anyway, you can simply manually recreate the venv on 3.12:

```
deactivate
rm -rf ~/.venv
python -V  # confirm you have 3.12 here
python -m venv --upgrade-deps --prompt indico ~/.venv
source ~/.venv/bin/activate
pip install setuptools wheel
pip install uwsgi
pip install indico
```
