### ISSUE TITLE
Custom menu pages title leaked when access is deined

### ISSUE THREAD

**Issue by kewisch** [indico/indico#6416]
**Describe the bug**
The custom pages you can add to event menus all have an id. You can cycle through them by visiting e.g. https://events.example.com/event/12/page/345 which will redirect to https://events.example.com/event/12/page/345-sekrit-page . If the user doesn't have permission for that page, they can still read the title via the URL slug.

**To Reproduce**
1. Create custom pages that have access restrictions
2. Visit the URL in a private window
3. See redirected URL title

**Expected behavior**
Access restrictions should be applied before the redirect occurs. If the user has no access, the URL should not redirect.

**Comment by ThiefMaster** [comment]
Hmm, interesting one. How common is it for menu item titles to contain secret information though.

Anyway, I agree that it's worth looking into a way to fix it and avoid the redirect to include the slug if the user has no access.

**Comment by kewisch** [comment]
Probably not very common, I just happened to notice so I thought I'd let you know. I guess if someone from the press was really interested in leaking where the next Ubuntu Summit might be, they could have cycled through the pages to see a page titled "Exploring The Hague" before the location was announced.

**Comment by ThiefMaster** [comment]
Just opened a PR for it. Feel free to give it a try if you still have a test/dev system!
