### ISSUE TITLE
CERN logo in footer is low-res/blurry

### ISSUE THREAD

**Issue by avivace** [indico/indico#6457]
![image](https://github.com/user-attachments/assets/53f0e0ab-725b-4409-b26a-346d138ab320)

**Comment by GovernmentPlates** [comment]
This doesn't relate to Indico itself, but rather the template overrides we use on the CERN Indico instance.


Nonetheless, noted - thanks :)

**Comment by tomasr8** [comment]
Thanks @avivace! ;) This'll be a nice task for our latest newcomer in the team :)

Just for reference, here's the official logo in SVG: https://design-guidelines.web.cern.ch/downloads
