### ISSUE TITLE
change filetype for globe.png

### ISSUE THREAD

**Issue by bbb-user-de** [indico/indico#6465]
Could we change the filetype for globe.png (size ~2.9MB) to .webp?
The .webp file has only ~0.213MB

globe.webp was processed with cwebp (default settings)
[globe.zip](https://github.com/user-attachments/files/16493597/globe.zip)

**Comment by ThiefMaster** [comment]
The picture you added there is completely different from the [one we have in our repo](https://raw.githubusercontent.com/indico/indico/master/indico/web/static/images/globe.png)?!

But yes, I wouldn't mind replacing the PNG with a JPEG or WEBP one. Not sure why we use a PNG there anyway, for photos that's clearly not a good format...

**Comment by bbb-user-de** [comment]
SRY...
here is the right picture
[globe.zip](https://github.com/user-attachments/files/16493838/globe.zip)

**Comment by GovernmentPlates** [comment]
@bbb-user-de Feel free to open up a PR for this :)

**Comment by ThiefMaster** [comment]
it will auto-close once the PR is merged
