### ISSUE TITLE
Safari causes issues with `DateInput` component

### ISSUE THREAD

**Issue by GovernmentPlates** [indico/indico#6474]
Safari seems to send a different date format to the `DateInput` component in our registration forms, which raises a confusing validation error. Instead of formatting dates with a `-` separator, Safari chooses to use `/`, which breaks our validation check.

See below (comparing this with Chrome):
![image](https://github.com/user-attachments/assets/f839ecdc-35e8-41df-b4ad-7e2d7525be1f)

**Comment by ThiefMaster** [comment]
FYI I also pinged @foxbunny about this bug yesterday (since it's related to his code)

**Comment by GovernmentPlates** [comment]
#6501 should resolve this
