### ISSUE TITLE
Room booking: Equipment type availability information is not updated when a room gets deleted

### ISSUE THREAD

**Issue by moschn-unibonn** [indico/indico#6493]
**Describe the bug**
I stumbled upon this by chance when adding features to our equipment types. One of the equipments stated the information "Available in 1 room", but I was unable to find the room it was attached to. I remembered that a co-worker had been experimenting a bit with the equipments and a test room which has since been deleted. I recreated the situation on our test instance (see steps below) which showed the same outcome. The availability information is not updated when a room an equipment is attached to gets deleted.

**To Reproduce**
1. Add a new equipment type
2. Add a new room and add the equipment to it via the options tab
3. The equipment information in the "Equipment & Features" admin overview now correctly states "Available in 1 room"
4. Delete the room
5. The equipment information still states "Available in 1 room", even after refreshing the page

**Expected behavior**
The equipment information should be updated to the correct number of rooms (or in this case to "Currently unused").

**Comment by ThiefMaster** [comment]
Indeed, hat happens because rooms are soft-deleted. We should fix this by not counting deleted rooms for this purpose.
