### ISSUE TITLE
Retain original order of the Keywords and Label fields in the function Edit keywords and label in Event editing

### ISSUE THREAD

**Issue by alittle60** [indico/indico#6531]
I'm always frustrated when editing Keywords and Label (in all Event Types), when the order of the fields switches after the edit pencil icon is clicked.

See image below for what the screen looks like before the edit pencil icon is selected (![image](https://github.com/user-attachments/assets/20797c3a-b153-4c96-956e-12710d636b9a)

Order of fields on the pre-edit page:
1. Keywords field
2. Label field

Once the edit pencil icon is selected (see image below), the order changes to:
1. Label field
3. Label message field
4. Keywords field

![image](https://github.com/user-attachments/assets/650fdba3-4ec2-407e-9fc5-b161d236d720)

**Describe the solution you'd like**
I would like the fields to be the same order on both the pre-edit page and edit page:

For example:
1. Keywords
2. Label field
3. Label message field

I don't care what order the fields are in but they should retain their order in editing.

Thanks very much in advance from your users.

**Comment by ThiefMaster** [comment]
Indeed, that order should remain the same...
