### ISSUE TITLE
Fix faulty checking for empty string and extend to more formats 

### ISSUE THREAD

**Issue by AjobK** [indico/indico#6538]
**Describe the bug**
The `check-format-strings` function should warn us when we remove `{}` from a translation string. Currently with empty braces this is not the case (see below). We also want to extend the feature so that we support `%(...)` notation.

**To Reproduce**
1. Go to a translation file
2. Change a `msgstr` that contains `{}` to not contain that `{}` anymore.
3. Run `indico i18n check-format-strings`
4. It should show that there were `No issues found!`

**Screenshots**
![image](https://github.com/user-attachments/assets/053536c3-966a-4d95-b823-43ac85deb185)

**Comment by AjobK** [comment]
When the function below:

```python
def _extract_placeholders(string):
    return set(re.findall(r'(\{[^}]*+\})', string))
    ```
    
Is changed to the code below, it works.

```python
def _extract_placeholders(string):
    return set(re.findall(r'(\{[^}]*\})', string))
    ```

In that case we indeed get output.

![Screenshot from 2024-09-13 16-40-47](https://github.com/user-attachments/assets/f860aa51-5ec3-4bf1-8133-289dba764e08)

**Comment by AjobK** [comment]
The fixes for each language will also be done by us, with the aid of native and fluent speakers of each language. It will be part of the same PR

**Comment by AjobK** [comment]
When installing all languages (`tx pull --all`), the following languages seem to be broken:

![Screenshot from 2024-09-16 11-21-19](https://github.com/user-attachments/assets/7dbd0a7c-924d-4b74-b5da-9d546dd62757)

Will be looking for native (or very fluent) speakers of these languages to help

**Comment by ThiefMaster** [comment]
You can also open issues on transifex on the broken strings, and hope that the translators are active enough to fix it. (which for some languages I know they are, for others possibly not)

**Comment by AjobK** [comment]
> You can also open issues on transifex on the broken strings, and hope that the translators are active enough to fix it. (which for some languages I know they are, for others possibly not)

Sure! For most of these languages I actually know native speakers. They're 'small' fixes so this should suffice. For languages like Mongolian I will definitely open an issue

**Comment by AjobK** [comment]
**Update**

Fixed Croation translations (only format string names, no context)
Fixed Dutch translations

**Comment by AjobK** [comment]
Fixed all translations except Japanase and Arabic. Awaiting translation from natives.

![Screenshot from 2024-09-16 17-05-57](https://github.com/user-attachments/assets/457f021a-8b11-44c5-b788-235c92c7421f)
