### ISSUE TITLE
Improve registration email notifications

### ISSUE THREAD

**Issue by Moliholy** [indico/indico#6539]
**Is your feature request related to a problem? Please describe.**
When event managers fill the templates for notification emails, they expect the full markdown body they filled to be the sole content of the emails that will be delivered. However, turns out the system fills for them some content, and such action is not indicated elsewhere nor is intuitive and leads to confusion and many time incoherent content being sent.

![photo_2024-09-13_19-14-35](https://github.com/user-attachments/assets/d7ce8b75-9265-4657-a75d-5f33ff747a29)
![photo_2024-09-13_19-08-56](https://github.com/user-attachments/assets/692e5afe-bf81-4710-a2e7-f3d0ef87326a)

**Describe the solution you'd like**
We propose to create a "Preview email" button near the markdown content that, when clicked, displays a dialog that shows how would the email look like before being sent. This way the user can check not only the full email body, but also how the markdown written gets rendered. This will allow to edit the body accordingly.

![photo_2024-09-13_19-08-48](https://github.com/user-attachments/assets/744c2c6c-6331-4063-a44d-27c57dbcfdce)

**Describe alternatives you've considered**
Other alternatives would be not to include default content in the email template, and instead pre-fill the default text area widget with the current text. This solution would require to handle the placeholders accordingly, which is not so easy to do since those placeholders are currently rendered inside the jinja template, and would likely require to perform naive text replacements.

**Comment by ThiefMaster** [comment]
Indeed, making the full email editable is a no-go because it contains lots of HTML formatting which we REALLY do not want to pass through the WYSIWYG editor.

Adding the ability to show a preview sounds like an excellent idea. The tricky part is what to use in the preview... some registrant? Dummy data (hard for custom fields)? Empty field data? Dummy data for known personal-data fields and empty for others?

PS: You may want to s/event/registration/ in the title of this issue since it seems to be just about registration emails.

**Comment by tomasr8** [comment]
Might be worth to see if we can reuse the "new" React email dialogs for this

**Comment by ThiefMaster** [comment]
I think this might be hard because those are not ad-hoc emails but configuring text snippets that are then included in the registration notification emails (which are highly dynamic and generated from Jinja templates)...

**Comment by Moliholy** [comment]
> The tricky part is what to use in the preview... some registrant? Dummy data (hard for custom fields)? Empty field data? Dummy data for known personal-data fields and empty for others?

My initial approach was the latter. To fill as much information as possible, leaving placeholders (like {user_name}, for example) for what we can't.

> PS: You may want to s/event/registration/ in the title of this issue since it seems to be just about registration emails.

Done 👍
