### ISSUE TITLE
Multi-day conferences - contributions scheduled on the later days are scheduled incorrectly

### ISSUE THREAD

**Issue by alittle60** [indico/indico#6540]
Multi-day conferences - contributions scheduled on the later days are scheduled incorrectly
For example: when adding Contributions to Day 2 of a multi-day conference, Indico:
1. gives the following notification - Event start time changed to 4:00 am.
2. places the Contribution meant for Day 2 on Day 1 at 4:00 a.m.
3. changes the Start time (in Settings) of the entire conference to 4:00 am.

Video of the issue:
![Contribution Bug](https://github.com/user-attachments/assets/7183569d-846a-4b4a-8d76-5dd4bf0456eb)

Steps to Reproduce:
1.     Create multi day conference:  e.g. September 13, 2024 to September 16, 2024, 9:00 am to 4:00 pm
2.	Create several contributions
3.	Go to Timetable
4.     Go to Day 1, Friday, September 13, 2024
5. 	Go to Add new and select Contribution – a contribution is added as expected at 9:00 am
6. 	Go to Day 2 in the timetable, Saturday, September 14, 2024
7. 	Go to Add new and select Contribution - at this point the user sees the Notification = “Event start time changed to 4:00 a.m.”  and the Contribution is placed in the Timetable on Friday, September 13, 2024, at 4:00 am. As well, in event Settings – Start has been changed by Indico to 4:00 am as per the above notification

Expected behaviour:
I expect my Contribution to be placed in the Timetable on the date I call them from, e.g. if I am on Day 2 in the timetable, the contribution should be placed in Day 2.  Also, I would never expect Indico to change the Start date of my conference.

Screenshots:
![image](https://github.com/user-attachments/assets/c9e3a4e3-1f0c-4547-9f40-bdcfd6865448)

**Additional context**
We tested this in your demo environment and we were able to reproduce this issue.

**Comment by tomasr8** [comment]
Thanks for the detailed report @alittle60 ! #6541 should address this :)

**Comment by alittle60** [comment]
Thank you, can you please tell me if this bug fix will be in v 3.3.5 and if so, when will 3.3.5 be released?
Best,
Anne

**Comment by ThiefMaster** [comment]
It will, but we don't have any particular plan on when we'll release it yet (so far all the things in there are pretty minor). You could easily apply it as a hotfix on your instance though.
