### ISSUE TITLE
Event logos are sent with "no-cache" header, eating traffic when browing an event's pages

### ISSUE THREAD

**Issue by olifre** [indico/indico#6555]
**Describe the bug**
When browsing through an event with a large event logo, such as:
https://indico.cern.ch/event/1386170/overview
the logo is sent to the browser with a `no-cache` header, i.e.:
```
cache-control: no-cache
```
which means the logo is loaded each time any sub-page of the event is loaded. In the example case, this means 1 MB of traffic which can be noticeable e.g. on a mobile connection. 

**To Reproduce**
1. Create an event and use a nice and large image as "Event Logo" in "Customization => Layout". 
2. Click on any page of the event (no matter whether logged in or logged out). 
3. Observe the logo is loaded each time (e.g. check out Accomodation information, time table etc. on a phone with slow mobile connection). 

**Expected behavior**
Logo sent without "no-cache" header to save bandwidth.

**Comment by ThiefMaster** [comment]
Maybe they should not use a 1MB logo to begin with. This could be converted to webp which makes it about 100kB instead...

Anyway, I agree that, especially considering we already have a timestamp in the url that acts as a cache buster when the logo changes, event logos should have caching enabled.

**Comment by olifre** [comment]
> Maybe they should not use a 1MB logo to begin with. This could be converted to webp which makes it about 100kB instead...

Fully agreed, but I have seen this on so many events that it seems a technical solution is more effective (and allowing caching seemed more reasonable than limiting upload size or force-converting images) :wink: . 

> Anyway, I agree that, especially considering we already have a timestamp or checksum (not sure which one we use here) in the url that acts as a cache buster when the logo changes, event logos should have caching enabled.

Thanks! :+1:
