### ISSUE TITLE
Missing translation strings in Transifex

### ISSUE THREAD

**Issue by markpolyak** [indico/indico#6624]
**Describe the bug**
Unable to find in Transifex any of the strings located in `indico/indico/modules/events/contributions/client/js/index.jsx`

**To Reproduce**
1. Go to https://app.transifex.com/indico/indico/translate/
2. Choose language
3. Search for 'Filter sessions' (code is located [here](https://github.com/indico/indico/blob/56d1300fa4c13d4bde01bb596169f6b1eb05e477/indico/modules/events/contributions/client/js/index.jsx#L140))
4. See the 'No results found' message

Alternatively:
1. Open Indico and go to an event page
2. Switch to an event management area
3. Select Organization -> Contributions in the menu on the left
4. Add a new contribution if there are none
5. Switch to German language, which has 100% of all strings translated according to Transifex
6. Click a dropdown arrow in either 'Session' ('Sitzung') or 'Track' column
7. See a popup with untranslated English text

**Expected behavior**
It should be possible to translate strings located in `indico/indico/modules/events/contributions/client/js/index.jsx` with Transifex

**Comment by ThiefMaster** [comment]
Thanks, this is now fixed and I pushed the missing strings.
