### ISSUE TITLE
Translation of "Select a category" dialog (missing "{0} categories" string from Transifex)

### ISSUE THREAD

**Issue by markpolyak** [indico/indico#6638]
In the "Select a category" dialog (e.g. "Create meeting" from the menu -> press "Choose category" button) the popup text, which appears when a mouse pointer is hovered over the number of categories and events on the right hand side of each row in the dialog, is **partially translated**. The text is "{0} categories | {0} events" with numbers inserted instead of "{0}" and single or plural form of the word "category"/"event" used.

The problem is that the "{0} events" part of that string is properly translated, while the "{0} categories" always stays in English.

**To Reproduce**
1. Go to "Create meeting" in the main menu
2. Click on "Choose category" button
3. Hover mouse pointer over the numbers on the right hand side of any row in the dialog
4. See mixed-language text in the popup (see the screenshot for reference)

Or just search for `"{0} categories"` on Transifex and see that it is missing.

**Expected behavior**
The text of the popup should be fully translated.

**Screenshots**
German translation is used because on Transifex it is 100% translated, so no English words should be present (in theory)
![2024-12-01_21-33-52](https://github.com/user-attachments/assets/a75c2da9-ed9c-4b33-8d3a-22f4dc606486)

**Additional context**
 I assume that the code is located here: [indico/web/client/js/jquery/widgets/categorynavigator.js](https://github.com/indico/indico/blob/4fa81c297f4c08d5b842e420a26125627c5bc4cd/indico/web/client/js/jquery/widgets/categorynavigator.js#L300). So the issue might be with `indico/web/client/js/jquery/widgets/categorynavigator.js` missing from Transifex. The "{0} events" substring is present in Transifex as it appears also in `indico/modules/categories/client/js/display.js`, but the "{0} categories" substring seems to be unique to `categorynavigator.js`.

**Comment by ThiefMaster** [comment]
For some reason this template string containing two nested translatable strings was not correctly extracted. Splitting it into something that's cleaner anyway fixed it.

**Comment by tomasr8** [comment]
Maybe something worth reporting upstream if it's a bug in extraction?

**Comment by ThiefMaster** [comment]
Not sure if gettext-inside-templatestring is even supported... (but TBH I also didn't test it, since IMHO it's something that should not be done for the sake of readability)

**Comment by tomasr8** [comment]
Looks like it's a known issue: https://github.com/python-babel/babel/issues/329
