### ISSUE TITLE
Add single/plural form of counters to registration statistics page

### ISSUE THREAD

**Issue by markpolyak** [indico/indico#6641]
**Is your feature request related to a problem? Please describe.**
The registration statistics page contains counters, such as "Registrations", "Days left to register" and "Countries".  They are showed always with a plural form of the word, e.g. "1 registration**s**", "1 countrie**s**", and so on.

**Describe the solution you'd like**
The text should be "1 countr**y**", "2 countr**ies**", etc., with respect to other languages that might have more than two word forms for countable items. 

**Describe alternatives you've considered**
Text might be rewritten among the lines of "Countries: 1", i.e. the plural form of the word goes first, followed by the value of the counter. In this case there is no need to bother with multiple word forms for each statistic (in theory), though this might not be true for all languages.

**Additional context**
The code is [here](https://github.com/indico/indico/blob/26ae5ce7a594cbb68968d0058b9d16f6a9d0e857/indico/modules/events/registration/templates/management/regform_stats.html#L37). Unfortunately, I don't have any experience with specifying multiple forms of the same translation string in a template, so I'm unable to suggest a fix right away.
![2024-12-02_16-40-51](https://github.com/user-attachments/assets/01efd338-551a-4ff3-96bc-eff8840346dd)

**Comment by ThiefMaster** [comment]
```
ngettext('Registration', 'Registrations', stats.registrations|length),  stats.registrations|length)
```

This should work. Likewise for the others.
