### ISSUE TITLE
Use a combined pot file bundle (#6606) .tx/config file_filter 

### ISSUE THREAD

**Issue by aforouz** [indico/indico#6670]
**Describe the bug**
file_filter = indico/translations/<lang>/LC_MESSAGES/messages-all.po
what's this?
It doesn't let other languages compile!
Do you change installation?

**To Reproduce**
1. Go to ') .tx/config '
2. Click on 'line 23'
3. file_filter = indico/translations/<lang>/LC_MESSAGES/messages-all.po

**Comment by ThiefMaster** [comment]
Which command is failing and with which error message?

**Comment by aforouz** [comment]
in installation guide, when I want to run "indico i18n compile indico" and I get this error, "indico/translations/en_GB/LC_MESSAGES/message-all.po not found"

**Comment by aforouz** [comment]
One more thing! why there's no DEFAULT_LOCATION(en_GB)?
When I want to prepare db this language, this error will be displayed.

**Comment by tomasr8** [comment]
Thanks for the report! We are currently transitioning to a single POT file (`messages-all.pot`), though compilation should still work as normal. Try pulling the latest PO files with `indico i18n pull indico` before compiling.

**Comment by aforouz** [comment]
I tried it too and get this error.
"tx ERROR: ValueError: not enough values to unpack (expected 2, got 1)
Error pulling from transifex"

**Comment by aforouz** [comment]
That was error of compile indico.
"Error running CompileCatalog for indico - /home/aforouz/dev/indico/src/indico/translations/en_GB/LC_MESSAGES/messages-all.po does not exist!"

**Comment by ThiefMaster** [comment]
did you update to the latest git master?

**Comment by aforouz** [comment]
I cloned it about 11 hours ago about 3 times.

**Comment by aforouz** [comment]
May I ask you to install it and check what would happen for you?

**Comment by ThiefMaster** [comment]
i pushed a commit maybe 1-2 hours ago...

**Comment by aforouz** [comment]
Thanks so much.
It works now.
