### ISSUE TITLE
Payment method duplication and per-registration choices

### ISSUE THREAD

**Issue by laf070810** [indico/indico#6672]
**Is your feature request related to a problem? Please describe.**

Consider the following case. We may have to pay for registration fee and accommodation fee on Indico. Registration fee has to be paid by one payment method to the institute and accommodation fee by another method to the hotel. We don't want participants to mix the payment methods since we certainly cannot pay accommodation fee to the institute and vice versa. Currently enabled payment methods in an event seem to appear in all registrations in the event. It would be convenient if we can specify different payment methods for different registrations in the same event. 

Further, paying to institute and paying to the hotel may use the same payment method, i.e. same payment plugin. It would be good if we can duplicate a payment method with the same payment plugin but different parameters (e.g. payment API URL). 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ThiefMaster** [comment]
Duplicating payment methods, partial payments using different methods are, just like e.g. automated refunds or being able to add/removed paid options later and then paying/refunding the difference, would introduce a huge amount of extra complexity so I don't think this is going to happen...

FWIW I don't think i makes much sense to handle the payment to the hotel via Indico at all in such a case.

**Comment by laf070810** [comment]
Partial payments and refunding are indeed complex. But we are not aiming at partial payments. Just to allow different payment methods for different registrations. 

The idea of payment as marking of "Complete" registration is concise and elegant, though IMHO I think we will still face many practical cases where multiple payments are needed in one event, e.g. registration fee, accommodation fee, excursion fee, banquet fee, etc. And paying on Indico instead of on-site paying could have some benefits of for example reducing volunteers' pressure and avoiding crowdedness. But yeah this can be out of scope. 

Anyway this issue is not a big one. Different events can enable different payment methods. So as a workaround we can create a new event and put the accommodation payment in the new event, which seems a bit awkward though, if we still want to do multiple payments on Indico.
