### ISSUE TITLE
"Apply" button translate

### ISSUE THREAD

**Issue by aforouz** [indico/indico#6680]
**Describe the bug**
I try to translate "Apply" but it doesn't affect in language changing.

**To Reproduce**
0. Run indico.
1. Go to 'Room booking'
2. Click on 'List of Rooms'
3. Scroll down to 'Building'
4. See "Apply" is still on English and doesn't change after set language on non English ones.

**Screenshots**
![Screenshot 2024-12-22 200729](https://github.com/user-attachments/assets/dbca2e4f-9db6-4c8b-a1c5-fb9e0e717259)

**Additional context**
Translating doesn't affect this button.

**Comment by ThiefMaster** [comment]
Is that Turkish? I just checked on Transifex, and "Apply" simply has no translation there yet. So not a bug, just a missing translation...

**Comment by aforouz** [comment]
Actually I'm translating Farsi and that's what happen!

![Screenshot 2024-12-22 222419](https://github.com/user-attachments/assets/e8109105-2cbe-4880-9808-5dde9d8977ae)
![Screenshot 2024-12-22 222442](https://github.com/user-attachments/assets/d7433797-0d12-4cad-8a8f-73c4984fca01)
![Screenshot 2024-12-22 222514](https://github.com/user-attachments/assets/b6b1df4a-3dee-449f-943d-187685b52da1)
![Screenshot 2024-12-22 222519](https://github.com/user-attachments/assets/967f773f-7a94-40ec-b9ae-886a2862bd80)

**Comment by ThiefMaster** [comment]
You need to use the latest git master. We added context there since "Apply" can have different meanings ("applying for participation in an event" vs "applying a filter"):

```
#: indico/modules/rb/client/js/common/filters/FilterDropdown.jsx
msgctxt "Filters"
msgid "Apply"
```

**Comment by aforouz** [comment]
Thanks so much.
I'll update it and report if there was any problem.
