### ISSUE TITLE
how to configure an external Apache proxy setup?

### ISSUE THREAD

**Issue by parmarhimanshu** [indico/indico#6681]
We have limited public IPs and many services are running with Apache proxy. We need to set up Indico on a separate system.
Can anyone give me a step by step guide on how to configure an external Apache proxy setup?

**Comment by ThiefMaster** [comment]
- This kind of question better fits in our forum, https://talk.getindico.io
- Setting up a reverse proxy is pretty trivial and - besides setting `USE_PROXY = True` in indico.conf (which is already documented) - not really specific to Indico. So you should be able to use one of the many guides out there.
