### ISSUE TITLE
Do not offer to download material if there is not

### ISSUE THREAD

**Issue by jbenito3** [indico/indico#730]
``` yaml
# Ticket imported from Trac
```

 you should not be able to select 'Download material' link from "More" dropdown menu, if there is no material available. In the end it downloaded a package called full-material.zip which was a 6byte file (i.e. completely empty). Suggest that this option be grayed out if indeed there is no material to download.

**Comment by ThiefMaster** [comment]
We show a message if there is no material, so empty zip files no longer happen

> There are no materials matching your criteria.
