### ISSUE TITLE
Use plugin system to compute access to resources

### ISSUE THREAD

**Issue by pferreir** [indico/indico#754]
``` yaml
# Ticket imported from Trac
```

Plugins should be able to specify who has access to certain resources. The core should ask them them whenever needed. This would get rid of the infamous:

```

from MaKaC.webinterface.rh.collaboration import RCCollaborationAdmin, RCCollaborationPluginAdmin

```

all through `conference.py`

**Comment by ThiefMaster** [comment]
The `can_access` signal covers this.
