### ISSUE TITLE
Add registrants as speakers, authors and so on

### ISSUE THREAD

**Issue by jbenito3** [indico/indico#758]
``` yaml
# Ticket imported from Trac
```

Following scenario: People register for my conference and don't have an Indico-Account (let's say I don't require one). Even when the speakers (subset of the registrants) in that case are not able to upload their contribuitions themselves, I (as admin) could do it by hand. 
What I'd like to do then is to create contributions (via the Contributions menu) and assign somebody of the registrants as presenter.

**Comment by plourenco** [comment]
Not applicable anymore
