### ISSUE TITLE
Let the registrant indicate whther he/she wants his name advertised publicly

### ISSUE THREAD

**Issue by jbenito3** [indico/indico#823]
``` yaml
# Ticket imported from Trac
```

I've got something to propose: There is a possibility to show publicly a
list of participants. However, not everybody may agree to have their
name published. For HEPiX we ran this week, it would have been extremely
useful if we could have published immediately a list of registrants that
agreed to be on the list.

Would it hence be possible to introduce a flag for the registrant that
decides whether he/she is shown on the publicly accessible list?

Cheers,

Helge

**Comment by pferreir** [comment]
This is part of #1415.
