### ISSUE TITLE
Room Booking: Calendar: "Change period"

### ISSUE THREAD

**Issue by indico-bot** [indico/indico#880]
``` yaml
# Ticket imported from Trac
# Reported by: gcerto
```

On the Calendar page of the room booking: [https://indico.cern.ch/roomBooking.py/bookingList?roomGUID=allRooms&day=today]

The "change period" link does not make sense, indeed, the period allowed for this page is "One day" nothing more. However, the popup window let you choose a period and return an error if you choose a period bigger than one day.

So we should allow only one date field and let the users choose the day they want to see.

**Comment by mic4ael** [comment]
I think this one is kind of obsolete since we allow specifying more than one day in the Change period popup without throwing an error.
