### ISSUE TITLE
Allow file naming when download materials

### ISSUE THREAD

**Issue by arescope** [indico/indico#962]
``` yaml
# Ticket imported from Trac
```

When uploading slides to an Indico agenda via the "Manage Material" option, it is possible in the Advanced tab to set the display name. However this is ignored when the file is downloaded.

What I would like is to be able to have my own personal convention for naming my slides, but to be able to specify how they should be named when downloaded by someone else for a particular meeting. For example, my talks may have some cryptic meeting name and date in the filenames, but someone downloading all files for a meeting may prefer a more obvious name for them, eg just my name.

So I would like to suggest that the display name set in the advanced tab should also be the downloaded filename.

This used to be possible in the old version of Indico but is still not supported by the new version (despite a previous request).

**Comment by pferreir** [comment]
Old issue. Use case seems quite uncommon.
