### ISSUE TITLE
i18n goes wrong for Slides/Transparents

### ISSUE THREAD

**Issue by DirkHoffmann** [indico/indico#994]
``` yaml
# Ticket imported from Trac
```

Here is a tricky one, and I am not sure how to handle it, because it is second or third order of i18n efforts.

I noticed that material flagged as "Slides" sometimes appears as "Slides" in the event page, sometimes under "Transparents". This is bad for two reasons:
- The name depends on the user's preference (the user who submits them!). But on the _same_ meeting you may have "Slides" and "Transparents" (and later 透明片 probably). It should only display the same thing whatever the user (who reads it) has as a preference.
- I was told by users with french language selected that they also submit the material as "Slides" (like with english). Only the transfer to InDiCo (and later display) are made in their preferred language. It should probably work the other way round: The user chooses "Slides" or "Transparents" in his preferred language, then InDiCo stores them under the same generic type ("slides"?) and later displays all of them as "Transparentas" on the event page for a spanish-preferring reader.

**Comment by ThiefMaster** [comment]
predefined material types are pretty much gone
